### ISSUE TITLE
can't persist onetomany, manytoone(Bidirectional Association) in Hbase, its also in Unidirectional Association

### ISSUE THREAD

**Issue by daddyauden** [Impetus/kundera#1009]
@Entity
    @Table(name = "CLASSROOM", schema = "EDUCATION@hbase")
    @IndexCollection(columns = {
        @Index(name = "name")
    })
    public class ClassroomEntity implements Serializable {
        private static final long serialVersionUID = 8020522006409395867L;

        /**
         * ID
         */
        @Id
        @NotNull
        @GeneratedValue(strategy = GenerationType.TABLE)
        @Column(name = "CLASSROOM_ID")
        private Integer classroomId;

    // ignore name definition

        @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "classroom",   targetEntity = StudentEntity.class)
        private Set<StudentEntity> students;

        ...set and get
    }

    @Entity
    @Table(name = "STUDENT", schema = "EDUCATION@hbase")
    @IndexCollection(columns = {
        @Index(name = "name")
    })
    public class StudentEntity implements Serializable
    {
        private static final long serialVersionUID = 8020522006409395867L;

        /**
         * ID
         */
        @Id
        @NotNull
        @GeneratedValue(strategy = GenerationType.TABLE)
        @Column(name = "STUDENT_ID")
        private Integer studentId;

    //ignore name definition

        /**
         * CLASS ENTITY
         */
        @ManyToOne(fetch = FetchType.LAZY)
        @JoinColumn(name = "CLASSROOM_ID")
        public ClassEntity classroom;

        ...set and get
    }

In the controller

        Set<StudentEntity> students = new HashSet<>();

        StudentEntity s1 = new StudentEntity();
        s1.setStudentId(10);
        s1.setName("aaa");
        students.add(s1);

        StudentEntity s2 = new StudentEntity();
        s2 setStudentId(20);
        s2.setName("bbb");
        students.add(s2);

        ClassroomEntity classroom = new ClassroomEntity();
        classroom.setClassroomId(100);
        classroom.setName("ccc");
        classroom.setStudents(students);

        someService.insertClassroom(classroom);

Persistence Unit:

    <persistence-unit name="hbase">
            <provider>com.impetus.kundera.KunderaPersistence</provider>
            <properties>
                <property name="kundera.nodes" value="localhost" />
                <property name="kundera.port" value="2181" />
                <property name="kundera.keyspace" value="EDUCATION" />
                <property name="kundera.dialect" value="hbase" />
                <property name="kundera.ddl.auto.prepare" value="create" />
                <property name="kundera.client.lookup.class" value="com.impetus.client.hbase.HBaseClientFactory" />
                <property name="kundera.show.query" value="true" />
                <property name="kundera.batch.size" value="5" />
                <property name="kundera.datastore.file.path" value="META-INF/datastore-hbase.xml" />
            </properties>
        </persistence-unit>

I use hbase shell, can list classroom name and student name, but can't list classroomId, studentId and the onetomany & manytoone association data

**Comment by devender-yadav** [comment]
HI @jackyang1984,

What are HBase and Kundera version you using?

**Comment by devender-yadav** [comment]
Please have a look at existing association test case - https://github.com/Impetus/Kundera/tree/trunk/src/kundera-hbase/kundera-hbase-v2/src/test/java/com/impetus/client/hbase/crud/association

**Comment by daddyauden** [comment]
@devender-yadav 
hadoop: 2.7.6
hbase: 2.0.0
kundera: 3.12

yes, i try the crud test, but didn't work

**Comment by devender-yadav** [comment]
@jackyang1984 can you please error logs.

**Comment by daddyauden** [comment]
@devender-yadav have not error, two entities can persist data to hbase, but the association between them can not

**Comment by devender-yadav** [comment]
@jacksonic I will try to replicate it today in our system with particular versions.
Are you using `kundera-hbase-v2`?

**Comment by daddyauden** [comment]
@devender-yadav yes

**Comment by daddyauden** [comment]
@devender-yadav i saw many example about kundera with cassandra, more than kundera with hbase, is kundera the best friend with cassandra?

**Comment by daddyauden** [comment]
@devender-yadav below is my maven pom

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

    <groupId>com.abc</groupId>
    <artifactId>cs</artifactId>
    <version>v1</version>
    <packaging>jar</packaging>

	<name>cs</name>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.2.RELEASE</version>
		<relativePath/>
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
        <hadoop.version>2.7.6</hadoop.version>
		<hbase.version>1.2.6</hbase.version>
		<kundera.version>3.12</kundera.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>spring-boot-starter-tomcat</artifactId>
					<groupId>org.springframework.boot</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jetty</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jpa</artifactId>
        </dependency>


        <dependency>
            <groupId>com.impetus.kundera.client</groupId>
            <artifactId>kundera-hbase-v2</artifactId>
            <version>${kundera.version}</version>
        </dependency>
        
            
            
            
            
        
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-client</artifactId>
            <version>${hbase.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-server</artifactId>
            <version>${hbase.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-server</artifactId>
            <version>${hbase.version}</version>
            <classifier>tests</classifier>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-common</artifactId>
            <version>${hbase.version}</version>
            <classifier>tests</classifier>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-common</artifactId>
            <version>${hbase.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-hadoop-compat</artifactId>
            <version>${hbase.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-common</artifactId>
            <version>${hadoop.version}</version>
        </dependency>
    </dependencies>
</project>

**Comment by devender-yadav** [comment]
@jackyang1984,

Kundera with Cassandra is more popular. But kundera-hbase and kundera-mongodb are also active and commonly used in Kundera community.

**Comment by devender-yadav** [comment]
@jackyang1984,

There is no `JoinTable` annotation in your entities. Thus, Join table will not be created in your particular example. 

This is working fine at my end.

**Comment by daddyauden** [comment]
@devender-yadav when i add JoinTable, get error:@JoinTable not supported for one to many association

so, what about your JoinTable?

**Comment by daddyauden** [comment]
@devender-yadav 
https://github.com/Impetus/Kundera/wiki/Polyglot-Persistence  the example have not also, so maybe you can add it

**Comment by devender-yadav** [comment]
@jackyang1984 Join table is generally used for Many to Many associations. Is there any reason that you need separate join table for One to Many association. 

What issue are you facing with example - https://github.com/Impetus/Kundera/wiki/Polyglot-Persistence

**Comment by daddyauden** [comment]
@devender-yadav yes, i do as the Polyglot-Persistence, but didn't work, but i need use onetomany and manytoone, so kundera is not support both of them?

**Comment by devender-yadav** [comment]
@jackyang1984 Kundera does support both of them. That's why we have added the wiki for polyglot persistence - https://github.com/Impetus/Kundera/wiki/Polyglot-Persistence

What exact issue are you facing with polyglot persistence? Please share error logs and expected results.

**Comment by daddyauden** [comment]
@devender-yadav 

@Entity
@Table(name = "CLASSROOM", schema = "EDUCATION@hbase")
public class ClassroomEntity {
    @Id
    @NotNull
    @GeneratedValue(strategy = GenerationType.TABLE)
    @Column(name = "CLASSROOM_ID")
    private Integer classroomId;

    @Column(name = "CLASSROOM_NAME")
    private String classroomName;

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "CLASSROOM_STUDENT")
    private Set<StudentEntity> students;
}

@Entity
@Table(name = "STUDENT", schema = "EDUCATION@hbase")
public class StudentEntity {
    @Id
    @NotNull
    @GeneratedValue(strategy = GenerationType.TABLE)
    @Column(name = "STUDENT_ID")
    private Integer studentId;

    @Column(name = "STUDENT_NAME")
    private String studentName;
}

// Controller
        ClassroomEntity classroom = new ClassroomEntity();
        classroom.setClassroomName("classroom1");

        Set<StudentEntity> students = new HashSet<>();
        StudentEntity s1 = new StudentEntity();
        s1.setStudentName("test1");

        StudentEntity s2 = new StudentEntity();
        s2.setStudentName("test2");

        students.add(s1);
        students.add(s2);

        classroom.setStudents(students);

        service.insertClassroom(classroom);

My expected is save classroom data, student data and onetomany data to hbase,  but......,   in fact, onetomany data don't save to hbase, as the same time havn't error log to display, it's really havn't error log!!!!!!

**Comment by devender-yadav** [comment]
Hi @jackyang1984,

I tried to replicate this at my end. Its working fine.

Entities:

```
@Entity
@Table(name = "CLASSROOM", schema = "kundera_db@hbase_pu")
public class ClassroomEntity
{
    @Id
    @NotNull
    @GeneratedValue(strategy = GenerationType.TABLE)
    @Column(name = "CLASSROOM_ID")
    private Integer classroomId;

    @Column(name = "CLASSROOM_NAME")
    private String classroomName;

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "CLASSROOM_STUDENT")
    private Set<StudentEntity> students;

    // getter setters
}
```


```
@Entity
@Table(name = "STUDENT", schema = "kundera_db@hbase_pu")
public class StudentEntity
{
    @Id
    @NotNull
    @GeneratedValue(strategy = GenerationType.TABLE)
    @Column(name = "STUDENT_ID")
    private Integer studentId;

    @Column(name = "STUDENT_NAME")
    private String studentName;

    // getters and setters
}
```

Test Class:

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("hbase_pu");
        EntityManager em = emf.createEntityManager();

        ClassroomEntity classroom = new ClassroomEntity();
        classroom.setClassroomId(501);
        classroom.setClassroomName("class1");

        Set<StudentEntity> students = new HashSet<>();

        StudentEntity s1 = new StudentEntity();
        s1.setStudentId(101);
        s1.setStudentName("student1");
        students.add(s1);

        StudentEntity s2 = new StudentEntity();
        s2.setStudentId(102);
        s2.setStudentName("student2");
        students.add(s2);

        classroom.setStudents(students);

        em.persist(classroom);

Persistence Unit


	<persistence-unit name="hbase_pu">
		<provider>com.impetus.kundera.KunderaPersistence</provider>
		<class>com.dev.test.StudentEntity</class>
		<class>om.dev.test.ClassroomEntity</class>
		<exclude-unlisted-classes>true</exclude-unlisted-classes>
		<properties>
			<property name="kundera.nodes" value="localhost" />
			<property name="kundera.port" value="60000" />
			<property name="kundera.keyspace" value="kundera_db" />
			<property name="kundera.dialect" value="hbase" />
			<property name="kundera.client.lookup.class" value="com.impetus.client.hbase.HBaseClientFactory" />
			<property name="kundera.ddl.auto.prepare" value="create" />
		</properties>
	</persistence-unit>

Data in HBase:

> scan "kundera_db:CLASSROOM"

    ROW                                                  COLUMN+CELL                                                                                                                                            
     \x00\x00\x01\xF5                                    column=CLASSROOM:CLASSROOM_NAME, timestamp=1526367106622, value=class1                                                                                 
    1 row(s) in 0.1210 seconds


>scan "kundera_db:STUDENT"

    ROW                                                  COLUMN+CELL                                                                                                                                            
     \x00\x00\x00e                                       column=STUDENT:CLASSROOM_STUDENT, timestamp=1526367106633, value=\x00\x00\x01\xF5                                                                      
     \x00\x00\x00e                                       column=STUDENT:STUDENT_NAME, timestamp=1526367106633, value=student1                                                                                   
     \x00\x00\x00f                                       column=STUDENT:CLASSROOM_STUDENT, timestamp=1526367106636, value=\x00\x00\x01\xF5                                                                      
     \x00\x00\x00f                                       column=STUDENT:STUDENT_NAME, timestamp=1526367106636, value=student2                                                                                   
    2 row(s) in 0.1150 seconds

**Comment by daddyauden** [comment]
@devender-yadav I find my codes bug where is

https://github.com/Impetus/Kundera/blob/trunk/examples/container/jboss/data-keeper/src/main/java/com/impetus/kundera/datakeeper/dao/DataKeeperDaoImpl.java

@Override
    public void insert(Object entity)
    {
        em.persist(entity);
        em.clear();
    }

if comment em.clear(), it's running

**Comment by devender-yadav** [comment]
@jackyang1984 but it should work in both cases i.e. with and without clearing persistence cache.

**Comment by daddyauden** [comment]
@devender-yadav 

Unidirectional onetomany now is ok, but now Bidirectional onttomany is not, all datas and Bidirectional relation data is stored, but  i can't get the many side data

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.StackOverflowError
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1006) ~[spring-webmvc-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) ~[spring-webmvc-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) ~[spring-webmvc-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) ~[spring-webmvc-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865) ~[jetty-servlet-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) ~[jetty-servlet-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215) ~[websocket-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) ~[jetty-servlet-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) ~[jetty-servlet-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) ~[spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) ~[jetty-servlet-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) ~[jetty-servlet-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) ~[jetty-servlet-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) ~[jetty-servlet-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) ~[jetty-security-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) ~[jetty-servlet-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.Server.handle(Server.java:531) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) ~[jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) [jetty-io-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760) [jetty-util-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678) [jetty-util-9.4.10.v20180503.jar!/:9.4.10.v20180503]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: java.lang.StackOverflowError: null
	at java.io.StringWriter.write(StringWriter.java:112) ~[na:1.8.0_171]
	at com.google.gson.stream.JsonWriter.string(JsonWriter.java:591) ~[gson-2.8.4.jar!/:na]
	at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402) ~[gson-2.8.4.jar!/:na]

**Comment by devender-yadav** [comment]
@jackyang1984,

Please share your latest Bidirectional OneToMany relational entities.

**Comment by daddyauden** [comment]
@devender-yadav have kundera-hbase-v2 support left join operation? if support, how to write the query?

**Comment by devender-yadav** [comment]
@jackyang1984 you can't write left join query on kundera-hbase-v2.

**Comment by daddyauden** [comment]
@devender-yadav ok.  Two tables is ManyToOne Relationship, i just select one table by another table field, do you know how to do that?
