### ISSUE TITLE
 com.impetus.kundera.configure.schema.SchemaGenerationException: org.apache.thrift.transport.TTransportException

### ISSUE THREAD

**Issue by podorskaja** [Impetus/kundera#1037]
Hi, 

I'm trying to go through the tutorial https://github.com/Impetus/Kundera/wiki/Getting-Started-in-5-minutes

my configs are exactly the same as in the tutorial above, however, this is the error that I get

```
21:37:07.600 [main] INFO com.impetus.kundera.persistence.EntityManagerFactoryImpl - Loading Core
21:37:07.636 [main] INFO com.impetus.kundera.loader.CoreLoader - Loading Kundera Core Metdata ... 
21:37:07.640 [main] INFO com.impetus.kundera.persistence.EntityManagerFactoryImpl - Loading Persistence Unit MetaData For Persistence Unit(s) cassandra_pu.
21:37:07.660 [main] INFO com.impetus.kundera.configure.PersistenceUnitConfiguration - Loading Metadata from persistence.xml ...
21:37:07.990 [main] INFO com.impetus.kundera.configure.PersistenceUnitConfiguration - Finishing persistence unit metadata configuration ...
21:37:08.024 [main] DEBUG com.impetus.kundera.configure.MetamodelConfiguration - Loading Entity Metadata...
21:37:08.039 [main] INFO com.impetus.kundera.configure.MetamodelConfiguration - No class to scan for persistence unit cassandra_pu. Entities will be loaded from classpath/ context-path
21:37:08.311 [main] DEBUG com.impetus.kundera.validation.rules.EntityAnnotationRule - Validating User
21:37:08.420 [main] DEBUG com.impetus.kundera.configure.MetamodelConfiguration - Metadata not found in cache for User
21:37:08.490 [main] DEBUG com.impetus.kundera.metadata.MetadataBuilder - Processing @Entity >> class User
21:37:08.530 [main] DEBUG com.impetus.kundera.metadata.processor.TableProcessor - Processing @Entity(User) for Persistence Object.
21:37:08.713 [main] INFO com.impetus.kundera.configure.ClientMetadataBuilder - Loading client factory for persistence unit cassandra_pu
21:37:08.715 [main] INFO com.impetus.kundera.client.ClientResolver - Initializing client factory for: cassandra_pu
21:37:08.809 [main] INFO com.impetus.kundera.client.ClientResolver - Finishing factory initialization
21:37:08.809 [main] INFO com.impetus.kundera.configure.SchemaConfiguration - Configuring schema export for : cassandra_pu
21:37:08.958 [main] INFO com.impetus.client.cassandra.config.CassandraPropertyReader - Returning placement strategy value org.apache.cassandra.locator.SimpleStrategy
Exception in thread "main" com.impetus.kundera.configure.schema.SchemaGenerationException: org.apache.thrift.transport.TTransportException
	at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.create(CassandraSchemaManager.java:264)
	at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.handleOperations(AbstractSchemaManager.java:264)
	at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.exportSchema(AbstractSchemaManager.java:115)
	at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.exportSchema(CassandraSchemaManager.java:166)
	at com.impetus.kundera.configure.SchemaConfiguration.configure(SchemaConfiguration.java:191)
	at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:48)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:408)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configure(EntityManagerFactoryImpl.java:161)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:135)
	at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:85)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
	at KunderaExample.main(KunderaExample.java:22)
Caused by: org.apache.thrift.transport.TTransportException
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129)
	at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql3_query(Cassandra.java:1734)
	at org.apache.cassandra.thrift.Cassandra$Client.execute_cql3_query(Cassandra.java:1719)
	at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.onCql3CreateKeyspace(CassandraSchemaManager.java:409)
	at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.createKeyspace(CassandraSchemaManager.java:317)
	at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.onCreateKeyspace(CassandraSchemaManager.java:294)
	at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.createOrUpdateKeyspace(CassandraSchemaManager.java:278)
	at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.create(CassandraSchemaManager.java:260)
	... 11 more
```

**Comment by podorskaja** [comment]
Problem solved. By default cassandra is launched with a closed port 

`docker run --name cassandra1 -d -e CASSANDRA_START_RPC=true -p 9160:9160 -p 9042:9042 -p 7199:7199 -p 7001:7001 -p 7000:7000 cassandra`
