### ISSUE TITLE
[Question] quick start example throwin NPE

### ISSUE THREAD

**Issue by jackchappelear** [Impetus/kundera#106]
I am able to connect to my cassandra cluster OK using Jassandra, but I am getting following NPE with Kundera

2012-08-21 10:35:05,018 [INFO ] [main] com.impetus.client.cassandra.config.CassandraPropertyReader  - No property file found in class path, kundera will use default property
2012-08-21 10:35:07,081 [INFO ] [main] com.impetus.kundera.persistence.EntityManagerFactoryImpl  - EntityManagerFactory created for persistence unit : cassandra_pu
Exception in thread "main" com.impetus.kundera.KunderaException: java.lang.NullPointerException
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:285)
    at com.gs.credit.OtherKunderaExample.main(OtherKunderaExample.java:21)
Caused by: java.lang.NullPointerException
    at com.impetus.kundera.persistence.event.EntityEventDispatcher.fireEventListeners(EntityEventDispatcher.java:53)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:134)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:279)
    ... 1 more

pretty much following the example and copied the code, only adding a local package.

**Comment by mevivs** [comment]
Please share your entity class definition and persistence.xml

**Comment by mevivs** [comment]
It looks like... Either "cassandra_pu" is missing from your entity definition, either "persistence.xml" is not available in classpath.

**Comment by mevivs** [comment]
Have a look at sample project at:
https://github.com/downloads/impetus-opensource/Kundera-Examples/project%20(1).zip

**Comment by jackchappelear** [comment]
I'll look at the sample project in the AM, was in meetings for rest of afternoon

**Comment by vavava** [comment]
It seems i have the same issue - line numbers match. EntityManagerImpl.java:285 ( from kundera-cassandra-2.0.7-jar-with-dependencies.jar ). I am including a more detailed log, hope it helps:

<pre>
2012-09-11 14:48:41,807 [INFO ] [main] com.impetus.kundera.KunderaPersistence  - Loading Core
2012-09-11 14:48:41,809 [INFO ] [main] com.impetus.kundera.loader.CoreLoader  - Loading Kundera Core Metdata ... 
2012-09-11 14:48:41,811 [INFO ] [main] com.impetus.kundera.KunderaPersistence  - Loading Application MetaData and Initializing Client(s) For Persistence Unit(s)
 cassandra_pu
2012-09-11 14:48:41,818 [INFO ] [main] com.impetus.kundera.configure.PersistenceUnitConfiguration  - Loading Metadata from persistence.xml ...
2012-09-11 14:48:41,927 [INFO ] [main] com.impetus.kundera.configure.PersistenceUnitConfiguration  - Finishing persistence unit metadata configuration ...
2012-09-11 14:48:41,927 [INFO ] [main] com.impetus.kundera.configure.ClientFactoryConfiguraton  - Loading Client(s) For Persistence Unit(s) cassandra_pu
2012-09-11 14:48:41,928 [INFO ] [main] com.impetus.kundera.client.ClientResolver  - Initializing client factory for: cassandra_pu
2012-09-11 14:48:41,933 [INFO ] [main] com.impetus.kundera.client.ClientResolver  - Finishing factory initialization
2012-09-11 14:48:41,933 [INFO ] [main] com.impetus.kundera.loader.GenericClientFactory  - Loading client metadata for persistence unit : cassandra_pu
2012-09-11 14:48:41,934 [INFO ] [main] com.impetus.kundera.loader.GenericClientFactory  - Initializing client for persistence unit : cassandra_pu
2012-09-11 14:48:41,934 [INFO ] [main] com.impetus.client.cassandra.pelops.PelopsClientFactory  - Initializing Threadsafe Indexmanager. Is it really threadsafe?
2012-09-11 14:48:41,958 [INFO ] [main] com.impetus.client.cassandra.config.CassandraPropertyReader  - No property file found in class path, kundera will use def
ault property
2012-09-11 14:48:41,958 [INFO ] [main] com.impetus.kundera.loader.GenericClientFactory  - Constructing pool for persistence unit : cassandra_pu
2012-09-11 14:48:41,966 [INFO ] [main] org.scale7.cassandra.pelops.Cluster  - Dynamic node discovery is disabled, using [127.0.0.1] as a static list of nodes
2012-09-11 14:48:41,974 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Initialising pool configuration policy: Config{maxActivePerNode=20,
 maxTotal=-1, maxIdlePerNode=10, minIdlePerNode=10, maxWaitForConnection=4000, testConnectionsWhileIdle=true, timeBetweenScheduledMaintenanceTaskRunsMillis=6000
0, nodeDownSuspensionMillis=10000}
2012-09-11 14:48:41,975 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Initialising pool node selection strategy: org.scale7.cassandra.pel
ops.pool.LeastLoadedNodeSelectionStrategy@3b75078b
2012-09-11 14:48:41,975 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Initialising pool node suspension strategy: org.scale7.cassandra.pe
lops.pool.NoOpNodeSuspensionStrategy@2e5bbd6
2012-09-11 14:48:41,976 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Initialising pool connection validator: org.scale7.cassandra.pelops
.pool.DescribeVersionConnectionValidator@2c19e15c
2012-09-11 14:48:41,985 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Pre-initialising connections for nodes: [127.0.0.1:9160]
2012-09-11 14:48:41,986 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Adding node '127.0.0.1' to the pool...
2012-09-11 14:48:42,030 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Registering MBean 'com.scale7.cassandra.pelops.pool:type=PooledNode
-KunderaExamples-127.0.0.1'...
2012-09-11 14:48:42,068 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Running maintenance tasks during initialization...
2012-09-11 14:48:42,074 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Configuring scheduled tasks to run every 60000 milliseconds
2012-09-11 14:48:42,082 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Registering MBean 'com.scale7.cassandra.pelops.pool:type=Pool-Kunde
raExamples'...
2012-09-11 14:48:42,083 [INFO ] [main] org.scale7.cassandra.pelops.Pelops  - Pelops adds new pool 127.0.0.1:9160:KunderaExamples
2012-09-11 14:48:42,083 [INFO ] [main] com.impetus.kundera.configure.MetamodelConfiguration  - No class to scan for persistence unit cassandra_pu. Entities will
 be loaded from classpath/ context-path
2012-09-11 14:48:42,089 [INFO ] [main] com.impetus.kundera.persistence.EntityManagerFactoryImpl  - EntityManagerFactory created for persistence unit : cassandra
_pu
2012-09-11 14:48:42,103 [INFO ] [main] com.impetus.kundera.client.ClientResolver  - Returning client instance for:cassandra_pu
2012-09-11 14:48:42,111 [WARN ] [main] com.impetus.kundera.metadata.KunderaMetadataManager  - No Entity metadata found for the class class org.rege.arseis.kunde
ra.User. Any CRUD operation on this entity will fail.If your entity is for RDBMS, make sure you put fully qualified entity class name under <class></class> tag 
in persistence.xml for RDBMS persistence unit. Returning null value.
Exception in thread "main" com.impetus.kundera.KunderaException: java.lang.NullPointerException
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:285)
    at org.rege.arseis.kundera.KunderaExample.main(KunderaExample.java:22)
Caused by: java.lang.NullPointerException
    at com.impetus.kundera.persistence.event.EntityEventDispatcher.fireEventListeners(EntityEventDispatcher.java:53)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:134)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:279)
    ... 1 more
</pre>

**Comment by mevivs** [comment]
This happens if entity is not annotated with @Table annotation or corresponding persistence.xml is not in classpath.

Kindly download 
https://github.com/downloads/impetus-opensource/Kundera-Examples/project%20(1).zip

for reference.

-Vivek

**Comment by vavava** [comment]
But it is:

<pre>
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
@Entity
@Table(name = "users", schema = "KunderaExamples@cassandra_pu")
public class User {
...
</pre>

Also, if i omit the persistence.xml from the classpath i get a different error, specifically saying so: 

<pre>
2012-09-11 15:13:29,036 [INFO ] [main] com.impetus.kundera.KunderaPersistence  - Loading Core
2012-09-11 15:13:29,038 [INFO ] [main] com.impetus.kundera.loader.CoreLoader  - Loading Kundera Core Metdata ... 
2012-09-11 15:13:29,040 [INFO ] [main] com.impetus.kundera.KunderaPersistence  - Loading Application MetaData and Initializing Client(s) For Persistence Unit(s)
 cassandra_pu
2012-09-11 15:13:29,048 [INFO ] [main] com.impetus.kundera.configure.PersistenceUnitConfiguration  - Loading Metadata from persistence.xml ...
2012-09-11 15:13:29,063 [INFO ] [main] com.impetus.kundera.configure.PersistenceUnitConfiguration  - Could not find any META-INF/persistence.xml  file in the cl
asspath
2012-09-11 15:13:29,063 [ERROR] [main] com.impetus.kundera.configure.PersistenceUnitConfiguration  - Error occurred during persistence unit configuration, Cause
d by:Could not find any META-INF/persistence.xml  file in the classpath
Exception in thread "main" com.impetus.kundera.loader.PersistenceLoaderException: com.impetus.kundera.utils.InvalidConfigurationException: Could not find any ME
TA-INF/persistence.xml  file in the classpath
    at com.impetus.kundera.configure.PersistenceUnitConfiguration.configure(PersistenceUnitConfiguration.java:103)
    at com.impetus.kundera.configure.Configurator.configure(Configurator.java:67)
    at com.impetus.kundera.KunderaPersistence.initializeKundera(KunderaPersistence.java:99)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:75)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at org.rege.arseis.kundera.KunderaExample.main(KunderaExample.java:13)
Caused by: com.impetus.kundera.utils.InvalidConfigurationException: Could not find any META-INF/persistence.xml  file in the classpath
    at com.impetus.kundera.configure.PersistenceUnitConfiguration.findPersistenceMetadatas(PersistenceUnitConfiguration.java:131)
    at com.impetus.kundera.configure.PersistenceUnitConfiguration.configure(PersistenceUnitConfiguration.java:86)
    ... 6 more
</pre>

**Comment by mevivs** [comment]
Looks like persistence unit is in classpath, but classes are not. Either add your classes within `<class/>`` or try to make them available in root folder of your persistence.xml

Please download and refer above mentioned project.

**Comment by jackchappelear** [comment]
Thanx I was able to resolve the issue. After some fiddling with maven proxies I got the sample to work fine.

**Comment by xamry** [comment]
Great!
