### ISSUE TITLE
ClassNotFoundException: com.impetus.client.mongodb.MongoDBClientFactory

### ISSUE THREAD

**Issue by felixgao** [Impetus/kundera#122]
Not sure if I did something wrong here.

added the following dependencies
        <dependency>
            <groupId>com.impetus.core</groupId>
            <artifactId>kundera-core</artifactId>
            <version>2.1</version>
        </dependency>
        <dependency>
            <groupId>com.impetus.client</groupId>
            <artifactId>kundera-mongo</artifactId>
            <version>2.1</version>
        </dependency>

com.impetus.kundera.client.ClientResolverException: java.lang.ClassNotFoundException: com.impetus.client.mongodb.MongoDBClientFactory
    at com.impetus.kundera.client.ClientResolver.getClientFactory(ClientResolver.java:104)
    at com.impetus.kundera.configure.ClientFactoryConfiguraton.configure(ClientFactoryConfiguraton.java:57)
    at com.impetus.kundera.configure.Configurator.configure(Configurator.java:64)
    at com.impetus.kundera.KunderaPersistence.initializeKundera(KunderaPersistence.java:103)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:81)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at com.katami.offline.loader.mongo.osm.BaseDao.startup(BaseDao.java:21)
    at com.katami.offline.loader.mongo.osm.dao.NodeDaoImpl.init(NodeDaoImpl.java:32)
    at com.katami.offline.loader.mongo.osm.dao.NodeDaoImplTest.insertOnePlaceTest(NodeDaoImplTest.java:31)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
    at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:71)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:199)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.lang.ClassNotFoundException: com.impetus.client.mongodb.MongoDBClientFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at com.impetus.kundera.client.ClientResolver.getClientFactory(ClientResolver.java:89)
    ... 36 more

**Comment by mevivs** [comment]
Dependencies looks ok. Please share repository settings. Or please verify if kundera mongo jar is downloaded and available in classpath.
-Vivek

**Comment by kkmishra** [comment]
Hi felixgao,

I tried run in 5 min example :-
https://github.com/impetus-opensource/Kundera/wiki/Getting-Started-in-5-minutes,
with dependency :-
https://github.com/downloads/impetus-opensource/Kundera/kundera-mongo-2.1-jar-with-dependencies.jar

and its working fine for me

please let me know, If you encounter with any other problem.

Thanks
Kuldeep

**Comment by felixgao** [comment]
The following is in my repository tag

``` xml
<repositories>
      <repository>
        <id>sonatype-nexus</id>
        <name>Kundera Public Repository</name>
        <url>https://oss.sonatype.org/content/repositories/releases</url>
        <releases>
          <enabled>true</enabled>
        </releases>
        <snapshots>
          <enabled>true</enabled>
        </snapshots>
      </repository>
      <repository>
        <id>riptano</id>
        <name>riptano</name>
        <url>http://mvn.riptano.com/content/repositories/public</url>
      </repository>
      <repository>
            <id>kundera-snapshot</id>
            <name>Kundera Snapshot Repository</name>
            <url>http://kundera.googlecode.com/svn/maven2/maven-repo-snapshot/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>morphia.googlecode.com</id>
            <name>Morphia Repo at Google Code</name>
            <url>http://morphia.googlecode.com/svn/mavenrepo</url>
        </repository>
        <repository>
            <id>kundera-release</id>
            <name>Kundera Release Repository</name>
            <url>http://kundera.googlecode.com/svn/maven2/maven-repo-release/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>kundera-missing</id>
            <name>Kundera Public Missing Resources Repository</name>
            <url>http://kundera.googlecode.com/svn/maven2/maven-missing-resources/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
  </repositories>
```

When I look at my ide. only com.impetus.core is in the class path.  However,
[11:15:32][/]> ls -alR ~/.m2/repository/com/impetus/client/kundera-mongo/2.1/
total 120
drwxr-xr-x  7 felixgao  staff    238 Sep 29 16:53 .
drwxr-xr-x  3 felixgao  staff    102 Sep 29 16:53 ..
-rw-r--r--  1 felixgao  staff    202 Sep 29 16:53 _maven.repositories
-rw-r--r--  1 felixgao  staff  41136 Sep 29 16:53 kundera-mongo-2.1.jar
-rw-r--r--  1 felixgao  staff     40 Sep 29 16:53 kundera-mongo-2.1.jar.sha1
-rw-r--r--  1 felixgao  staff   1693 Sep 29 16:53 kundera-mongo-2.1.pom
-rw-r--r--  1 felixgao  staff     40 Sep 29 16:53 kundera-mongo-2.1.pom.sha1
The jar files is downloaded locally.  

So I think it might be a problem with IntelliJ.

**Comment by mevivs** [comment]
I guess it is working fine now. Please verify.

-Vivek
