### ISSUE TITLE
Kundera 2.0.3 pom.xml contains no transitive dependencies

### ISSUE THREAD

**Issue by wingnut** [Impetus/kundera#13]
The transitive dependencies for 2.0.3 are missing from the pom.xml

Looks OK for 2.0.1 and 2.0.2 in:
http://kundera.googlecode.com/svn/maven2/maven-missing-resources/com/impetus/kundera

**Comment by mevivs** [comment]
Kundera google code needs to be updated for this.

**Comment by mevivs** [comment]
Done.

**Comment by wingnut** [comment]
Thanks!

However, I have a new problem when using the pom.

My code works fine in eclipse from a junit test when running against a standalone Cassandra 0.8.2 IF i have an eclipse "external jar" dependency to the kundera-2.0.3-jar-with-dependencies.jar. All I try to do is persist one entity.

But it fails on a nullpointer inside KunderaIndexer if I use the new pom instead:

javax.persistence.PersistenceException: java.lang.NullPointerException
    at com.impetus.kundera.ejb.EntityManagerImpl.persist(EntityManagerImpl.java:356)
    at com.ericsson.research.warp.sensors.ResourceRegistryResource.registerProxy(ResourceRegistryResource.java:50)
    at com.ericsson.research.warp.sensors.ResourceRegistryResourceTest.registerProxy(ResourceRegistryResourceTest.java:108)
    at com.ericsson.research.warp.sensors.ResourceRegistryResourceTest.runTestsInOrder(ResourceRegistryResourceTest.java:82)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.NullPointerException
    at org.apache.cassandra.db.ColumnFamily.<init>(ColumnFamily.java:82)
    at org.apache.cassandra.db.ColumnFamily.create(ColumnFamily.java:70)
    at org.apache.cassandra.db.ColumnFamily.create(ColumnFamily.java:65)
    at org.apache.cassandra.db.RowMutation.add(RowMutation.java:150)
    at org.apache.cassandra.db.RowMutation.add(RowMutation.java:170)
    at lucandra.CassandraUtils.addMutations(CassandraUtils.java:525)
    at lucandra.IndexWriter.addDocument(IndexWriter.java:250)
    at com.impetus.kundera.index.KunderaIndexer.indexDocument(KunderaIndexer.java:411)
    at com.impetus.kundera.index.KunderaIndexer.onPersist(KunderaIndexer.java:318)
    at com.impetus.kundera.index.KunderaIndexer.performIndexing(KunderaIndexer.java:232)
    at com.impetus.kundera.index.KunderaIndexer.index(KunderaIndexer.java:174)
    at com.impetus.kundera.index.IndexManager.write(IndexManager.java:119)
    at com.impetus.kundera.ejb.EntityManagerImpl.persist(EntityManagerImpl.java:347)
    ... 26 more

**Comment by mevivs** [comment]
looks like...column family or keyspace is not already created!

**Comment by wingnut** [comment]
Yes, that was my guess too based on my debugging attempts.
However, it works fine from within Eclipse using an explicit external jar dependency.

**Comment by mevivs** [comment]
really strange.. could you please try extracting kundera dependency jar and all into classpath?

**Comment by wingnut** [comment]
Tried adding the kundera-2.0.3-jar-with-dependencies.jar to our maven repo and using that explicitly instead of the "real" dependency. Same result. Even stranger...

**Comment by mevivs** [comment]
Hi,
Did you try 
Unzip kundera-2.0.3-jar-with-dependencies.jar

and adding all jars into classpath?

Vivek

**Comment by mevivs** [comment]
I suggest to take a look on new 2.0.4 release. All such issues are resolved.

Sincerely,
Vivek

**Comment by xamry** [comment]
fixed in 2.0.4, closing
