### ISSUE TITLE
JPQL queries without WHERE clause or parameters fail

### ISSUE THREAD

**Issue by jacek99** [Impetus/kundera#136]
it seems that any JPQL query without any parameters gets rejected by Kundera Cassandra.

e.g.

DELETE FROM Country

gives us

javax.persistence.PersistenceException: Bad query format: Country
    at com.impetus.kundera.query.KunderaQuery.initEntityClass(KunderaQuery.java:349) ~[kundera-cassandra-2.1-jar-with-dependencies.jar:na]
    at com.impetus.kundera.query.KunderaQuery.postParsingInit(KunderaQuery.java:334) ~[kundera-cassandra-2.1-jar-with-dependencies.jar:na]
    at com.impetus.kundera.query.QueryResolver.getQueryImplementation(QueryResolver.java:75) ~[kundera-cassandra-2.1-jar-with-dependencies.jar:na]
    at com.impetus.kundera.persistence.PersistenceDelegator.createQuery(PersistenceDelegator.java:558) ~[kundera-cassandra-2.1-jar-with-dependencies.jar:na]
    at com.impetus.kundera.persistence.EntityManagerImpl.createQuery(EntityManagerImpl.java:441) ~[kundera-cassandra-2.1-jar-with-dependencies.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_09]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_09]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_09]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_09]
    at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:365) ~[spring-orm-3.1.2.RELEASE.jar:3.1.2.RELEASE]
    at $Proxy29.createQuery(Unknown Source) ~[na:na]

Likewise for "SELECT FROM Country"

If I look at the code in KunderaQuery (lines 334-349) it does some weird splitting on ":" or "? " and if it doesn't find it rejects the query as invalid.

The Country entity in this case is trivial (with some Lombok @Data annotations)

@Entity
@Table(name="countries", schema="SCHEDULING@scheduling_pu")
@Data @EqualsAndHashCode(of="countryCode") @ToString(of={"countryCode","name"})
public class Country {
    @Id @Column(name="country_code")
    private String countryCode;
    @Column(name="name")
    private String name;
}

**Comment by mevivs** [comment]
"DELETE FROM Country c " should work for you.

**Comment by mevivs** [comment]
It' s minor bug and it should have worked without giving alias as well!

Here is a test case to demonstrate the same:

https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/crud/PersonCassandraTest.java

Method: onInsertCassandra

Sample:

```
        // Delete without WHERE clause.

        String deleteQuery = "DELETE from PersonCassandra p";
        q = em.createQuery(deleteQuery);
        Assert.assertEquals(3, q.executeUpdate());
```

-Vivek

**Comment by xamry** [comment]
Fixed. All below variations are valid:
select p from Person p
select from Person p
select from Person.

For valid JPA grammar, see:
http://openjpa.apache.org/builds/1.0.4/apache-openjpa-1.0.4/docs/manual/jpa_langref.html#jpa_langref_bnf

In summary: 

select_statement ::= select_clause from_clause [where_clause] [groupby_clause] [having_clause] [orderby_clause]
update_statement ::= update_clause [where_clause]
delete_statement ::= delete_clause [where_clause]

from_clause ::= FROM identification_variable_declaration {, {identification_variable_declaration | collection_member_declaration}}\* 
update_clause ::= UPDATE abstract_schema_name [[ AS ] identification_variable] SET update_item {, update_item}\* 
delete_clause ::= DELETE FROM abstract_schema_name [[ AS ] identification_variable] 

Here identification variable is optional for UPDATE and DELETE queries, while mandatory for SELECT queries.

Closing...
Amresh
