### ISSUE TITLE
Kundera on glassfish 3.1

### ISSUE THREAD

**Issue by sahlex** [Impetus/kundera#16]
Hi.

When I deploy a war project using kundera 2.0.4 on glassfish I get the following exception.

<pre>
PWC1406: Servlet.service() for servlet com.brodos.cassandra.Application threw exception
org.apache.commons.lang.NotImplementedException: TODO
        at com.impetus.kundera.persistence.EntityManagerImpl.createQuery(EntityManagerImpl.java:323)
        at com.sun.enterprise.container.common.impl.EntityManagerWrapper.createQuery(EntityManagerWrapper.java:468)
        at com.brodos.cassandra.business.event.boundary.EventResource.readEvents(EventResource.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1052)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1124)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:5366)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:619)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:861)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doAround(SystemInterceptorProxy.java:162)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:144)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:861)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:370)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:5338)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:5326)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:214)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
        at $Proxy377.readEvents(Unknown Source)
        at com.brodos.cassandra.business.event.boundary.__EJB31_Generated__EventResource__Intf____Bean__.readEvents(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1539)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:281)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:98)
        at com.sun.enterprise.web.PESessionLockingStandardPipeline.invoke(PESessionLockingStandardPipeline.java:91)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:162)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:330)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:231)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:232)
        at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:828)
        at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:725)
        at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1019)
        at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:225)
        at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
        at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
        at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
        at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
        at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
        at java.lang.Thread.run(Thread.java:662)
</pre>

I provided the kundera-cassandra-2.0.4-jar-with-dependencies.jar in the domain/lib directory.
If I run the same code in a jar project its working fine.

Best regards, 

Alexander.

**Comment by sahlex** [comment]
Ok, this seems to be because kundera does not support

```
Query q = em.createQuery("select e from LogEvent e", EventLog.class);
```

When I change it to 

```
Query q = em.createQuery("select e from LogEvent e");
```

Exception is:

<pre>
javax.persistence.PersistenceException: No entity found by the name: LogEvent
        at com.impetus.kundera.query.KunderaQuery.initEntityClass(KunderaQuery.java:252)
        at com.impetus.kundera.query.KunderaQuery.postParsingInit(KunderaQuery.java:214)
        at com.impetus.kundera.query.QueryResolver.getQueryImplementation(QueryResolver.java:52)
        at com.impetus.kundera.persistence.PersistenceDelegator.createQuery(PersistenceDelegator.java:549)
        at com.impetus.kundera.persistence.EntityManagerImpl.createQuery(EntityManagerImpl.java:174)
        at com.sun.enterprise.container.common.impl.EntityManagerWrapper.createQuery(EntityManagerWrapper.java:436)
        at com.brodos.cassandra.business.event.boundary.EventResource.readEvents(EventResource.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1052)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1124)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:5366)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:619)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:861)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doAround(SystemInterceptorProxy.java:162)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:144)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:861)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:370)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:5338)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:5326)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:214)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
        at $Proxy379.readEvents(Unknown Source)
        at com.brodos.cassandra.business.event.boundary.__EJB31_Generated__EventResource__Intf____Bean__.readEvents(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1539)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:281)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:98)
        at com.sun.enterprise.web.PESessionLockingStandardPipeline.invoke(PESessionLockingStandardPipeline.java:91)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:162)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:330)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:231)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:232)
        at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:828)
        at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:725)
        at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1019)
        at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:225)
        at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
        at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
        at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
        at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
        at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
        at java.lang.Thread.run(Thread.java:662)
</pre>


persistence.xml is:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
    <persistence-unit name="eventsPU">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <properties>
            <property name="kundera.nodes" value="localhost"/>
            <property name="kundera.port" value="9160"/>
            <property name="kundera.keyspace" value="Log"/>
            <property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.client" value="Pelops"/>
            <property name="kundera.cache.provider_class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
        </properties>
    </persistence-unit>
</persistence>
```

Best regards,
Alexander

**Comment by mevivs** [comment]
Hi,
Wait for 2.0.5 release as it will have other some more stronger query support.

With Best Regards,
Vivek

**Comment by mevivs** [comment]
Please map your entity in persistence.xml as like

```
        <class>com.impetus.kundera.pbpoc.entities.StatsFactDetail</class>           
```

Make an entry like this replace it with LogEvent.

**Comment by sahlex** [comment]
I tried that before with the same result...

**Comment by sahlex** [comment]
BTW, When will 2.0.5 be released?

**Comment by sahlex** [comment]
Perhaps the bundeled kundera-client (with dependencies) is responsible for this? If I build the war, every dependency is placed in the war despite the fact, that in kundera-cassandra-2.0.4-jar-with-dependencies.jar all libraries are included. 

That is because the dependencies in the kundera-cassandra 2.0.4 pom.xml are of (implicit) scope compile and thus maven will place them in the war (if not excluded from dependency explicitly).

As mentioned earlier, the same code is working in a standalone jar (without injection and JavaEE stuff of course, but the persistence.xml is the same).

**Comment by mevivs** [comment]
It is slated for january end release.

LogEvent -> EventLog.class looks like pointing to different names !

If firing a query like select e from LogEvent e. it has to be same entity name.

please verify.

**Comment by sahlex** [comment]
Sorry, just a typo, the program code is correct.... :-(

**Comment by mevivs** [comment]
Could you please post your entity defintition here?

**Comment by sahlex** [comment]
How about attaching the whole project? Is it possible?

Here you are:

``` java
package com.brodos.cassandra.business.event.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 */
@Entity(name="LogEvent")
@Table(schema="Log@eventsPU", name="LogEvent")
// @Table(schema="Log", name="LogEvent")
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class LogEvent {

    @XmlAttribute
    @Id
    String id;

    @XmlElement
    @Column(name="message")
    private String Message;

    @XmlAttribute
    @Column(name="level")
    private String level;

    @XmlAttribute
    @Column(name="timestamp")
    private Long timestamp = new Date().getTime();

    public LogEvent() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMessage() {
        return Message;
    }

    public void setMessage(String Message) {
        this.Message = Message;
    }

    public Level getLevel() {
        return Level.valueOf(level);
    }

    public void setLevel(Level level) {
        this.level = level.toString();
    }

    public Date getTimestamp() {
        return new Date(timestamp);
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp.getTime();
    }
}
```

**Comment by mevivs** [comment]
Please paste ur persistence.xml entries

**Comment by mevivs** [comment]
Looks OK. Just wanted to know if your persistence.xml is loaded properly or not? Can you please verify if it is in persistence.xml? As what looks to me is ur PU is not loaded properly.

Those Xml annotations required for something else than kundera?

**Comment by sahlex** [comment]
The XmlAnnotations are for returning the entity via restful interface (jersey in case of glassfish). I might try without those...

In the meanwhile I create the EntityManager instance using a direct call to Persistence.createEntityManagerFactory infavor of injection via @PersistenceContext.

The persistence unit gets loaded as I see these entries in the log file:

<pre>
[#|2012-01-03T08:41:59.897+0000|INFO|glassfish3.1.1|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=35;_ThreadName=Thread-2;|2012-01-03 08:41:59,897 [INFO ] [http-thread-pool-10080(5)] com.impetus.kundera.KunderaPersistence  - Loading Core                                                                           
|#]                                                                                                                                                                      

[#|2012-01-03T08:41:59.898+0000|INFO|glassfish3.1.1|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=35;_ThreadName=Thread-2;|2012-01-03 08:41:59,897 [INFO ] [http-thread-pool-10080(5)] com.impetus.kundera.loader.CoreLoader  - Loading factories ...                                                                   
|#]                                                                                                                                                                      

[#|2012-01-03T08:41:59.921+0000|INFO|glassfish3.1.1|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=35;_ThreadName=Thread-2;|2012-01-03 08:41:59,921 [INFO ] [http-thread-pool-10080(5)] com.impetus.kundera.persistence.EntityManagerFactoryImpl  - EntityManagerFactory created for persistence unit : eventsPU         
|#]                                                                                                                                                                      
</pre>


persistence.xml is:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
  <persistence-unit name="eventsPU">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>com.brodos.cassandra.business.event.entity.LogEvent</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>
    <properties>
      <property name="kundera.nodes" value="localhost"/>
      <property name="kundera.port" value="9160"/>
      <property name="kundera.keyspace" value="Log"/>
      <property name="kundera.dialect" value="cassandra"/>
      <property name="kundera.client" value="Pelops"/>
      <property name="kundera.cache.provider_class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
    </properties>
  </persistence-unit>
</persistence>
```

If I could hand you the project over (just 4k) you could perhaps try it yourself?

Best regards and thanks for your help,

Alexander.

**Comment by sahlex** [comment]
Removing the Xml\* annotations doesn't change a thing.

As the code is running without glassfish in the backgroung I think it's some interference with the glassfish classes...

**Comment by mevivs** [comment]
Can you please email it to me at  vivek.mishra@yahoo.com

Thanks,
Vivek

**Comment by mevivs** [comment]
Can you please email complete project to me at vivek.mishra@yahoo.com

**Comment by sahlex** [comment]
Hi.

With the project I mailed you the exception is gone. The problem seems to be with the kundera-2.0.4-with-dependencies.
If I explicitly set the dependencies and exclude some stuff glassfish provides by itself, its running without exception.

But...

_No entities are returned...._

Keep on going :-) (as I will do as well...)

Best regards,

Alexander.

**Comment by mevivs** [comment]
Can you connect me to IM on gtalk or yahoo?

**Comment by mevivs** [comment]
In case if you are looking for support on secondry index on cassandra? It will be in 2.0.5 release alongwith 1.0.x cassandra migration.

So if you persist entities via kundera you will be able to find them. as it create lucene based indexes required for search.

**Comment by sahlex** [comment]
Ahhh, that's the reason for why I don't get the entities I did not create with kundera. 
Entities created with kundera do show up!

Thx.

**Comment by mevivs** [comment]
Ok..
Wait for this month end release, as we will release JPA support over secondary index support over cassandra in this. So that u can execute queries. on a single entities and as well as (Cross Store persisted entities).

Sincerely,
Vivek

**Comment by sahlex** [comment]
Where is the lucene index stored? And is there a way to rebuild it?

**Comment by mevivs** [comment]
As of now, these will be stored at $user_home$/lucene folder.

**Comment by mevivs** [comment]
IT is made configurable now with 2.0.5.

**Comment by thizzle** [comment]
Hey, can the OP please submit more details about how he fixed this issue? I'm running into the same issue with Jersey 1.13 and Kundera 2.0.8 (mongodb).
I'm getting that `No entity found by the name: User` error when attempting to create a query from an EntityManager instance.

Thanks!

**Comment by mevivs** [comment]
Please refer https://github.com/impetus-opensource/Kundera/issues/90 for more clarification and i guess it may not be working because of same reason.

-Vivek

**Comment by thizzle** [comment]
Thanks for the tip! Using the latest version (2.0.8-SNAPSHOT) appears to have resolved this issue for me. Kundera now correctly finds my JPA-annotated entity classes.
