### ISSUE TITLE
Compound Key issue

### ISSUE THREAD

**Issue by rramdin** [Impetus/kundera#168]
I tried following your guide for compound keys, and I believe I did so basically verbatim. Here is my code:

```
@Entity
@Table(name = "executions", schema = "data_test@dev_cluster")
public class Execution implements IExecution {

    @EmbeddedId
    private ExecutionId id;

    @Column(name = "time_stamp")
    private long timeStamp;

    @Column(name = "message_time")
    private long messageTime;

    @Column(name = "quantity")
    private BigDecimal quantity;

    @Column(name = "price")
    private BigDecimal price;

    public Execution() {

    }
    .....
}

@Embeddable
public class ExecutionId implements Serializable {

    @Column(name = "order_unique_id")
    private String orderUniqueId;

    @Column(name = "execution_id")
    private String executionId;

    public ExecutionId() {

    };
    ....
}
```

Here is my test:

```
    Execution e = ....
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("dev_cluster");
    EntityManager em = emf.createEntityManager();
    em.setProperty("cql.version", "3.0.0");     
    em.persist(e);
```

This is what I'm getting:

Exception in thread "main" java.lang.ClassCastException: com.impetus.kundera.metadata.model.type.DefaultEmbeddableType cannot be cast to com.impetus.kundera.metadata.model.type.AbstractIdentifiableType
    at com.impetus.kundera.metadata.processor.MetaModelBuilder$TypeBuilder$AttributeBuilder.build(MetaModelBuilder.java:407)
    at com.impetus.kundera.metadata.processor.MetaModelBuilder$TypeBuilder.build(MetaModelBuilder.java:303)
    at com.impetus.kundera.metadata.processor.MetaModelBuilder$TypeBuilder.processOnEmbeddables(MetaModelBuilder.java:279)
    at com.impetus.kundera.metadata.processor.MetaModelBuilder$TypeBuilder.buildType(MetaModelBuilder.java:209)
    at com.impetus.kundera.metadata.processor.MetaModelBuilder$TypeBuilder.build(MetaModelBuilder.java:303)
    at com.impetus.kundera.metadata.processor.MetaModelBuilder.construct(MetaModelBuilder.java:139)
    at com.impetus.kundera.metadata.processor.TableProcessor.populateMetadata(TableProcessor.java:140)
    at com.impetus.kundera.metadata.processor.TableProcessor.process(TableProcessor.java:87)
    at com.impetus.kundera.metadata.MetadataBuilder.buildEntityMetadata(MetadataBuilder.java:118)
    at com.impetus.kundera.configure.MetamodelConfiguration.scanClassAndPutMetadata(MetamodelConfiguration.java:346)
    at com.impetus.kundera.configure.MetamodelConfiguration.loadEntityMetadata(MetamodelConfiguration.java:222)
    at com.impetus.kundera.configure.MetamodelConfiguration.configure(MetamodelConfiguration.java:103)
    at com.impetus.kundera.configure.Configurator.configure(Configurator.java:65)
    at com.impetus.kundera.KunderaPersistence.initializeKundera(KunderaPersistence.java:104)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:77)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)

Using version 2.3.

**Comment by mevivs** [comment]
Can you please your db script to create column family.

-Vivek

**Comment by rramdin** [comment]
```
CREATE TABLE executions (
    order_unique_id varchar,
    execution_id varchar,
    time_stamp bigint,
    message_time bigint,
    price decimal,
    quantity decimal,
    PRIMARY KEY (order_unique_id, execution_id)
);
```

**Comment by mevivs** [comment]
This is what i have tried as junit:

```
@Entity
@Table(name = "executions", schema = "CompositeCassandra@compositedatatype")
public class Execution {

    @EmbeddedId
    private ExecutionId id;

    @Column(name = "time_stamp")
    private long timeStamp;

    @Column(name = "message_time")
    private long messageTime;

    @Column(name = "quantity")
    private BigDecimal quantity;

    @Column(name = "price")
    private BigDecimal price;

    public Execution() {

    }
// setters and getters.
}

```

Embeddable Entity

```
@Embeddable
public class ExecutionId
{

    @Column(name = "order_unique_id")
    private String orderUniqueId;

    @Column(name = "execution_id")
    private String executionId;

    public ExecutionId() {

    }

    public String getOrderUniqueId()
    {
        return orderUniqueId;
    }

    public void setOrderUniqueId(String orderUniqueId)
    {
        this.orderUniqueId = orderUniqueId;
    }

    public String getExecutionId()
    {
        return executionId;
    }

    public void setExecutionId(String executionId)
    {
        this.executionId = executionId;
    }

```

Junit:

```
package com.impetus.client.crud.compositeType;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import junit.framework.Assert;

import org.apache.cassandra.thrift.InvalidRequestException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.thrift.TException;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.impetus.client.persistence.CassandraCli;


public class CompoundKeyJunitTests
{

    private static final String PERSISTENCE_UNIT = "compositedatatype";

    private EntityManagerFactory emf;

    /** The Constant logger. */
    private static final Log logger = LogFactory.getLog(CompositeDataTypeTest.class);

    /**
     * @throws java.lang.Exception
     */
    @Before
    public void setUp() throws Exception
    {
        CassandraCli.cassandraSetUp();
        CassandraCli.initClient();
        loadData();
        emf = Persistence.createEntityManagerFactory(PERSISTENCE_UNIT);
    }

    @Test
    public void onCRUD() throws InstantiationException, IllegalAccessException
    {
        EntityManager em = emf.createEntityManager();
        em.setProperty("cql.version", "3.0.0");  
        ExecutionId executionId = new ExecutionId();
        executionId.setExecutionId("1_e");
        executionId.setOrderUniqueId("1_o");
        Execution execution = new Execution();
        execution.setId(executionId);
        execution.setMessageTime(System.currentTimeMillis());
        execution.setTimeStamp(new Date().getTime());
        em.persist(execution);

        em.clear();

        Execution e = em.find(Execution.class, executionId);
        Assert.assertNotNull(e);
        Assert.assertEquals("1_e", e.getId().getExecutionId());

    }

    @After
    public void tearDown()
    {
        CassandraCli.dropKeySpace("CompositeCassandra");
    }
    private void loadData()
    {

        CassandraCli.createKeySpace("CompositeCassandra");
       String cql_Query = " CREATE TABLE executions (order_unique_id varchar,execution_id varchar, time_stamp bigint, message_time bigint, price decimal, quantity decimal, PRIMARY KEY (order_unique_id, execution_id))";
        try
        {
            CassandraCli.getClient().set_keyspace("CompositeCassandra");
        }
        catch (InvalidRequestException e)
        {
            logger.error(e.getMessage());
        }
        catch (TException e)
        {
            logger.error(e.getMessage());
        }
        CassandraCli.executeCqlQuery(cql_Query);

    }

}
```

CassandraCli is using embeddedCassandraService available in kundera-cassandra/src/test/java package.

-Vivek

**Comment by mevivs** [comment]
It's working fine for me Cassandra 1.2 and Kundera 2.3

**Comment by mevivs** [comment]
Just tried by implementing IExecution (marker interface) and Embeddable with Serializable interface. Not able to find any issue.

-Vivek

**Comment by mevivs** [comment]
This error:
Exception in thread "main" java.lang.ClassCastException: com.impetus.kundera.metadata.model.type.DefaultEmbeddableType cannot be cast to com.impetus.kundera.metadata.model.type.AbstractIdentifiableType
at com.impetus.kundera.metadata.processor.MetaModelBuilder$TypeBuilder$AttributeBuilder.build(MetaModelBuilder.java:407)
at com.impetus.kundera.metadata.processor.MetaModelBuilder$TypeBuilder.build(MetaModelBuilder.java:303)
at 

can only occur if, any embeddable entity is holding a field annotated with @Id or @EmbeddedId annotation.

To Reproduce, just change this:

```
@Embeddable
public class ExecutionId implements Serializable
{

    @Column(name = "order_unique_id")
    private String orderUniqueId;

```

To

```
@Embeddable
public class ExecutionId implements Serializable
{

    @Column(name = "order_unique_id")
    @Id
    private String orderUniqueId;
```

Hope this helps to rectify issue.

Cheers,
-Vivek

**Comment by mevivs** [comment]
I will add more descriptive logging for this error.

-Vivek

**Comment by rramdin** [comment]
Thanks for your help. Transitioning from Super Columns to composite keys--I had another class with errors in it that was getting picked up (Execution vs. Executions). Thanks again!
