### ISSUE TITLE
Kundera has problems with more than one persistence unit

### ISSUE THREAD

**Issue by sahlex** [Impetus/kundera#18]
When defining two cassandra persistence units in one persistence.xml, using the second one gives an error:

<pre>
java.lang.NullPointerException
        at com.impetus.kundera.metadata.KunderaMetadataManager.getEntityMetadata(KunderaMetadataManager.java:96)
        at com.impetus.kundera.persistence.PersistenceDelegator.getMetadata(PersistenceDelegator.java:850)
        at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:464)
        at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:144)
        at com.sun.enterprise.container.common.impl.EntityManagerWrapper.persist(EntityManagerWrapper.java:269)
        at com.brodos.cassandra.business.article.control.ArticleScannerBean.scanArticles(ArticleScannerBean.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1052)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1124)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:5366)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:619)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:861)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doAround(SystemInterceptorProxy.java:162)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:144)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:861)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:370)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:5338)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:5326)
        at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:101)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
</pre>

**Comment by mevivs** [comment]
This looks to me a good issue with kundera. Quick fix needed.

Sent from Yahoo! Mail on Android

**Comment by mevivs** [comment]
Could you please explain and shae ur persistence unit?

Same set of entities pointed to different persistence unit?

**Comment by sahlex** [comment]
Here you go:

``` xml

<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
    <persistence-unit name="eventsPU">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>com.brodos.cassandra.business.event.entity.LogEvent</class>
        <exclude-unlisted-classes>true</exclude-unlisted-classes>
        <properties>
            <property name="kundera.nodes" value="localhost"/>
            <property name="kundera.port" value="9160"/>
            <property name="kundera.keyspace" value="Log"/>
            <property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.client" value="Pelops"/>
            <property name="kundera.cache.provider_class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
        </properties>
    </persistence-unit>
    <persistence-unit name="articlesPU">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>com.brodos.cassandra.business.article.entity.Article</class>
        <exclude-unlisted-classes>true</exclude-unlisted-classes>
        <properties>
            <property name="kundera.nodes" value="localhost"/>
            <property name="kundera.port" value="9160"/>
            <property name="kundera.keyspace" value="articles"/>
            <property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.client" value="Pelops"/>
            <property name="kundera.cache.provider_class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
        </properties>
    </persistence-unit>
    <persistence-unit name="tboPU" transaction-type="JTA">
        <provider>org.hibernate.ejb.HibernatePersistence</provider>
        <jta-data-source>jdbc/tbo</jta-data-source>
<!--        <class>     classes omitted...   </class> -->
        <exclude-unlisted-classes>true</exclude-unlisted-classes>
        <properties>
            <property name="hibernate.dialect" value="org.hibernate.dialect.Oracle10gDialect"/>
            <property name="hibernate.show_sql" value="false"/>
            <property name="hibernate.archive.autodetection" value="class"/>
        </properties>
    </persistence-unit>
</persistence>
```

**Comment by mevivs** [comment]
Looks ok To me.

Hi Amry,
Can we look into this please? This definitly needs a quick fix. Can we release a patch for this?

Sincerely,
Vivek

**Comment by mevivs** [comment]
While looking into persistence unit, just to share with you, you can use KunderaPersistence provider even for Hibernate.
Could you please try by removing out:

 <persistence-unit name="tboPU" transaction-type="JTA">
        <provider>org.hibernate.ejb.HibernatePersistence</provider>
        <jta-data-source>jdbc/tbo</jta-data-source>



```
    <exclude-unlisted-classes>true</exclude-unlisted-classes>
    <properties>
        <property name="hibernate.dialect" value="org.hibernate.dialect.Oracle10gDialect"/>
        <property name="hibernate.show_sql" value="false"/>
        <property name="hibernate.archive.autodetection" value="class"/>
    </properties>
</persistence-unit>
```

Still getting same error? Or if you try to point it to KunderaPersistence. Rest hibernate properties can remain same.

Thanks,
vivek

**Comment by mevivs** [comment]
I think this issue is because of Different persistence provider.

**Comment by sahlex** [comment]
When reaching the first em.createQuery of the hibernate-driven persistence unit it throws:

<pre>
javax.ejb.EJBException
        at com.sun.ejb.containers.BaseContainer.processSystemException(BaseContainer.java:5193)
        at com.sun.ejb.containers.BaseContainer.completeNewTx(BaseContainer.java:5091)
        at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4879)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2039)
        at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:114)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.NullPointerException
        at com.impetus.kundera.query.KunderaQuery.initEntityClass(KunderaQuery.java:248)
        at com.impetus.kundera.query.KunderaQuery.postParsingInit(KunderaQuery.java:214)
        at com.impetus.kundera.query.QueryResolver.getQueryImplementation(QueryResolver.java:52)
        at com.impetus.kundera.persistence.PersistenceDelegator.createQuery(PersistenceDelegator.java:549)
        at com.impetus.kundera.persistence.EntityManagerImpl.createQuery(EntityManagerImpl.java:174)
        at com.sun.enterprise.container.common.impl.EntityManagerWrapper.createQuery(EntityManagerWrapper.java:436)
        at com.brodos.cassandra.business.article.control.ArticleScannerBean.scanArticles(ArticleScannerBean.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1052)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1124)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:5366)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:619)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:861)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doAround(SystemInterceptorProxy.java:162)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:144)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:861)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:370)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:5338)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:5326)
        at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:101)
        ... 5 more

</pre>

**Comment by mevivs** [comment]
please share your persistence unit configuration for hibernate driven entity

**Comment by sahlex** [comment]
I'm talking about the very same configuration, I posted earlier. If I follow your advice and change org.hibernate.ejb.HibernatePersistence to KunderaPresistence I get the exception above.

**Comment by mevivs** [comment]
```
<persistence-unit name="tboPU" transaction-type="JTA">
         <provider>com.impetus.kundera.KunderaPersistence</provider>
        <jta-data-source>jdbc/tbo</jta-data-source>
<!--        <class>     classes omitted...   </class> -->
        <exclude-unlisted-classes>true</exclude-unlisted-classes>
        <properties>
            <property name="hibernate.dialect" value="org.hibernate.dialect.Oracle10gDialect"/>
            <property name="hibernate.show_sql" value="false"/>
            <property name="hibernate.archive.autodetection" value="class"/>
        </properties>
    </persistence-unit>
```

is this correct?

Could you try by mapping hibernate classes with in 

```
 <class>com.brodos.cassandra.business.article.entity.Article</class>
```

in case if not done already. We are already looking into this issue. will help us to understand the scenario completely.

**Comment by mevivs** [comment]
Looking into issue

**Comment by mevivs** [comment]
in case of multiple persistence units you need to create emf like this.

Persistence.createEntityManagerFactory("testHibernate,kcassandra"); 

If planning to use entities for both persistence units.

**Comment by mevivs** [comment]
Okay. i had a test around this. Created 2 persistence units pointing to same cassandra data store and 1 pointing to mysql instance. 

```
    <persistence-unit name="testHibernate">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
            <class>com.impetus.client.Player</class>            
            <class>com.impetus.client.onetoone.OTONPerson</class>           
            <class>com.impetus.client.onetoone.OTONSPerson</class>          
            <class>com.impetus.client.onetomany.OTMNPerson</class>          
            <class>com.impetus.client.onetomany.bi.OTMBNPerson</class>          
            <class>com.impetus.client.manytoone.MTONPerson</class>          
            <class>com.impetus.client.manytomany.MTMNPerson</class>         
            <class>com.impetus.client.onetoone.OTOAddress</class>           
            <class>com.impetus.client.onetoone.OTOSAddress</class>          
            <class>com.impetus.client.onetomany.OTMAddress</class>          
            <class>com.impetus.client.onetomany.bi.OTMBAddress</class>          
            <class>com.impetus.client.manytoone.MTOAddress</class>          
            <class>com.impetus.client.manytomany.MTMAddress</class>         
        <properties>            
<!--             <property name="hibernate.hbm2ddl.auto" value="create-drop"/>
 -->            <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5Dialect"/>
            <property name="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver"/>
            <property name="hibernate.connection.url" value="jdbc:mysql://localhost/test"/>
            <property name="hibernate.connection.username" value="root"/>
            <property name="kundera.client" value="rdbms"/>
            <property name="hibernate.connection.password" value="impetus"/>
            <property name="hibernate.current_session_context_class" value="org.hibernate.context.ThreadLocalSessionContext" />
            <property name="hibernate.show_sql" value="true"/>
            <property name="hibernate.format_sql" value="true"/>

        </properties>

    </persistence-unit>

        <persistence-unit name="kcassandra">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <properties>            
            <property name="kundera.nodes" value="localhost"/>
            <property name="kundera.port" value="9160"/>
            <property name="kundera.keyspace" value="KunderaKeyspace"/>
            <property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.client" value="Pelops"/>
            <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
        </properties>

    </persistence-unit>

        <persistence-unit name="kcassandra1">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <properties>            
            <property name="kundera.nodes" value="localhost"/>
            <property name="kundera.port" value="9160"/>
            <property name="kundera.keyspace" value="KunderaKeyspace"/>
            <property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.client" value="Pelops"/>
            <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
        </properties>

    </persistence-unit>
```

And added a finder method like this.

```
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("testHibernate,kcassandra,kcassandra1");

    EntityManager em = emf.createEntityManager();

    em.persist(prepareObject());

    Query q = em.createQuery("Select p from OTONPerson p");

    List<Person> p = q.getResultList();

    System.out.println(p.size());
```

---

This is working fine. But as my sql object is not persisted so indexes were not created, in result finder was not returning anything(which will be enabled in 2.0.5)

In case u want to use hibernatePersistence alongwith KunderaPersistence. Then u need to create seperate EMF for both.

As mentioned above, to deal with multiple PU's in Kundera, u need to instantiate ur EMF for both

Hope it helps.

**Comment by mevivs** [comment]
Hi Alex,
Any luck with my recent comments?

**Comment by sahlex** [comment]
Hi mevivs.

I'm not creating the EMF by myself. I'm using JEE6 injection (@PersistenceContext) to inject an EntityManager into a stateless session bean. 

In the project in question I try to transfer (ETL so to say) from one database to cassandra. So I'm reading from one database (persistence unit 1, oracle) to a different data model in cassandra (persistence unit 2). The PUs are completely independent and - as mentioned earlier - I'm not creating the entity manager factories by myself... 

Best regards, Alexander.

**Comment by impetus-opensource-admin** [comment]
Hi Alex,
To deal with multiple persistence units. EMF needs to pass comma seperated list of PUs.

i believe @PersistenceUnits(not sure whether it will help or not) does allow injection of multiple persistence units.  I can see this as a bug with in kundera, if not dealt as mentioned above.

Could you please email me your project to look into configuration and find out a way around for this?

As i can see you might be annotating different EMs with different PersistenceContexts. Kundera handles it in different way.

With warm regards,
Vivek

**Comment by sahlex** [comment]
Well, I wrote a CDI producer factory for the injection of the EntityManager (quite simple):

``` java
package com.brodos.cassandra.business.commons.control;

import javax.enterprise.inject.Produces;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;

public class EntityManagerFactory {

    @Produces
    public EntityManager getEntityManager()
    {
        javax.persistence.EntityManagerFactory emf = Persistence.createEntityManagerFactory("articlesPU,tboPU");
        return emf.createEntityManager();
    }
}
```

So i can inject the EntityManager using (which works perfect thanks to CDI)

``` java
@Inject
EntityManager em;
```

and changed my persistence.xml to :

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
    <persistence-unit name="articlesPU">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>com.brodos.cassandra.business.article.entity.Article</class>
        <exclude-unlisted-classes>true</exclude-unlisted-classes>
        <properties>
            <property name="kundera.nodes" value="localhost"/>
            <property name="kundera.port" value="9160"/>
            <property name="kundera.keyspace" value="articles"/>
            <property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.client" value="Pelops"/>
            <property name="kundera.cache.provider_class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
        </properties>
    </persistence-unit>
  <persistence-unit name="tboPU" transaction-type="JTA">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <jta-data-source>jdbc/tbo</jta-data-source>
    <class>com.brodos.tbo.entity.Address</class>
    ... (many classes here, removed them for brevity
    <class>com.brodos.tbo.entity.Countryname</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>
    <shared-cache-mode>ENABLE_SELECTIVE</shared-cache-mode>
    <properties>
      <property name="hibernate.dialect" value="org.hibernate.dialect.Oracle10gDialect"/>
      <property name="hibernate.show_sql" value="false"/>
      <property name="hibernate.archive.autodetection" value="class"/>
      <property name="kundera.client" value="rdbms"/>
      <property name="hibernate.show_sql" value="true"/>
    </properties>
  </persistence-unit>
</persistence>
```

Now I get:

<pre>
A system exception occurred during an invocation on EJB ArticleScannerBean method public void com.brodos.cassandra.business.article.control.ArticleScannerBean.scanArticles(int)                                                      
javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton ArticleScannerBean                      
        at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:721)
        at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:451)
        at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:216)
        at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:177)
        at com.sun.ejb.containers.AbstractSingletonContainer.checkInit(AbstractSingletonContainer.java:423)
        at com.sun.ejb.containers.CMCSingletonContainer._getContext(CMCSingletonContainer.java:117)
        at com.sun.ejb.containers.BaseContainer.getContext(BaseContainer.java:2528)
        at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:1895)
        at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:99)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
Caused by: javax.ejb.CreateException: Initialization failed for Singleton ArticleScannerBean
        at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:547)
        at com.sun.ejb.containers.AbstractSingletonContainer.access$100(AbstractSingletonContainer.java:79)
        at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:719)
        ... 13 more
Caused by: com.impetus.kundera.client.ClientResolverException: com.impetus.client.rdbms.RDBMSClientFactory
        at com.impetus.kundera.client.ClientResolver.getClientFactory(ClientResolver.java:93)
        at com.impetus.kundera.KunderaPersistence.initializeKundera(KunderaPersistence.java:101)
        at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:72)
        at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
        at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
        at com.brodos.cassandra.business.commons.control.EntityManagerFactory.getEntityManager(EntityManagerFactory.java:20)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.jboss.weld.util.reflection.SecureReflections$13.work(SecureReflections.java:305)
        at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:54)
        at org.jboss.weld.util.reflection.SecureReflectionAccess.runAsInvocation(SecureReflectionAccess.java:163)
        at org.jboss.weld.util.reflection.SecureReflections.invoke(SecureReflections.java:299)
        at org.jboss.weld.introspector.jlr.WeldMethodImpl.invokeOnInstance(WeldMethodImpl.java:188)
        at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstance(MethodInjectionPoint.java:169)
        at org.jboss.weld.bean.ProducerMethod$1.produce(ProducerMethod.java:149)
        at org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:361)
        at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:67)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:690)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:772)
        at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:138)
        at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:872)
        at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:884)
        at org.jboss.weld.bean.SessionBean$1$1.proceed(SessionBean.java:195)
        at org.glassfish.weld.services.InjectionServicesImpl.aroundInject(InjectionServicesImpl.java:134)
        at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:50)
        at org.jboss.weld.bean.SessionBean$1.inject(SessionBean.java:190)
        at org.glassfish.weld.services.JCDIServiceImpl.injectEJBInstance(JCDIServiceImpl.java:223)
        at com.sun.ejb.containers.BaseContainer.injectEjbInstance(BaseContainer.java:1675)
        at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:506)
        ... 15 more
|#]

</pre>

**Comment by sahlex** [comment]
Perhaps it cannot cope with jta-data-source in persistence.xml?

**Comment by mevivs** [comment]
Transactional and such support <jta-data-soure> is on roadmap.

**Comment by sahlex** [comment]
Ah ok... hmm...

**Comment by mevivs** [comment]
Except JTA it looks ok to me. Even as underlying architecture delegates rdbms calls to Hibernate. So jta-data-source should work for rdbms calls.

I did try the same to create EM and EMF like this only:

javax.persistence.EntityManagerFactory emf = Persistence.createEntityManagerFactory("articlesPU,tboPU");

It was fine. Except, as data is not persisted in rdbms via Kundera, so read did not work(as indexes were not created).

Now coming back to your exception. I can see that this is happening as trying to load RDBMS related stuff, but it is not added into path. 

In case if working with jar-with-dependencies. Please download "2.0.4-jar-withdependencies" for "RDBMS".

else add dependency in pom.xml for  "rdbms client" like given below:

```
<dependency>
    <groupId>com.impetus.client</groupId>
    <artifactId>kundera-rdbms</artifactId>
    <version>2.0.4</version>
</dependency>
```

I think this should solve your problem.

With warm regards,
Vivek

**Comment by mevivs** [comment]
Path to download rdbms one is :
https://github.com/downloads/impetus-opensource/Kundera/kundera-rdbms-2.0.4-jar-with-dependencies.jar

P.S: 2.0.5 is going to enable support of inbuilt index support,(if provided by underlying database).

Sincerely,
Vivek

**Comment by mevivs** [comment]
Done.
