### ISSUE TITLE
om.impetus.kundera.KunderaException: java.lang.ClassCastException: org.apache.hadoop.hbase.client.HTablePool$PooledHTable cannot be cast to org.apache.hadoop.hbase.client.HTable

### ISSUE THREAD

**Issue by lucarosellini** [Impetus/kundera#182]
Hello,
I am getting the following exception while running tests against an embedded HBase instance.

Why does in all of the method signatures of classes beleonging to kundera-hbase 'org.apache.hadoop.hbase.client.HTable' is used instead of its generic interface 'org.apache.hadoop.hbase.client.HTableInterface' ?

Best regards,
Luca

<code>
Caused by: com.impetus.kundera.KunderaException: java.lang.ClassCastException: org.apache.hadoop.hbase.client.HTablePool$PooledHTable cannot be cast to org.apache.hadoop.hbase.client.HTable
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:223)
    at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:365)
    at $Proxy43.persist(Unknown Source)
    at com.pt.crawler.dao.AbstractDao.persist(AbstractDao.java:47)
    ... 23 more
Caused by: java.lang.ClassCastException: org.apache.hadoop.hbase.client.HTablePool$PooledHTable cannot be cast to org.apache.hadoop.hbase.client.HTable
    at com.impetus.client.hbase.admin.HBaseDataHandler.gethTable(HBaseDataHandler.java:409)
    at com.impetus.client.hbase.admin.HBaseDataHandler.writeData(HBaseDataHandler.java:270)
    at com.impetus.client.hbase.HBaseClient.onPersist(HBaseClient.java:412)
    at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:84)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:193)
    at com.impetus.kundera.graph.Node.flush(Node.java:525)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:426)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:170)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:217)
    ... 29 more
</code>

**Comment by mevivs** [comment]
Looks like a version incompatibility issue. Kundera is compatible wit 0.92.x version. Kundera-hbase tests are already working within EmbeddedHBase, you may want to refer:
https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-hbase/src/test/java/com/impetus/client/hbase/junits/HBaseCli.java

for it's usage.

-Vivek

**Comment by mevivs** [comment]
Kundera 2.4 is upgraded for 0.94.3

**Comment by xamry** [comment]
Please verify and close

**Comment by mevivs** [comment]
Closing.

-Vivek
