### ISSUE TITLE
NullPointerException during init of entity

### ISSUE THREAD

**Issue by ralmodiel** [Impetus/kundera#195]
I'm receiving this error:

java.lang.NullPointerException
    at com.impetus.kundera.query.KunderaQuery.initEntityClass(KunderaQuery.java:358)
    at com.impetus.kundera.query.KunderaQuery.postParsingInit(KunderaQuery.java:333)
    at com.impetus.kundera.query.QueryResolver.getQueryImplementation(QueryResolver.java:75)
    at com.impetus.kundera.persistence.PersistenceDelegator.createQuery(PersistenceDelegator.java:576)
    at com.impetus.kundera.persistence.EntityManagerImpl.createNamedQuery(EntityManagerImpl.java:485)

My entity is defined like this:

package com.xxxx.mongodb.entities;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

@Entity
@Table(name = "ERROR_MESSAGES", schema="local")
@NamedQueries({
    @NamedQuery(name=ErrorMessage.FETCH_BY_LANG_ERRCODE, 
            query="select e from ErrorMessage e where e.languageCode = :langCode and e.errorCode= :errorCode " )
})
public class ErrorMessage implements java.io.Serializable {
    public final static String FETCH_BY_LANG_ERRCODE = "ErrorMessage.FETCH_BY_LANG_ERRCODE";

```
@Id
@GeneratedValue(strategy = IDENTITY)
@Column(name = "_id", unique = true, nullable = false)
private String errorId;

@Column(name = "language_code", length = 100)
private String languageCode;

@Column(name = "error_code", nullable = false, length = 20)
private String errorCode;

@Column(name = "error_message", nullable = false, length = 1000)
private String errorMessage;


public ErrorMessage() {
}

public ErrorMessage(String errorCode, String errorMessage) {
    this.errorCode = errorCode;
    this.errorMessage = errorMessage;
}


public String getErrorId() {
    return this.errorId;
}

public void setErrorId(String errorId) {
    this.errorId = errorId;
}

public String getLanguageCode() {
    return languageCode;
}

public void setLanguageCode(String languageCode) {
    this.languageCode = languageCode;
}

public String getErrorCode() {
    return this.errorCode;
}

public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
}

public String getErrorMessage() {
    return this.errorMessage;
}

public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
}

/*@JsonIgnore
public Date getDateCreated(){
    if (getErrorId()!=null){
        return(MongoDBUtils.getDateFromObjectId(getErrorId()));
    }
    return(null);
}*/
```

}

Hope you could help

**Comment by mevivs** [comment]
I will have a look . query looks ok to me.

-Vivek

**Comment by ralmodiel** [comment]
I found the problem.  It's in my persistence.xml file.  Thanks anyway. :-)

**Comment by mevivs** [comment]
Still, i would like to keep it open for better validation and logging. Do you mind opening a new issue to track for better logging?

-Vivek

**Comment by ralmodiel** [comment]
Yes please.  Do you already have a target release for the version with better validation and logging?

**Comment by mevivs** [comment]
Yes. We are doing it, so in case you have more to share around this. It will be great.

-Vivek

**Comment by eliquious** [comment]
Hey, I'm seeing this error as well. I'm new to Spring and probably also have an error in my persistence.xml file but I just can't seem to find it.

You guys have any ideas?

``` xml
<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
             version="2.0">
    <persistence-unit name="maria_pu">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>com.examples.spring.hibernate.CollectionEntity</class>

        <properties>
            <property name="kundera.client.lookup.class" value="com.impetus.client.rdbms.RDBMSClientFactory" />
            <property name="hibernate.show_sql" value="false" />
            <property name="hibernate.format_sql" value="false" />
            <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5InnoDBDialect"/>
            <property name="hibernate.connection.driver_class" value="org.mariadb.jdbc.Driver" />
            <property name="hibernate.connection.url" value="jdbc:mysql://localhost:3306/mydb" />
            <property name="hibernate.connection.username" value="root" />
            <property name="hibernate.connection.password" value="" />
            <property name="hibernate.current_session_context_class" value="thread"/>
        </properties>
    </persistence-unit>
</persistence>
```

**Comment by mevivs** [comment]
Please share com.examples.spring.hibernate.CollectionEntity  definition and CRUD code snippet

-Vivek

**Comment by eliquious** [comment]
Here's the Entity:

``` java
import common.util.persistence.AuditableEntity;
import common.util.persistence.AuditableEntityListener;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;

import javax.persistence.*;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Entity
@EntityListeners(value = { AuditableEntityListener.class})
@Table(name = "collection", schema = "", catalog = "mydb")
public class CollectionEntity {

    @Id
    @Column(name = "collection_id")
    private int collectionId;

    @Basic
    @Column(name = "collection_name")
    private String collectionName;

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinColumn(name = "collection_type_id")
    private CollectionTypeEntity collectionType;

    @Basic
    @Column(name = "active")
    private boolean active;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at")
    private Date createdDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at")
    private Date updatedDate;

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public int getCollectionId() {
        return collectionId;
    }

    public void setCollectionId(int collectionId) {
        this.collectionId = collectionId;
    }

    public String getCollectionName() {
        return collectionName;
    }

    public void setCollectionName(String collectionName) {
        this.collectionName = collectionName;
    }

    public CollectionTypeEntity getCollectionType() {
        return collectionType;
    }

    public void setCollectionTypeId(CollectionTypeEntity collectionType) {
        this.collectionType = collectionType;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }
}
```

And here's the Spring controller

``` java
import com.example.spring.hibernate.CollectionEntity;
import com.example.spring.repositories.CollectionRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.annotation.Resource;

@Controller
public class CollectionController {

    @Autowired
    private CollectionRepository collectionRepository;

    @RequestMapping(value="/collections", method= RequestMethod.GET)
    public String listCollections(ModelMap model) {
        model.addAttribute("collection", new CollectionEntity());

        // THE ERROR HAPPENS HERE
        model.addAttribute("collections", collectionRepository.findAll());
        return "collections";
    }
}
```

The error is reported when I call `findAll()` on the `collectionRepository`.

The `CollectionRepository` interface simply extends `JpaRepository<CollectionEntity, Long>`.

**Comment by eliquious** [comment]
It looks like the `getResult()` call in `KunderaQuery.initEntityClass` (line 390) is `null`.

Going back even further, the `tokenizer` for the `KunderaQueryParser` has a `queryString` of `Select  from CollectionEntity null`. Which seems to be wrong as well. I hope that gives some more insight.

**Comment by eliquious** [comment]
I've documented the error in more detail [here](http://stackoverflow.com/questions/23281335/nullpointerexception-spring-jpa-kundera-error-creating-entity-class).

**Comment by eliquious** [comment]
Has there been any progress on this issue?

**Comment by mevivs** [comment]
@eliquious 
Let me have a look and post an update by tomorrow?

-Vivek

**Comment by eliquious** [comment]
@mevivs 
Thanks! That would be great!

**Comment by mevivs** [comment]
Possible to email me sample project to have a quick look on this?

-Vivek

**Comment by eliquious** [comment]
Sure, let me put something together. I'll get it to you later today.
