### ISSUE TITLE
Cassandra DecoratedKey error !

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#222]
It has the fellow errors, when using kunder2.4 + cassandra1.2.2.
This may be the problem of Cassandra, is it right?
At this time ,i can not read data from CF by pk or index, so i need to drop CF verytime.
Can you give me some surggestions with it?

[kumdera error]
.....time out.....

[cassandra error]
DecoratedKey(162640225995110079429900120306685427741, 138167101dd211b20000242d50cf1ff7) in /var/lib/cassandra/data/pgl/savedata/pgl-savedata-he-1-Data.db
    at org.apache.cassandra.db.columniterator.SSTableSliceIterator.<init>(SSTableSliceIterator.java:60)
    at org.apache.cassandra.db.filter.SliceQueryFilter.getSSTableColumnIterator(SliceQueryFilter.java:67)
    at org.apache.cassandra.db.filter.QueryFilter.getSSTableColumnIterator(QueryFilter.java:79)
    at org.apache.cassandra.db.CollationController.collectAllData(CollationController.java:256)
    at org.apache.cassandra.db.CollationController.getTopLevelColumns(CollationController.java:64)
    at org.apache.cassandra.db.ColumnFamilyStore.getTopLevelColumns(ColumnFamilyStore.java:1345)
    at org.apache.cassandra.db.ColumnFamilyStore.getColumnFamily(ColumnFamilyStore.java:1207)
    at org.apache.cassandra.db.ColumnFamilyStore.getColumnFamily(ColumnFamilyStore.java:1137)
    at org.apache.cassandra.db.index.keys.KeysSearcher$1.computeNext(KeysSearcher.java:195)
    at org.apache.cassandra.db.index.keys.KeysSearcher$1.computeNext(KeysSearcher.java:113)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:140)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:135)
    at org.apache.cassandra.db.ColumnFamilyStore.filter(ColumnFamilyStore.java:1454)
    at org.apache.cassandra.db.index.keys.KeysSearcher.search(KeysSearcher.java:88)
    at org.apache.cassandra.db.index.SecondaryIndexManager.search(SecondaryIndexManager.java:577)
    at org.apache.cassandra.db.ColumnFamilyStore.search(ColumnFamilyStore.java:1443)
    at org.apache.cassandra.service.RangeSliceVerbHandler.executeLocally(RangeSliceVerbHandler.java:48)
    at org.apache.cassandra.service.RangeSliceVerbHandler.doVerb(RangeSliceVerbHandler.java:63)
    at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:59)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
ERROR [ReadStage:18613] 2013-03-22 09:07:26,377 AbstractCassandraDaemon.java (line 135) Exception in thread Thread[ReadStage:18613,5,main]

**Comment by mevivs** [comment]
Can you please provide information around this issue?

-Vivek

**Comment by zhouhero** [comment]
It seems cassandra's bug will be fixed in 1.2.4
- pls refer to fellow:
  https://issues.apache.org/jira/browse/CASSANDRA-4687
