### ISSUE TITLE
CQLTranslator ignores @Transient annotation

### ISSUE THREAD

**Issue by dtuzikov** [Impetus/kundera#232]
When using CQLTranslator with transient field the exception occurs:
<code>Caused by: java.lang.IllegalArgumentException: attribute of the given name and type is not present in the managed type, for name:accessRoles
    at com.impetus.kundera.metadata.model.type.AbstractManagedType.checkForValid(AbstractManagedType.java:955)
    at com.impetus.kundera.metadata.model.type.AbstractManagedType.getAttribute(AbstractManagedType.java:470)
    at com.impetus.client.cassandra.thrift.CQLTranslator.onTranslation(CQLTranslator.java:212)
    at com.impetus.client.cassandra.thrift.CQLTranslator.prepareColumnOrColumnValues(CQLTranslator.java:131)
    at com.impetus.client.cassandra.CassandraClientBase.onpersistOverCompositeKey(CassandraClientBase.java:909)
    at com.impetus.client.cassandra.thrift.ThriftClient.onPersist(ThriftClient.java:154)
    at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:86)
    at com.impetus.client.cassandra.thrift.ThriftClient.persist(ThriftClient.java:133)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:183)
    at com.impetus.kundera.graph.Node.flush(Node.java:525)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:456)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:184)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:168)
    ... 45 more
</code>

Possibly, this is because of using entityClazz.getDeclaredFields() method in CQLTranslator.onTranslation instead of metamodel.

**Comment by xamry** [comment]
Please share your entity definition and CRUD code in order for us to investigate this further.

**Comment by dtuzikov** [comment]
``` java
@Embeddable
public class UserDataPK implements Serializable {
    @Column(name = "user_key")
    private String userKey;

    @Column(name = "user_sys")
    private String userSys;

    //... constructor, getters, setters 
}

@Entity
@Table(name = "user_data", schema = "sch001@cassandra_pu")
public class UserData {
    @EmbeddedId
    protected UserDataPK pk;

    @Column (name = "profile_data")
    private String _profileData;

    @Column (name = "access_roles")
    private String _accessRoles;

    @Transient
    private Set<AccessTokenRole> accessRoles;

    @Transient
    private UserProfileData profileData;

    //... constructor, getters, setters 
}

public class UserDAO implements IUserDAO {
    @PersistenceContext(type = PersistenceContextType.EXTENDED)
    private EntityManager em;

    @Override
    public void persistUserData(UserData userData) {
        em.persist(userData);
    }
}
```

**Comment by pires** [comment]
Why would you need _@Transient_? AFAIK, _only_ fields annotated with _@Column_ will be persisted. This is different from what Hibernate (or any other JPA implementation to my knowledge) would do.

**Comment by dtuzikov** [comment]
> only fields annotated with @Column will be persisted

This is not true for CQLTranslator with Kundera 2.4 and Cassandra

**Comment by xamry** [comment]
This has been fixed in the trunk, Please verify and close.

**Comment by dtuzikov** [comment]
Fixed in trunk
