### ISSUE TITLE
Error when upgrading from Kundera 2.2.1 to 2.4

### ISSUE THREAD

**Issue by thfp** [Impetus/kundera#251]
Hi,

I'm recently trying to upgrade my Kundera plugin from version 2.2.1 to 2.4.
I found my code will prompt for errors on my Cassandra DB under 2.4 (2.3.1 as well) but the old version which is 2.2.1.

It looks like Thrift was trying to work on my "Queries" CF, but instead of looking for CF name "Queries", it trying to looking for "queries" CF which first letter "Q" is become a lower case here, and of course I don't have a CF defined for name "queries" so the error happens. I had confirmed that in my code CF is named "Queries", and I put a sysout for testing and is says received name "Queries" before proceed to execute CQL query. And the thing is all my codes works for version 2.2.1 but not 2.4 (or 2.3.1).

Here is console error outputs:

<pre>
QueryDAO: tableName is Queries
ERROR com.impetus.client.cassandra.CassandraClientBase : Error while executing native CQL query Caused by: CassandraClientBase.java:747
InvalidRequestException(why:unconfigured columnfamily queries)
    at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result.read(Cassandra.java:37849)
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
    at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql3_query(Cassandra.java:1562)
    at org.apache.cassandra.thrift.Cassandra$Client.execute_cql3_query(Cassandra.java:1547)
    at com.impetus.client.cassandra.CassandraClientBase.executeQuery(CassandraClientBase.java:699)
    at com.impetus.client.cassandra.pelops.PelopsClient.executeQuery(PelopsClient.java:606)
    at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:124)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:155)
    at omid.common.cassandra.dao.QueryDAO.getAllQueries(QueryDAO.java:67)
    at omid.crawler.twitter.TwitterCrawlerSpring.start(TwitterCrawlerSpring.java:94)
    at omid.crawler.twitter.TweetCrawler.main(TweetCrawler.java:29)
</pre>

Partial of my code may be useful for finding the problem:

<pre>createEntityManager();
System.out.println("QueryDAO: tableName is " + tableName);
javax.persistence.Query query = entityManager.createNativeQuery("SELECT * FROM " + tableName, Query.class);
if(query.getResultList() == null) return new ArrayList<Query>();
</pre>

AND my entityManager is kinda special here, cause I need a dynamic way to define CF names, so it can gets "different" CF names during the run-time.

<pre>
public static void createEntityManager() {
        if (entityManager == null) {
            metadata = KunderaMetadataManager.getEntityMetadata(Query.class);
            metadata.setSchema(CassandraDB.getKeySpaceName());
            tableName = metadata.getTableName();
            entityManager = CassandraDB.getEntityManagerFactory()
                    .createEntityManager();
        }
    }
</pre>

Thank you in advance!

**Comment by mevivs** [comment]
Hi,
This is because of CQL interpret everything in lowercase. Since you are executing CQL native query so in order to ensure case senstivity, please change:

```
javax.persistence.Query query = entityManager.createNativeQuery("SELECT * FROM " + tableName, Query.class);
```

with

```
javax.persistence.Query query = entityManager.createNativeQuery( "select * from \""+tableName+"\"", Query.class);
```

Hope it helps.

-Vivek

**Comment by thfp** [comment]
Thank you Vivek. The changes worked for version 2.4, but will not be working for 2.2.1.
At least I know where is the problem. Thanks again.
