### ISSUE TITLE
java.lang.NoClassDefFoundError: org/hibernate/collection/internal/PersistentSet

### ISSUE THREAD

**Issue by bejayoharen** [Impetus/kundera#295]
In Kundera 2.5.1 I receive the following error unless I add hibernate-core 4.1.7-final to my pom.

<pre>
Internal Server Error (500) - org/hibernate/collection/internal/PersistentSet
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:508)
    at org.restlet.resource.ServerResource.put(ServerResource.java:1225)
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:574)
    at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:640)
    at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:339)
    at org.restlet.resource.ServerResource.handle(ServerResource.java:902)
    at org.restlet.resource.Finder.handle(Finder.java:246)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:431)
    at org.restlet.routing.Router.handle(Router.java:648)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:154)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
    at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:84)
    at org.restlet.Application.handle(Application.java:381)
    at org.restlet.ext.wadl.WadlApplication.handle(WadlApplication.java:753)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:431)
    at org.restlet.routing.Router.handle(Router.java:648)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:431)
    at org.restlet.routing.Router.handle(Router.java:648)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:154)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
    at org.restlet.Component.handle(Component.java:392)
    at org.restlet.Server.handle(Server.java:516)
    at org.restlet.engine.ServerHelper.handle(ServerHelper.java:72)
    at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:152)
    at org.restlet.ext.jetty.JettyServerHelper$WrappedServer.handle(JettyServerHelper.java:170)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:589)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1048)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:601)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:411)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:535)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.NoClassDefFoundError: org/hibernate/collection/internal/PersistentSet
    at com.impetus.kundera.utils.DeepEquals.deepEquals(DeepEquals.java:265)
    at com.impetus.kundera.utils.DeepEquals.deepEquals(DeepEquals.java:96)
    at com.impetus.kundera.graph.ObjectGraphBuilder.getNode(ObjectGraphBuilder.java:148)
    at com.impetus.kundera.graph.ObjectGraphBuilder.addChildNodesToGraph(ObjectGraphBuilder.java:269)
    at com.impetus.kundera.graph.ObjectGraphBuilder.getNode(ObjectGraphBuilder.java:197)
    at com.impetus.kundera.graph.ObjectGraphBuilder.getObjectGraph(ObjectGraphBuilder.java:73)
    at com.impetus.kundera.persistence.PersistenceDelegator.remove(PersistenceDelegator.java:349)
    at com.impetus.kundera.persistence.EntityManagerImpl.remove(EntityManagerImpl.java:226)
    at com.xonami.rest.server.LocalResource.resetDB(LocalResource.java:573)
    at com.xonami.rest.server.LocalResource.put(LocalResource.java:221)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:494)
    ... 53 more
Caused by: java.lang.ClassNotFoundException: org.hibernate.collection.internal.PersistentSet
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
</pre>

**Comment by mevivs** [comment]
Kundera needs this for dirty check on entitiy objects. We are working on decoupling Hibernate from Kundera-core

-Vivek

**Comment by chhavigangwal** [comment]
Hibernate-core has already been upgraded to 4.1.7-final since Kundera 2.6. I tried the following code
I made two entities user and Address. 

```
@Entity
@Table(name = "AddressGeneratedId", schema = "testdb")
@IndexCollection(columns = { @Index(name = "street") })
public class AddressGeneratedId
{
    @Id
    @Column(name = "ADDRESS_ID")
    @GeneratedValue()
    private int addressId;

    @Column(name = "STREET")
    private String street;



}
```

User entity which has ManyToOne association  with Address and is loaded lazily.

```
@Entity
@Table(name = "UserGeneratedId", schema = "testdb")
@IndexCollection(columns = { @Index(name = "personName") })
public class UserGeneratedId
{
    @Id
    @Column(name = "PERSON_ID")
    @GeneratedValue()
    private int personId;

    @Column(name = "PERSON_NAME")
    private String personName;

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
   @JoinColumn(name = "ADDRESS_ID")
    private AddressGeneratedId address;



}
```

When I tried crud operation with the following code,it worked for me.

```

 AddressGeneratedId address = new AddressGeneratedId();
 address.setStreet("sector 20, G Block");

UserGeneratedId user = new UserGeneratedId();
user.setAddress(address);
user.setPersonName("Kuldeep");
em.persist(user);
em.clear();
```
