### ISSUE TITLE
JBoss EAP 6.1 - Could not find any META-INF/persistence.xml  file in the classpath

### ISSUE THREAD

**Issue by TheGeekPharaoh** [Impetus/kundera#303]
I am trying to play around with Kundera 2.5.1 on JBoss EAP 6.1 (essentially the same as JBoss AS 7.1).  However, when I deploy my application, I see the following Exception:

[0m[31m12:44:24,119 ERROR [org.jboss.msc.service.fail](ServerService Thread Pool -- 91) MSC000001: Failed to start service jboss.persistenceunit."KunderaTests-ear.ear/KunderaTests-ejb.jar#KunderaTests": org.jboss.msc.service.StartException in service jboss.persistenceunit."KunderaTests-ear.ear/KunderaTests-ejb.jar#KunderaTests": com.impetus.kundera.loader.PersistenceLoaderException: com.impetus.kundera.utils.InvalidConfigurationException: Could not find any META-INF/persistence.xml  file in the classpath
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:103) [jboss-as-jpa-7.2.0.Final-redhat-8.jar:7.2.0.Final-redhat-8]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [rt.jar:1.7.0_07]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [rt.jar:1.7.0_07]
    at java.lang.Thread.run(Thread.java:722) [rt.jar:1.7.0_07]
    at org.jboss.threads.JBossThread.run(JBossThread.java:122) [jboss-threads-2.1.0.Final-redhat-1.jar:2.1.0.Final-redhat-1]
Caused by: com.impetus.kundera.loader.PersistenceLoaderException: com.impetus.kundera.utils.InvalidConfigurationException: Could not find any META-INF/persistence.xml  file in the classpath
    at com.impetus.kundera.configure.PersistenceUnitConfiguration.configure(PersistenceUnitConfiguration.java:103)
    at com.impetus.kundera.configure.Configurator.configure(Configurator.java:65)
    at com.impetus.kundera.KunderaPersistence.initializeKundera(KunderaPersistence.java:104)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:77)
    at com.impetus.kundera.KunderaPersistence.createContainerEntityManagerFactory(KunderaPersistence.java:65)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.createContainerEntityManagerFactory(PersistenceUnitServiceImpl.java:200) [jboss-as-jpa-7.2.0.Final-redhat-8.jar:7.2.0.Final-redhat-8]
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.access$600(PersistenceUnitServiceImpl.java:57) [jboss-as-jpa-7.2.0.Final-redhat-8.jar:7.2.0.Final-redhat-8]
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:99) [jboss-as-jpa-7.2.0.Final-redhat-8.jar:7.2.0.Final-redhat-8]
    ... 4 more
Caused by: com.impetus.kundera.utils.InvalidConfigurationException: Could not find any META-INF/persistence.xml  file in the classpath
    at com.impetus.kundera.configure.PersistenceUnitConfiguration.findPersistenceMetadatas(PersistenceUnitConfiguration.java:131)
    at com.impetus.kundera.configure.PersistenceUnitConfiguration.configure(PersistenceUnitConfiguration.java:86)
    ... 11 more

The Kundera JARs (core & cassandra) are deployed within my EAR.  There is a Web application project, and a separate EJB project that houses the entities.  The persistence.xml file is in the EJB project under the src/META-INF path, but I still get this exception.  I do not have any problems with other JPA providers, such as Hibernate.

My persistence.xml file looks like this:

<persistence xmlns="http://java.sun.com/xml/ns/persistence"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0">

```
<persistence-unit name="KunderaTests">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <properties>
        <property name="kundera.nodes" value="localhost" />
        <property name="kundera.port" value="9160" />
        <property name="kundera.keyspace" value="dev" />
        <property name="kundera.dialect" value="cassandra" />
        <property name="kundera.client.lookup.class"
            value="com.impetus.client.cassandra.pelops.PelopsClientFactory" />
    </properties>
</persistence-unit>
```

</persistence>

Am I missing something?  Does my configuration look okay?  Or, is this an issue with deploying Kundera on JBoss EAP 6.1?

**Comment by mevivs** [comment]
Can you give it a try with latest trunk? There are some issues reported for JBoss As 7.1,which are working on. But with JBoss 6.1 EAP it should work.  Also please share deployment model for your war/ear

-Vivek

**Comment by mevivs** [comment]
See if given below thread is any help:

https://groups.google.com/forum/#!topic/kundera-discuss/x0AqH_Te6eQ

**Comment by TheGeekPharaoh** [comment]
What kind of info do you need around the war/ear model?  The structure looks something like this:

KunderaTests.ear
  ->KunderaTestsWeb.war
  ->KunderaTests-ejb.jar (this is where my persistence.xml and Entity classes are)

**Comment by impetus-opensource-admin** [comment]
See above thread. i guess it is discussing same and deployment changes for 6.1 EAP only.

-Vivek

**Comment by TheGeekPharaoh** [comment]
Just tried downloading trunk using the instructions on the downloads page, but got this error...

ERROR] Failed to execute goal on project kundera-cassandra: Could not resolve dependencies for project com.impetus.client:kundera-cassandra:jar:2.6-SNAPSHOT: Could not transfer artifact com.impetus.core:kundera-core:jar:tests:2.6-SNAPSHOT from/to atlassian (https://repository.atlassian.com/maven2/): Error transferring file: java.security.cert.CertificateException: No subject alternative DNS name matching repository.atlassian.com found. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :kundera-cassandra

**Comment by mevivs** [comment]
Did you clone complete git project?
After this please run:

mvn clean install -DskipTests  { skip tests, as it needs running server for mongodb,redis etc)

and then build your war/ear.

-Vivek

**Comment by TheGeekPharaoh** [comment]
@impetus-opensource I don't see anything in that thread related to the error I'm seeing.  JBoss recognizes the JAR within the EAR just fine.  It looks as though it's something within Kundera that can't find the persistence.xml file.

**Comment by mevivs** [comment]
Ok. This has been reported earlier for glassfish as well. I have added a fix for this in current trunk. Here it is:
https://github.com/impetus-opensource/Kundera/issues/284

I suggest you to try with latest trunk.

-Vivek

**Comment by TheGeekPharaoh** [comment]
@mevivs Yes, I tried running the mvn clean install again, but with the same results.  It appears to be due to the fact that https://repository.atlassian.com is down or doesn't exist.

**Comment by TheGeekPharaoh** [comment]
@mevivs Correction!  Looks like this last time it was the oracle-nosql project that failed.  I just commented that out from the pom.xml file and re-ran the build.  Worked just fine.  I'll run another test with trunk and see if that solves my issue.

**Comment by TheGeekPharaoh** [comment]
@mevivs Retested using the trunk code and it corrected the issue.  Thanks for your help!
