### ISSUE TITLE
Something is terribly wrong, No Entity metadata found for the class class com.rumbo.cassandra.entities.FlightPrice. Returning null value.

### ISSUE THREAD

**Issue by Ferparishuertas** [Impetus/kundera#31]
I receive the following error.Seems annotation value sno read but i cannot see the showstopper

Can you help me?

2012-02-03 14:09:50,761 [INFO ] [main] com.impetus.kundera.KunderaPersistence  - Loading Core
2012-02-03 14:09:50,765 [INFO ] [main] com.impetus.kundera.loader.CoreLoader  - Loading factories ... 
2012-02-03 14:09:50,772 [INFO ] [main] com.impetus.kundera.KunderaPersistence  - Loading Application MetaData and Initializing Client(s) For Persistence Unit(s) pu
2012-02-03 14:09:50,774 [DEBUG] [main] com.impetus.kundera.loader.ApplicationLoader  - Loading User Application...
2012-02-03 14:09:50,776 [DEBUG] [main] com.impetus.kundera.loader.PersistenceUnitLoader  - Loading Metadata from persistence.xml...
2012-02-03 14:09:50,797 [INFO ] [main] com.impetus.kundera.loader.PersistenceUnitLoader  - Looking up for persistence unit: pu
2012-02-03 14:09:51,701 [DEBUG] [main] com.impetus.kundera.loader.MetamodelLoader  - Loading Entity Metadata...
2012-02-03 14:09:51,739 [INFO ] [main] com.impetus.kundera.KunderaPersistence  - Loading Client(s) For Persistence Unit(s) pu
2012-02-03 14:09:51,746 [INFO ] [main] com.impetus.kundera.loader.GenericClientFactory  - Loading client metadata for persistence unit : pu
2012-02-03 14:09:51,746 [INFO ] [main] com.impetus.kundera.loader.GenericClientFactory  - Initializing client for persistence unit : pu
2012-02-03 14:09:51,746 [INFO ] [main] com.impetus.kundera.KunderaPersistence  - Initializing Threadsafe Indexmanager. Is it really threadsafe?
2012-02-03 14:09:51,857 [INFO ] [main] com.impetus.kundera.loader.GenericClientFactory  - Constructing pool for persistence unit : pu
2012-02-03 14:09:51,876 [INFO ] [main] org.scale7.cassandra.pelops.Cluster  - Dynamic node discovery is disabled, using [localhost] as a static list of nodes
2012-02-03 14:09:51,887 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Initialising pool configuration policy: Config{maxActivePerNode=20, maxTotal=-1, maxIdlePerNode=10, minIdlePerNode=10, maxWaitForConnection=2147483647, testConnectionsWhileIdle=true, timeBetweenScheduledMaintenanceTaskRunsMillis=60000, nodeDownSuspensionMillis=10000}
2012-02-03 14:09:51,888 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Initialising pool node selection strategy: org.scale7.cassandra.pelops.pool.LeastLoadedNodeSelectionStrategy@b1074a
2012-02-03 14:09:51,889 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Initialising pool node suspension strategy: org.scale7.cassandra.pelops.pool.NoOpNodeSuspensionStrategy@4ee70b
2012-02-03 14:09:51,889 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Initialising pool connection validator: org.scale7.cassandra.pelops.pool.DescribeVersionConnectionValidator@1eec35
2012-02-03 14:09:51,900 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Pre-initialising connections for nodes: [localhost:9160]
2012-02-03 14:09:51,900 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Adding node 'localhost' to the pool...
2012-02-03 14:09:51,944 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Registering MBean 'com.scale7.cassandra.pelops.pool:type=PooledNode-DynamicSEO-localhost'...
2012-02-03 14:09:51,973 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Made new connection 'Connection[DynamicSEO][localhost:9160][19673895]'
2012-02-03 14:09:51,975 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - transport is open 'org.apache.thrift.transport.TFramedTransport@f01771'
2012-02-03 14:09:51,975 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - set keyspace  'DynamicSEO'
2012-02-03 14:09:51,983 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Made new connection 'Connection[DynamicSEO][localhost:9160][11743647]'
2012-02-03 14:09:51,984 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - transport is open 'org.apache.thrift.transport.TFramedTransport@7ecd78'
2012-02-03 14:09:51,984 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - set keyspace  'DynamicSEO'
2012-02-03 14:09:51,984 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Made new connection 'Connection[DynamicSEO][localhost:9160][14910620]'
2012-02-03 14:09:51,985 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - transport is open 'org.apache.thrift.transport.TFramedTransport@11756a4'
2012-02-03 14:09:51,985 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - set keyspace  'DynamicSEO'
2012-02-03 14:09:51,986 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Made new connection 'Connection[DynamicSEO][localhost:9160][20526817]'
2012-02-03 14:09:51,986 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - transport is open 'org.apache.thrift.transport.TFramedTransport@141fab6'
2012-02-03 14:09:51,986 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - set keyspace  'DynamicSEO'
2012-02-03 14:09:51,987 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Made new connection 'Connection[DynamicSEO][localhost:9160][11731442]'
2012-02-03 14:09:51,987 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - transport is open 'org.apache.thrift.transport.TFramedTransport@44cbbe'
2012-02-03 14:09:51,987 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - set keyspace  'DynamicSEO'
2012-02-03 14:09:51,988 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Made new connection 'Connection[DynamicSEO][localhost:9160][10233621]'
2012-02-03 14:09:51,988 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - transport is open 'org.apache.thrift.transport.TFramedTransport@1c9e67a'
2012-02-03 14:09:51,988 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - set keyspace  'DynamicSEO'
2012-02-03 14:09:51,989 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Made new connection 'Connection[DynamicSEO][localhost:9160][3823508]'
2012-02-03 14:09:51,989 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - transport is open 'org.apache.thrift.transport.TFramedTransport@4be2cc'
2012-02-03 14:09:51,989 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - set keyspace  'DynamicSEO'
2012-02-03 14:09:51,989 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Made new connection 'Connection[DynamicSEO][localhost:9160][1503089]'
2012-02-03 14:09:51,990 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - transport is open 'org.apache.thrift.transport.TFramedTransport@1c208b0'
2012-02-03 14:09:51,990 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - set keyspace  'DynamicSEO'
2012-02-03 14:09:51,990 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Made new connection 'Connection[DynamicSEO][localhost:9160][29919449]'
2012-02-03 14:09:51,991 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - transport is open 'org.apache.thrift.transport.TFramedTransport@f1f051'
2012-02-03 14:09:51,991 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - set keyspace  'DynamicSEO'
2012-02-03 14:09:51,991 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Made new connection 'Connection[DynamicSEO][localhost:9160][30969271]'
2012-02-03 14:09:51,992 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - transport is open 'org.apache.thrift.transport.TFramedTransport@402af3'
2012-02-03 14:09:51,992 [DEBUG] [main] org.scale7.cassandra.pelops.Connection  - set keyspace  'DynamicSEO'
2012-02-03 14:09:51,992 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Running maintenance tasks during initialization...
2012-02-03 14:09:51,992 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Attempting to acquire lock for maintenance tasks
2012-02-03 14:09:51,992 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Starting maintenance tasks
2012-02-03 14:09:51,992 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Updating pool configuration properties based on policy: Config{maxActivePerNode=20, maxTotal=-1, maxIdlePerNode=10, minIdlePerNode=10, maxWaitForConnection=2147483647, testConnectionsWhileIdle=true, timeBetweenScheduledMaintenanceTaskRunsMillis=60000, nodeDownSuspensionMillis=10000}
2012-02-03 14:09:51,992 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Determining which nodes need to be added and removed based on latest nodes list
2012-02-03 14:09:51,993 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Evaluating which nodes should be suspended
2012-02-03 14:09:51,993 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Evaluating if node localhost should be suspended
2012-02-03 14:09:51,993 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Validating and possibly evicting idle connections based on configuration rules
2012-02-03 14:09:51,995 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Validating connection 'Connection[DynamicSEO][localhost:9160][19673895]'
2012-02-03 14:09:51,999 [DEBUG] [main] org.scale7.cassandra.pelops.pool.DescribeVersionConnectionValidator  - Connection 'Connection[DynamicSEO][localhost:9160][19673895]' passed validation
2012-02-03 14:09:51,999 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Validating connection 'Connection[DynamicSEO][localhost:9160][11743647]'
2012-02-03 14:09:51,999 [DEBUG] [main] org.scale7.cassandra.pelops.pool.DescribeVersionConnectionValidator  - Connection 'Connection[DynamicSEO][localhost:9160][11743647]' passed validation
2012-02-03 14:09:52,000 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Validating connection 'Connection[DynamicSEO][localhost:9160][14910620]'
2012-02-03 14:09:52,000 [DEBUG] [main] org.scale7.cassandra.pelops.pool.DescribeVersionConnectionValidator  - Connection 'Connection[DynamicSEO][localhost:9160][14910620]' passed validation
2012-02-03 14:09:52,000 [DEBUG] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Finished maintenance tasks
2012-02-03 14:09:52,000 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Configuring scheduled tasks to run every 60000 milliseconds
2012-02-03 14:09:52,006 [INFO ] [main] org.scale7.cassandra.pelops.pool.CommonsBackedPool  - Registering MBean 'com.scale7.cassandra.pelops.pool:type=Pool-DynamicSEO'...
2012-02-03 14:09:52,008 [INFO ] [main] org.scale7.cassandra.pelops.Pelops  - Pelops adds new pool localhost:9160:DynamicSEO
2012-02-03 14:09:52,011 [INFO ] [main] com.impetus.kundera.persistence.EntityManagerFactoryImpl  - EntityManagerFactory created for persistence unit : pu
2012-02-03 14:09:52,012 [DEBUG] [main] com.impetus.kundera.persistence.EntityManagerFactoryImpl  - Creating EntityManager for persistence unit : pu
2012-02-03 14:09:52,018 [DEBUG] [main] com.impetus.kundera.persistence.EntityManagerFactoryImpl  - Created EntityManager for persistence unit : pu
2012-02-03 14:09:52,020 [WARN ] [main] com.impetus.kundera.metadata.KunderaMetadataManager  - Something is terribly wrong, No Entity metadata found for the class class com.rumbo.cassandra.entities.FlightPrice. Returning null value.
java.lang.NullPointerException
    at com.impetus.kundera.persistence.event.EntityEventDispatcher.fireEventListeners(EntityEventDispatcher.java:53)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:465)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:144)
    at com.rumbo.cassandra.SimpleQueryTest.testCreateEntity(SimpleQueryTest.java:29)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at junit.framework.TestCase.runTest(TestCase.java:164)
    at junit.framework.TestCase.runBare(TestCase.java:130)
    at junit.framework.TestResult$1.protect(TestResult.java:106)
    at junit.framework.TestResult.runProtected(TestResult.java:124)
    at junit.framework.TestResult.run(TestResult.java:109)
    at junit.framework.TestCase.run(TestCase.java:120)
    at junit.framework.TestSuite.runTest(TestSuite.java:230)
    at junit.framework.TestSuite.run(TestSuite.java:225)
    at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by mevivs** [comment]
You need to annotate your entity like:
@Table(name = "columnFamilyName", schema = "keyspace@persistenceunitname")

You can refer

https://github.com/impetus-opensource/Kundera-Examples/tree/Kundera-Examples-2.0.5/src/test/java/com/impetus/kundera/examples/crud

for CRUD operations.

Vivek

**Comment by Ferparishuertas** [comment]
Thisis waht i have and on peristence the class undel <class>

@Entity
@Table(name = "SeoPrice", schema = "DynamicSEO@pu")
pu is persiyenceunit on persistence.xml

**Comment by mevivs** [comment]
Please share your persistence.xml and persistence code snippet

**Comment by Ferparishuertas** [comment]
<persistence-unit name="pu">
<provider>com.impetus.kundera.KunderaPersistence</provider>
<class>com.rumbo.cassandra.entities.FlightPrice</class>
<properties>
<property name="kundera.nodes" value="localhost" />
<property name="kundera.port" value="9160" />
<property name="kundera.keyspace" value="DynamicSEO" />
<property name="kundera.dialect" value="cassandra" />
            <property name="kundera.client" value="Pelops" />
            <property name="kundera.annotations.scan.package" value="com.rumbo" />
            <property name="kundera.cache.provider.class"
                value="com.impetus.kundera.cache.ehcache.EhCacheProvider" />
            <property name="kundera.cache.config.resource" value="/ehcache-test.xml" />
        </properties>
    </persistence-unit>

```
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("pu");
    EntityManager em = emf.createEntityManager();

    FlightPrice price = new FlightPrice();
    price.setId("22");
    price.setOrigin("mad");
    price.setDestination("lon");
    price.setPrice(new Long(30));

    em.persist(price);

    em.close();
```

**Comment by mevivs** [comment]
kunder version?
2.0.4 or 2.0.5?

**Comment by Ferparishuertas** [comment]
2.0.4

**Comment by mevivs** [comment]
Can you please give it a try with 2.0.5? 
Not yet released but trunk is stable.

**Comment by Ferparishuertas** [comment]
Is there a snapshot jar?

On Fri, Feb 3, 2012 at 6:23 PM, Vivek Mishra <
reply@reply.github.com

**Comment by mevivs** [comment]
Not yet released, in final testing phase. u need to build code from source itself.

**Comment by Ferparishuertas** [comment]
I saw it. i t was a auto omported hibernate entity instead persistence entity

Thank you for the quick support

**Comment by mevivs** [comment]
Okay cool. Else  i was wondering why is it happening. everything was looking OK to me.

Great!

Vivek
