### ISSUE TITLE
Running 5min setup example leads to slf4j-api 1.6.x (or later) is incompatible with this binding.

### ISSUE THREAD

**Issue by jaksky** [Impetus/kundera#336]
Part of my pom.xml:

```
<properties>
    <kundera.version>2.6</kundera.version>
</properties>

<dependencies>

    <!--Kundera ORM-->
    <!--<dependency>-->
        <!--<groupId>com.impetus.core</groupId>-->
        <!--<artifactId>kundera-core</artifactId>-->
        <!--<version>${kundera.version}</version>-->
    <!--</dependency>-->

    <dependency>
        <groupId>com.impetus.client</groupId>
        <artifactId>kundera-hbase</artifactId>
        <version>${kundera.version}</version>
        <exclusions>

        </exclusions>
    </dependency>

    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.6</version>
        <scope>test</scope>
    </dependency>


</dependencies>
```

Getting:

SLF4J: slf4j-api 1.6.x (or later) is incompatible with this binding.
SLF4J: Your binding is version 1.5.5 or earlier.
SLF4J: Upgrade your binding to version 1.6.x. or 2.0.x

java.lang.NoSuchMethodError: org.slf4j.impl.StaticLoggerBinder.getSingleton()Lorg/slf4j/impl/StaticLoggerBinder;
    at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
    at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:279)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:252)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:265)
    at com.impetus.kundera.KunderaPersistence.<clinit>(KunderaPersistence.java:43)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at java.lang.Class.newInstance(Class.java:374)
    at javax.persistence.spi.PersistenceProviderResolverHolder$DefaultPersistenceProviderResolver.getPersistenceProviders(Unknown Source)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)

**Comment by kirankom** [comment]
I had the same issue. Was solved by changing the kundera version - i used v2.3.1.
