### ISSUE TITLE
Getting java.lang.IllegalArgumentException: Not a host:port pair: PBUF

### ISSUE THREAD

**Issue by jaksky** [Impetus/kundera#337]
Guys,

I am trying to use Kundera with HBase 0.95 and getting java.lang.IllegalArgumentException: Not a host:port pair: PBUF

Have any clue what is wrong

Caused by: java.lang.IllegalArgumentException: Not a host:port pair: PBUF

localhost����܀(
at org.apache.hadoop.hbase.util.Addressing.parseHostname(Addressing.java:60)
at org.apache.hadoop.hbase.ServerName.(ServerName.java:101)
at org.apache.hadoop.hbase.ServerName.parseVersionedServerName(ServerName.java:283)
at org.apache.hadoop.hbase.MasterAddressTracker.bytesToServerName(MasterAddressTracker.java:77)
at org.apache.hadoop.hbase.MasterAddressTracker.getMasterAddress(MasterAddressTracker.java:61)
at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getMaster(HConnectionManager.java:671)
at org.apache.hadoop.hbase.client.HBaseAdmin.(HBaseAdmin.java:110)
at com.impetus.client.hbase.admin.HBaseDataHandler.(HBaseDataHandler.java:114)
... 34 more

Using latest vesion of Kundera 2.6

**Comment by mevivs** [comment]
Kundera 2.6 supports HBase 0.94.3 . Please have a look at 

https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-hbase/src/test/java/com/impetus/client/hbase/crud/PersonHBaseTest.java

for basic HBase junit.

-Vivek

**Comment by mevivs** [comment]
HBase version upgrade is planned for next release(probably 2.7). Will post an update on this.

-Vivek

**Comment by mevivs** [comment]
HBase version upgrade is planned for released( > 2.8)

-Vivek
