### ISSUE TITLE
Support for Allow Filtering

### ISSUE THREAD

**Issue by Gargee** [Impetus/kundera#352]
Hi I have this requirement where in i need to query the cassandra Db with allow Filtering clause.
When i try this on cassandra DB directly using cql this query works.
But when i try this with kudera it doesnt.Does Kundera support "Allow filtering"?

**Comment by Gargee** [comment]
I am using this query 

ON cassandra directly on terminal using cql 
select \* from "PhotosLog" where "SKUGroupID" = 245698 and "ChangeStatusID"=1 limit 10 ALLOW FIlTERING; 
this works !!
but when i try doing it using Kundera :- it doesnt.My kundera query is : 

public final String PhotoLogSelect = "select p from PhotosLog p where p.skuGroupID=245698 and p.changeStatusID=1 limit 10 ALLOW FIlTERING";
}
 and i am getting this error 

Exception in thread "main" javax.persistence.PersistenceException: InvalidRequestException(why:line 1:100 missing EOF at 'LIMIT')
    at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:1957)
    at com.impetus.client.cassandra.CassandraClientBase.executeQuery(CassandraClientBase.java:764)
    at com.impetus.client.cassandra.pelops.PelopsClient.executeQuery(PelopsClient.java:642)
    at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:122)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:150)
    at com.expedia.lux.content.dal.PhotoDal.selectphotolog(PhotoDal.java:106)
    at com.expedia.lux.content.mainClass.KunderaExample.main(KunderaExample.java:67)
Caused by: InvalidRequestException(why:line 1:100 missing EOF at 'LIMIT')
    at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result.read(Cassandra.java:37849)
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
    at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql3_query(Cassandra.java:1562)
    at org.apache.cassandra.thrift.Cassandra$Client.execute_cql3_query(Cassandra.java:1547)
    at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:1766)
    at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:1925)
    ... 6 more

**Comment by mevivs** [comment]
```
public final String PhotoLogSelect = "select p from PhotosLog p where p.skuGroupID=245698 and p.changeStatusID=1 limit 10 ALLOW FIlTERING";
```

Executing it as em.createNativeQuery() or em.createNamedQuery()?

Kundera supports ALLOW FILTERING by default on JPQL query.

-Vivek

**Comment by Gargee** [comment]
Thanks for your reply.My code works with hardcoded values like:-

```
public final String PhotoLogSelect = "select * from \"PhotosLog\"  where \"SKUGroupID\"=245698 and \"ChangeStatusID\"=1 limit 10 ALLOW FILTERING";
```

But how can we use named Parameters here?I tried both positional parameters and also named ones for but i am getting errors 

named ones:-
    public final String PhotoLogSelect = "select \* from \"PhotosLog\"  where \"SKUGroupID\"=:sid and \"ChangeStatusID\"=:chid limit 10 ALLOW FILTERING";

positional query:-

```
public final String PhotoLogSelect = "select * from \"PhotosLog\"  where \"SKUGroupID\"=? and \"ChangeStatusID\"=? limit 10 ALLOW FILTERING";}
```

java code for named query:-
        EntityManager em = cKDao.getEntityManager();
        Query q = em.createNativeQuery(kqueries.PhotoLogSelect, PhotosLog.class);
        q.setParameter("sid",245698);
        q.setParameter("chid",1);
        List<PhotosLog> results = q.getResultList();
        for (PhotosLog p:results){
            System.out.println(p.getCreateUser());

java code for positional query:-

```
EntityManager em = cKDao.getEntityManager();
    Query q = em.createNativeQuery(kqueries.PhotoLogSelect, PhotosLog.class);
    q.setParameter(1,245698);
    q.setParameter(2,1);
    List<PhotosLog> results = q.getResultList();
    for (PhotosLog p:results){
        System.out.println(p.getCreateUser());
```

Error:-
        Exception in thread "main" com.impetus.kundera.query.QueryHandlerException: No named parameter present for query
    at com.impetus.kundera.query.KunderaQuery.setParameterValue(KunderaQuery.java:695)
    at com.impetus.kundera.query.KunderaQuery.setParameter(KunderaQuery.java:658)
    at com.impetus.kundera.query.QueryImpl.setParameter(QueryImpl.java:622)
    at com.expedia.lux.content.dal.PhotoDal.simpleSelectPhoto(PhotoDal.java:114)
    at com.expedia.lux.content.mainClass.KunderaExample.main(KunderaExample.java:68)

**Comment by mevivs** [comment]
Few things : 
1. First is, you need to execute it as named JPQL query. 

For example to execute such queries:
select \* from "PhotosLog" where "SKUGroupID" = 245698 and "ChangeStatusID"=1 limit 10 ALLOW FIlTERING; 

it's JPQL query would be(PhotosLog is an entity with SKUGroupID,ChangeStatusID as fields) :

```
        Map propertyMap = new HashMap();
        propertyMap.put(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_3_0);
// for CQL queries, set CQL version as CQL3
        emf = Persistence.createEntityManagerFactory("cassandra_pu", propertyMap);
        em = emf.createEntityManager();

String query = "select p from PhotosLog p where p.SKUGroupID = ?1 and p.ChangeStatusID = ?2";
Query jpaQuery = em.createNamedQuery(query);
jpaQuery.setParameter(1, 245698);   // set parameter
jpaQuery.setParameter(2, 1);           // set parameter
jpaQuery.setMaxResults(10); // To Apply LIMIT

List<PhotosLog> results = em.getResultList();

```

ALLOW FILTERING will automatically be applied on such queries.

Hope this helps.

-Vivek

**Comment by Gargee** [comment]
thanks it works
