### ISSUE TITLE
NPE on persist/merge (Kundera v2.6.1)

### ISSUE THREAD

**Issue by bsideup** [Impetus/kundera#381]
```
Caused by: java.lang.NullPointerException
    at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:54)
    at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
    at java.lang.reflect.Field.get(Field.java:372)
    at com.impetus.kundera.property.PropertyAccessorHelper.getObject(PropertyAccessorHelper.java:135)
    at com.impetus.kundera.property.PropertyAccessorHelper.getId(PropertyAccessorHelper.java:262)
    at com.impetus.client.mongodb.MongoDBDataHandler.getDocumentFromEntity(MongoDBDataHandler.java:215)
    at com.impetus.client.mongodb.MongoDBClient.onPersist(MongoDBClient.java:654)
    at com.impetus.client.mongodb.MongoDBClient.onPersist(MongoDBClient.java:528)
    at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:88)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:183)
    at com.impetus.kundera.graph.Node.flush(Node.java:523)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:413)
    at com.impetus.kundera.persistence.PersistenceDelegator.merge(PersistenceDelegator.java:466)
    at com.impetus.kundera.persistence.EntityManagerImpl.merge(EntityManagerImpl.java:198)
    ... 72 more
```

**Test.java:**

``` java
@Entity
@Table(name = "tests", schema = "NNS@NNSPU")
public class Test {
    @Id
    private String id;

    @ElementCollection
    @CollectionTable
    private List<CurvePoint> curvePoints;

    public Test() {
    }

    public List<CurvePoint> getCurvePoints() {
        return curvePoints;
    }

    public void setCurvePoints(List<CurvePoint> curvePoints) {
        this.curvePoints = curvePoints;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Test(String id, List<CurvePoint> curvePoints) {
        this.id = id;
        this.curvePoints = curvePoints;
    }
}
```

**CurvePoint.java:**

``` java
@Embeddable
public class CurvePoint{
    @Column
    private String id;
    @Column
    private int rpm;
    @Column
    private int moment;

    public CurvePoint() { }

    public CurvePoint(String id, int rpm, int moment) {
        this.id = id;
        this.rpm = rpm;
        this.moment = moment;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public int getRpm() {
        return rpm;
    }

    public void setRpm(int rpm) {
        this.rpm = rpm;
    }

    public int getMoment() {
        return moment;
    }

    public void setMoment(int moment) {
        this.moment = moment;
    }
}
```

**Usage:**

``` java
Test test = new Test("100500", Arrays.asList(new CurvePoint("9000", 100500, 42)));

testDao.merge(test);
```

**Comment by mevivs** [comment]
Hi,
Could you please change code snippet as below:

```
   CurvePoint point = new CurvePoint("9000", 100500, 42);

        List<CurvePoint> points = new ArrayList<CurvePoint>();
        points.add(point);

        Geometry test = new Geometry("100500", points);
```

I think it should work for you. 

I will get it fixed for "Arrays.asList" in 2.8 

-Vivek

**Comment by bsideup** [comment]
Yeah! It works! Thanks!

BTW, also doesn't work with anonymous Lists

``` java
newCar.setCurvePoints(new ArrayList<CurvePoint>(){{
            add(new CurvePoint("1",1,2));
        }});
```

**Comment by mevivs** [comment]
Just to add, problem with this issue is:
java.util.Arrays.ArrayList inner class does not expose any public "no-arg-constructor". Kundera needs it for dirty check and  deep cloning.

-Vivek
