### ISSUE TITLE
byte[] @Column or @Id is not supported with  Kundera+CQL

### ISSUE THREAD

**Issue by jfgosselin** [Impetus/kundera#396]
For the following entity :

  TABLE test (
    key text,
    data blob,
    PRIMARY KEY (key)
  ) 

  @Entity
  @Table(name = "test", schema = "kunderatest@cassandra_pu")
   public class Dummy {

  @Id
  private String id;

  @Column(name = "data")
  private byte[] data;

  }

I get the following error :

12:25:41,067 ERROR   com.impetus.client.cassandra.pelops.PelopsClient: 465 - Error during persist while executing query  INSERT INTO "test"("key","data") VALUES('123',[B@75d252d) , Caused by: .
InvalidRequestException(why:line 1:57 mismatched character ')' expecting set null)
    at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result.read(Cassandra.java:37849)
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)

**Comment by mevivs** [comment]
Hi,
Can you please provide more details on this?  CQL3 does provide some blob conversion function. Did you try executing a native CQL3 query with byte[] ?

-Vivek

**Comment by jfgosselin** [comment]
Hi,

No, it wasn't a native query, here's the code:

```
Map<String, String> propertyMap = new HashMap<String, String>();
propertyMap.put(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_3_0);
EntityManagerFactory emf = Persistence.createEntityManagerFactory("cassandra_pu", propertyMap);
EntityManager em = emf.createEntityManager();

Dummy d = new Dummy();
d.setId("123");
d.setData("a blob".getBytes());
em.persist(d);

em.close();
emf.close();
```

ERROR 2013-09-17 09:41:26,548 [main] com.impetus.client.cassandra.pelops.PelopsClient -  Error during persist while executing query  INSERT INTO "test"("id","data") VALUES('123',[B@2321b59a) , Caused by: .
InvalidRequestException(why:line 1:57 mismatched character ')' expecting '-')
    at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result.read(Cassandra.java:37849)
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
    at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql3_query(Cassandra.java:1562)
    at org.apache.cassandra.thrift.Cassandra$Client.execute_cql3_query(Cassandra.java:1547)
    at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:1734)
    at com.impetus.client.cassandra.pelops.PelopsClient.onPersist(PelopsClient.java:461)
    at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:88)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:183)
    at com.impetus.kundera.graph.Node.flush(Node.java:523)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:413)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:151)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:168)

**Comment by mevivs** [comment]
Hi,
I mean did you try to execute CQL3 query for same scenario via cqlsh? 

-Vivek

**Comment by jfgosselin** [comment]
Yes , with cqlsh : INSERT INTO test(id,data) VALUES('123',0x6120626c6f62);

But Kundera is doing a .toString()

**Comment by mevivs** [comment]
A fix has been pushed in current trunk branch. Releasing with 2.8 

-Vivek

**Comment by mevivs** [comment]
Any update. Got a chance to verify ?

-Vivek

**Comment by jfgosselin** [comment]
Thanks for the fix!

Do you have maven repo for 2.8-SNAPSHOT ?

**Comment by mevivs** [comment]
Nope. you need to build

**Comment by jfgosselin** [comment]
Problem solved ! Thanks
