### ISSUE TITLE
MongoDB, Kundera v2.7.1, permissions issue

### ISSUE THREAD

**Issue by bsideup** [Impetus/kundera#414]
https://github.com/impetus-opensource/Kundera/blob/9f7cd186965704d50c01f9c84fc166ff295d9fd5/src/kundera-mongo/src/main/java/com/impetus/client/mongodb/schemamanager/MongoDBSchemaManager.java#L350

``` java
private void getDBName()
    {
        List<String> dbs = mongo.getDatabaseNames();
        for (String dbName : dbs)
        {
            if (dbName.equalsIgnoreCase(databaseName))
            {
                databaseName = dbName;
                break;
            }
        }
    }
```

This code throws

```
Caused by: com.mongodb.CommandResult$CommandFailure: command failed [listDatabases]: { "serverUsed" : "*********/54.217.63.18:27017" , "ok" : 0.0 , "errmsg" : "unauthorized"}
        at com.mongodb.CommandResult.getException(CommandResult.java:88)
        at com.mongodb.CommandResult.throwOnError(CommandResult.java:134)
        at com.mongodb.Mongo.getDatabaseNames(Mongo.java:374)
        at com.impetus.client.mongodb.schemamanager.MongoDBSchemaManager.getDBName(MongoDBSchemaManager.java:350)
        at com.impetus.client.mongodb.schemamanager.MongoDBSchemaManager.update(MongoDBSchemaManager.java:144)
        at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.handleOperations(AbstractSchemaManager.java:255)
        at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.exportSchema(AbstractSchemaManager.java:108)
        at com.impetus.client.mongodb.schemamanager.MongoDBSchemaManager.exportSchema(MongoDBSchemaManager.java:76)
        at com.impetus.kundera.configure.SchemaConfiguration.configure(SchemaConfiguration.java:176)
        at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:45)
        at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:349)
        at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:113)
        at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:83)
        at com.impetus.kundera.KunderaPersistence.createContainerEntityManagerFactory(KunderaPersistence.java:65)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:288)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:310)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1547)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1485)
```

if user have no rights to query "show databases". 

Seems like it's not necessary at all to call this block of code. 

BTW, this issue was finded while using MongoHQ.com, and it blocks any ability to use it at all, so this is critical issue i guess.

Thanks!

**Comment by mevivs** [comment]
:+1: 

KK, please look into this.

-Vivek
