### ISSUE TITLE
NPE on persist/merge/remove after clear()

### ISSUE THREAD

**Issue by bsideup** [Impetus/kundera#428]
```
java.lang.NullPointerException
      at com.impetus.kundera.persistence.context.CacheBase.clear(CacheBase.java:186)
      at com.impetus.kundera.persistence.context.PersistenceCache.clean(PersistenceCache.java:100)
      at com.impetus.kundera.persistence.PersistenceDelegator.rollback(PersistenceDelegator.java:744)
      at com.impetus.kundera.persistence.EntityManagerImpl.doRollback(EntityManagerImpl.java:949)
      at com.impetus.kundera.persistence.EntityManagerImpl.merge(EntityManagerImpl.java:203)
      at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:606)
      at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:366)
      at com.sun.proxy.$Proxy30.merge(Unknown Source)
      at com.cm.dragonfeed.dao.AbstractDao.merge(AbstractDao.java:23)
```

```
java.lang.NullPointerException
      at com.impetus.kundera.persistence.PersistenceDelegator.find(PersistenceDelegator.java:230)
      at com.impetus.kundera.persistence.PersistenceDelegator.findById(PersistenceDelegator.java:184)
      at com.impetus.kundera.persistence.EntityManagerImpl.find(EntityManagerImpl.java:257)
      at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:606)
      at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:366)
      at com.sun.proxy.$Proxy30.find(Unknown Source)
      at com.cm.dragonfeed.dao.AbstractDao.find(AbstractDao.java:19)
```

EHCache is not used.

**Comment by bsideup** [comment]
one more:

```
java.lang.NullPointerException
      at com.impetus.kundera.lifecycle.states.ManagedState.handleFind(ManagedState.java:152)
      at com.impetus.kundera.graph.Node.find(Node.java:502)
      at com.impetus.kundera.persistence.PersistenceDelegator.find(PersistenceDelegator.java:243)
      at com.impetus.kundera.persistence.PersistenceDelegator.findById(PersistenceDelegator.java:184)
      at com.impetus.kundera.persistence.EntityManagerImpl.find(EntityManagerImpl.java:257)
      at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:606)
      at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:366)
      at com.sun.proxy.$Proxy30.find(Unknown Source)
      at com.cm.dragonfeed.dao.AbstractDao.find(AbstractDao.java:19)
```

with EHCache enabled.
