### ISSUE TITLE
KunderaMongo 2.8, JPQL query with enum

### ISSUE THREAD

**Issue by bsideup** [Impetus/kundera#434]
when query contains "where" with "enumField = :enumValue" condition i'm getting this Exception:

```
java.lang.RuntimeException: json can't serialize type : SomeEnumType au.org.aurin.workflow.datamodel.ComponentType
    at com.mongodb.util.JSON.serialize(JSON.java:261)
    at com.mongodb.util.JSON.serialize(JSON.java:141)
    at com.mongodb.util.JSON.serialize(JSON.java:58)
    at com.mongodb.BasicDBObject.toString(BasicDBObject.java:84)
```

looks like enum handling in JPQL is broken.

Thanks!

**Comment by mevivs** [comment]
Fixed and releasing with 2.8.1
