### ISSUE TITLE
@Id is not used from @MappedSuperclass with Kundera 2.8

### ISSUE THREAD

**Issue by subes** [Impetus/kundera#447]
I have an AbstractEntity class with @MappedSuperclass annotated which has a @Id annotated field:

```
@MappedSuperclass
public abstract class AbstractEntity {
@Id
@TableGenerator(name = "AEntity_id_generatorStrategy", table = "SequenceEntity", allocationSize = 1000)
@GeneratedValue(strategy = GenerationType.TABLE, generator = "AEntity_id_generatorStrategy")
private Long id;
```

Then a TestEntity that extends AbstractEntity. 

```
@Entity
public class TestEntity extends AbstractEntity {
```

Though Kundera complains that TestEntity has to have a field with @Id. In that case it would be wiser if Kundera would detect the @Id annotated field.

```
Caused by: com.impetus.kundera.metadata.validator.InvalidEntityDefinitionException: de.invesdwin.common.persistence.jpa.TestEntity must have an @Id field.
    at com.impetus.kundera.metadata.processor.TableProcessor.validateIdAttribute(TableProcessor.java:350)
    at com.impetus.kundera.metadata.processor.TableProcessor.validateAndSetId(TableProcessor.java:341)
    at com.impetus.kundera.metadata.processor.TableProcessor.populateMetadata(TableProcessor.java:153)
    at com.impetus.kundera.metadata.processor.TableProcessor.process(TableProcessor.java:87)
    at com.impetus.kundera.metadata.MetadataBuilder.buildEntityMetadata(MetadataBuilder.java:131)
    at com.impetus.kundera.configure.MetamodelConfiguration.scanClassAndPutMetadata(MetamodelConfiguration.java:391)
    at com.impetus.kundera.configure.MetamodelConfiguration.loadEntityMetadata(MetamodelConfiguration.java:230)
    at com.impetus.kundera.configure.MetamodelConfiguration.configure(MetamodelConfiguration.java:102)
    at com.impetus.kundera.configure.Configurator.configure(Configurator.java:65)
    at com.impetus.kundera.KunderaPersistence.initializeKundera(KunderaPersistence.java:109)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:81)
    at com.impetus.kundera.KunderaPersistence.createContainerEntityManagerFactory(KunderaPersistence.java:65)
```

**Comment by chhavigangwal** [comment]
I tried to reproduce the issue with Kundera 2.8 snapshot as well as with the current trunk but was not able to reproduce the issue. Can you please share a sample project and a bit more details around the specific scenario?

**Comment by subes** [comment]
You say Kundera 2.8 snapshot, though I already see 2.8 released here: http://mvnrepository.com/artifact/com.impetus.core/kundera-core/2.8

Can you tell me what repository you used? If possible I would like to try then aswell with the snapshot version you mentioned.

**Comment by subes** [comment]
With Kundera 2.9-SNAPSHOT I get a different Stacktrace:

```
java.lang.IllegalArgumentException: The identifiable type does not have an id class
    at com.impetus.kundera.metadata.model.type.AbstractIdentifiableType.getIdClassAttributes(AbstractIdentifiableType.java:196)
    at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation$IdMetadata.<init>(JpaMetamodelEntityInformation.java:211)
    at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation.<init>(JpaMetamodelEntityInformation.java:77)
    at org.springframework.data.jpa.repository.support.JpaEntityInformationSupport.getMetadata(JpaEntityInformationSupport.java:65)
    at org.springframework.data.jpa.repository.support.SimpleJpaRepository.<init>(SimpleJpaRepository.java:92)
    at de.invesdwin.common.persistence.jpa.api.ADao.getDelegate(ADao.java:45)
```

The getDelegate() method in that case:

```
    private synchronized SimpleJpaRepository<TestEntity, Long> getDelegate() {
        if (delegate == null) {
            delegate = new SimpleJpaRepository<TestEntity, Long>(TestEntity.class, getEntityManager());
        }
        return delegate;
    }
```

So I think you should be able to reproduce this problem when trying the above sample with Spring-Data-JPA.

**Comment by mevivs** [comment]
Hi,
Could you please share a sample project to reproduce and debug this issue?

-Vivek

**Comment by subes** [comment]
I have created a sample project by extracting the relevant modules from my platform. You can download it here:
URL: http://invesdwin.de/public/kundera-sample.zip

You can try the sample by just running: mvn clean install
It should fail on the invesdwin-common-persistence-jpa-kundera-rdbms module (using Kundera-2.9-SNAPSHOT)
Alternatively import the maven modules in eclipse and run the KunderaTestSuite inside invesdwin-common-persistence-jpa-kundera-rdbms.

@mevivs: I have sent you the password to the ecrypted zip to you email address: vivek.mishra@yahoo.com
Tell me when you have downloaded the sample, so I can delete it from my server. The code is not to be published. :)

**Comment by subes** [comment]
thanks, I verified that this now works for me with trunk
