### ISSUE TITLE
I have a problem using kundera-rdbms.

### ISSUE THREAD

**Issue by yo2dh** [Impetus/kundera#45]
Hi.

I have a problem using kundera-rdbms 2.0.5.

persistence.xml 

```
<persistence-unit name="mysqlPU">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>com.testkun.kunderatest.Person</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>
    <properties> 
        <property name="kundera.client" value="rdbms" />
        <property name="hibernate.show_sql" value="true" />
        <property name="hibernate.format_sql" value="true" />
        <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5Dialect" />
        <property name="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver" />
        <property name="hibernate.connection.url" value="jdbc:mysql://localhost/test" />
        <property name="hibernate.connection.username" value="root" />
        <property name="hibernate.connection.password" value="test" />
        <property name="hibernate.current_session_context_class" value="org.hibernate.context.ThreadLocalSessionContext" />
    </properties>
</persistence-unit>
```

Person.java 

<pre>
package com.testkun.kunderatest;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "person" , schema = "test")
public class Person
{
    @Id 
    @Column (name="Name", length = 20)
    String  Name;

    @Column (name="Text", length = 45)
    String  Text;
    
    public String getName ()
    {
        return Name;
    }

    public void setName ( String name )
    {
        Name = name;
    }

    public String getText ()
    {
        return Text;
    }

    public void setText ( String text )
    {
        Text = text;
    }
}
</pre>

App.java

<pre>
package com.testkun.kunderatest;

import java.util.Date;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

public class App 
{
    public static void main( String[] args )
    {
       
        Person person = new Person();
        person.setName ( "Test" );
        person.setText ( "Test" );
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory ( "mysqlPU" );
        EntityManager em = emf.createEntityManager();
  
        em.persist ( person );

        em.close();    
        emf.close();   
    }
}
</pre>

And then I got :

</pre>

2012-03-06 16:58:41,030 [INFO ] [main] com.impetus.kundera.KunderaPersistence  - Loading Core
2012-03-06 16:58:41,034 [INFO ] [main] com.impetus.kundera.loader.CoreLoader  - Loading factories ... 
2012-03-06 16:58:41,044 [INFO ] [main] com.impetus.kundera.KunderaPersistence  - Loading Application MetaData and Initializing Client(s) For Persistence Unit(s) mysqlPU
2012-03-06 16:58:41,075 [INFO ] [main] com.impetus.kundera.loader.PersistenceUnitLoader  - Looking up for persistence unit: mysqlPU
2012-03-06 16:58:42,078 [INFO ] [main] com.impetus.kundera.persistence.EntityManagerFactoryImpl  - Loading Client(s) For Persistence Unit(s) mysqlPU
2012-03-06 16:58:42,088 [INFO ] [main] com.impetus.kundera.loader.GenericClientFactory  - Loading client metadata for persistence unit : mysqlPU
2012-03-06 16:58:42,088 [INFO ] [main] com.impetus.kundera.loader.GenericClientFactory  - Initializing client for persistence unit : mysqlPU
2012-03-06 16:58:42,134 [INFO ] [main] com.impetus.kundera.loader.GenericClientFactory  - Constructing pool for persistence unit : mysqlPU
2012-03-06 16:58:42,135 [INFO ] [main] com.impetus.kundera.persistence.EntityManagerFactoryImpl  - EntityManagerFactory created for persistence unit : mysqlPU
2012-03-06 16:58:42,146 [WARN ] [main] com.impetus.kundera.metadata.KunderaMetadataManager  - Something is terribly wrong, No Entity metadata found for the class class com.testkun.kunderatest.Person. If your entity is for RDBMS, make sure you put fully qualified entity class name under <class></class> tag in persistence.xml for RDBMS persistence unit. Returning null value.
java.lang.NullPointerException
    at com.impetus.kundera.persistence.event.EntityEventDispatcher.fireEventListeners(EntityEventDispatcher.java:54)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:587)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:152)
    at com.testkun.kunderatest.App.main(App.java:38)
Exception in thread "main" javax.persistence.PersistenceException: java.lang.NullPointerException
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:604)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:152)
    at com.testkun.kunderatest.App.main(App.java:38)
Caused by: java.lang.NullPointerException
    at com.impetus.kundera.persistence.event.EntityEventDispatcher.fireEventListeners(EntityEventDispatcher.java:54)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:587)
    ... 2 more
</pre>
Did I have a mistake?

Please, let me know.

**Comment by mevivs** [comment]
Kuldeep: Could you please look into this?

Also, there are some issues raised and fixed in current branch (2.0.6), so i suggest if you could build current developement branch?

https://github.com/impetus-opensource/Kundera/issues/40
https://github.com/impetus-opensource/Kundera/issues/1

**Comment by mevivs** [comment]
Verified with pom based dependency and as well as downloadable jar-dependencies. Working fine.
Please refer :

https://github.com/impetus-opensource/Kundera-Examples/blob/Kundera-Examples-2.0.5/src/test/java/com/impetus/kundera/examples/crud/PersonTest.java

For any further reference.

-Vivek

**Comment by yo2dh** [comment]
I used the branch (2.0.6), but I had another error.

<pre>
    public static EntityMetadata getEntityMetadata(Class entityClass)
    {
        // entityClass = "com.testkun.kunderatest.Person"
        List<String> persistenceUnits = KunderaMetadata.INSTANCE.getApplicationMetadata().getMappedPersistenceUnit(entityClass);
        
        // persistence units will only have more than 1 persistence unit in case of RDBMS.
        for (String pu : persistenceUnits)   // !!!! persistenceUnits is null. ---- exception
        {
               ....
        }
</pre>


Console :

<pre>
2012-03-06 23:54:48,281 [INFO ] [main] com.impetus.kundera.KunderaPersistence  - Loading Core
2012-03-06 23:54:48,284 [INFO ] [main] com.impetus.kundera.loader.CoreLoader  - Loading Kundera Core Metdata ... 
2012-03-06 23:54:48,293 [INFO ] [main] com.impetus.kundera.KunderaPersistence  - Loading Application MetaData and Initializing Client(s) For Persistence Unit(s) mysqlPU
2012-03-06 23:54:48,302 [INFO ] [main] com.impetus.kundera.configure.PersistenceUnitConfiguration  - Loading Metadata from persistence.xml ...
2012-03-06 23:54:49,527 [INFO ] [main] com.impetus.kundera.configure.PersistenceUnitConfiguration  - Finishing persistence unit metadata configuration ...
2012-03-06 23:54:49,653 [INFO ] [main] com.impetus.kundera.persistence.EntityManagerFactoryImpl  - Loading Client(s) For Persistence Unit(s) mysqlPU
2012-03-06 23:54:49,654 [INFO ] [main] com.impetus.kundera.client.ClientResolver  - Initializing client factory for: mysqlPU
2012-03-06 23:54:49,663 [INFO ] [main] com.impetus.kundera.client.ClientResolver  - Finishing factory initialization
2012-03-06 23:54:49,663 [INFO ] [main] com.impetus.kundera.loader.GenericClientFactory  - Loading client metadata for persistence unit : mysqlPU
2012-03-06 23:54:49,664 [INFO ] [main] com.impetus.kundera.loader.GenericClientFactory  - Initializing client for persistence unit : mysqlPU
2012-03-06 23:54:49,699 [INFO ] [main] com.impetus.kundera.loader.GenericClientFactory  - Constructing pool for persistence unit : mysqlPU
2012-03-06 23:54:49,699 [INFO ] [main] com.impetus.kundera.persistence.EntityManagerFactoryImpl  - EntityManagerFactory created for persistence unit : mysqlPU
Exception in thread "main" java.lang.NullPointerException
    at com.impetus.kundera.metadata.KunderaMetadataManager.getEntityMetadata(KunderaMetadataManager.java:129)
    at com.impetus.kundera.persistence.PersistenceDelegator.getMetadata(PersistenceDelegator.java:729)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:479)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:157)
    at com.testkun.kunderatest.App.main(App.java:38)
</pre>

**Comment by mevivs** [comment]
Please share your example. Entity definition, persistence.xml, CRUD operations.

I hope you must have followed :

https://github.com/impetus-opensource/Kundera-Examples/blob/Kundera-Examples-2.0.5/src/test/java/com/impetus/kundera/examples/crud/PersonTest.java

**Comment by yo2dh** [comment]
I changed kundera to hibernate in my project.

hibernate's persistence.xml : 
<code>
&ltpersistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd" 
    version="2.0">

```
<persistence-unit name="mysqlPU">
    <provider>org.hibernate.ejb.HibernatePersistence</provider>
    <class>com.testkun.kunderatest.Person</class>
    <properties>
        <property name="hibernate.show_sql" value="true" />
        <property name="hibernate.format_sql" value="true" />
        <property name="hibernate.use_sql_comments" value="true" />

        <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5Dialect" />
        <property name="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver" />
        <property name="hibernate.connection.url" value="jdbc:mysql://localhost/test" />
        <property name="hibernate.connection.username" value="root" />
        <property name="hibernate.connection.password" value="test" />
        <property name="hibernate.current_session_context_class" value="org.hibernate.context.ThreadLocalSessionContext" /> 

    </properties>
</persistence-unit>
```

&lt/persistence>

</code>

Java unit test source :

<pre><code>
    private static EntityManagerFactory emf;    
    private static EntityManager em;
    private Map<Object, Object> col;

    @Before    
    public void setUp() throws Exception    
    {        
        emf = Persistence.createEntityManagerFactory("mysqlPU");
        em = emf.createEntityManager();        
    }    
    
//    @Test
    public void testInsertRdbms()
    {
        Person person = new Person ( "person" , "test" );
        em.persist ( person );
    col.put ( "person" , person );

        Person personRDBMS = em.find ( Person.class , "person" );
        Assert.assertNotNull ( personRDBMS );
        Assert.assertEquals ( "test" , personRDBMS.getText() );
        
    }

    @After 
    public void tearDown() throws Exception
    {
        for ( Object val : col.values() )
        {
            em.remove ( val );
        }
    }

</code></pre>

The project using hibernate was working. 
But, kundera, not working.

kundera's persistence.xml : 

    <persistence-unit name="mysqlPU">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>com.testkun.kunderatest.Person</class>
        <properties>
            <property name="kundera.client" value="rdbms" />
            <property name="hibernate.show_sql" value="true" />
            <property name="hibernate.format_sql" value="true" />
            <property name="hibernate.use_sql_comments" value="true" />
            
            <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5Dialect" />
            <property name="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver" />
            <property name="hibernate.connection.url" value="jdbc:mysql://localhost/test" />
            <property name="hibernate.connection.username" value="root" />
            <property name="hibernate.connection.password" value="test" />
            <property name="hibernate.current_session_context_class" value="org.hibernate.context.ThreadLocalSessionContext" /> 
            
        </properties>
    </persistence-unit>
</code>

Person.java, entity class, is not changed.

pom.xml :

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.testkun</groupId>
    <artifactId>kunderatest</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>kunderatest</name>
    <url>http://maven.apache.org</url>

    <repositories>
        <repository>
            <id>kundera-missing</id>
            <name>Kundera Public Missing Resources Repository</name>
            <url>http://kundera.googlecode.com/svn/maven2/maven-missing-resources</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>riptano</id>
            <name>riptano</name>
            <url>http://mvn.riptano.com/content/repositories/public</url>
        </repository>
        <repository>
            <id>maven.scale7.org</id>
            <name>Scale7 Maven Repo</name>
            <url>https://github.com/s7/mvnrepo/raw/master</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>



    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.impetus.client</groupId>
            <artifactId>kundera-rdbms</artifactId>
            <version>2.0.5</version>
        </dependency>
        <dependency>
            <groupId>com.impetus.client</groupId>
            <artifactId>kundera-cassandra</artifactId>
            <version>2.0.5</version>
        </dependency>
         
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.6.3</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.4</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.6</source>
                    <target>1.6</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>


I got the error :
<pre>
WARN : com.impetus.kundera.metadata.KunderaMetadataManager - Something is terribly wrong, No Entity metadata found for the class class com.testkun.kunderatest.Person. If your entity is for RDBMS, make sure you put fully qualified entity class name under <class></class> tag in persistence.xml for RDBMS persistence unit. Returning null value.
java.lang.NullPointerException
    at com.impetus.kundera.persistence.event.EntityEventDispatcher.fireEventListeners(EntityEventDispatcher.java:54)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:587)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:152)
    at com.testkun.kunderatest.AppTest.testInsertRdbms(AppTest.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at junit.framework.TestCase.runTest(TestCase.java:168)
    at junit.framework.TestCase.runBare(TestCase.java:134)
    at junit.framework.TestResult$1.protect(TestResult.java:110)
    at junit.framework.TestResult.runProtected(TestResult.java:128)
    at junit.framework.TestResult.run(TestResult.java:113)
    at junit.framework.TestCase.run(TestCase.java:124)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:81)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</pre>


Why did not the kundera recognize <!class>com.testkun.kunderatest.Person</!class> in my persistence.xml?

**Comment by mevivs** [comment]
Could you please email me your project at vivek.mishra@yahoo.com

Kundera does recognize class tags and it works fine.  Can you try column annotation without length value?

Are you able to run Person Test written in kundera examples (link is given below):

https://github.com/impetus-opensource/Kundera-Examples/blob/Kundera-Examples-2.0.5/src/test/java/com/impetus/kundera/examples/crud/PersonTest.java

Let me know if it is working for you or not?

-Vivek

**Comment by yo2dh** [comment]
I emailed you my project file. 

I removed the length value in the column annotation, but it did not work. :(

**Comment by yo2dh** [comment]
I found the reason. 

My project is in "F:\My Project" folder.

com.impetus.kundera.classreading.ClasspathReader class :

<pre><code>
    @Override
    public final URL[] findResourcesByContextLoader()
    {
        ...
            URL[] urls = ((URLClassLoader) classLoader).getURLs();
            for (URL url : urls)
            {
                if (url.getPath().endsWith("/"))
                {
                    File file = new File(url.getPath() + classRelativePath + ".class");
                    if (file.exists())
...
</code></pre>


url.getPath() <- "F:\My%20Project".

So, file.exists()'s value is false.

And I think there may be a problem in another language folder such like korean.
