### ISSUE TITLE
Kundera 2.0.6-SNAPSHOT errors

### ISSUE THREAD

**Issue by yo2dh** [Impetus/kundera#46]
Hi.

I found the bugs.

Please, check the source codes.

In SpringSource Tool Suite's tc Server, Class folder is "C:\Program Files\springsource...\classes".

1.There is no /" at the end of class folder. 

So, run "new JarFileIterator(url.openStream(), filter); " at getResourceIterator in Reader class.

<pre>
            else if (!urlString.endsWith("/"))
            {
                return new JarFileIterator(url.openStream(), filter);
            }
</pre>

1.  Because of "Program%20Files" folder,  
   
   ```
           if (f.isDirectory())
   ```

f.isDirectory()'s value is false.

I fixed this source code.

<pre>
path = URLDecoder.decode ( url.getPath() , "UTF-8" );
</pre>

1. <pre>
       EntityManagerFactory emf = Persistence.createEntityManagerFactory ( "cassandraPU" );
       EntityManager em = emf.createEntityManager();
   
       @SuppressWarnings("unchecked")
       List<Content> listContent = em.createQuery ( "Select q from Content q" ).getResultList();
   </pre>

I got the error.

<pre>
Exception in thread "main" java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:922)
    at com.impetus.kundera.metadata.model.ApplicationMetadata.getPersistenceUnitMetadata(ApplicationMetadata.java:114)
    at com.impetus.client.cassandra.pelops.PelopsUtils.generatePoolName(PelopsUtils.java:50)
    at com.impetus.client.cassandra.pelops.PelopsClient.find(PelopsClient.java:677)
    at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:100)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:157)
    at com.testkun.kunderatest.App.main(App.java:75)
</pre>

The project at Kundera 2.0.5 works well.

**Comment by mevivs** [comment]
Where your entities reside? Could you please confirm relative path?

-Vivek

**Comment by nwallman** [comment]
I get a very similar issue when I run the SNAPSHOT:

java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:768)
    at com.impetus.kundera.metadata.model.ApplicationMetadata.getPersistenceUnitMetadata(ApplicationMetadata.java:114)
    at com.impetus.client.cassandra.pelops.PelopsUtils.generatePoolName(PelopsUtils.java:51)
    at com.impetus.client.cassandra.pelops.PelopsClient.find(PelopsClient.java:677)
    at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:100)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:157)
    at com.noob.batch.domain.wow.dao.RealmDAOImpl.getEnabledRealms(RealmDAOImpl.java:27)
    at com.noob.batch.domain.wow.mgr.RealmManager.getEnabledRealms(RealmManager.java:75)
    at com.noob.batch.BootStrap.doBoostrap(BootStrap.java:36)
    at com.noob.batch.RunBootStrap.main(RunBootStrap.java:13)

My entities reside here: D:\workspace\auctiontools\auctiontools-batch\target\classes

**Comment by nwallman** [comment]
Tracking it down now, it appears sometimes the ClientResolver.discoverClient(persistenceUnit) doesn't return a client with the persistenceUnit set.

**Comment by mevivs** [comment]
Shall i close it now?

**Comment by nwallman** [comment]
Didn't I already close it?  If it's not go ahead.
