### ISSUE TITLE
NullPointerException is thrown while fetching data from hbase when a field is in query but not in the Entity

### ISSUE THREAD

**Issue by tarang-dawer** [Impetus/kundera#469]
Example Query : -  Select p from Entity p where p.volme = 9

field Name in Entity is volume

Kundera generates the query and throws null pointer while retrieving data from hbase.

**Comment by mevivs** [comment]
2013-12-05 11:23:11 main [ERROR] ProcessFunction - Internal error processing query
java.lang.NullPointerException
    at java.util.StringTokenizer.<init>(StringTokenizer.java:182)
    at java.util.StringTokenizer.<init>(StringTokenizer.java:204)
    at com.impetus.client.hbase.query.HBaseQuery.getBytes(HBaseQuery.java:512)
    at com.impetus.client.hbase.query.HBaseQuery.access$200(HBaseQuery.java:62)
    at com.impetus.client.hbase.query.HBaseQuery$QueryTranslator.onParseFilter(HBaseQuery.java:409)
    at com.impetus.client.hbase.query.HBaseQuery$QueryTranslator.translate(HBaseQuery.java:361)
    at com.impetus.client.hbase.query.HBaseQuery.onQuery(HBaseQuery.java:158)
    at com.impetus.client.hbase.query.HBaseQuery.populateEntities(HBaseQuery.java:97)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:150)
    at

**Comment by mevivs** [comment]
Already fixed in 2.9 release. Please verify.

**Comment by tarang-dawer** [comment]
Verified & working.
