### ISSUE TITLE
Exception while inserting data into cassandra column having composite keys

### ISSUE THREAD

**Issue by jeetkulkarni** [Impetus/kundera#493]
I am getting the below exception while inserting data into 4 columns in a column family having a composite key

me.prettyprint.hector.api.exceptions.HInvalidRequestException: InvalidRequestException(why:Not enough bytes to read value of component 0)
        at me.prettyprint.cassandra.service.ExceptionsTranslatorImpl.translate(ExceptionsTranslatorImpl.java:50)
        at me.prettyprint.cassandra.service.KeyspaceServiceImpl$1.execute(KeyspaceServiceImpl.java:97)
        at me.prettyprint.cassandra.service.KeyspaceServiceImpl$1.execute(KeyspaceServiceImpl.java:90)
        at me.prettyprint.cassandra.service.Operation.executeAndSetResult(Operation.java:101)
        at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:232)
        at me.prettyprint.cassandra.service.KeyspaceServiceImpl.operateWithFailover(KeyspaceServiceImpl.java:131)
        at me.prettyprint.cassandra.service.KeyspaceServiceImpl.batchMutate(KeyspaceServiceImpl.java:102)
        at me.prettyprint.cassandra.service.KeyspaceServiceImpl.batchMutate(KeyspaceServiceImpl.java:108)
        at me.prettyprint.cassandra.model.MutatorImpl$3.doInKeyspace(MutatorImpl.java:222)
        at me.prettyprint.cassandra.model.MutatorImpl$3.doInKeyspace(MutatorImpl.java:219)
        at me.prettyprint.cassandra.model.KeyspaceOperationCallback.doInKeyspaceAndMeasure(KeyspaceOperationCallback.java:20)
        at me.prettyprint.cassandra.model.ExecutingKeyspace.doExecute(ExecutingKeyspace.java:85)
        at me.prettyprint.cassandra.model.MutatorImpl.execute(MutatorImpl.java:219)

Below is the definition of my cassandra column family created using CQL3 and Cassandra 2.0.3

CREATE TABLE "UsageReports_KeySpace"."UsageReports_Tbl" (
  sub_event_id text,
  event_date int,
  event_timestamp bigint,
  event_id text,
  ipaddress text,
  occd text,
  user_id text,
  PRIMARY KEY (sub_event_id, event_date, event_timestamp)
) WITH CLUSTERING ORDER BY (event_date ASC, event_timestamp ASC) AND
  bloom_filter_fp_chance=0.010000 AND
  caching='KEYS_ONLY' AND
  comment='' AND
  dclocal_read_repair_chance=0.000000 AND
  gc_grace_seconds=864000 AND
  read_repair_chance=0.100000 AND
  replicate_on_write='true' AND
  populate_io_cache_on_flush='false' AND
  compaction={'class': 'SizeTieredCompactionStrategy'} AND
  compression={'sstable_compression': 'LZ4Compressor'};

CREATE INDEX occd_idx ON "UsageReports_KeySpace"."UsageReports_Tbl" (occd);

Below is the code that I am using for inserting the data
Hector API version 0.8.0-2
Cluster cluster = HFactory.getOrCreateCluster("TestCluster",
                "localhost:9160");

```
    Keyspace keyspaceOperator = HFactory.createKeyspace("UsageReports_KeySpace",
            cluster);
    try {
        Mutator<Composite> mutator = HFactory.createMutator(keyspaceOperator,new CompositeSerializer());

        Composite rowKey = new Composite();

        rowKey.addComponent("ACCT", stringSerializer);
        rowKey.addComponent(20120101,me.prettyprint.cassandra.serializers.IntegerSerializer.get());
        rowKey.addComponent(BigInteger.valueOf(1234567),me.prettyprint.cassandra.serializers.BigIntegerSerializer.get());

        mutator.addInsertion(rowKey, "UsageReports_Tbl", HFactory.createColumn("event_id", "RUN", stringSerializer, stringSerializer));
        mutator.addInsertion(rowKey, "UsageReports_Tbl", HFactory.createColumn("ipaddress", "x.x.x.x.", stringSerializer, stringSerializer));
        mutator.addInsertion(rowKey, "UsageReports_Tbl", HFactory.createColumn("occd", "AXIOM", stringSerializer, stringSerializer));
        mutator.addInsertion(rowKey, "UsageReports_Tbl", HFactory.createColumn("user_id", "PCQILC1", stringSerializer, stringSerializer));
        mutator.execute();
```

Thanks
Jeet

**Comment by mevivs** [comment]
Looks like it's an issue with Hector not with Kundera. Hector community should help you out with this.

-Vivek

**Comment by jeetkulkarni** [comment]
Ok Thanks. I will check with the Hector community
