### ISSUE TITLE
NullPointerException creating EntityManager

### ISSUE THREAD

**Issue by janinko** [Impetus/kundera#506]
Hi,

I'm using Kundera for Neo4j on JBoss EAP some issues with getting it work. One of them is NullPointerException when trying to persist entity.

EAP 6.1.1
Kundera 2.9

``` java
    @PersistenceContext(unitName = "neo4jPU")
    protected EntityManager em;

    public void create(NeoArtifact entity) {
        em.persist(entity);
    }
```

```
Caused by: java.lang.NullPointerException
    at org.jboss.as.jpa.container.EntityManagerUtil.createEntityManager(EntityManagerUtil.java:44) [jboss-as-jpa-7.2.1.Final-redhat-10.jar:7.2.1.Final-redhat-10]
    at org.jboss.as.jpa.transaction.TransactionUtil.getOrCreateTransactionScopedEntityManager(TransactionUtil.java:114) [jboss-as-jpa-7.2.1.Final-redhat-10.jar:7.2.1.Final-redhat-10]
    at org.jboss.as.jpa.container.TransactionScopedEntityManager.getEntityManager(TransactionScopedEntityManager.java:74) [jboss-as-jpa-7.2.1.Final-redhat-10.jar:7.2.1.Final-redhat-10]
    at org.jboss.as.jpa.container.AbstractEntityManager.persist(AbstractEntityManager.java:563) [jboss-as-jpa-7.2.1.Final-redhat-10.jar:7.2.1.Final-redhat-10]
    at org.jboss.buildtracker.database.dao.neo4j.impl.NeoTestDAO.create(NeoTestDAO.java:18) [build-tracker-backend-1.0.0-SNAPSHOT.jar:]
```

``` xml
  <persistence-unit name="neo4jPU">
      <provider>com.impetus.kundera.KunderaPersistence</provider>
      <class>org.jboss.buildtracker.database.dao.neo4j.model.NeoArtifact</class>
      <class>org.jboss.buildtracker.database.dao.neo4j.model.NeoContains</class>
      <class>org.jboss.buildtracker.database.dao.neo4j.model.NeoDependency</class>
      <class>org.jboss.buildtracker.database.dao.neo4j.model.NeoRelease</class>
      <exclude-unlisted-classes>true</exclude-unlisted-classes>
      <properties>
          <property name="kundera.nodes" value="localhost"/>
          <property name="kundera.port" value="7474"/>
          <property name="kundera.dialect" value="neo4j"/>
          <property name="kundera.client.lookup.class" value="com.impetus.client.neo4j.Neo4JClientFactory" />
          <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
          <property name="kundera.cache.config.resource" value="/ehcache-test.xml"/>
          <property name="kundera.transaction.resource.class" value="com.impetus.client.neo4j.Neo4JTransaction" />
      </properties>
  </persistence-unit>
```

**Comment by mevivs** [comment]
Please refer 
https://github.com/impetus-opensource/Kundera/issues/180

You need to:
1. jboss.as.jpa.managed as false in persistence.xml
2. include your entity classes with in tag and to true in persistence.xml

-Vivek

**Comment by janinko** [comment]
I added

``` xml
          <property name="jboss.as.jpa.managed" value="false" />
```

into my persistence.xml, and now it even fails to deploy:

```
18:24:39,201 INFO  [org.jboss.weld.deployer] (MSC service thread 1-5) JBAS016005: Starting Services for CDI deployment: bt.war
18:24:39,258 INFO  [org.jboss.weld.Version] (MSC service thread 1-5) WELD-000900 1.1.13 (redhat)
18:24:39,349 INFO  [org.jboss.weld.deployer] (MSC service thread 1-8) JBAS016008: Starting weld service for deployment bt.war
18:24:40,685 ERROR [org.jboss.as.server] (DeploymentScanner-threads - 1) JBAS015870: Deploy of deployment "bt.war" was rolled back with the following failure message: {"JBAS014771: Services with missing/unavailable dependencies" => ["jboss.naming.context.java.module.bt.bt.env.\"org.jboss.buildtracker.database.dao.neo4j.impl.GenericNeoDAO\".em is missing [jboss.persistenceunit.\"bt.war#neo4jPU\"]"]}
18:24:40,705 INFO  [org.jboss.weld.deployer] (MSC service thread 1-8) JBAS016009: Stopping weld service for deployment bt.war
```

``` java
public abstract class GenericNeoDAO<T> implements GenericDAO<T> {

    @PersistenceContext(unitName = "neo4jPU")
    protected EntityManager em;

```

**Comment by mevivs** [comment]
Can't get much from logs. Please provide more logs. Also, Sample application to deploy over JBoss is available here =>
https://github.com/impetus-opensource/Kundera/tree/trunk/examples/container/jboss

-Vivek

**Comment by janinko** [comment]
with `<property name="jboss.as.jpa.managed" value="false" />` https://gist.github.com/janinko/ffdf92b21592acbe8d3a
without https://gist.github.com/janinko/38ee472f847ce05c66af

**Comment by kkmishra** [comment]
Looks like issue #519 , Fixed in current trunk branch.
Please verify.

Thanks
Kuldeep

**Comment by chhavigangwal** [comment]
Looks like issue is more specific to CDI configuration. Same is being discussed on google group  https://groups.google.com/forum/#!topic/kundera-discuss/spkIZnKYNdQ. We are looking into this.
