### ISSUE TITLE
KunderaMongo - Issues with JSON Serialization

### ISSUE THREAD

**Issue by pdirksen** [Impetus/kundera#515]
MongoDB Version: 2.2.7
Kundera: kundera-mongo 2.9

``` java

@Entity
public class TestObservation {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String id;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne
    private TestFeature feature;

    public TestFeature getTestFeature() {
        return feature;
    }

    public void setTestFeature(TestFeature feature) {
        this.feature = feature;
    }
}

@Entity
public class TestFeature {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String id;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Basic(optional = false)
    @Column(nullable = false, unique = true)
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(mappedBy = "feature", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<TestObservation> observations;

    public List<TestObservation> getObservations() {
        return observations;
    }

    public void setObservations(List<TestObservation> observations) {
        this.observations = observations;
    }
}


Transaction transaction = em.getTransaction();
transaction.begin();

TestFeature feature = new TestFeature();
feature.setName("Testie");
em.persist(feature);

TestObservation tObs = new TestObservation();
tObs.setTestFeature(feature);        
em.persist(tObs);

List<TestObservation> testie = em.createQuery("SELECT o FROM TestObservation o WHERE o.feature = :feature", TestObservation.class).
setParameter("feature", feature).getResultList();

transaction.commit();
```

Causes:

```
Error during executing query, Caused by:
java.lang.RuntimeException: json can't serialize type : class de.cebitec.gendb.persistence.TestFeature
    at com.mongodb.util.ClassMapBasedObjectSerializer.serialize(ClassMapBasedObjectSerializer.java:77)
    at com.mongodb.util.JSONSerializers$MapSerializer.serialize(JSONSerializers.java:307)
    at com.mongodb.util.ClassMapBasedObjectSerializer.serialize(ClassMapBasedObjectSerializer.java:79)
    at com.mongodb.util.JSON.serialize(JSON.java:56)
    at com.mongodb.util.JSON.serialize(JSON.java:41)
    at com.mongodb.BasicDBObject.toString(BasicDBObject.java:83)
    at com.impetus.client.mongodb.MongoDBClient.loadData(MongoDBClient.java:424)
    at com.impetus.client.mongodb.query.MongoDBQuery.recursivelyPopulateEntities(MongoDBQuery.java:176)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:157)
```

Did I really miss something?

**Comment by mevivs** [comment]
```
List<TestObservation> testie = em.createQuery("SELECT o FROM TestObservation o WHERE o.feature = :feature", TestObservation.class).
```

Such queries are not yet supported, only scalar values are allowed as part of Where clause(Except in case of embedded composite key). I am wondering what you exactly want by this JPQL?

-Vivek

**Comment by pdirksen** [comment]
I would like to get all TestObservation objects which have a specific Feature object.

**Comment by mevivs** [comment]
Since it is a bi directional association. You could query same via TestFeature as well!

-Vivek

**Comment by chhavigangwal** [comment]
@pdirksen 

Is the issue resolved for you?

Chhavi

**Comment by chhavigangwal** [comment]
@pdirksen 

Any updates ?

Chhavi
