### ISSUE TITLE
Invalid stream header while retrieving an EmbeddedId using Kundera 2.9

### ISSUE THREAD

**Issue by msfbrasil** [Impetus/kundera#518]
Hello there!

I'm migrating the persistence API of an application from "Hector API" to "Kundera".

Application is pretty simple and have only two entities.

It was very ease to create the DAO for both entities with all common operations using Kundera (version 2.9).

The problem occurs on all operations that involve the reading the entity that has an EmbeddedId (or composite key on Cassandra).
This key is composed by "text" and "date"

During full list, I get the exception trace below for each row on the table and the partition key (the "text" field) is not filled:

31 Jan 2014 14:07:30 [main] WARN  com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.setFieldValueViaCQL - Error while setting fieldid value via CQL, Caused by: .
com.impetus.kundera.property.PropertyAccessException: java.io.StreamCorruptedException: invalid stream header: 64635F67
    at com.impetus.kundera.property.accessor.ObjectAccessor.fromBytes(ObjectAccessor.java:70)
    at com.impetus.kundera.property.PropertyAccessorHelper.set(PropertyAccessorHelper.java:56)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.setFieldValueViaCQL(CassandraDataHandlerBase.java:1201)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateViaThrift(CassandraDataHandlerBase.java:1102)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.onColumn(CassandraDataHandlerBase.java:1018)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateEntity(CassandraDataHandlerBase.java:621)
    at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2114)
    at com.impetus.client.cassandra.CassandraClientBase.executeSelectQuery(CassandraClientBase.java:833)
    at com.impetus.client.cassandra.thrift.ThriftClient.executeQuery(ThriftClient.java:944)
    at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:140)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:153)
    at com.impetus.client.cassandra.query.CassQuery.onExecuteUpdate(CassQuery.java:269)
    at com.impetus.kundera.query.QueryImpl.executeUpdate(QueryImpl.java:136)
    at 
        ... my TestingCode ....
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

Could someone please help me on that?

Thanks and best regards,
Mauro.

**Comment by mevivs** [comment]
Data persisted via Kundera or was already available with database?

-Vivek

**Comment by mevivs** [comment]
Please share your entity definition as well

-Vivek

**Comment by msfbrasil** [comment]
Hi and thanks for the help!

We are starting with the database from scratch.
I've just installed Cassandra and created the model using "cqlsh". Versions of them follow below:

[cqlsh 4.1.0 | Cassandra 2.0.4 | CQL spec 3.1.1 | Thrift protocol 19.39.0]

Entities were created with commands:

CREATE TABLE tags (id text PRIMARY KEY, backend text, customer_id text, entity text, location text, ip text, metric text);
CREATE TABLE ts (id text, time timestamp, value double, PRIMARY KEY (id, time));

I'll only focus on "ts" entity, given that "tags" one (that has no compound key) works perfectly.

"ts" entity definition is as follows:

@Entity
@Table(name = "ts", schema = "KEYSPACE_NAME")
public class TimeSeries extends BaseEntity<TimeSeriesId> {

```
private static final long serialVersionUID = -6584472077951636637L;

@Transient
private ConfigurationTag configurationTag;

@EmbeddedId
private TimeSeriesId id;

@Column(name = "value")
private Double value;

.... the getters, setters, etc
```

}

and 

@Embeddable
public class TimeSeriesId implements Serializable {

```
private static final long serialVersionUID = 4951139620096359351L;

@Column(name = "id")
private String id;

@Column(name = "time")
private Date timestamp;

.... the getters, setters, etc
```

}

I have already tried to change the client to "Pelops..." (now is configured with "Thrift..." on "persistence.xml") and to change some jars versions, but with no effect.

Please let me know if you need any additional information.

Thanks,
Mauro.

**Comment by mevivs** [comment]
I am trying at my end. Till the time Please try by changing 

```
@EmbeddedId
private TimeSeriesId id;

```

to 

```
@EmbeddedId
private TimeSeriesId timeSeriesId;
```

If it works.

-Vivek

**Comment by mevivs** [comment]
Hi, 
This is what i have tried.

```
@Embeddable
public class TimeSeriesId
{

    private static final long serialVersionUID = 4951139620096359351L;

    @Column(name = "id")
    private String id;

    @Column(name = "time")
    private Date timestamp;

// getters and setters
```

```
@Entity
@Table(name = "ts")
public class TimeSeries
{

    private static final long serialVersionUID = -6584472077951636637L;

    @EmbeddedId
    private TimeSeriesId timeSeriesId;

    @Column(name = "value")
    private Double value;

// getters and setters
}
```

CRUD snippet

```

        Map<String,String> propMap = new HashMap<String, String>();

        propMap.put(CassandraConstants.CQL_VERSION,CassandraConstants.CQL_VERSION_3_0);
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("CassandraPU",propMap);
        EntityManager em = emf.createEntityManager();

//        em.getDelegate();

       TimeSeries series = new TimeSeries();

       TimeSeriesId id = new TimeSeriesId();
       id.setId("t1");
       id.setTimestamp(new Date());


       series.setId(id);
       series.setValue(12d);

       em.persist(series);

       em.clear();
       TimeSeries found = em.find(TimeSeries.class, id);
       System.out.println(found.getId().getId());

```

cql3 output

![image](https://f.cloud.github.com/assets/456249/2053271/cab82db8-8aa4-11e3-8471-3134da29c569.png)

I think issue here is:
1. same column name for timeseries embedded id and embeddable attribute "id"

Hope it helps.

-Vivek

**Comment by msfbrasil** [comment]
Man...

I was trying to debug it here...
Getting into the deep of Kundera when I saw your response...

I was a little sceptic because of the nature of the "fix" :-p, but I changed it and it worked perfectly.

Thanks a lot!
You saved my weekend :-D.

Best regards,
Mauro.

**Comment by mevivs** [comment]
Reason for this issue is , you cannot have two 2 columns(nested column) with same name

Closing it.

-Vivek

**Comment by msfbrasil** [comment]
Thanks a lot for sharing the reason.
It's good to know.

Thanks again for the help and have a good weekend.
Mauro.
