### ISSUE TITLE
Executing update with ANDs and ORs incorrectly transformed into broken select query

### ISSUE THREAD

**Issue by xdavidjung** [Impetus/kundera#523]
When executing this query:

UPDATE Secret s SET s.revoked=true WHERE s.id.client_name = test_client AND s.id.secret_name = 'test_secret_2' OR s.id.secret_name = 'test_secret'

I get this error when I hit query.executeUpdate():
    2014-02-12 17:56:54 ERROR CassandraClientBase:1925 - Error during executing query SELECT \* FROM "secret" WHERE "client_name" = 'test_client' AND "secret_name" = 'test_secret_2' AND "secret_name" = 'test_secret' LIMIT 100  ALLOW FILTERING, Caused by: InvalidRequestException(why:secret_name cannot be restricted by more than one relation if it includes an Equal) .
    2014-02-12 17:56:54 ERROR CassandraClientBase:2138 - Error while executing native CQL query Caused by: .
javax.persistence.PersistenceException: InvalidRequestException(why:secret_name cannot be restricted by more than one relation if it includes an Equal)
        at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:1927)
        at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2103)
        at com.impetus.client.cassandra.CassandraClientBase.executeSelectQuery(CassandraClientBase.java:834)
        at com.impetus.client.cassandra.thrift.ThriftClient.executeQuery(ThriftClient.java:916)
        at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:137)
        at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:920)
        at com.impetus.kundera.query.QueryImpl.onUpdateDeleteEvent(QueryImpl.java:268)
        at com.impetus.client.cassandra.query.CassQuery.onExecuteUpdate(CassQuery.java:266)
        at com.impetus.kundera.query.QueryImpl.executeUpdate(QueryImpl.java:133)

Somewhere in the implementation there is a query that tries to transform my original update query into a select query, and that query seems to be being transformed incorrectly.

Here's my code snippet, let me know if I'm doing it wrong.

```
        String queryString = getQueryString(clientName, secretNames);
        Query updateQuery = em.createQuery(queryString);

        em.getTransaction().begin();
        updateQuery.executeUpdate();  // Where the error is occurring.
        em.getTransaction().commit();
```

**Comment by xdavidjung** [comment]
Nevermind, didn't realize Kundera didn't support OR for Cassandra.
