### ISSUE TITLE
@Embeddable not working on kundera-neo4j

### ISSUE THREAD

**Issue by gurkerl83** [Impetus/kundera#527]
Hi, is it possible to use @Embeddable, @Embedded and @EmbeddedId with kundera-neo4j - 2.10? Trying the mentioned Annotations Neo4jClient is throwing 

java.lang.IllegalArgumentException: Unknown property type on: , class "@Embeddable Entity"

at org.neo4j.kernel.impl.nioneo.store.PropertyStore.encodeValue(PropertyStore.java:582)[120:neo4j-kernel:1.9.05]
    at org.neo4j.kernel.impl.nioneo.xa.WriteTransaction.nodeAddProperty(WriteTransaction.java:1238)[120:neo4j-kernel:1.9.05]
    at org.neo4j.kernel.impl.persistence.PersistenceManager.nodeAddProperty(PersistenceManager.java:144)[120:neo4j-kernel:1.9.05]
    at org.neo4j.kernel.impl.core.NodeManager.nodeAddProperty(NodeManager.java:910)[120:neo4j-kernel:1.9.05]
    at org.neo4j.kernel.impl.core.NodeImpl.addProperty(NodeImpl.java:123)[120:neo4j-kernel:1.9.05]
    at org.neo4j.kernel.impl.core.Primitive.setProperty(Primitive.java:436)[120:neo4j-kernel:1.9.05]
    at org.neo4j.kernel.impl.core.NodeImpl.setProperty(NodeImpl.java:53)[120:neo4j-kernel:1.9.05]
    at org.neo4j.kernel.impl.core.NodeProxy.setProperty(NodeProxy.java:130)[120:neo4j-kernel:1.9.05]
    at com.impetus.client.neo4j.GraphEntityMapper.populateNodeProperties(GraphEntityMapper.java:320)[154:kundera-neo4j:2.10]

thanks!

**Comment by mevivs** [comment]
Could you please share entity definitions?

-Vivek

**Comment by chhavigangwal** [comment]
Please share the entity definitions to further analyze the issue.

Chhavi

**Comment by chhavigangwal** [comment]
A sample test case for using @Embeddable, @EmbeddedId  with kundera-neo4j can be found at : 

https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-neo4j/src/test/java/com/impetus/client/neo4j/imdb/composite/IMDBCompositeKeyTest.java

Chhavi
