### ISSUE TITLE
Problems with Kundera Neo4j on JBoss EAP 6.1.1

### ISSUE THREAD

**Issue by janinko** [Impetus/kundera#535]
Hi,

I encountered some problems when trying to make Kundera with Neo4j working for EAP 6.11. I was trying Kundera versions 2.10 and 2.11-SNAPSHOT of 25ede9fa7e7514188ed35a83aa576e7633cc221b.

In my persistence.xml:

``` xml
  <persistence-unit name="neo4jPU">
     <provider>com.impetus.kundera.KunderaPersistence</provider>
     <class>org.jboss.buildtracker.database.dao.neo4j.model.NeoArtifact</class>
     <class>org.jboss.buildtracker.database.dao.neo4j.model.NeoDependency</class>
     <exclude-unlisted-classes>true</exclude-unlisted-classes>
     <properties>
        <property name="kundera.datastore.file.path" value="tmp/qwertza.db"/>
        <property name="kundera.dialect" value="neo4j"/>
        <property name="kundera.client.lookup.class" value="com.impetus.client.neo4j.Neo4JClientFactory" />
        <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
        <property name="kundera.cache.config.resource" value="/ehcache-test.xml"/>
        <property name="kundera.transaction.resource.class" value="com.impetus.client.neo4j.Neo4JTransaction" />
        <property name="jboss.as.jpa.managed" value="false" />
     </properties>
  </persistence-unit>
```

When trying to deploy, it failed with:

```
15:30:48,235 INFO  [org.jboss.as.controller] (Controller Boot Thread) JBAS014774: Service status report
JBAS014775:    New missing/unsatisfied dependencies:
      service jboss.persistenceunit."build-tracker.ear/build-tracker-backend.jar#neo4jPU" (missing) dependents: [service jboss.naming.context.java.comp.build-tracker.build-tracker-backend.NeoTestDAO.env."org.jboss.buildtracker.database.dao.neo4j.impl.GenericNeoDAO".em]
```

---

Then I removed line with `jboss.as.jpa.managed` from the peristence.xml.
Whith Kundera 2.10 I got following error when the `kundera.client.lookup.class` is set. It looked to me like inverted condition, but the error is not present in 2.11-SNAPSHOT.

```
15:15:42,069 INFO  [com.impetus.kundera.persistence.EntityManagerFactoryImpl] (ServerService Thread Pool -- 49) Loading Core
15:15:42,071 INFO  [com.impetus.kundera.loader.CoreLoader] (ServerService Thread Pool -- 49) Loading Kundera Core Metdata ... 
15:15:42,076 INFO  [com.impetus.kundera.persistence.EntityManagerFactoryImpl] (ServerService Thread Pool -- 49) Loading Persistence Unit MetaData For Persistence Unit(s) neo4jPU.
15:15:42,079 INFO  [com.impetus.kundera.configure.PersistenceUnitConfiguration] (ServerService Thread Pool -- 49) Loading Metadata from persistence.xml ...
15:15:42,086 ERROR [com.impetus.kundera.configure.PersistenceUnitConfiguration] (ServerService Thread Pool -- 49) kundera.client property is missing for persistence unit:neo4jPU
15:15:42,087 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 49) MSC000001: Failed to start service jboss.persistenceunit."build-tracker.ear/build-tracker-backend.jar#neo4jPU": org.jboss.msc.service.StartException in service jboss.persistenceunit."build-tracker.ear/build-tracker-backend.jar#neo4jPU": java.lang.IllegalArgumentException: kundera.client property is missing for persistence unit:neo4jPU
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:103)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_51]
    at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_51]
    at org.jboss.threads.JBossThread.run(JBossThread.java:122) [jboss-threads-2.1.0.Final-redhat-1.jar:2.1.0.Final-redhat-1]
Caused by: java.lang.IllegalArgumentException: kundera.client property is missing for persistence unit:neo4jPU
    at com.impetus.kundera.configure.PersistenceUnitConfiguration.configure(PersistenceUnitConfiguration.java:136)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configurePersistenceUnit(EntityManagerFactoryImpl.java:656)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:111)
    at com.impetus.kundera.KunderaPersistence.createContainerEntityManagerFactory(KunderaPersistence.java:63)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.createContainerEntityManagerFactory(PersistenceUnitServiceImpl.java:200)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.access$600(PersistenceUnitServiceImpl.java:57)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:99)
    ... 4 more
```

---

With Kundera 2.11-SNAPSHOT the previous error is not present any more, but I'm getting the following one. I found out that Neo4j is using Lucene indexer compiled against Lucene 3.6.2 but Kundera is using Lucene 4.4.0 and some method was changed to final between these versions.

```
15:23:15,849 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 48) MSC000001: Failed to start service jboss.persistenceunit."build-tracker.ear/build-tracker-backend.jar#neo4jPU": org.jboss.msc.service.StartException in service jboss.persistenceunit."build-tracker.ear/build-tracker-backend.jar#neo4jPU": org.neo4j.kernel.lifecycle.LifecycleException: Failed to transition org.neo4j.kernel.InternalAbstractGraphDatabase$DefaultKernelExtensionLoader@fbfc6d1 from NONE to STOPPED
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:103)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_51]
    at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_51]
    at org.jboss.threads.JBossThread.run(JBossThread.java:122) [jboss-threads-2.1.0.Final-redhat-1.jar:2.1.0.Final-redhat-1]
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Failed to transition org.neo4j.kernel.InternalAbstractGraphDatabase$DefaultKernelExtensionLoader@fbfc6d1 from NONE to STOPPED
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:388)
    at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:82)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:116)
    at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:230)
    at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:79)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:70)
    at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:205)
    at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:56)
    at com.impetus.client.neo4j.Neo4JClientFactory.createPoolOrConnection(Neo4JClientFactory.java:107)
    at com.impetus.kundera.loader.GenericClientFactory.load(GenericClientFactory.java:119)
    at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:55)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:405)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configure(EntityManagerFactoryImpl.java:158)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:113)
    at com.impetus.kundera.KunderaPersistence.createContainerEntityManagerFactory(KunderaPersistence.java:63)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.createContainerEntityManagerFactory(PersistenceUnitServiceImpl.java:200)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.access$600(PersistenceUnitServiceImpl.java:57)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:99)
    ... 4 more
Caused by: java.lang.VerifyError: class org.neo4j.index.impl.lucene.LuceneDataSource$1 overrides final method tokenStream.(Ljava/lang/String;Ljava/io/Reader;)Lorg/apache/lucene/analysis/TokenStream;
    at java.lang.ClassLoader.defineClass1(Native Method) [rt.jar:1.7.0_51]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800) [rt.jar:1.7.0_51]
    at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:344) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:422) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:260) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:75) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.jboss.modules.Module.loadModuleClass(Module.java:526) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:188) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:444) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:432) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:374) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:119) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.neo4j.index.lucene.LuceneIndexProvider.load(LuceneIndexProvider.java:72)
    at org.neo4j.kernel.InternalAbstractGraphDatabase$DefaultKernelExtensionLoader.loadIndexImplementations(InternalAbstractGraphDatabase.java:1181)
    at org.neo4j.kernel.InternalAbstractGraphDatabase$DefaultKernelExtensionLoader.init(InternalAbstractGraphDatabase.java:1153)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:382)
    ... 21 more
```

**Comment by mevivs** [comment]
Can you please verify, if you have multiple lucene-core jars in classpath. AFAIK, kundera-neo4j is using neo4j 1.8.1 and lucene-core 's 3.5.0 only

-Vivek

**Comment by janinko** [comment]
I packaged it with com.impetus.kundera.core:fallback-impl witch comes with lucene 4.4.0.
When I packaged it withoud fallback-impl there was lucene 3.5.0 from kundera-neo4j, but when deploying I was getting `ClassNotFoundException` for `com.impetus.kundera.cache.ehcache.EhCacheProvider` which I found in the fallback-impl.

```
16:08:52,027 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 49) MSC000001: Failed to start service jboss.persistenceunit."build-tracker.ear/build-tracker-backend.jar#neo4jPU": org.jboss.msc.service.StartException in service jboss.persistenceunit."build-tracker.ear/build-tracker-backend.jar#neo4jPU": com.impetus.kundera.cache.CacheException: Could not find class com.impetus.kundera.cache.ehcache.EhCacheProvider. Check whether you spelled it correctly in persistence.xml
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:103)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_51]
    at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_51]
    at org.jboss.threads.JBossThread.run(JBossThread.java:122) [jboss-threads-2.1.0.Final-redhat-1.jar:2.1.0.Final-redhat-1]
Caused by: com.impetus.kundera.cache.CacheException: Could not find class com.impetus.kundera.cache.ehcache.EhCacheProvider. Check whether you spelled it correctly in persistence.xml
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.initSecondLevelCache(EntityManagerFactoryImpl.java:438)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configure(EntityManagerFactoryImpl.java:172)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:113)
    at com.impetus.kundera.KunderaPersistence.createContainerEntityManagerFactory(KunderaPersistence.java:63)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.createContainerEntityManagerFactory(PersistenceUnitServiceImpl.java:200)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.access$600(PersistenceUnitServiceImpl.java:57)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:99)
    ... 4 more
Caused by: java.lang.ClassNotFoundException: com.impetus.kundera.cache.ehcache.EhCacheProvider from [Module "deployment.build-tracker.ear:main" from Service Module Loader]
    at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:196) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:444) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:432) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:374) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:119) [jboss-modules.jar:1.2.2.Final-redhat-1]
    at java.lang.Class.forName0(Native Method) [rt.jar:1.7.0_51]
    at java.lang.Class.forName(Class.java:190) [rt.jar:1.7.0_51]
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.initSecondLevelCache(EntityManagerFactoryImpl.java:432)
    ... 10 more
```

Should I use something different in persistence.xml then this?

``` xml
        <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
```

**Comment by mevivs** [comment]
Do you need to enable L2 cache? if not, then you can disable this property

```
<property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider" />          
<property name="kundera.cache.config.resource" value="/ehcache-test.xml" />
```

from persistence.xml

https://github.com/impetus-opensource/Kundera/wiki/Troubleshooting (point 3)

Else, i suggest to exclude  lucene-core dependency with fallback-impl dependency as:

```

        <dependency>
            <groupId>com.impetus.kundera.core</groupId>
            <artifactId>fallback-impl</artifactId>
            <version>${project.version}</version>
                       <exclusions>
                              <exclusion>
                                <groupId>org.apache.lucene</groupId>
                            <artifactId>lucene-core</artifactId>
                             <exclusion>
                       </exclusions>
        </dependency>
```

**Comment by janinko** [comment]
Ok, I disabled it and now it deployed. But I'm getting followong error when trying to use entityManager.persist()

```
Caused by: com.impetus.kundera.KunderaException: Please bind [com.impetus.kundera.persistence.jta.KunderaJTAUserTransaction] for :{java:comp/UserTransaction} lookupclass org.jboss.tm.usertx.client.ServerVMClientUserTransaction
    at com.impetus.kundera.persistence.EntityManagerImpl.onLookUp(EntityManagerImpl.java:861) [kundera-core.jar:]
    at com.impetus.kundera.persistence.EntityManagerImpl.checkTransactionNeeded(EntityManagerImpl.java:826) [kundera-core.jar:]
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:166) [kundera-core.jar:]
    at org.jboss.as.jpa.container.AbstractEntityManager.persist(AbstractEntityManager.java:563) [jboss-as-jpa-7.2.1.Final-redhat-10.jar:7.2.1.Final-redhat-10]
```

**Comment by mevivs** [comment]
transaction-type attribute in persistence.xml is set to "JTA" ?
If yes, you need to bind it as transaction resource.
In case of Tomcat

http://tomcat.apache.org/tomcat-7.0-doc/jndi-resources-howto.html

<Transaction> - Add a resource factory for instantiating the UserTransaction object instance that is available at java:comp/UserTransaction.

```
<Transaction factory="com.impetus.kundera.persistence.jta.UserTransactionFactory" />
```

HTH,
-Vivek

**Comment by mevivs** [comment]
Any update? Tested with 2.11? 

-Vivek

**Comment by janinko** [comment]
Hi,

I'm now testing Hibernate OGM.

Honza
