### ISSUE TITLE
Kundera does not handle multiple relations in neo4j entities

### ISSUE THREAD

**Issue by FangmingD** [Impetus/kundera#565]
I just created a simple Actor class with two relations. When persist new Actor instance, I only set one relation and in find I got Exception, because Kundera try to set a relation I did not persist. (In my own code, I have two different relation and entities related to one entity, here just created two dummy movie, role classes)

In real scenario, one entity could have tens of relations, but not every entity should have all the relations in database.
like Person could be an entity, employees --> company could be one relation, but not every person needs to have this relation.

```
@Entity
@Table(name = "actor", schema = "oculus")
public class Actor
{
    @Id
    @Column(name = "ACTOR_ID")
    private String id;

    @Column(name = "ACTOR_NAME")
    private String name;

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @MapKeyJoinColumn(name = "ACTS_IN")
    private Map<Role1, Movie> movies1;

    public void addMovie(Role1 role, Movie movie)
    {
        if (movies1 == null) movies1 = new HashMap<Role1, Movie>();
        movies1.put(role, movie);
    }

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @MapKeyJoinColumn(name = "ACTS_IN")
    private Map<Role2, Movie2> movies2;

    public Map<Role2, Movie2> getMovies2() {
        return movies2;
    }

    public void setMovies2(Map<Role2, Movie2> movies2) {
        this.movies2 = movies2;
    }

    public void addMovie2(Role2 role2, Movie2 movie2)
    {
        if (movies2 == null) movies2 = new HashMap<Role2, Movie2>();
        movies2.put(role2, movie2);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Map<Role1, Movie> getMovies1() {
        return movies1;
    }

    public void setMovies1(Map<Role1, Movie> movies1) {
        this.movies1 = movies1;
    }
}
```

Unit Test

```
@Before
    public void setup() throws Exception {
        Actor pa = new Actor();
        pa.setId(PID);
        pa.setName(PNAME);

        Movie pm = new Movie();
        pm.setId(OID);
        pm.setTitle(ONAME);

        Role1 pr = new Role1();
        pr.setRoleName(RID);
        pr.setRoleType("roletype");
        pr.setActor(pa);
        pr.setMovie(pm);

        pa.addMovie(pr, pm);

        ta.persist(pa);
    }

    @Test
    public void should_save_entity() throws Exception {
        Assert.assertNotNull(ta.find(Actor.class, PID));
    }
```

Exception in com.impetus.kundera.persistence.AssociationBuilder  method populateCollectionFromMap()  line 228

```
Caused by: java.lang.IllegalArgumentException: Can not set us.oculus.example.entities.Actor field us.oculus.example.entities.Role1.actor to us.oculus.example.entities.Role2
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:146)
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:150)
    at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:37)
    at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:57)
    at java.lang.reflect.Field.set(Field.java:657)
    at com.impetus.kundera.property.PropertyAccessorHelper.set(PropertyAccessorHelper.java:107)
    ... 37 more
```

**Comment by mevivs** [comment]
Sounds like an issue. Will have a look and fix this.

-Vivek

**Comment by FangmingD** [comment]
fix line 261 in com.impetus.kundera.persistence.AssociationBuilder
add

```
if(relationshipClass.getName().equalsIgnoreCase(mapKeyEntity.getClass().getName())){
```

**Comment by kkmishra** [comment]
Hi,

You have same MapKeyJoinColumn for both relation i.e. @MapKeyJoinColumn(name = "ACTS_IN") as per jpa you have to provide different-different MapKeyJoinColumn for different-different relations.

Please try by changing it. It should work for you.

-Kuldeep

**Comment by chhavigangwal** [comment]
Does the suggestion resolves the issue? Any updates ?

Chhavi
