### ISSUE TITLE
Datastax Java driver no hosts avaialble exception

### ISSUE THREAD

**Issue by ansarrafique** [Impetus/kundera#572]
Getting no host exception below with a datastax java driver. The same code works for Pelops and Thrift. I have changed kundera client lookup class and port in persistence.xml file. 

com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /192.168.100.20 (com.datastax.driver.core.TransportException: [/192.168.100.20] Unexpected exception triggered (java.lang.NoSuchMethodError: com.google.common.collect.Maps.immutableEnumMap(Ljava/util/Map;)Lcom/google/common/collect/ImmutableMap;)))
    at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:186)
    at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:81)
    at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:794)
    at com.datastax.driver.core.Cluster$Manager.access$100(Cluster.java:721)
    at com.datastax.driver.core.Cluster.<init>(Cluster.java:82)
    at com.datastax.driver.core.Cluster.<init>(Cluster.java:67)
    at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:690)
    at com.impetus.kundera.client.cassandra.dsdriver.DSClientFactory.createPoolOrConnection(DSClientFactory.java:238)
    at com.impetus.kundera.loader.GenericClientFactory.load(GenericClientFactory.java:119)
    at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:55)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:404)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configure(EntityManagerFactoryImpl.java:157)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:131)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:85)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at com.leuven.lmaas.emf.EMFactory.createEntityManager(EMFactory.java:47)
    at com.leuven.lmaas.storage.LogStorageService.prepare(LogStorageService.java:45)
    at backtype.storm.daemon.executor$eval5170$fn__5171$fn__5183.invoke(executor.clj:689)
    at backtype.storm.util$async_loop$fn__390.invoke(util.clj:431)
    at clojure.lang.AFn.run(AFn.java:24)
    at java.lang.Thread.run(Thread.java:744)

Below persistence.xml file

```
<persistence-unit name="cassandra_pu">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <properties>
        <property name="kundera.nodes" value="192.168.100.20" />
        <property name="kundera.port" value="9042" />
        <property name="kundera.keyspace" value="kundera-example" />
        <property name="kundera.dialect" value="cassandra" />
        <property name="kundera.client.lookup.class"
            value="com.impetus.kundera.client.cassandra.dsdriver.DSClientFactory" />
        <property name="kundera.ddl.auto.prepare" value="update" />
    </properties>
</persistence-unit>
```

**Comment by mevivs** [comment]
Did you enabled native_cql3_support in cassandra.yaml?

-Vivek

**Comment by ansarrafique** [comment]
I am using Cassandra 2.0.6 version, latest one and I think it is enabled by default. There is no property native_cql3_support in cassandra.yaml. However, start_native_transport is enabled.

**Comment by mevivs** [comment]
Datastax java driver 1.x is not compatible with Cassandra 2.x(As per datastax team)

Kundera currently supports Cassandra 1.2.9 and Datastax 1.x version

-Vivek

**Comment by ansarrafique** [comment]
Thanks and when a support for Cassandra 2.x is planned  ?

**Comment by ansarrafique** [comment]
I have tried again with Cassandra 1.2.9, but getting same exception. I am using Kundera 2.11 with Apache Cassandra 1.2.9, and  start_native_transport is enabled.

**Comment by ansarrafique** [comment]
Are there other properties to specify while creating entity manager factory for datastax java driver ?

EntityManagerFactory emf = Persistence.createEntityManagerFactory("cassandra_pu");
            mgr = emf.createEntityManager();

I assume it should work as it works for Thrift and Pelops.

**Comment by mevivs** [comment]
Just had a look:

```
triggered (java.lang.NoSuchMethodError: com.google.common.collect.Maps.immutableEnumMap(Ljava/util/Map;)Lcom/google/common/collect/ImmutableMap;)))
```

I suspect it is because of multiple guava jars present in classpath.

-Vivek

**Comment by ansarrafique** [comment]
Rite, that was the problem I think, but still it doesn't work properly. I have excluded other jars from classpath

```
        <exclusions>
            <exclusion>
                <groupId>org.slf4j</groupId>
                <artifactId>*</artifactId>
            </exclusion>
            <exclusion>
                <groupId>log4j</groupId>
                <artifactId>*</artifactId>
            </exclusion>
            <exclusion>
                <groupId>com.google.guava</groupId>
                <artifactId>*</artifactId>
            </exclusion>
        </exclusions>
```

Actually, I am  not getting any exception neither on the server side nor on the client side, but it doesn't seems to persist data. The same code works fine for Thrift and Pelops using Kundera.

**Comment by kkmishra** [comment]
Hi Ansar,

Is it possible for you to share some sample code, to reproduce the error which you are facing?

There are some junits which are working with same persistence.xml properties which you have provided in your persistence.xml

Here are some link :
Test :
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-cassandra/cassandra-ds-driver/src/test/java/com/impetus/kundera/client/cassandra/crud/PersonEntityTest.java

Persistence.xml :
https://github.com/impetus-opensource/Kundera/tree/trunk/src/kundera-cassandra/cassandra-ds-driver/src/test/resources/META-INF

-Kuldeep

**Comment by ansarrafique** [comment]
The same code has already been shared.

**Comment by kkmishra** [comment]
yes, looking into it. Will update you soon.

**Comment by ansarrafique** [comment]
Thank you.

**Comment by ansarrafique** [comment]
Solved.

**Comment by nixoldb** [comment]
How do you solved it?

**Comment by ansarrafique** [comment]
I was constantly getting this exception so I decided to stick with Thrift
and Pelops.

Ansar
