### ISSUE TITLE
Entities that extend a MappedSuperclass do not validate Ids properly

### ISSUE THREAD

**Issue by makearl** [Impetus/kundera#577]
Hi,

If an Entity containing an @Id annotation extends a MappedSuperclass without an @Id annotation, a RuleValidationException is thrown. This happens because the list of keys found when iterating through the Entity's annotations gets erased when each super class is evaluated.

I think the fix to this problem would just be removing the line that clears the list of keys at line 99 of EntityFieldAnnotationRule.java.

Here's the exception that occurs when you hit this issue:
Exception in thread "main" com.impetus.kundera.validation.rules.RuleValidationException: dev.model.DeviceType must have an @Id field.
    at com.impetus.kundera.validation.rules.EntityFieldAnnotationRule.onEntityKey(EntityFieldAnnotationRule.java:167)
    at com.impetus.kundera.validation.rules.EntityFieldAnnotationRule.onSuperClass(EntityFieldAnnotationRule.java:137)
    at com.impetus.kundera.validation.rules.EntityFieldAnnotationRule.validate(EntityFieldAnnotationRule.java:75)
    at com.impetus.kundera.validation.AbstractValidationFactory.validate(AbstractValidationFactory.java:49)
    at com.impetus.kundera.validation.BootstrapValidationFactory.validate(BootstrapValidationFactory.java:61)
    at com.impetus.kundera.configure.MetamodelConfiguration.scanClassAndPutMetadata(MetamodelConfiguration.java:337)
    at com.impetus.kundera.configure.MetamodelConfiguration.loadEntityMetadata(MetamodelConfiguration.java:231)
    at com.impetus.kundera.configure.MetamodelConfiguration.configure(MetamodelConfiguration.java:112)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configure(EntityManagerFactoryImpl.java:154)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:131)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:85)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at dev.TestTables.main(TestTables.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)

**Comment by chhavigangwal** [comment]
Is DeviceType an entity or mappedSuperClass? Can you please share entity hierarchy structure ?

**Comment by makearl** [comment]
DeviceType is an Entity. Here's the mapped super class and the entity that inherits from it:

```
@MappedSuperclass
@EntityListeners(value = { AuditableEntityListener.class})
public class AuditableEntity implements Serializable {
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at")
    private Date createdDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at")
    private Date updatedDate;

    protected void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    protected void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}
```

Here's the DeviceType Entity:

```
@Entity
@Table(name = "device_type", schema = "mydb")
public class DeviceType extends AuditableEntity {
    @Id
    @Column(name = "device_type_id")
    private int id;

    @Column(name = "type")
    private String type;

    // Other columns and getters/setters
}
```

When I remove line 99 from EntityFieldAnnotationRule.java, I can successfully persist this Entity.

**Comment by chhavigangwal** [comment]
Sounds like an issue! Would you like to submit a pull request for same?

**Comment by makearl** [comment]
Sure, I added pull request #578 for this issue. Thanks!
