### ISSUE TITLE
Can't get RDBMS Entities with relationships

### ISSUE THREAD

**Issue by kkmishra** [Impetus/kundera#579]
Hi,

I'm having a problem retrieving RDBMS Entities that have relationships (I've tried OneToOne and ManyToOne). When I try to retrieve them, I get a Null Pointer Exception:
java.lang.NullPointerException
at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988)
at com.impetus.kundera.metadata.model.ApplicationMetadata.getQuery(ApplicationMetadata.java:272)
at com.impetus.client.rdbms.query.RDBMSEntityReader.getSqlQueryFromJPA(RDBMSEntityReader.java:226)
at com.impetus.client.rdbms.query.RDBMSEntityReader.findById(RDBMSEntityReader.java:576)
at com.impetus.kundera.lifecycle.states.ManagedState.handleFind(ManagedState.java:135)
at com.impetus.kundera.graph.Node.find(Node.java:500)
at com.impetus.kundera.persistence.PersistenceDelegator.find(PersistenceDelegator.java:231)
at com.impetus.kundera.persistence.PersistenceDelegator.findById(PersistenceDelegator.java:182)
at com.impetus.kundera.persistence.EntityManagerImpl.find(EntityManagerImpl.java:258)
at dev.TestTables.main(TestTables.java:102)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)

I've narrowed down where the issue is happening but not why. If an Entity has relationships, then findById in RDBMSEntityReader tries to execute a special case that calls getSqlQueryFromJPA. getSqlQueryFromJPA expects the jpaQuery member variable to be initialized but it's not. What's supposed to initialize this query variable? From what I can tell, it would only get initialized if it hit the first constructor that passes 'query' in. Currently, it hits the second constructor.

When I try passing straight through to Hibernate in findById, I can successfully retrieve the object when using Eager fetching. When I use Lazy fetching, I get the following error when trying to use the result:
org.hibernate.SessionException: proxies cannot be fetched by a stateless session

Why is there a special case used when an entity has relationships instead of passing it straight down to Hibernate? 

Any thoughts or suggestions would be appreciated.

**Comment by kkmishra** [comment]
Hi,

1) NullPointerException has been fixed in current trunk.
2) I am working on lazy loading problem, will update soon.

Thanks
Kuldeep

**Comment by kkmishra** [comment]
Hi,

Please share your sample code, that would be good for me to replicate  org.hibernate.SessionException problem.

Thanks
Kuldeep

**Comment by chhavigangwal** [comment]
Fixed. Released with Kundera-2.12.
