### ISSUE TITLE
Cannot persist a map in Cassandra

### ISSUE THREAD

**Issue by sltang** [Impetus/kundera#592]
Hi,

I am using Cassandra 2.0.5 and Kundera 2.12-SNAPSHOT. I have a domain class with a Map field called properties defined as:

```
@ElementCollection(fetch=FetchType.EAGER)
    @Column(name="properties") 
    private Map<String, String> properties;
```

and a method for adding properties to the map:

```
public void addProperty(String name, String value)
    {
        if(properties == null)
        {
            properties = new HashMap<String, String>();
        }
        properties.put(name, value);
    } 
```

I add properties to the field and persist:

```
user.addProperty("prop1", "value1");
    user.addProperty("prop2", "value2");
```

I do see the column being created in Cassandra:

```
  properties map<text, text>,
```

But it throws an exception:

```
Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to java.lang.String
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator$StringTypeBuilder.compose(CassandraDataTranslator.java:626)
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator$StringTypeBuilder.access$500(CassandraDataTranslator.java:616)
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator.compose(CassandraDataTranslator.java:243)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.getThriftColumnValue(CassandraDataHandlerBase.java:1395)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.getColumnValue(CassandraDataHandlerBase.java:1372)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.onColumnOrSuperColumnThriftRow(CassandraDataHandlerBase.java:1308)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.toThriftRow(CassandraDataHandlerBase.java:372)
    at com.impetus.client.cassandra.pelops.PelopsClient.onPersist(PelopsClient.java:524)
```

Once the above is removed, it works without a problem. Do you know what is wrong here?

Thanks,
SL

**Comment by sltang** [comment]
I found the cause. I have to switch from Thrift to CQL as documented in https://github.com/impetus-opensource/Kundera/wiki/Cassandra-Specific-Features.
