### ISSUE TITLE
InvalidRequestException while primary key auto generation and CQL 3 is used

### ISSUE THREAD

**Issue by moldziej** [Impetus/kundera#607]
There is an InvalidRequestException when:
- @GeneratedValue is used
- CQL 3.0.0 is set up on entity factory
- schema auto generation is used

On Kundera 2.12, I've modified CassandraGeneratedIdTest:

``` diff
diff -ru cassandra-core.orig/src/test/java/com/impetus/client/generatedId/CassandraGeneratedIdTest.java cassandra-core/src/test/java/com/impetus/client/generatedId/CassandraGeneratedIdTest.java
--- cassandra-core.orig/src/test/java/com/impetus/client/generatedId/CassandraGeneratedIdTest.java  2014-05-20 19:33:52.000000000 +0200
+++ cassandra-core/src/test/java/com/impetus/client/generatedId/CassandraGeneratedIdTest.java   2014-06-05 16:06:04.778249700 +0200
@@ -15,7 +15,9 @@
  */
 package com.impetus.client.generatedId;

+import java.util.HashMap;
 import java.util.List;
+import java.util.Map;

 import javax.persistence.EntityManager;
 import javax.persistence.EntityManagerFactory;
@@ -49,7 +51,10 @@
     public void setUp() throws Exception
     {
         CassandraCli.cassandraSetUp();
-        emf = Persistence.createEntityManagerFactory("cassandra_generated_id");
+        Map<String, String> propertyMap = new HashMap<String, String>();
+        propertyMap.put("cql.version", "3.0.0");
+        
+        emf = Persistence.createEntityManagerFactory("cassandra_generated_id", propertyMap);
     }

     @After
@@ -154,6 +159,7 @@
         }
         catch (KunderaException e)
         {
+            e.printStackTrace();
             Assert.fail();
         }
```

Running the test:

``` bash
cassandra-core>mvn -Dtest=CassandraGeneratedIdTest test
```

causes InvalidRequestException(why:Not enough bytes to read value of component 0):

```
Running com.impetus.client.generatedId.CassandraGeneratedIdTest
log4j:WARN No appenders could be found for logger (org.apache.cassandra.service.CassandraDaemon).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
com.impetus.kundera.KunderaException: com.impetus.kundera.KunderaException: InvalidRequestException(why:Not enough bytes to read value of component 0)
        at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)
        at com.impetus.client.generatedId.CassandraGeneratedIdTest.testPersist(CassandraGeneratedIdTest.java:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: com.impetus.kundera.KunderaException: InvalidRequestException(why:Not enough bytes to read value of component 0)
        at com.impetus.client.cassandra.CassandraClientBase.getGeneratedValue(CassandraClientBase.java:1837)
        at com.impetus.client.cassandra.thrift.ThriftClient.generate(ThriftClient.java:1111)
        at com.impetus.client.cassandra.thrift.ThriftClient.generate(ThriftClient.java:97)
        at com.impetus.kundera.persistence.IdGenerator.onTableGenerator(IdGenerator.java:168)
        at com.impetus.kundera.persistence.IdGenerator.generateId(IdGenerator.java:72)
        at com.impetus.kundera.persistence.IdGenerator.generateAndSetId(IdGenerator.java:53)
        at com.impetus.kundera.graph.GraphGenerator.onPreChecks(GraphGenerator.java:225)
        at com.impetus.kundera.graph.GraphGenerator.generate(GraphGenerator.java:126)
        at com.impetus.kundera.graph.GraphGenerator.generateGraph(GraphGenerator.java:78)
        at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:134)
        at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)
        ... 32 more
Caused by: InvalidRequestException(why:Not enough bytes to read value of component 0)
        at org.apache.cassandra.thrift.Cassandra$get_result$get_resultStandardScheme.read(Cassandra.java:10200)
        at org.apache.cassandra.thrift.Cassandra$get_result$get_resultStandardScheme.read(Cassandra.java:10177)
        at org.apache.cassandra.thrift.Cassandra$get_result.read(Cassandra.java:10092)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
        at org.apache.cassandra.thrift.Cassandra$Client.recv_get(Cassandra.java:624)
        at org.apache.cassandra.thrift.Cassandra$Client.get(Cassandra.java:609)
        at com.impetus.client.cassandra.CassandraClientBase.getGeneratedValue(CassandraClientBase.java:1799)
        ... 42 more
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 29.377 sec <<< FAILURE!
testPersist(com.impetus.client.generatedId.CassandraGeneratedIdTest)  Time elapsed: 29.322 sec  <<< FAILURE!
```

It seems that there is a problem with schema auto generation when CQL 3.0.0 is used. In particular with "kundera_sequences" table.
Without CQL 3.0.0 kundera_sequences is generated as:

```
CREATE TABLE kundera_sequences (
  key text,
  sequence_value counter,
  PRIMARY KEY (key)
) WITH COMPACT STORAGE AND
...
```

With CQL 3.0.0 set it is:

```
CREATE TABLE kundera_sequences (
  id text,
  sequence_value counter,
  PRIMARY KEY (id)
) WITH
..
```

Note, that with CQL 3.0.0 set, primary key name is **id** instead of **key**. It seems that id name is taken from the id property of one of entities.

``` java
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private int id;
```

Regards,
Marcin

**Comment by kkmishra** [comment]
Hi 
Change the given code

```
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private int id;
```

by this one

```
@Id
@GeneratedValue(strategy = GenerationType.TABLE)
private int id;
```

It should work.

Thanks
Kuldeep

**Comment by moldziej** [comment]
I guess that id column name in kundera_sequences table is taken from _one of entities_ from the test. I provided the one with GenerationType.IDENTITY as an example.

In my code I only use GenerationType.TABLE. I provided the patch to the unit test for your convinience.

The test actually fails for the CassandraGeneratedIdStrategyTable when em.persist() is invoked:

``` java
CassandraGeneratedIdStrategyTable strategyTable = new CassandraGeneratedIdStrategyTable();
strategyTable.setName("KK");
em.persist(strategyTable);
```

CassandraGeneratedIdStrategyTable entity has GenerationType.TABLE strategy:

``` java
@Id
@TableGenerator(name = "table_gen_1")
@GeneratedValue(generator = "table_gen", strategy = GenerationType.TABLE)
private int id;
```

Regards,
Marcin.

**Comment by kkmishra** [comment]
Hi @moldziej 

It is working with thrift. As a work around you can create entity manager factory without property map.

```
emf = Persistence.createEntityManagerFactory("cassandra_generated_id");
```

I confirm its an issue with cql-3.0.0 version. Will get fixed and released with 2.13 version.

Thanks

**Comment by moldziej** [comment]
Thank you for fast response.

I actually need CQL-3.0.0 because I use HashSet in entities (with thrift there is  com.impetus.kundera.KunderaException: java.lang.ClassCastException: java.util.HashSet cannot be cast to java.lang.String exception)

I am looking forward to Kundera 2.13 being released.
Thank you,
Marcin.

**Comment by kkmishra** [comment]
A fix has been added in the current trunk branch.
Please verify.

Thanks
Kuldeep

**Comment by moldziej** [comment]
The fix solves the issue.

I wonder however, what is the difference between setting CQL3 on entity manager factory:

``` java
Map<String, String> propertyMap = new HashMap<String, String>();
propertyMap.put("cql.version", "3.0.0");
emf = Persistence.createEntityManagerFactory("cassandra_generated_id", propertyMap);
```

and on client only:

``` java
Map<String, Client> clientMap = (Map<String, Client>) em.getDelegate();
PelopsClient pc = (PelopsClient)clientMap.get("cassandra_pu");
pc.setCqlVersion("3.0.0");
```

Why if I set CQL3.0 directly on PelopsClient, InvalidRequestException described above doesn't occur?

Regards,
Marcin.

**Comment by mevivs** [comment]
@moldziej 
I prefer to use ThriftClient, as with PelopsClient underlying Pelops API is not maintained by pelops developers anymore! 

AFAIK, setting it with EMF would set it for multiple sessions, where as at client level it would be specific to client only.

HTH,
-Vivek
