### ISSUE TITLE
Kundera allows mapping-file tag in persistence.xml?

### ISSUE THREAD

**Issue by vanessaschissato** [Impetus/kundera#618]
I want to define a default listener to my entities in a external file (orm.xml).
For that, i need to define this mapping file in the persistence.xml, according to the specification JPA:

``` xml
<persistence xmlns="http://java.sun.com/xml/ns/persistence"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0">
    <persistence-unit name="test" transaction-type="RESOURCE_LOCAL">

        <provider>com.impetus.kundera.KunderaPersistence</provider>

        <mapping-file>META-INF/orm.xml</mapping-file>

    </persistence-unit>
</persistence>

```

But, this exception is throwed by Kundera:

``` java
Caused by: com.impetus.kundera.loader.PersistenceLoaderException: com.impetus.kundera.utils.InvalidConfigurationException: persistence.xml is not conform against the supported schema definitions.
    at com.impetus.kundera.configure.PersistenceUnitConfiguration.configure(PersistenceUnitConfiguration.java:100)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configurePersistenceUnit(EntityManagerFactoryImpl.java:663)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:137)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:85)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:78)
```

**Comment by chhavigangwal** [comment]
Kundera currently does not support reading

```
<mapping-file>META-INF/orm.xml</mapping-file>
```

You need to define these listeners as class files only. An example for same :+1: 
https://github.com/impetus-opensource/Kundera/blob/ad6998066adc0d9157f3f706dbdd7f87c2bb0576/src/kundera-mongo/src/test/java/com/impetus/client/crud/event/PersonHandler.java

Hope this Helps !
Chhavi
