### ISSUE TITLE
Type cast error in CassandraDataTranslator class

### ISSUE THREAD

**Issue by hanishbansal** [Impetus/kundera#623]
When we use compose api of  CassandraDataTranslator class to convert data type of particular object, it is giving java.lang.ClassCastException.

For example:

```
    public static void main(String[] args) {
           byte[] value = CassandraDataTranslator.compose(Double.class, "45.12", true);
    }
```

Above piece of code is giving below exception:

```
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator$DoubleTypeBuilder.compose(CassandraDataTranslator.java:554)
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator$DoubleTypeBuilder.access$400(CassandraDataTranslator.java:545)
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator.compose(CassandraDataTranslator.java:241)
```

Expected Behaviour:

It should cast the value properly using `double d = Double.valueOf(obj)` api or `double d = new Double(obj.toString())`.

Actual Behaviour:
It is casting the value by `double d = (Double)obj`. That is giving ClassCastException.

**Comment by mevivs** [comment]
i wonder why don't you try with

```
    byte[] value = CassandraDataTranslator.compose(Double.class, Double.parseDouble("45.12"), true);

```

AFAIK, CassandraDataTranslator is meant to compose/decompose bytes in Cassandra format. May be you should try  Kundera's accessor api.

HTH,
-Vivek

**Comment by mevivs** [comment]
=>
https://github.com/impetus-opensource/Kundera/blob/7b58ecab2f65c04b7a1e396de71bda308b58b762/src/jpa-engine/core/src/main/java/com/impetus/kundera/property/accessor/DoubleAccessor.java

**Comment by hanishbansal** [comment]
We are also using CassandraDataTranslator to compose/decompose bytes in Cassandra format.

Object's values are coming at run time so their data types may be different for different objects.

**Comment by mevivs** [comment]
@hanishbansal 
Point which i am trying to discuss here is, Either compose/decompose using CassandraDataTranslator or if it is about double to byte[] conversion then DoubleAccessor would be best place to look into.

Rest, Kundera core team people can be best to comment on it.

-Vivek
