### ISSUE TITLE
ALLOW FILTERING when refer to collection

### ISSUE THREAD

**Issue by AleksanderMielczarek** [Impetus/kundera#631]
Hi,
I'm using Cassandra 2.10rc5 and Kundera 2.13
I have two entities: User and Group:

User.java

```
package com.entities;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "users")
public class User extends Audit {

    @Id
    @Column(name = "userId")
    private String userId = null;

    @Column(name = "firstName")
    private String firstName;

    @Column(name = "lastName")
    private String lastName;

    @Column(name = "password")
    private String password;

    @Column(name = "sex")
    @Enumerated(EnumType.STRING)
    private Sex sex;

    @Column(name = "country")
    private String country;

    @Column(name = "company")
    private String company;

    @Column(name = "email")
    private String email;

    @Column(name = "tel")
    private String tel;

    @OneToMany(mappedBy = "owner", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "ownerId")
    private List<Group> groups = new ArrayList<>();

    @OneToMany(mappedBy = "owner", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "ownerId")
    private List<Mail> mails = new ArrayList<>();

    @OneToMany(mappedBy = "owner", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "ownerId")
    private List<Task> tasks = new ArrayList<>();

    @OneToMany(mappedBy = "owner", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "ownerId")
    private List<Template> templates = new ArrayList<>();

    public User() {

    }

    public User(String userId, String firstName, String lastName, String password, Sex sex, String country, String company, String email, String tel,
            List<Group> groups, List<Mail> mails, List<Task> tasks, List<Template> templates) {
        super();
        this.userId = userId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.password = password;
        this.sex = sex;
        this.country = country;
        this.company = company;
        this.email = email;
        this.tel = tel;
        this.groups = groups;
        this.mails = mails;
        this.tasks = tasks;
        this.templates = templates;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Sex getSex() {
        return sex;
    }

    public void setSex(Sex sex) {
        this.sex = sex;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public List<Group> getGroups() {
        return groups;
    }

    public void setGroups(List<Group> groups) {
        this.groups = groups;
    }

    public List<Mail> getMails() {
        return mails;
    }

    public void setMails(List<Mail> mails) {
        this.mails = mails;
    }

    public List<Task> getTasks() {
        return tasks;
    }

    public void setTasks(List<Task> tasks) {
        this.tasks = tasks;
    }

    public List<Template> getTemplates() {
        return templates;
    }

    public void setTemplates(List<Template> templates) {
        this.templates = templates;
    }
}
```

Group.java

```
package com.entities;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "groups")
public class Group extends Audit {

    @Id
    @Column(name = "groupId")
    private UUID groupId = null;

    // @Column(name="ownerId")
    // private UUID ownerId;

    @Column(name = "name")
    private String name;

    @Column(name = "description")
    private String description;

    @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    private User owner;

    @OneToMany(mappedBy = "group", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "groupId")
    private List<Task> tasks = new ArrayList<>();

    // @OneToMany(mappedBy="group")
    // @JoinColumn(name="groupId")
    // Collection<MailByGroup> mailsByGroups;

    @ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinTable(name = "mails_groups", joinColumns = { @JoinColumn(name = "groupId") }, inverseJoinColumns = { @JoinColumn(name = "mailId") })
    private List<Mail> mails = new ArrayList<>();

    public Group() {

    }

    public Group(UUID groupId, String name, String description, User owner, List<Task> tasks, List<Mail> mails) {
        super();
        this.groupId = groupId;
        this.name = name;
        this.description = description;
        this.owner = owner;
        this.tasks = tasks;
        this.mails = mails;
    }

    public UUID getGroupId() {
        return groupId;
    }

    public void setGroupId(UUID groupId) {
        this.groupId = groupId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public User getOwner() {
        return owner;
    }

    public void setOwner(User owner) {
        this.owner = owner;
    }

    public List<Task> getTasks() {
        return tasks;
    }

    public void setTasks(List<Task> tasks) {
        this.tasks = tasks;
    }

    public List<Mail> getMails() {
        return mails;
    }

    public void setMails(List<Mail> mails) {
        this.mails = mails;
    }
}
```

When I want to get all users and refer to user's group:

```
List<Group> groups = em.createNamedQuery("select user from User user", User.class).getResultList().get(0).getGroups();
for (Group item : groups) {
    System.out.println(item.getGroupId());
}
```

I get following exception

```
log4j:WARN No appenders could be found for logger (com.impetus.kundera.persistence.EntityManagerFactoryImpl).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" javax.persistence.PersistenceException: javax.persistence.PersistenceException: com.impetus.kundera.KunderaException: InvalidRequestException(why:Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING)
 at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2090)
 at com.impetus.client.cassandra.CassandraClientBase$CQLClient.findByRelationQuery(CassandraClientBase.java:2213)
 at com.impetus.client.cassandra.CassandraClientBase.findByRelationQuery(CassandraClientBase.java:1922)
 at com.impetus.client.cassandra.pelops.PelopsClient.findByRelation(PelopsClient.java:412)
 at com.impetus.kundera.persistence.AbstractEntityReader.fetchRelations(AbstractEntityReader.java:410)
 at com.impetus.kundera.persistence.AbstractEntityReader.onRelation(AbstractEntityReader.java:206)
 at com.impetus.kundera.persistence.AbstractEntityReader.onRelation(AbstractEntityReader.java:176)
 at com.impetus.kundera.persistence.AbstractEntityReader.handleAssociation(AbstractEntityReader.java:120)
 at com.impetus.kundera.persistence.AbstractEntityReader.recursivelyFindEntities(AbstractEntityReader.java:430)
 at com.impetus.kundera.proxy.collection.AbstractProxyBase.eagerlyLoadDataCollection(AbstractProxyBase.java:113)
 at com.impetus.kundera.proxy.collection.AbstractProxyCollection.iterator(AbstractProxyCollection.java:221)
 at com.impetus.kundera.proxy.collection.ProxyList.iterator(ProxyList.java:115)
 at com.entities.test.Test.main(Test.java:32)
Caused by: javax.persistence.PersistenceException: com.impetus.kundera.KunderaException: InvalidRequestException(why:Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING)
 at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:1900)
 at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2054)
 ... 12 more
Caused by: com.impetus.kundera.KunderaException: InvalidRequestException(why:Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING)
 at com.impetus.client.cassandra.CassandraClientBase.execute(CassandraClientBase.java:2328)
 at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:1885)
 ... 13 more
Caused by: InvalidRequestException(why:Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING)
 at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result$execute_cql3_query_resultStandardScheme.read(Cassandra.java:49032)
 at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result$execute_cql3_query_resultStandardScheme.read(Cassandra.java:49009)
 at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result.read(Cassandra.java:48924)
 at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
 at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql3_query(Cassandra.java:1693)
 at org.apache.cassandra.thrift.Cassandra$Client.execute_cql3_query(Cassandra.java:1678)
 at com.impetus.client.cassandra.CassandraClientBase.execute(CassandraClientBase.java:2322)
 ... 14 more
```

But when I use EAGER fetching everything is OK. Could you investigate this problem?
Thanks

**Comment by chhavigangwal** [comment]
You need to call : 

```
em.createQuery("select user from User user", User.class).getResultList().get(0).getGroups();
```

instead of 

```
em.createNamedQuery("select user from User user", User.class).getResultList().get(0).getGroups();
```

Chhavi

**Comment by mevivs** [comment]
In addition, it looks to me because of not applying limit while fetching relation by query. Ideally it should 100 as default. Sounds like a bug while lazily fetching relation values(eg groups)

-Vivek

**Comment by mevivs** [comment]
Also its better to use thrift client factory in place of pelops

**Comment by AleksanderMielczarek** [comment]
HI,

Thanks for replay but none of those answers worked. I'm still getting exception with allow filtering. I tried to use getMaxResult() but it failed.

**Comment by mevivs** [comment]
@lusiak 
Looks like i am not able to convey  my thoughts. setMaxResults() would not be any help. This is an issue with Kundera while implicitly fetching relational entities. Code should set limit(default 100) or set to MaxResults() provided by parent query. That should solve the issue. 

Kundera team should be able to better judge on this.

-Vivek

**Comment by AleksanderMielczarek** [comment]
As I understood, actually the only solution is to use eager fetching. Also  function find behaves weirdly for me. When I try to get user:

```
User user = em.find(User.class, "mateo081");
```

and refer to its list of groups, i get empty list. Is it normal behaviour?

**Comment by AleksanderMielczarek** [comment]
However, when all fetching type I've changed to eager, something very terrible has occurred. I cannot get from database even one object. For example this code:

```
User u = em.createQuery("select user from User user", User.class).getResultList().get(o);
System.out.println(u.getUserId());
```

produces:

```
log4j:WARN No appenders could be found for logger (com.impetus.kundera.persistence.EntityManagerFactoryImpl).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" javax.persistence.PersistenceException: javax.persistence.PersistenceException: com.impetus.kundera.KunderaException: InvalidRequestException(why:Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING)
 at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2090)
 at com.impetus.client.cassandra.CassandraClientBase$CQLClient.findByRelationQuery(CassandraClientBase.java:2213)
 at com.impetus.client.cassandra.CassandraClientBase.findByRelationQuery(CassandraClientBase.java:1922)
 at com.impetus.client.cassandra.thrift.ThriftClient.findByRelation(ThriftClient.java:571)
 at com.impetus.kundera.persistence.AbstractEntityReader.fetchRelations(AbstractEntityReader.java:410)
 at com.impetus.kundera.persistence.AbstractEntityReader.onRelation(AbstractEntityReader.java:206)
 at com.impetus.kundera.persistence.AbstractEntityReader.onRelation(AbstractEntityReader.java:176)
 at com.impetus.kundera.persistence.AbstractEntityReader.handleAssociation(AbstractEntityReader.java:120)
 at com.impetus.kundera.persistence.AbstractEntityReader.recursivelyFindEntities(AbstractEntityReader.java:430)
 at com.impetus.kundera.query.QueryImpl.setRelationEntities(QueryImpl.java:185)
 at com.impetus.client.cassandra.query.CassQuery.recursivelyPopulateEntities(CassQuery.java:233)
 at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:986)
 at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:163)
 at com.impetus.kundera.query.KunderaTypedQuery.getResultList(KunderaTypedQuery.java:250)
 at com.entities.test.Test.main(Test.java:23)
Caused by: javax.persistence.PersistenceException: com.impetus.kundera.KunderaException: InvalidRequestException(why:Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING)
 at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:1900)
 at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2054)
 ... 14 more
Caused by: com.impetus.kundera.KunderaException: InvalidRequestException(why:Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING)
 at com.impetus.client.cassandra.CassandraClientBase.execute(CassandraClientBase.java:2328)
 at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:1885)
 ... 15 more
Caused by: InvalidRequestException(why:Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING)
 at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result$execute_cql3_query_resultStandardScheme.read(Cassandra.java:49032)
 at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result$execute_cql3_query_resultStandardScheme.read(Cassandra.java:49009)
 at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result.read(Cassandra.java:48924)
 at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
 at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql3_query(Cassandra.java:1693)
 at org.apache.cassandra.thrift.Cassandra$Client.execute_cql3_query(Cassandra.java:1678)
 at com.impetus.client.cassandra.CassandraClientBase.execute(CassandraClientBase.java:2322)
 ... 16 more
```

**Comment by chhavigangwal** [comment]
@lusiak 

I tried the same with around 1000 records in users table and could not reproduce the issue at my end. Can you share a sample app to further debug the issue ?

Chhavi

**Comment by chhavigangwal** [comment]
@lusiak 

Was the issue resolved at your end ?

Chhavi

**Comment by AleksanderMielczarek** [comment]
This can be closed.
