### ISSUE TITLE
Entity object is invalid, operation failed

### ISSUE THREAD

**Issue by gorishagh** [Impetus/kundera#634]
Hi, I have a simple Entity which I want to persist to Cassandra database. But I keep getting the following exception. Also, the schema doesn't get created at all. I include my entity class and persistence.xml. I dont know what I am doing wrong. Please help.

///////////////////////////////////////// persistence.xml ///////////////////////////////
<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0">

```
<persistence-unit name="cassandra_pu">
    <provider>com.impetus.kundera.KunderaPersistence</provider>     
    <class>com.sra.EPiCSCloudAnalytics.Model.RiakFileInfo</class>
    <class>com.sra.EPiCSCloudAnalytics.Model.UsageInfo</class>
    <class>com.sra.EPiCSCloudAnalytics.Model.FileCount</class>

    <properties>         
        <property name="kundera.nodes" value="localhost"/>
        <property name="kundera.port" value="9160"/>
        <property name="kundera.keyspace" value="riakfileinfo"/>
        <property name="kundera.dialect" value="cassandra"/>
        <property name="kundera.ddl.auto.prepare" value="create" />
        <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
      <!--  <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider" />
        <property name="kundera.cache.config.resource" value="/ehcache.xml" />   -->
    </properties>       
</persistence-unit>
```

</persistence>

//////////////////////////////////////////////// Entity ///////////////////////////////////////////////////////////////////

package com.sra.EPiCSCloudAnalytics.Model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;
@Entity
//@Table(name = "riakfileinfo")
@XmlRootElement
public class RiakFileInfo implements Serializable{
    @Id @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="ID")
    private long id;
    @Column(name="FILEOWNER")
    private String fileOwner;
    @Column(name="FILECATEGORY")
    private String fileCategory;
    @Column(name="FILENAME")
    private String fileName;
    @Column(name="FILETYPE")
    private String fileType;
    @Column(name="FILESIZE")
    private long fileSize;
    @Column(name="DATE")
    @Temporal(TemporalType.TIMESTAMP)
    private Date date;
    public RiakFileInfo()
    {}
    public void setId(long id)
    {
        this.id = id;
    }
    public long getId()
    {
        return this.id;
    }
    public void setFileOwner(String owner)
    {
        this.fileOwner = owner;
    }
    public String getFileOwner()
    {
        return this.fileOwner;
    }
    public void setFileCategory(String category)
    {
        this.fileCategory = category;
    }
    public String getFileCategory()
    {
        return this.fileCategory;
    }
    public void setFileName(String name)
    {
        this.fileName = name;
    }
    public String getFileName()
    {
        return this.fileName;
    }
    public void setFileType(String type)
    {
        this.fileType = type;
    }
    public String getFileType()
    {
        return this.fileType;
    }
    public void setFileSize(long size)
    {
        this.fileSize = size;
    }
    public long getFileSize()
    {
        return this.fileSize;
    }
    public void setDate(Date date)
    {
        this.date = date;
    }
    public Date getDate()
    {
        return this.date;
    }
    /\* (non-Javadoc)
     \* @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "RiakFileInfo [id=" + id + ", fileOwner=" + fileOwner
                + ", fileCategory=" + fileCategory + ", fileName=" + fileName
                + ", fileType=" + fileType + ", fileSize=" + fileSize
                + ", date=" + date + "]";
    }
}

I would appreciate any help. Thanks..

**Comment by gorishagh** [comment]
The Exception is:

Aug 27, 2014 5:49:53 PM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
com.impetus.kundera.KunderaException: java.lang.IllegalArgumentException: Entity object is invalid, operation failed. Please check previous log message for details
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)
    at com.sra.EPiCSCloudAnalytics.Engine.Core.getNewInfo(Core.java:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Entity object is invalid, operation failed. Please check previous log message for details
    at com.impetus.kundera.validation.rules.NullOrInvalidEntityRule.validate(NullOrInvalidEntityRule.java:52)
    at com.impetus.kundera.graph.GraphGenerator.generate(GraphGenerator.java:124)
    at com.impetus.kundera.graph.GraphGenerator.generateGraph(GraphGenerator.java:78)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:130)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)
    ... 41 more

**Comment by chhavigangwal** [comment]
@gorishagh 

Can you try changing

```
private long id;
```

to

```
@Column(name="ID")
private String id;

or 

@Column(name="ID")
private UUID id;
```

And check if the  problem still persists ?

Auto id generation using AUTO strategy  in Kundera-cassandra is supported over non number data types.

Hope that Helps!
Chhavi

**Comment by gorishagh** [comment]
Hi Chhavi,
thanks for your answer, but I still have the same problem.

**Comment by gorishagh** [comment]
OK

**Comment by gorishagh** [comment]
I think I've narrowed down the problem down to persistence.xml. I do get the same exception when I delete <class>com.sra.EPiCSCloudAnalytics.Model.RiakFileInfo</class>. So basically I think Kundera doesnt see that there exists such class. Is it possible that this is the problem? And any Idea how to fix it? Thanks.

**Comment by gorishagh** [comment]
< class >com.sra.EPiCSCloudAnalytics.Model.RiakFileInfo< /class >

This is what I delete from persistence.xml. the <class> tag was deleted mistakenly in the previous comment.

**Comment by chhavigangwal** [comment]
@gorishagh 

Please make sure each of the entity class included have an id attribute annotated with @Id. Also, Please add the following in persistence.xml :

```
<exclude-unlisted-classes>true</exclude-unlisted-classes>
```

below classes tag like :

```
   <class>com.sra.EPiCSCloudAnalytics.Model.RiakFileInfo</class>
    <class>com.sra.EPiCSCloudAnalytics.Model.UsageInfo</class>
    <class>com.sra.EPiCSCloudAnalytics.Model.FileCount</class>
   <exclude-unlisted-classes>true</exclude-unlisted-classes>
```

This tells Kundera to not include any other class except for the ones mentioned.
Also, please change the auto generated field type from Long.

Chhavi

**Comment by chhavigangwal** [comment]
@gorishagh 

If possible, Can you please share a sample project which can help us debug the issue further?

Chhavi

**Comment by gorishagh** [comment]
Thanks allot Chhavi. the < exclude-unlisted-classes>true< /exclude-unlisted-classes> solved the problem. But it doesn't kind of make sense to me. Why should we list our entity classes if at the end we have to exclude the unlisted classes? It seems Kundera includes everything by default? or ...? I don't understand.
So the changes that I did are the followings:
add < exclude-unlisted-classes> to persistence.xml
change @GeneratedValue(strategy = GenerationType.Auto)
to
@Id @GeneratedValue(strategy = GenerationType.TABLE)
    @Column(name="ID")
    private Long id;

and keep the id field as Long.

For the sample project, I will try to create a sample project and regenerate similar error if still needed.

**Comment by chhavigangwal** [comment]
@gorishagh 

It is a mechanism which tells Kundera not to include anything else apart from the classes specified, for a given persistence unit, even if some other classes are present in the classpath.

Chhavi

**Comment by vinitsharma87** [comment]
@chhavigangwal I am experiencing this same kind of issue. My exception is as follows:

```
[error] c.i.k.q.KunderaQuery - No entity Employee found, please verify it is properly annotated with @Entity and not a mapped Super class
[error] m.p.EmployeeDAOImpl$ - Error : 
com.impetus.kundera.query.QueryHandlerException: No entity found by the name: Employee
    at com.impetus.kundera.query.KunderaQuery.initEntityClass(KunderaQuery.java:608) ~[kundera-core-3.2.jar:na]
    at com.impetus.kundera.query.KunderaQuery.postParsingInit(KunderaQuery.java:540) ~[kundera-core-3.2.jar:na]
    at com.impetus.kundera.query.QueryResolver.getQueryImplementation(QueryResolver.java:86) ~[kundera-core-3.2.jar:na]
    at com.impetus.kundera.persistence.PersistenceDelegator.getQueryInstance(PersistenceDelegator.java:560) ~[kundera-core-3.2.jar:na]
    at com.impetus.kundera.persistence.PersistenceDelegator.createQuery(PersistenceDelegator.java:521) ~[kundera-core-3.2.jar:na]
[error] m.p.EmployeeProcessImpl$ - No entity found by the name: Employee
```

My entity file is as under: 

**Employee.scala**

```
package models.domains

import java.util.Date
import javax.persistence._
import java.util.UUID

@Entity
@Table(name = "employee", schema = "EmployeeExample@cassandra_employees")
class Employee {

  @Id
  var id: String = UUID.randomUUID.toString()

  @Column(name = "name")
  var name: String = "Employee"

  @Column(name = "address")
  var address: String = "Address"

  @Column(name = "dob")
  var dob: String = (new Date).toLocaleString()

  @Column(name = "joiningDate")
  var joiningDate: String = (new Date).toLocaleString()

  @Column(name = "designation")
  var designation: String = "Test"
}

case class EmployeeForm(id: String, name: String, address: String, dob: Date, joiningDate: Date, designation: String)
```

**persistence.xml:**

```
<persistence xmlns="http://java.sun.com/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    https://raw.github.com/impetus-opensource/Kundera/Kundera-2.0.4/kundera-core/src/test/resources/META-INF/persistence_2_0.xsd"
             version="2.0">
    <persistence-unit name="cassandra_employees">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>models.domains.Employee</class>
       <exclude-unlisted-classes>true</exclude-unlisted-classes>
        <properties>
            <property name="kundera.nodes" value="localhost"/>
            <property name="kundera.port" value="9160"/>
            <property name="kundera.keyspace" value="EmployeeExample"/>
            <property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.client.lookup.class"
                      value="com.impetus.client.cassandra.thrift.ThriftClientFactory"/>
        </properties>
    </persistence-unit>
</persistence>
```

I am using Play 2.3 with cassandra 2.2.4. Can anyone please tell me why I am experiencing this issue. AFAIK the issue is with the entity file itself. Please tell, what wrong thing I have declared in my entity  file ? I have my primary key field in cassandra db of type `UUID`. Kindly help.

**Comment by chhavigangwal** [comment]
Please update your persistence.xml by adding the following (updated above) :

```
<exclude-unlisted-classes>true</exclude-unlisted-classes>
```

Chhavi

**Comment by vinitsharma87** [comment]
Hello @chhavigangwal, I did added this above written xml tag in persistence.xml, but still the same error is there. I have primary key field in database table as `UUID`. I want to know, if I have kept the correct mapping in `Employee.scala` file for it. The cassandra table is created with this schema: 
`CREATE TABLE employee (id uuid PRIMARY KEY, name text, address text, dob text, joiningDate text, designation text);`

**Comment by vinitsharma87** [comment]
@chhavigangwal Can you join me for a chat if its feasible at your end ? [Chat](http://webchat.freenode.net/?channels=Kundera#)

**Comment by chhavigangwal** [comment]
@vinitsharma87 

Please connect here https://gitter.im/impetus-opensource/Kundera?utm_source=badge

**Comment by vinitsharma87** [comment]
@chhavigangwal, I am online now at gitter.

**Comment by kamakkar** [comment]
@chhavigangwal I am experiencing the same issue as @vinitsharma87. I have the @Entity  tag over my entity classes. However, while running the application, I get the below error 
2017-01-06 16:02:18 - No entity found by the name: ServerDetails
2017-01-06 16:02:18 - No entity found by the name: ApplicationConfiguration
2017-01-06 16:02:21 - No entity ApplicationConfiguration found, please verify it is properly annotated with @Entity and not a mapped Super class

**Comment by devender-yadav** [comment]
Hi @kamakkar,

This information is not sufficient. Please raise another issue with Entity, persistence.xml, Kundera version, database used information or chat with us at [gitter](https://gitter.im/impetus-opensource/Kundera).

-Dev
