### ISSUE TITLE
@Enumerated broken 2.13 - Cassandra

### ISSUE THREAD

**Issue by gncm** [Impetus/kundera#646]
I am using 2.13 with cassandra 2.10. @Enumerated seems to be broken. I tried both EnumType.STRING and ORDINAL. Any ideas ?

java.lang.IllegalArgumentException: Invalid value INACTIVE of type unknown to the query builder
    at com.datastax.driver.core.querybuilder.Utils.appendStringIfValid(Utils.java:134)
    at com.datastax.driver.core.querybuilder.Utils.appendValue(Utils.java:115)
    at com.datastax.driver.core.querybuilder.Utils.appendValue(Utils.java:91)
    at com.datastax.driver.core.querybuilder.Utils.joinAndAppendValues(Utils.java:66)
    at com.datastax.driver.core.querybuilder.Insert.buildQueryString(Insert.java:59)
    at com.datastax.driver.core.querybuilder.BuiltStatement.toString(BuiltStatement.java:183)
    at org.springframework.cassandra.core.CqlTemplate$12.doInSession(CqlTemplate.java:512)
    at org.springframework.cassandra.core.CqlTemplate$12.doInSession(CqlTemplate.java:506)
    at org.springframework.cassandra.core.CqlTemplate.doExecute(CqlTemplate.java:483)
    at org.springframework.cassandra.core.CqlTemplate.doExecute(CqlTemplate.java:506)
    at org.springframework.cassandra.core.CqlTemplate.execute(CqlTemplate.java:1184)
    at org.springframework.data.cassandra.core.CassandraTemplate.insert(CassandraTemplate.java:531)
    at org.springframework.data.cassandra.core.CassandraTemplate.insert(CassandraTemplate.java:211)
    at org.springframework.data.cassandra.core.CassandraTemplate.insert(CassandraTemplate.java:206)

**Comment by chhavigangwal** [comment]
Kundera is currently most stable with Cassandra - 2.04 , however can you please share your entity definition ?

Chhavi

**Comment by mevivs** [comment]
```
java.lang.IllegalArgumentException: Invalid value INACTIVE of type unknown to the query builder
at com.datastax.driver.core.querybuilder.Utils.appendStringIfValid(Utils.java:134)
at com.datastax.driver.core.querybuilder.Utils.appendValue(Utils.java:115)
at com.datastax.driver.core.querybuilder.Utils.appendValue(Utils.java:91)
at com.datastax.driver.core.querybuilder.Utils.joinAndAppendValues(Utils.java:66)
at com.datastax.driver.core.querybuilder.Insert.buildQueryString(Insert.java:59)
at com.datastax.driver.core.querybuilder.BuiltStatement.toString(BuiltStatement.java:183)
at org.springframework.cassandra.core.CqlTemplate$12.doInSession(CqlTemplate.java:512)
```

isn't it like you are using Spring data for this?

-Vivek

**Comment by chhavigangwal** [comment]
@gncm 

An updates ?

Chhavi
