### ISSUE TITLE
 All hosts are down. please check servers manully(Kundera cassandra)

### ISSUE THREAD

**Issue by sreekanth0041** [Impetus/kundera#670]
My application working fine for local database but when connecting to remote database i am getting the below error

```
com.impetus.kundera.KunderaException: All hosts are down. please check servers manully.
    at com.impetus.client.cassandra.thrift.ThriftClientFactory.getPoolUsingPolicy(ThriftClientFactory.java:198)
    at com.impetus.client.cassandra.thrift.ThriftClientFactory.instantiateClient(ThriftClientFactory.java:184)
    at com.impetus.kundera.loader.GenericClientFactory.getClientInstance(GenericClientFactory.java:245)
    at com.impetus.kundera.persistence.EntityManagerImpl.discoverClient(EntityManagerImpl.java:990)
    at com.impetus.kundera.persistence.EntityManagerImpl.<init>(EntityManagerImpl.java:142)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:250)
    at MainClient.main(MainClient.java:74)
```

My code is
persistence.xml

```
<persistence xmlns="http://java.sun.com/xml/ns/persistence"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    https://raw.github.com/impetus-opensource/Kundera/Kundera-2.0.4/kundera-core/src/test/resources/META-INF/persistence_2_0.xsd"
    version="2.0">
    <persistence-unit name="cassandra">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>com.xrg.common.persistence.entity.Product</class>
        <class>com.xrg.common.persistence.entity.Category</class>
        <exclude-unlisted-classes>true</exclude-unlisted-classes>
        <properties>
            <property name="kundera.nodes" value="192.168.0.2" />
            <property name="kundera.port" value="9042" />
            <property name="kundera.keyspace" value="xxx" />
            <property name="kundera.dialect" value="cassandra" />
            <property name="kundera.client" value="thrift" />
            <property name="kundera.client.lookup.class"
                value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
            <property name="kundera.cache.provider.class"
                value="com.impetus.kundera.cache.ehcache.EhCacheProvider" />
            <property name="kundera.client.property" value="kunderaCounter.xml" />
            <property name="net.sf.ehcache.configurationResourceName"
                value="ehcache-test.xml" />
            <property name="jboss.as.jpa.managed" value="false" />
        </properties>
    </persistence-unit>
</persistence>
```

ehcache-test.xml

```
<ehcache xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ehcache.xsd">
        <diskStore path="java.io.tmpdir"/>
        <defaultCache maxElementsInMemory="10000" eternal="false" timeToIdleSeconds="120"
                timeToLiveSeconds="300" overflowToDisk="true" diskSpoolBufferSizeMB="30"
                maxElementsOnDisk="100000" diskPersistent="false" diskExpiryThreadIntervalSeconds="120"
                memoryStoreEvictionPolicy="LRU" />
        <cache name="com.impetus.kundera.entity.Product" maxElementsInMemory="10000"
                maxElementsOnDisk="1000" eternal="false" overflowToDisk="true" diskSpoolBufferSizeMB="20"
                timeToIdleSeconds="300" timeToLiveSeconds="600" />

        <cache name="com.impetus.kundera.entity.Category" maxElementsInMemory="10000"
                maxElementsOnDisk="1000" eternal="false" overflowToDisk="true" diskSpoolBufferSizeMB="20"
                timeToIdleSeconds="300" timeToLiveSeconds="600" />
</ehcache>
```

kunderaCounter.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<clientProperties>
    <datastores>
        <dataStore>
            <name>cassandra</name>
            <connection>
                <properties>
                </properties>
            </connection>
            <schemas>
                <schema>
                    <name>xxx</name>
                    <tables>
                        <table>
                            <name>SUBORDINATES_COUNTER</name>
                            <properties>

                                <property name="default.validation.class" value="CounterColumnType"></property>
                                <property name="key.validation.class" value="UTF8Type"></property>
                            </properties>
                        </table>
                    </tables>
                </schema>
            </schemas>
        </dataStore>
    </datastores>
</clientProperties>
```

Category.java

```
@Entity
@Table(name = "product_category", schema = "xxx@cassandra")
public class Category {
    @Id
    @Column(name = "category_id")
    private String category_id;

    @Column(name = "category_name")
    private String category_name;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinColumn(name = "cid")
    private List<Product> products;
//getter and setters
}
```

Product.java

```
@Entity
@Table(name = "product", schema = "xxx@cassandra")
public class Product implements Serializable {
//product_id text primary key,product_name text,category_id text,brand_id text,product_price text,features map<text,text>
    @Id
    @Column(name = "product_id")
    private String product_id;

    @Column(name = "product_name")
    private String product_name;

    @Column(name = "category_id")
    private String category_id;

    @Column(name = "brand_id")
    private String brand_id;

    @Column(name = "product_price")
    private String product_price;
@Column(name = "features")
    private Map<String, String> features;
//setter and getters
}
```

Test,java

```
            List<Product> list = new ArrayList<Product>();
            Product product = new Product();
            product.setProduct_name("Spice Android One Dream");
            product.setProduct_id(CassandraUtil.getUniqueId());
            product.setBrand_id("Spice");
            product.setProduct_price("13000");
            Map<String, String> map = new HashMap<String, String>();
            map.put("Color", "Black");
            map.put("OS", "Android");
            map.put("RAM", "1GB");
            map.put("Processor", "Dual core");
            product.setFeatures(map);

            Product product1 = new Product();
            product1.setProduct_name("Spice Android One Dream");
            product1.setProduct_id(CassandraUtil.getUniqueId());
            product1.setBrand_id("Spice");
            product1.setProduct_price("13000");
            Map<String, String> map1 = new HashMap<String, String>();
            map1.put("Color", "Black");
            map1.put("OS", "Android");
            map1.put("RAM", "1GB");
            map1.put("Processor", "Dual core");
            product1.setFeatures(map1);
            list.add(product);
            list.add(product1);
            category.setProducts(list);

        Map<String, String> propertyMap = new HashMap<String, String>();
            propertyMap.put(Constants.CQL_VERSION, Constants.CQL_VERSION_3_0);
            EntityManagerFactory emf = Persistence.createEntityManagerFactory(
                    "cassandra", propertyMap);
            EntityManager em = emf.createEntityManager();

            em.persist(category);
            em.close();
            emf.close();
```

Please help me

**Comment by chhavigangwal** [comment]
Is your Cassandra server configured to accept connections from remote server ?

Chhavi

**Comment by sreekanth0041** [comment]
Yes i given the permissions, and also its connecting with the below code without jpa.
When we use kundera cassandra i am getting the error.

```
   public static void main(String[] args) {
        EmployeePersistence ep = new EmployeePersistence("192.168.0.2", 9042);

        Set<String> email = new HashSet<String>();
        email.add("raju@gmail.com");
        email.add("raju@yahoo.com");
        email.add("raju@live.com");
        Map<String, String> vehicles = new HashMap<String, String>();
        vehicles.put("AP29AX5695", new Vehicle("AP29AX5695", "Discover 125 ST", "Bajaj").toString());
        vehicles.put("AP26AK5121", new Vehicle("AP26AK5121", "Scorpio ", "TATA").toString());

        Employee emp = new Employee(12425, "Raja Sekhar", email, vehicles);
        //    System.out.println("Employee Vehicles : " + employee.getVehiclesMap());
        //    ep.persistEmployee(emp);

            List<Optional<Employee>> e = ep.queryEmployees();

            System.out.println("Employees  Details : \n ");
            for(Optional<Employee> employee : e){
                System.out.println("\n"+employee.get()+"\n");
            }

        }
,,,
```

**Comment by chhavigangwal** [comment]
We are looking into  the issue !

Chhavi

**Comment by sreekanth0041** [comment]
Maven dependencies are

```
    <dependencies>
        <dependency>
            <groupId>com.impetus.kundera.core</groupId>
            <artifactId>kundera-core</artifactId>
            <version>2.13</version>
        </dependency>
        <dependency>
            <groupId>com.impetus.kundera.client</groupId>
            <artifactId>kundera-cassandra</artifactId>
            <version>2.14</version>
        </dependency>
        <dependency>
            <groupId>org.apache.cassandra</groupId>
            <artifactId>cassandra-thrift</artifactId>
            <version>2.1.0</version>
        </dependency>

        <dependency>
            <groupId>com.impetus.kundera.core</groupId>
            <artifactId>fallback-impl</artifactId>
            <version>2.14</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-orm</artifactId>
            <version>3.1.2.RELEASE</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <version>3.1.2.RELEASE</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <version>3.1.2.RELEASE</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
```

**Comment by chhavigangwal** [comment]
@sreekanth0041 

Can you share a sample project to replicate the issue and help you resolve the same ?

Chhavi

**Comment by sreekanth0041** [comment]
Can you please share your mail id

**Comment by chhavigangwal** [comment]
Please mail your project at kundera@impetus.co.in

Chhavi

**Comment by mevivs** [comment]
@sreekanth0041 

```
     <property name="kundera.port" value="9042" />
```

is for native protocol not for thrift. Either change persistence.xml from ThriftClientFactory to DSClientFactory or change kundera.port to point thrift port( i.e 9160, by default).

HTH,
-Vivek
