### ISSUE TITLE
Kundera one to many not working

### ISSUE THREAD

**Issue by sreekanth0041** [Impetus/kundera#698]
One to many working for different entities but not working in the same entity
My code is below

```
@Entity
@Table(name = "USER", schema = "KunderaExamples@mongoTest")
public class UserMongo
{

    @Id
    @Column(name = "USER_ID")
    private String userId;

    @Id
    @Column(name = "USER_NAME")
    private String username;
    // One to many, will be persisted separately
    @OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.EAGER)
    @JoinColumn(name = "FOLLOWER_ID")
    private List<UserMongo> followers; // List of users who are following me

 public void addFollower(UserMongo follower)
    {
        if (this.followers == null || this.followers.isEmpty())
        {
            this.followers = new ArrayList<UserMongo>();
        }

        this.followers.add(follower);
    }
//setter and getters

}
```

Adding followers below

```
 @Override
    public void addFollower(String userId, String followerUserId)
    {
        UserMongo user = em.find(UserMongo.class, userId);
        UserMongo follower = em.find(UserMongo.class, followerUserId);

        user.addFollower(follower);
        em.persist(user);
    }
```

Help me

**Comment by chhavigangwal** [comment]
@sreekanth0041 

With Kundera you have only one @Id attribute in an entity class, so please remove @Id annotation from one of the attributes. 
Also, we tried persisting self referential OneToMany objects in MongoDB and it works fine .We are looking into the issue while fetching the object response and will update soon.

Chhavi

**Comment by sreekanth0041** [comment]
Yes i tried the same its working for insert but when i am getting the data showing below error

```
10:02:29,663 ERROR [stderr] (http-localhost-127.0.0.1-8080-1) Caused by: java.lang.NullPointerException

10:02:29,663 ERROR [stderr] (http-localhost-127.0.0.1-8080-1)   at com.impetus.client.mongodb.DefaultMongoDBDataHandler.getEntityFromDocument(DefaultMongoDBDataHandler.java:148)

10:02:29,667 ERROR [stderr] (http-localhost-127.0.0.1-8080-1)   at com.impetus.client.mongodb.MongoDBClient.populateEntity(MongoDBClient.java:1001)

10:02:29,667 ERROR [stderr] (http-localhost-127.0.0.1-8080-1)   at com.impetus.client.mongodb.MongoDBClient.loadData(MongoDBClient.java:446)

10:02:29,667 ERROR [stderr] (http-localhost-127.0.0.1-8080-1)   at com.impetus.client.mongodb.query.MongoDBQuery.recursivelyPopulateEntities(MongoDBQuery.java:214)

10:02:29,667 ERROR [stderr] (http-localhost-127.0.0.1-8080-1)   ... 39 more
```

Suggest me any alternate solution for this.

**Comment by chhavigangwal** [comment]
@sreekanth0041 

We are working on the fix for this issue and will update you soon.

Chhavi

**Comment by chhavigangwal** [comment]
@sreekanth0041 

A fix for the issue has been added in current branch and will be released as a part of the upcoming release. In order to help you further and better understand your issues , can you share the use case for which you are using kundera-mongo . You can also reach us at kundera@impetus.co.in for any further queries.

Chhavi

**Comment by chhavigangwal** [comment]
Closing with 2.17 release
