### ISSUE TITLE
[Kundera-datastax] NoHostAvailableException

### ISSUE THREAD

**Issue by ansarrafique** [Impetus/kundera#705]
I remember I already pointed out the same issue with 3 nodes Cassandra setup, but this time the same issue came up with a single node. 

Kundera-version: Kundera 2.11
Cassandra:2.0.6

Few records are successfully inserted, but  the problem starts afterwards and getting an exception on client side. I have only persistence.xml file and without any datastax related configuration file which I guess don't require anyway considering the default configurations will be selected (if I am wrong then please tell me what I specify in configuration and where to place such a file). I was reading that Kundera2.11 doesn't work with Cassandra 2.0.6, but how come few records are inserted. Is there any updated Kundera's version to use with Cassandra 2.x ? Exception below, thanks

Exception in thread "main" com.impetus.kundera.KunderaException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:175)
    at kunderamiddlewareperformance.performance.Driver.insertData(Driver.java:43)
    at kunderamiddlewareperformance.performance.Driver.main(Driver.java:23)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)
    at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:64)
    at com.datastax.driver.core.ResultSetFuture.extractCauseFromExecutionException(ResultSetFuture.java:269)
    at com.datastax.driver.core.Session$Manager.setKeyspace(Session.java:448)
    at com.datastax.driver.core.Cluster.connect(Cluster.java:146)
    at com.impetus.kundera.client.cassandra.dsdriver.DSClientFactory.getConnection(DSClientFactory.java:272)
    at com.impetus.kundera.client.cassandra.dsdriver.DSClient.execute(DSClient.java:517)
    at com.impetus.client.cassandra.CassandraClientBase$CQLClient.persist(CassandraClientBase.java:2001)
    at com.impetus.kundera.client.cassandra.dsdriver.DSClient.onPersist(DSClient.java:114)
    at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:96)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:191)
    at com.impetus.kundera.graph.Node.flush(Node.java:531)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:408)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:149)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:169)
    ... 2 more
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)
    at com.datastax.driver.core.RequestHandler.sendRequest(RequestHandler.java:106)
    at com.datastax.driver.core.Session$Manager.execute(Session.java:459)
    at com.datastax.driver.core.Session$Manager.executeQuery(Session.java:495)
    at com.datastax.driver.core.Session$Manager.setKeyspace(Session.java:442)
    ... 13 more

**Comment by chhavigangwal** [comment]
@ansarrafique 

Cassandra 2.0.4 support with Kundera was added from version 2.11.1. Latest version of Kundera is 2.15. Can you try running your code with kundera-cassandra 2.15 and Cassandra 2.0.4 ?

Chhavi

**Comment by chhavigangwal** [comment]
@ansarrafique 

Any updates ?

Chhavi

**Comment by ansarrafique** [comment]
It works.

Thanks,

BR,
AR
