### ISSUE TITLE
Error in persisting an Entity

### ISSUE THREAD

**Issue by cherry316** [Impetus/kundera#711]
Hello all,
Good day.

I encountered this error below on which I cannot find the answer on the google. Attached below are the Server log error, Persistence, Entity.class, and the class that I'm using in persisting the newly added entity data for reference. 
I hope you can help me with this. 

Thanks in advance,
Cherry

**Error in server log**

```
06:27:47,780 INFO  [com.impetus.kundera.persistence.EntityManagerImpl] (http-localhost-127.0.0.1-8083-1) Returning client instance for persistence unit cassandra_pu.
06:27:47,812 INFO  [stdout] (http-localhost-127.0.0.1-8083-1) user: null Hello World
06:27:47,843 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/Cass_Implementation].[CassServlet]] (http-localhost-127.0.0.1-8083-1) Servlet.service() for servlet CassServlet threw exception: com.impetus.kundera.KunderaException: java.lang.IllegalArgumentException: Entity object is invalid, operation failed. Please check previous log message for details
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180) [kundera-core-2.15.jar:]
    at session.TestClassService.main(TestClassService.java:25) [classes:]
    at CassServlet.service(CassServlet.java:48) at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar:]
    at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.1.1.Final.jar:7.1.1.Final]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
    at java.lang.Thread.run(Unknown Source) [rt.jar:1.7.0_71]
Caused by: java.lang.IllegalArgumentException: Entity object is invalid, operation failed. Please check previous log message for details
    at com.impetus.kundera.validation.rules.NullOrInvalidEntityRule.validate(NullOrInvalidEntityRule.java:52) [kundera-core-2.15.jar:]
    at com.impetus.kundera.graph.GraphGenerator.generate(GraphGenerator.java:125) [kundera-core-2.15.jar:]
    at com.impetus.kundera.graph.GraphGenerator.generateGraph(GraphGenerator.java:78) [kundera-core-2.15.jar:]
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:130) [kundera-core-2.15.jar:]
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174) [kundera-core-2.15.jar:]
```

**POMxml**
      <modelVersion>4.0.0</modelVersion>
      <groupId>Cass_Implementation</groupId>
      <artifactId>Cass_Implementation</artifactId>
      <version>0.0.1-SNAPSHOT</version>
      <packaging>war</packaging>

```
  <dependencies>
        <dependency>
              <groupId>junit</groupId>
              <artifactId>junit</artifactId>
              <version>4.12</version>
        </dependency>
        <dependency>
            <groupId>org.apache-extras.cassandra-jdbc</groupId>
            <artifactId>cassandra-jdbc</artifactId>
            <version>1.2.5</version>
        </dependency>
        <dependency>
                <groupId>com.datastax.cassandra</groupId>
                <artifactId>cassandra-driver-mapping</artifactId>
                <version>2.1.4</version>
        </dependency>
         <dependency>
                <groupId>org.apache.cassandra</groupId>
                <artifactId>cassandra-all</artifactId>
                <version>1.2.0-beta1</version>
        </dependency>
        <dependency>
                <groupId>org.apache.cassandra</groupId>
                <artifactId>cassandra-thrift</artifactId>
                <version>1.2.0-beta1</version>
        </dependency>
        <dependency>
                <groupId>com.datastax.cassandra</groupId>
                <artifactId>cassandra-driver-core</artifactId>
                <version>2.1.4</version>
                <exclusions>
                      <exclusion> 
                            <groupId>org.slf4j</groupId>
                            <artifactId>slf4j-log4j12</artifactId>
                      </exclusion>
                      <exclusion> 
                            <groupId>log4j</groupId>
                            <artifactId>log4j</artifactId>
                      </exclusion>
                </exclusions> 
        </dependency>  
        <dependency>
               <groupId>com.impetus.kundera.core</groupId>
               <artifactId>kundera-core</artifactId>
               <version>2.15</version>
         </dependency>
         <dependency>
               <groupId>com.impetus.kundera.client</groupId>
               <artifactId>kundera-cassandra</artifactId>
               <version>2.15</version>
         </dependency>
         <dependency>
              <groupId>com.impetus.kundera.core</groupId>
              <artifactId>fallback-impl</artifactId>
              <version>2.15</version>
        </dependency>
    </dependencies>

  <build>
        <plugins>           
             <!-- Compiler plugin enforces Java 1.6 compatibility and activates 
                annotation processors -->
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.1</version>
                <configuration>
                    <source>1.6</source>
                    <target>1.6</target>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <version>2.1.1</version>
                <configuration>
                    <!-- Java EE 6 doesn't require web.xml, Maven needs to 
                        catch up! -->
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                </configuration>
            </plugin>
            <!-- The JBoss AS plugin deploys your war to a local JBoss AS 
                container -->
            <!-- To use, run: mvn package jboss-as:deploy -->
            <plugin>
                <groupId>org.jboss.as.plugins</groupId>
                <artifactId>jboss-as-maven-plugin</artifactId>
                <version>7.1.1.Final</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.7.2</version>
                <configuration>
                    <systemPropertyVariables>
                        <tapestry.execution-mode>Qa</tapestry.execution-mode>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
  </build>

     <repositories>
        <repository>
            <id>sonatype-nexus</id>
                <name>Kundera Public Repository</name>
                <url>https://oss.sonatype.org/content/repositories/releases</url>
                <releases>
                    <enabled>true</enabled>
                </releases>
                <snapshots>
                    <enabled>false</enabled>
                </snapshots>
         </repository>
         <repository>
               <id>riptano</id>
               <name>riptano</name>
               <url>http://mvn.riptano.com/content/repositories/public</url>
        </repository>
    </repositories>
</project>
```

**Users entity class**

```
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import java.io.Serializable;
@Entity
@Table(name="users", schema="pcc4@cassandra_pu")
public class Users{ // implements Serializable{

//  private static final long serialVersionUID = -4135217519538775560L;

    /** Column user_id */
    @Id
    @Column(name="user_id")
    private Integer userId;
    public Integer getUserId() {
        return userId;
    }
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /** Column first_name */
    @Column(name="first_name")
    private String firstName;
    public String getFirstName() {
        return firstName;
    }
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /** Column last_name */
    @Column(name="last_name")
    private String lastName;
    public String getLastName() {
        return lastName;
    }
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Users(){super();}
}
```

**SimpleServiceClass**

```
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import entities.Users;
public class TestClassService {

    public static void main(String[] args){

        Users user = new Users();
        //(1, "Name_1", "LName_1");
        user.setFirstName("Hello");
        user.setLastName("World");

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("cassandra_pu");
        EntityManager em = emf.createEntityManager();

System.out.println("user: "+ user.getUserId()+" "+user.getFirstName()+" "+user.getLastName());
        em.persist(user);
    }
)   
```

**Comment by chhavigangwal** [comment]
@cherry316 

Are you setting the id of the entity by calling ?

```
Object user = add(1, "Name_1", "LName_1");
or 
user.setUserId(1);
```

if not please make sure you do that.

Also, update you pom.xml to include the following dependencies only: 

```
       <dependency>
              <groupId>junit</groupId>
              <artifactId>junit</artifactId>
              <version>4.12</version>
        </dependency>
          <dependency>
               <groupId>com.impetus.kundera.client</groupId>
               <artifactId>kundera-cassandra</artifactId>
               <version>2.15</version>
         </dependency>
         <dependency>
              <groupId>com.impetus.kundera.core</groupId>
              <artifactId>fallback-impl</artifactId>
              <version>2.15</version>
        </dependency>
```

If none of the above suggestions are able to resolve your issue please mail a sample project to us so that we can look into it further.

Hope this helps !
Chhavi

**Comment by cherry316** [comment]
Hi Chhavi,

I tried both below individually this morning to check. I also applied your suggestion regarding dependencies that should only be included in POM.xml but the error is still  the same.  

```
Object user = add(1, "Name_1", "LName_1");
em.persist(user);
```

and

```
Users user  = new Users();
user.setUserId(1); 
user.setFirstName("Hello");
user.setLastName("World");
em.persist(user);
```

I will send you an example project via google drive. 
Again, thanks for the immediate response. 

Cherry

**Comment by chhavigangwal** [comment]
@cherry316 

Once you have @id  field annotated, make sure it holds a value before persisting and it should work for you. You can directly mail the sample project (if needed) at kundera@impetus.co.in

Chhavi

**Comment by cherry316** [comment]
Implementing **Serializable** in my entity solved my problem. Though it does, I'm not convinced yet since I don't know how and why.  hahaha
Thanks @chhavigangwal and please consider this as close.  

```
    @Entity
    @Table(name="users", schema="pcc4@cassandra_pu")
    public class Users implements Serializable{ 

        private static final long serialVersionUID = 6653425147548009598L;

        /** Column user_id */
        @Id
        @Column(name="user_id")
        private Integer userId;
        public Integer getUserId() {
            return userId;
        }
        public void setUserId(Integer userId) {
            this.userId = userId;
        }
                    .  .  .
```

Cherry

**Comment by cherry316** [comment]
In case somebody has the same problem,
FYI, it is not the **Serializable** that solves this problem but rather, by adding the entity class enclosed with < class > < /class > tags in the persistence.
