### ISSUE TITLE
Problem to connect with cassandra

### ISSUE THREAD

**Issue by ankit5858** [Impetus/kundera#718]
We are getting below error while connecting with Cassandra 

Exception in thread "main" java.lang.NoClassDefFoundError: org/scale7/cassandra/pelops/IConnectionAuthenticator
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at com.impetus.kundera.client.ClientResolver.instantiateClientFactory(ClientResolver.java:90)
    at com.impetus.kundera.client.ClientResolver.getClientFactory(ClientResolver.java:56)
    at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:39)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:352)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:116)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:83)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at jers.net.hello.Kundra.main(Kundra.java:20)
Caused by: java.lang.ClassNotFoundException: org.scale7.cassandra.pelops.IConnectionAuthenticator
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 11 more
## below are my pom.xml file and java file.

```
<repositories>
<repository>
<id>sonatype-nexus</id>
<name>Kundera Public Repository</name>
<url>https://oss.sonatype.org/content/repositories/releases</url>
<releases>
<enabled>true</enabled>
</releases>
<snapshots>
<enabled>false</enabled>
</snapshots>
</repository>
<repository>
<id>kundera-missing</id>
<name>Kundera Public Missing Resources Repository</name>
<url>http://kundera.googlecode.com/svn/maven2/maven-missing-resources</url>
<releases>
<enabled>true</enabled>
</releases>
<snapshots>
<enabled>true</enabled>
</snapshots>
</repository>
<repository>
<id>central</id>
<name>Maven Central Repo</name>
<url>http://repo1.maven.org/maven2</url>
</repository>
<repository>
<id>riptano</id>
<name>riptano</name>
<url>http://mvn.riptano.com/content/repositories/public</url>
</repository>
<repository>
<id>maven.scale7.org</id>
<name>Scale7 Maven Repo</name>
<url>https://github.com/s7/mvnrepo/raw/master</url>
<snapshots>
<enabled>true</enabled>
</snapshots>
</repository>
</repositories>
<dependencies>
<dependency>
<groupId>com.impetus.client</groupId>
<artifactId>kundera-cassandra</artifactId>
<version>2.6</version>
</dependency>
<dependency>
<groupId>org.scale7</groupId>
<artifactId>scale7-pelops</artifactId>
<version>1.3-1.1.x</version>
</dependency>
</dependencies>
```

---

```
public class Kundra {
        public static void main(String[] args)
        {
            User user = new User();
            user.setUserId("0001");
            user.setFirstName("John");
            user.setLastName("Smith");
            user.setCity("London");
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("cassandra_pu");
            EntityManager em = emf.createEntityManager();
            em.persist(user);
            em.close();    
            emf.close();    
        }
    }
```

**Comment by chhavigangwal** [comment]
@ankit5858 

Which version of Cassandra are you using? Can you please update the kundera-cassandra dependency to :  

```
    <dependency>
            <groupId>com.impetus.client</groupId>
            <artifactId>kundera-cassandra</artifactId>
            <version>2.15</version>
        </dependency>

```

and update your persistence.xml to 

```
<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0">
    <persistence-unit name="cassandra_pu">
        <provider>com.impetus.kundera.KunderaPersistence</provider>     
        <properties>            
            <property name="kundera.nodes" value="localhost"/>
            <property name="kundera.port" value="9160"/>
            <property name="kundera.keyspace" value="KunderaExamples"/>
            <property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.client.lookup.class"
                value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />

        </properties>       
    </persistence-unit>
</persistence>
```

Please try running your code with updated configurations.

Hope that Helps!
Chhavi

**Comment by ankit5858** [comment]
Thanks Chhavi

Now it's getting work..  :)
