### ISSUE TITLE
Kundera casts String “1” to Integer 1 for Cassandra queries

### ISSUE THREAD

**Issue by marseg** [Impetus/kundera#733]
I've got the next exception 

Caused by: com.impetus.kundera.KunderaException: com.datastax.driver.core.exceptions.InvalidQueryException: Invalid INTEGER constant (1) for promo_code_id of type ascii
    at com.impetus.kundera.client.cassandra.dsdriver.DSClient.execute(DSClient.java:510) [kundera-cassandra-ds-driver.jar:]
    at com.impetus.kundera.client.cassandra.dsdriver.DSClient.executeQuery(DSClient.java:415) [kundera-cassandra-ds-driver.jar:]
    at com.impetus.client.cassandra.query.CassQuery.recursivelyPopulateEntities(CassQuery.java:245) [kundera-cassandra.jar:]
    at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:1266) [kundera-core.jar:]
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:187) [kundera-core.jar:]
    at com.impetus.kundera.query.KunderaTypedQuery.getResultList(KunderaTypedQuery.java:250) [kundera-core.jar:]

during executing next code 

```
Query query = getEM().createQuery(
                    "select apc from ActivatedPromoCode apc where apc.promoCodeId in ?1 " +
                            "and apc.isRegistrationPromo = true " +
                            "and apc.activationTimestamp > ?2 and apc.activationTimestamp < ?3");
            query.setParameter(1, promoCodeIds); // List<String>
            query.setParameter(2, startDate);
            query.setParameter(3, endDate);

            try {
                return query.getResultList();
            } catch (NoResultException e) {
                return null;
            }
```

the query that goes to Cassandra:

09:35:22,963 ERROR [com.impetus.kundera.client.cassandra.dsdriver.DSClient](Thread-0 %28HornetQ-client-global-threads-1819772796%29) Error while executing query SELECT \* FROM "activated_promo_code" WHERE "promo_code_id" IN (1) AND "is_registration_promo" = true AND "activation_timestamp" > '1427857200000' AND "activation_timestamp" < '1428116400000' LIMIT 100  ALLOW FILTERING

I've already asked the same question on stackoverflow http://stackoverflow.com/questions/29446592/kundera-cast-string-1-to-integer-1-in-queries. Here you can find more details if it will be nesessary. 

Can you explain when and why Kundera transfroms String "1" to Integer 1?

Will be happy if you can help me :)
Thanks,
Sergey

**Comment by marseg** [comment]
So, the problem was not in Kundera but in model class definition. Class contained 2 fields that mapped to one database field. Sometimes field promo_code_id casts to String and we got correct work and sometimes it casts to PromoCode and we got incorrect work. So, the solution is to use more appropriate schema definition.
