### ISSUE TITLE
Entity object is invalid

### ISSUE THREAD

**Issue by cherry316** [Impetus/kundera#737]
Hello all,
Good day.

I followed the links [Using-Compound-keys-with-Kundera](https://github.com/impetus-opensource/Kundera/wiki/Using-Compound-keys-with-Kundera) and [Schema-Generation](https://github.com/impetus-opensource/Kundera/wiki/Schema-Generation) .
 But I got these errors below which points to **em.persist(lm)** on my main class (CassServlet.java:75). It also says that my _Entity object is invalid_ however, I think I followed the instructions in the link correctly. May I know what is the cause of the error? 

```
10:17:07,546 INFO  [com.impetus.kundera.persistence.EntityManagerFactoryImpl] (http-localhost-127.0.0.1-8083-1) EntityManagerFactory created for persistence unit : cassandra_pu
10:17:07,546 INFO  [com.impetus.kundera.persistence.EntityManagerImpl] (http-localhost-127.0.0.1-8083-1) Returning client instance for persistence unit cassandra_pu.
10:17:07,562 ERROR [stderr] (http-localhost-127.0.0.1-8083-1) com.impetus.kundera.KunderaException: java.lang.IllegalArgumentException: Entity object is invalid, operation failed. Please check previous log message for details
10:17:07,577 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)
10:17:07,577 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at CassServlet.service(CassServlet.java:75)
10:17:07,577 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
10:17:07,577 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329)
10:17:07,593 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
10:17:07,593 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275)
10:17:07,593 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
10:17:07,608 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50)
10:17:07,608 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153)
10:17:07,608 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
10:17:07,624 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
10:17:07,624 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
10:17:07,624 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368)
10:17:07,640 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877)
10:17:07,640 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671)
10:17:07,640 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930)
10:17:07,655 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at java.lang.Thread.run(Unknown Source)
10:17:07,655 ERROR [stderr] (http-localhost-127.0.0.1-8083-1) Caused by: java.lang.IllegalArgumentException: Entity object is invalid, operation failed. Please check previous log message for details
10:17:07,655 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at com.impetus.kundera.validation.rules.NullOrInvalidEntityRule.validate(NullOrInvalidEntityRule.java:52)
10:17:07,671 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at com.impetus.kundera.graph.GraphGenerator.generate(GraphGenerator.java:125)
10:17:07,671 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at com.impetus.kundera.graph.GraphGenerator.generateGraph(GraphGenerator.java:78)
10:17:07,671 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:130)
10:17:07,671 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)
10:17:07,671 ERROR [stderr] (http-localhost-127.0.0.1-8083-1)   ... 16 more
```

**Entity :**

``` javascript
    @Entity
    @Table(name="LMNet", schema="pcc4_storage@cassandra_pu")
    public class LMNet implements Serializable{

        private static final long serialVersionUID = 1L;

        @EmbeddedId
        private CompoundKey key;

        private Integer state;
        private Double tonnage;
        // ... getters and setters...
        public lmn (){ super(); }
    }
```

**CompoundKey :**

``` javascript
    @Embeddable
    public class CompoundKey implements Serializable{

        private static final long serialVersionUID = 1L;

        // Partition key.
        @Column
        private String license;  
        // Clustering keys.
        @Column
        private String messageGroup;
        @Column
        private String type;
        @Column
        private Integer protocol;

        public CompoundKey(String license, String messageGroup, String type, Integer protocol){
            this.license = license;
            this.messageGroup = messageGroup;
            this.type = type;
            this.protocol = protocol;
        }
    }   
```

**Main Class (CassServlet.java) :**

``` javascript
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("cassandra_pu");
        EntityManager em = emf.createEntityManager();
        em.setProperty("cql.version", "3.0.0");
        try{
            CompoundKey ck = new CompoundKey("hello", "msgGrp", "type", 3);
            LMNet lm = new LMNet();
            lm.setKey(ck);
            lm.setState(123);
            em.persist(lm);    // <--- Error points here...
        }catch (Exception e) {
            e.printStackTrace();
        }
```

Best regards,
Cherry

**Comment by karthikprasad13** [comment]
@cherry316 

Hello,
Good day.

We tried to reproduce the issue using your entities, but everything is working fine. And what exactly is `public lmn (){ super(); }` in your entity? Can you share your `persistence.xml` file and also which version of Kundera you are using?

Karthik

**Comment by cherry316** [comment]
hi @karthikprasad13,
Thank for your immediate response, just pleas disregard _public lmn (){ super(); }_ .

Here is my persistence:

```
<persistence-unit name="cassandra_pu">
    <provider>com.impetus.kundera.KunderaPersistence</provider>   

     <!-- Include all entity classes here... -->
    <class>entities.Users</class>
    <class>entities.LMNet</class>
    <class>entities.CompoundKey</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>

    <properties>   
        <property name="cql.version"        value="3.0.0"/>
        <!-- Cassandra nodes to with Kundera will connect -->
        <property name="kundera.nodes"      value="localhost"/>
        <!-- Cassandra port -->
        <property name="kundera.port"       value="9160"/>
        <!-- Cassandra keyspace which Kundera will use -->
        <property name="kundera.keyspace"   value="pcc4"/>
        <property name="kundera.dialect"    value="cassandra"/>
        <property name="kundera.ddl.auto.prepare" value="create"/>

        <property name="kundera.client" value="thrift"/>

        <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
        <property name="kundera.cache.config.resource" value="/ehcache-test.xml" />

        <!-- prevents Error:  JBAS011466: PersistenceProvider 'com.impetus.kundera.KunderaPersistence' not found -->
        <property name="jboss.as.jpa.managed" value="false"/>        
    </properties>     
</persistence-unit>
```

Cherry

**Comment by karthikprasad13** [comment]
@cherry316 

Keyspace in your persistence-unit is defined as `pcc4`

```
<property name="kundera.keyspace"   value="pcc4"/>
```

And keyspace in your entity is defined as  `pcc4_storage`

```
@Table(name="LMNet", schema="pcc4_storage@cassandra_pu")
```

Thats why Kundera was failing to validate the entity. Please make them same.

Karthik

**Comment by cherry316** [comment]
@karthikprasad13 

Thank you very much, my bad, I didn't see that. 
It's fine now. ^____^
