### ISSUE TITLE
ConcurrentModificationException in FlushManager

### ISSUE THREAD

**Issue by nath-abhi** [Impetus/kundera#738]
We are using Kundera 2.8 and we are seeing high CPU and concurrent modification exception during persist. Here is the stacktrace:

java.lang.Thread.State: RUNNABLE
at java.lang.Throwable.fillInStackTrace(Native Method)
at java.lang.Throwable.fillInStackTrace(Throwable.java:782)
- locked <0x00000007b634af98> (a java.util.ConcurrentModificationException)
  at java.lang.Throwable.<init>(Throwable.java:250)
  at java.lang.Exception.<init>(Exception.java:54)
  at java.lang.RuntimeException.<init>(RuntimeException.java:51)
  at java.util.ConcurrentModificationException.<init>(ConcurrentModificationException.java:76)
  at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
  at java.util.HashMap$ValueIterator.next(HashMap.java:922)
  at com.impetus.kundera.persistence.context.FlushManager.onRollBack(FlushManager.java:415)
  at com.impetus.kundera.persistence.context.FlushManager.rollback(FlushManager.java:339)
  at com.impetus.kundera.persistence.PersistenceDelegator.rollback(PersistenceDelegator.java:742)
  at com.impetus.kundera.persistence.EntityManagerImpl.doRollback(EntityManagerImpl.java:944)
  at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:173)
  at sun.reflect.GeneratedMethodAccessor580.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:366)
  at com.sun.proxy.$Proxy109.persist(Unknown Source)

Wondering if this a know issue? Or if by upgrading to latest version, it will be resolved?

/Abhi

**Comment by chhavigangwal** [comment]
@cooolmagic 

Please try and upgrade it to latest version 2.16 .

Chhavi

**Comment by chhavigangwal** [comment]
@cooolmagic 

Any updates?
