### ISSUE TITLE
kundera-hbase-v2 NoClassDefFoundError org/apache/hadoop/hbase/client/ConnectionFactory

### ISSUE THREAD

**Issue by gdoubleu** [Impetus/kundera#753]
When I switch from kundera-hbase to kundera-hbase-v2. I get a NoClassDefFoundError on org/apache/hadoop/hbase/client/ConnectionFactory.

I am using a pre-1.0 version of the hbase-client. Had no issues with kundera-hbase (v1).

**Comment by pragalbhgarg** [comment]
Hi @gdoubleu,

The Class `ConnectionFactory` is added in HBase since the version 0.99.0. Kundera uses hbase 1.0.0 version. Since, you are getting a `NoClassDefFoundError`, it might be because of version mismatch. Please upgrade your client version to 0.99.0+ (1.0.0 recommended). Remove any older version of hbase from your classpath. You can do this by removing it from your .m2 repository.

Please also note that kundera-hbase-v2 has a different data model. You must read its wiki here- https://github.com/impetus-opensource/Kundera/wiki/Kundera-with-HBase#kundera-hbase-v2

Also we would like to have a live discussion with you on how you are planning to migrate and other feedbacks/suggestions regarding Kundera. We can connect using the following IRC client- http://webchat.freenode.net/?channels=Kundera# 
Please, let us know your availability so that we can help you better. 

-PG

**Comment by gdoubleu** [comment]
Hi PG, 

Prior to posting, I did try the hbase-client in v1 but I got quite a few errors, and I need to dig into this. 

Why would kundera-hbase-v2 and kundera-hbase not be interchangeable, runtime wise that is (I am aware of the different models as you pointed out)?

**Comment by pragalbhgarg** [comment]
Hi @gdoubleu,

Since you are aware of the data model, there must not be any issue shifting from kundera-hbase to kundera-hbase-v2. 
As I had mentioned, we can get into a live discussion regarding your experience with Kundera at http://webchat.freenode.net/?channels=Kundera# . Please let us know if we can have a discussion.

-PG

**Comment by gdoubleu** [comment]
Hi PG, 

Ok, so when switching my HBase client dependancies to v1.0.0, I now get the trace below.

Judging by where the exception is thrown (HBaseSchemaManager.java:547), it looks like the hosts are not set up properly, any idea? 

Exception in thread "main" com.impetus.kundera.configure.schema.SchemaGenerationException: Master not running exception, Caused by:java.lang.reflect.InvocationTargetException
    at com.impetus.client.hbase.schemamanager.HBaseSchemaManager.initiateClient(HBaseSchemaManager.java:547)
    at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.exportSchema(AbstractSchemaManager.java:112)
    at com.impetus.client.hbase.schemamanager.HBaseSchemaManager.exportSchema(HBaseSchemaManager.java:116)
    at com.impetus.kundera.configure.SchemaConfiguration.configure(SchemaConfiguration.java:188)
    at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:48)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:408)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configure(EntityManagerFactoryImpl.java:161)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:135)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:85)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
    at com.xxx.hbase.kundera.KunderaExample.main(KunderaExample.java:16)

**Comment by pragalbhgarg** [comment]
Hi @gdoubleu,

Please share your `persistence.xml` so that we can look into your issue. Are you setting any external client properties ? Please also check that HBase is up & running and zookeeper is listening to its port.

-PG

**Comment by gdoubleu** [comment]
Ok, so I got rid of the HBase error, not sure what went wrong as jps showed both required services were up (HMaster and HRegionServer). 

I now get an "Entity Object is invalid" error, trace is at the end of this message. Also below is the PU I used, as well as the persistance model of an HBase table. 

I can't see any difference with the source code I am seeing in the kundera-hbase-v2 code. 

# 

This is my PU: 

```
<persistence-unit name="hdp_hbase_pu">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>com.xyz.hbase.kundera.Book</class>
    <class>com.xyz.hbase.kundera.Alert</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>
    <properties>
        <property name="kundera.nodes" value="localhost" />
        <property name="kundera.port" value="60000" />
        <property name="kundera.keyspace" value="HBaseNew"/>
        <property name="kundera.dialect" value="hbase" />
        <property name="kundera.client.lookup.class" value="com.impetus.client.hbase.HBaseClientFactory" />
        <!-- <property name="kundera.ddl.auto.prepare" value="create" /> -->
        <property name="kundera.client.property" value="kundera-hbase.properties" />
    </properties>
</persistence-unit>
```

# 

This is how the head of the Book class looks like: 

@Entity
@Table(name = "books", schema = "HBaseNew@hdp_hbase_pu")

# public class Book { ..} 

"Exception in thread "main" com.impetus.kundera.KunderaException: java.lang.IllegalArgumentException: Entity object is invalid, operation failed. Please check previous log message for details
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)
    at com.xyz.hbase.kundera.KunderaExample.main(KunderaExample.java:19)
Caused by: java.lang.IllegalArgumentException: Entity object is invalid, operation failed. Please check previous log message for details
    at com.impetus.kundera.validation.rules.NullOrInvalidEntityRule.validate(NullOrInvalidEntityRule.java:52)
    at com.impetus.kundera.graph.GraphGenerator.generate(GraphGenerator.java:125)
    at com.impetus.kundera.graph.GraphGenerator.generateGraph(GraphGenerator.java:78)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:130)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)"

**Comment by chhavigangwal** [comment]
@gdoubleu 

Do you have an @Id annotated field in each of your entities ? 

Chhavi

**Comment by gdoubleu** [comment]
Hi Chhavi,

Yes the @Id are there.

In fact, thanks for pointing this out since its seems you've added a
@Column under the @Id in the test cases for the v2.

However this did not fix my issues :(

**Comment by chhavigangwal** [comment]
Can you please share the entire entity definition and also the class where you are calling the em.persist() method?

-Chhavi

**Comment by gdoubleu** [comment]
Hi,

I was finally able to get a HBase abstraction to work with Kundera – but
only on my sandbox.

What I have found is kundera-hbase-v2 requires Java 7
(java.lang.UnsupportedClassVersionError: javax/persistence/Persistence :
Unsupported major.minor version 51.0). I could use a hbase client with a
version of 0.98 max (higher requires also Java 7.

Any chance Kundera can be made compatible with Java 6?

G

**Comment by chhavigangwal** [comment]
@gdoubleu 

kundera-hbase-v2 supports Hbase version 1.0 which is not compatible with JDK 6. For more information check the following link : http://hbase.apache.org/book.html#java.

Chhavi

**Comment by chhavigangwal** [comment]
Closing with Kundera 3.1 release
