### ISSUE TITLE
when does kundera support hadoop version  2.6.0 

### ISSUE THREAD

**Issue by geosmart** [Impetus/kundera#773]
i want to know when does kundera support hadoop version  2.6.0 ？  

the latest kundera 3.0 is beased on hadoop 2.2.0(by 2013)

many new api about yarn come out since hadoop 2.2.0

**Comment by karthikprasad13** [comment]
@geosmart 

Please let us know which module of Kundera are you talking about? If it is related to kundera-spark, it uses hadoop 2.7.0 client.

-Karthik

**Comment by chhavigangwal** [comment]
@geosmart 

I can see that you are starting to use Hbase using Kundera.I would suggest you to use kundera-hbase-v2 which has support fro HBase 1.0 and uses hadoop 2.5.1 as an implicit dependency.

Chhavi

**Comment by geosmart** [comment]
thanks for reply  
but the [maven reposiroty](https://oss.sonatype.org/content/repositories/releases/com/impetus/client/) has no   kundera-hbase-v2, just only kundera-hbase,and latest version is 2.9  
here is  the pom property：  

``` xml
<properties>
<hadoop.version>1.1.1</hadoop.version>
<hbase.version>0.94.3</hbase.version>
</properties>
```

**Comment by chhavigangwal** [comment]
Can you try using this pom.xml and see ?

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>me.demo.hadoop</groupId>
    <artifactId>hbase.kundera</artifactId>
    <version>1.0</version>
    <name>hbase.kundera</name>
    <packaging>jar</packaging>

    <developers>
        <developer>
            <name>geosmart</name>
            <email>geosmart@foxmail.com</email>
            <timezone>UTC+8</timezone>
        </developer>
    </developers>

    <description>hbase.kundera示例</description>

    <!-- 项目属性 -->
    <properties>
        <jdk.version>1.7</jdk.version>
        <spring.version>3.1.2.RELEASE</spring.version>

        <hadoop.version>2.2.0</hadoop.version>
        <kundera-hbase.version>3.0</kundera-hbase.version>

        <commons-lang3.version>3.1</commons-lang3.version>
        <commons-io.version>2.4</commons-io.version>
        <slf4j.version>1.6.6</slf4j.version>
        <log4j.version>1.2.17</log4j.version>
        <junit.version>4.11</junit.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <repositories>
        <repository>
            <name>springsource</name>
            <id>maven2-springsource</id>
            <url>http://repo.springsource.org/release/</url>
        </repository>

        <repository>
            <id>sonatype-nexus-staging</id>
            <name>Nexus Release Repository</name>
            <url>http://repo1.maven.org/maven2/</url>
        </repository>

        <repository>
            <id>sonatype oss nexus repositories</id>
            <url>https://oss.sonatype.org/content/repositories/releases/</url>
        </repository>
    </repositories>

    <dependencies>
        <!-- Spring dependencies -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-support</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-orm</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <version>${spring.version}</version>
        </dependency>

        <dependency>
            <groupId>com.impetus.kundera.client</groupId>
            <artifactId>kundera-hbase-v2</artifactId>
            <version>${kundera-hbase.version}</version>
        </dependency>



        <!-- LOGGING begin -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <!-- LOGGING end -->

        <!-- TEST begin -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <finalName>hbase.kundera</finalName>
        <plugins>
            <!-- compiler插件, 设定JDK版本 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.0</version>
                <configuration>
                    <source>${jdk.version}</source>
                    <target>${jdk.version}</target>
                    <showWarnings>true</showWarnings>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

            <!-- test插件, 设置內存/ClassLoader -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.12.4</version>
                <configuration>
                    <argLine>-Xmx256M</argLine>
                </configuration>
            </plugin>

            <!-- cobertura插件, 设置不需要计算覆盖率的类 -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>cobertura-maven-plugin</artifactId>
                <version>2.5.1</version>
                <configuration>
                    <instrumentation>
                        <excludes>
                            <!-- <exclude>**/entity/**/*.class</exclude> <exclude>**/*Controller.class</exclude> 
                                <exclude>*.xls</exclude> -->
                        </excludes>
                    </instrumentation>
                </configuration>
            </plugin>

            <!-- eclipse插件, 设定wtp版本并添加springIDE nature -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-eclipse-plugin</artifactId>
                <version>2.9</version>
                <configuration>
                    <wtpversion>2.0</wtpversion>
                    <additionalProjectnatures>
                        <projectnature>org.springframework.ide.eclipse.core.springnature</projectnature>
                    </additionalProjectnatures>
                </configuration>
            </plugin>

            <!-- resource插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <nonFilteredFileExtensions>
                        <!-- 过滤流程定义资源文件 -->
                        <nonFilteredFileExtension>zip</nonFilteredFileExtension>
                        <nonFilteredFileExtension>rar</nonFilteredFileExtension>
                        <nonFilteredFileExtension>bar</nonFilteredFileExtension>
                        <nonFilteredFileExtension>png</nonFilteredFileExtension>
                        <nonFilteredFileExtension>activiti</nonFilteredFileExtension>
                        <nonFilteredFileExtension>bpmn</nonFilteredFileExtension>
                        <nonFilteredFileExtension>xls</nonFilteredFileExtension>
                        <nonFilteredFileExtension>xsd</nonFilteredFileExtension>
                        <nonFilteredFileExtension>doc</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>


            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.7</version>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <!-- 开发环境 -->
        <profile>
            <id>dev</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                        <filtering>true</filtering>
                        <includes>
                            <include>**/*.xml</include>
                            <include>**/*.xls</include>
                            <include>**/*.rar</include>
                            <include>**/*.xsd</include>
                            <include>**/*.properties</include>
                            <include>**/*.html</include>
                        </includes>
                    </resource>
                    <resource>
                        <directory>src/main/java</directory>
                        <includes>
                            <include>**/*.xml</include>
                        </includes>
                    </resource>
                </resources>
            </build>
        </profile>
    </profiles>
</project>
```

**Comment by geosmart** [comment]
i have try to use kundera-hbase-v2 ,
but just as i described in the [google group of kundera discuss](https://groups.google.com/forum/#!topic/kundera-discuss/NCEtDyetvR4)
the exception  always come out ,I'm  confused about how  the JPA load  and  don't know why i can not pass the testCase,

``` java
Caused by: java.lang.ClassNotFoundException: com.impetus.kundera.KunderaPersistence
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at org.springframework.util.ClassUtils.forName(ClassUtils.java:258)
    at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:291)
```

if I can't  solve this problem at last , I have to extract a baseDao from _springdata for  hadoop_

**Comment by devender-yadav** [comment]
@geosmart 

Are you able to solve the problem?

**Comment by geosmart** [comment]
i do not solve the problem,so i have to  implement a  orm with spring data for hadoop and jackson objectMapper,you can have a look at the [hbase.orm](https://github.com/geosmart/me.demo.hadoop/tree/master/hbase.orm)
