### ISSUE TITLE
Kundera Cassandra sequence table created but queried with wrong column names

### ISSUE THREAD

**Issue by ocheja** [Impetus/kundera#777]
Kundera auto generates a unique value for a field when annotated with <pre> <code type="java">@GeneratedValue(GenerationType.TABLE)</code></pre>
I can tell that kundera maintains a single column family for this with the different rows representing sequence for calling entities. However, this is not working as expected because the key column created has a column name "key" while kundera queries with 'sequence_name'. 
As a fix, I have altered the table "kundera_sequences" and changed the key column name to "sequence_name".

<pre><code> ERROR c.i.c.cassandra.CassandraClientBase - Error while executing query Update "kundera_sequences" set "sequence_value" = "sequence_value" + 1 where "sequence_name" = 'usertest'
 ERROR c.i.c.cassandra.CassandraIdGenerator - Error while using keyspace. Caused by: .
com.impetus.kundera.KunderaException: InvalidRequestException(why:Unknown key identifier sequence_name)
    at com.impetus.client.cassandra.CassandraClientBase.execute(CassandraClientBase.java:2577) ~[CassandraClientBase.class:na]
    at com.impetus.client.cassandra.CassandraIdGenerator.generate(CassandraIdGenerator.java:108) ~[CassandraIdGenerator.class:na]
    at com.impetus.kundera.persistence.IdGenerator.onTableGenerator(IdGenerator.java:208) [IdGenerator.class:na]
    at com.impetus.kundera.persistence.IdGenerator.generateId(IdGenerator.java:77) [IdGenerator.class:na]
    at com.impetus.kundera.persistence.IdGenerator.generateAndSetId(IdGenerator.java:58) [IdGenerator.class:na]
    at com.impetus.kundera.graph.GraphGenerator.onPreChecks(GraphGenerator.java:229) [GraphGenerator.class:na]
    at com.impetus.kundera.graph.GraphGenerator.generate(GraphGenerator.java:127) [GraphGenerator.class:na]
    at com.impetus.kundera.graph.GraphGenerator.generateGraph(GraphGenerator.java:78) [GraphGenerator.class:na]
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:130) [PersistenceDelegator.class:na]
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174) [EntityManagerImpl.class:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
    at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:344) [ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.class:4.1.4.RELEASE]
    at com.sun.proxy.$Proxy43.persist(Unknown Source) [na:na]</code></pre>

**Comment by amit-kr** [comment]
@genteel 

This happens when runnning it with CQL2. 
Try running it with CQL3 by setting property at emf or em level. Following is the [wiki](https://github.com/impetus-opensource/Kundera/wiki/Primary-Key-Auto-generation) and [test case](https://github.com/impetus-opensource/Kundera/blob/4ab46233e39b87c5516e0f870dd581b79eaac265/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/esindexer/PersonCassandraESIndexerTest.java#L125) link to set CQL3.

-Amit

**Comment by ocheja** [comment]
@amit-kr  I'm using CQL3 not CQL2. And I have it set this way:

<pre><code> @PersistenceContext(unitName = "cassandra-pu", type = PersistenceContextType.EXTENDED)
    public void setEntityManager(EntityManager entityManager) {
        
        Map<String, Client> clients = (Map<String, Client>) entityManager.getDelegate();
        Client client = clients.get("cassandra-pu");
        ((CassandraClientBase) client).setCqlVersion("3.0.0");
        this.entityManager = entityManager;
    } </code></pre>

**Comment by karthikprasad13** [comment]
@genteel 

You are setting CQL version at EntityManager level but your tables are being created when you create EntitymanagerFactory which is by default using CQL2. Please try to set CQL version before creating tables i.e. while creating EntityManagerFactory (as suggested by @amit-kr ).

```
Map propertyMap = new HashMap();
propertyMap.put(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_3_0);
EntityManagerFactory emf = Persistence.createEntityManagerFactory("cassandra-pu",propertyMap);
```

-Karthik

**Comment by chhavigangwal** [comment]
@genteel 

Any update ?

Chhavi

**Comment by ocheja** [comment]
@chhavigangwal I've moved away from using Cassandra after a benchmark with other NoSQL databases wasn't impressive. In fact, MySQL database had better performance than Cassandra; Mongo was light years ahead of both. However, @karthikprasad13's comment spots a good temporary fix on this issue.

**Comment by chhavigangwal** [comment]
Closing with Kundera 3.1 release
