### ISSUE TITLE
Kundera composite keys with find method‏ 

### ISSUE THREAD

**Issue by ansarrafique** [Impetus/kundera#797]
I am surprised to see that in order to get the result back from the Cassandra using Kundera, we need to provide both the partition key as well as the clustering key. This is bit surprising because I am expecting that only the partition key needs to be present. Please have a look at the entity below

@Embeddable
public class StudentKey {
    @Column
    private String firstname;
    @Column
    private String id;
}
@Entity
public class Student {
    @EmbeddedId
    private StudentKey key;
    @Column
    private String lastname;  
}

StudentKey key = new StudentKey();
key.setId("123");
key.setFirstname("abc");

Student s =new Student();
s.setKey(key);
s.setLastname("def");

em.persist(s);

StudentKey searchKey = new StudentKey();
searchKey.setFirstName("abc")
em.find(Student.Class, searchKey)

In my case, the partition key is the firstname, whereas the clustering key is id. I am getting an exception 

11:33:55.947 [main] ERROR c.i.c.cassandra.CassandraClientBase - Error while executing query SELECT \* FROM "Student" WHERE "firstname" = 'Ansar' AND "id" = null
11:33:55.955 [main] ERROR c.i.c.cassandra.CassandraClientBase - Error during executing query SELECT \* FROM "Student" WHERE "firstname" = 'Ansar' AND "id" = null, Caused by: {} .
com.impetus.kundera.KunderaException: InvalidRequestException(why:Invalid null clustering key part id)
    at com.impetus.client.cassandra.CassandraClientBase.execute(CassandraClientBase.java:2603) [kundera-cassandra-3.1.jar:na]
    at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:2053) [kundera-cassandra-3.1.jar:na]
    at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2277) [kundera-cassandra-3.1.jar:na]
    at com.impetus.client.cassandra.CassandraClientBase.executeSelectQuery(CassandraClientBase.java:926) [kundera-cassandra-3.1.jar:na]
    at com.impetus.client.cassandra.thrift.ThriftClient.executeQuery(ThriftClient.java:1062) [kundera-cassandra-3.1.jar:na]
    at com.impetus.client.cassandra.CassandraClientBase$CQLClient.find(CassandraClientBase.java:2418) [kundera-cassandra-3.1.jar:na]
    at com.impetus.client.cassandra.CassandraClientBase.populate(CassandraClientBase.java:787) [kundera-cassandra-3.1.jar:na]
    at com.impetus.client.cassandra.CassandraClientBase.find(CassandraClientBase.java:752) [kundera-cassandra-3.1.jar:na]
    at com.impetus.client.cassandra.CassandraClientBase.find(CassandraClientBase.java:686) [kundera-cassandra-3.1.jar:na]
    at com.impetus.client.cassandra.thrift.ThriftClient.find(ThriftClient.java:350) [kundera-cassandra-3.1.jar:na]
    at com.impetus.kundera.persistence.AbstractEntityReader.findById(AbstractEntityReader.java:81) [kundera-core-3.1.jar:na]
    at com.impetus.client.cassandra.query.CassandraEntityReader.findById(CassandraEntityReader.java:93) [kundera-cassandra-3.1.jar:na]
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFind(ManagedState.java:137) [kundera-core-3.1.jar:na]
    at com.impetus.kundera.graph.Node.find(Node.java:500) [kundera-core-3.1.jar:na]
    at com.impetus.kundera.persistence.PersistenceDelegator.find(PersistenceDelegator.java:225) [kundera-core-3.1.jar:na]
    at com.impetus.kundera.persistence.PersistenceDelegator.findById(PersistenceDelegator.java:174) [kundera-core-3.1.jar:na]
    at com.impetus.kundera.persistence.EntityManagerImpl.find(EntityManagerImpl.java:263) [kundera-core-3.1.jar:na]
    at test.kunderasecondaryindex.App.main(App.java:46) [classes/:na]

I verified it using Cassandra CQL and it works fine without specifying clustering key.

Another question is: how can we use @GeneratedValue(strategy=GenerationType.AUTO) in the case of composite key. For example, in my case, I want the id, which is the part of the key in the StudentKey class, to be auto generated. I can use @GeneratedValue(strategy=GenerationType.AUTO) if I don't have a composite key, but other-way around it doesn't work.

**Comment by ansarrafique** [comment]
Sorry, my mistake, the problem has been fixed.
