### ISSUE TITLE
Update with MongoDB

### ISSUE THREAD

**Issue by ansarrafique** [Impetus/kundera#801]
I am trying to update an entity by setting new values using Kundera platform with MongoDB. However, I am getting a duplicate key exception. The same code works with Cassandra. 

What is the safest way to update an entity with Kundera? Right now I am calling persist(entity) method and assume that it works as upsert(), the assumption doesn't hold with MongoDB, but does with Cassandra. Can you please tell me how to update it with MongoDB?

**Comment by ansarrafique** [comment]
Oct 29, 2015 7:48:54 PM com.leuven.distrinet.lmaas.dmmiddleware.damiddleware.DataAccessService store
INFO: document is not inserted in lmaas.RLog collection. Caused By:
com.impetus.kundera.KunderaException: com.impetus.kundera.KunderaException: document is not inserted in lmaas.RLog collection. Caused By:
	at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)
	at com.leuven.distrinet.lmaas.dmmiddleware.damiddleware.DataAccessService.store(DataAccessService.java:53)
	at com.leuven.distrinet.lmaas.dmmiddleware.services.DataManagementService.persist(DataManagementService.java:83)
	at com.leuven.distrinet.lmaas.client.controller.LogDataStorage.doGet(LogDataStorage.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:534)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.impetus.kundera.KunderaException: document is not inserted in lmaas.RLog collection. Caused By:
	at com.impetus.client.mongodb.MongoDBClient.onFlushCollection(MongoDBClient.java:1095)
	at com.impetus.client.mongodb.MongoDBClient.onPersist(MongoDBClient.java:834)
	at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:114)
	at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:197)
	at com.impetus.kundera.graph.Node.flush(Node.java:531)
	at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:403)
	at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:145)
	at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)
	... 27 more
Caused by: com.mongodb.MongoException$DuplicateKey: { "serverUsed" : "localhost:27017" , "err" : "E11000 duplicate key error index: lmaas.RLog.$_id_  dup key: { : 11 }" , "code" : 11000 , "n" : 0 , "connectionId" : 189 , "ok" : 1.0}
	at com.mongodb.CommandResult.getWriteException(CommandResult.java:88)
	at com.mongodb.CommandResult.getException(CommandResult.java:79)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:140)
	at com.mongodb.DBTCPConnector._checkWriteError(DBTCPConnector.java:135)
	at com.mongodb.DBTCPConnector.access$000(DBTCPConnector.java:40)
	at com.mongodb.DBTCPConnector$1.execute(DBTCPConnector.java:186)
	at com.mongodb.DBTCPConnector$1.execute(DBTCPConnector.java:181)
	at com.mongodb.DBPort.doOperation(DBPort.java:187)
	at com.mongodb.DBTCPConnector.doOperation(DBTCPConnector.java:208)
	at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:181)
	at com.mongodb.DBCollectionImpl.insertWithWriteProtocol(DBCollectionImpl.java:565)
	at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:195)
	at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:167)
	at com.mongodb.DBCollection.insert(DBCollection.java:93)
	at com.impetus.client.mongodb.MongoDBClient.onFlushCollection(MongoDBClient.java:1091)
	... 34 more

**Comment by devender-yadav** [comment]
@ansarrafique 

For updating entity object with Kundera-MongoDB, you need to call  `em.merge(object)` (_it will perform upsert operation_)

`em.insert()` performs insert operation with **[ACKNOWLEDGED](https://docs.mongodb.org/manual/core/write-concern/#acknowledged) WriteConcern**. So it will catch duplicate primary key error.

 Also, you can change the value of write concern (for example, UNACKNOWLEDGED so that no errors are shown for duplicate primary key )for a particular EntityManager instance using property:
`em.setProperty(MongoDBClientProperties.WRITE_CONCERN, WriteConcern.UNACKNOWLEDGED);`

Hope that helps.
-Devender

**Comment by ansarrafique** [comment]
Why the em.insert() for the MongoDB performs differently than Cassandra in the case of  update operation? Imagine, in the case of polyglot persistence, calling em.insert() for the update operation would end up in operation failure.

em.merge(object) implementation works for both Cassandra and MongoDB? What is advisable to use to update the data? is it em.insert() or em.merge()?

Also, can you please elaborate more on the writeconcern properties for the MongoDB? Why these properties (ACKNOWLEDGED and UNACKNOWLEDGED ) have an impact on the primary key? It either say wait for the operation to be completed (ACKNOWLEDGED ) or do not wait for operation to be completed (UNACKNOWLEDGED) . In addition, I think the default writeconcern property for Kundera in the case of MongoDB is UNACKNOWLEDGED not ACKNOWLEDGED.

**Comment by devender-yadav** [comment]
@ansarrafique 

Default Write Concern in MongoDB is **ACKNOWLEDGED**. Refer [this](https://docs.mongodb.org/manual/core/write-concern/#default-write-concern).

_Impact of primary key due  to WriteConcern Property._

According to MongoDB's documentation - "UNACKNOWLEDGED is similar to errors ignored; however, drivers will attempt to receive and handle network errors when possible and ACKNOWLEDGED write concern allows clients to catch network, **duplicate key**, and other errors.". Find more on WriteConcern [here](https://docs.mongodb.org/manual/core/write-concern/).

Now, with ACKNOWLEDGED WriteConcern when you insert a document in MongoDB with a primary that is already present in that collection it will show duplicate primary key error. As u mentioned, it will wait for the operation to be completed. MongoDB will not allow adding a document with the same primary key. So it will give you a duplicate Key error. In the case of UNACKNOWLEDGED, this error is ignored and obviously, the document will not be added as there is a duplicate primary key error. But no error is shown to the client. 

For updating a document in MongoDB with Kundera `em.merge()` should be used.​

**Comment by ansarrafique** [comment]
Sure, the default writeconcern property for the MongoDB  is ACKNOWLEDGED, whereas in Kundera it was set as UNACKNOWLEDGED (I verified this with Kundera 2.0.6 version). I am not sure if it is still set as UNACKNOWLEDGED. 

In the case of UNACKNOWLEDGED with the MongoDB, I doubt that the duplicate key error message will be ignored rather it will still throw the exception. Please correct me if I am wrong.

For updating a document in both Cassandra and MongoDB, still em.merge() should be used or it is advisable only in the case of MongoDB? If so, which method should be used to update a record for polyglot persistence?

**Comment by devender-yadav** [comment]
@ansarrafique 

Kundera 2.0.6 is an older version. Current version is **3.1**  In newer version, default writeconcern property for the Kundera-MongoDB is ACKNOWLEDGED.

In the case of UNACKNOWLEDGED with the MongoDB, **No exception is thrown**.

MongoDB & Cassandra both have a different way to handle inserts.
 In case on MongoDB, it won't allow upsert while inserting in the database. So Kundera is following the philosophy of mongoDB. It performs insert using `em.persist()` and update/upsert using `em.merge()`

And in case of Cassandra, insert and update are kind of similar under the hood. So, using `em.persist()/em.merge()` give similar results.

Apart from the individual behavior of the databases, while dealing with polyglot persistence I think using `em.persist()` for insert and `em.merge()` for update/upsert will make more sense.

**Comment by ansarrafique** [comment]
Thanks for the clarification Devender and thanks for pointing out that the write concern property is set as  ACKNOWLEDGED in the latest version of Kundera.
