### ISSUE TITLE
Subclassed Embedded Objects Only Persist the Base Class Attributes

### ISSUE THREAD

**Issue by saarelabronto** [Impetus/kundera#803]
Embedded subclasses are referenced by the base class. 

For concrete base classes this causes just the base class attributes to persist. 

For abstract base classes, persistence fails altogether because the base class cannot be instantiated, resulting in a NPE when attempting to dereference the non-existent base class instance.

When persisting embedded attributes, the type of the data should be inspected, not just the attribute type which may be a base class.

``` java
@Embeddable
@Table(name="myTable")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name="type_name")
abstract class Base {
  public Base() { }

  @Override
  @Column(name="type_name")
  public abstract String getTypeName();

  public abstract void setTypeName(String typeName);
}

@Embeddable
@Table(name="myTable")
@DiscriminatorValue(value="type_one")
public class TypeOne extends Base {
   protected String typeName;

   @Column("c1")
   public String c1;

   @Column("c2");
   public String c2;

   @Override
   @Column("type_name")
   public String getTypeName() { return typeName; }

   @Override
   public void setTypeName(String typeName) { this.typeName = typeName; }
}

@Entity
@Table(name="myTable" schema="mykeyspace@my_pu")
public class ContainingClass {
  @Id
  String id;

  @Column(name="timestamp")
  long timestamp;

  @Embedded
  Base data;
}
```

Results:

```
com.impetus.kundera.KunderaException: java.lang.NullPointerException
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)
    at HBaseCRUDTest.testCeateRead(HBaseCRUDTest.java:97)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.NullPointerException
    at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
    at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
    at java.lang.reflect.Field.get(Field.java:393)
    at com.impetus.kundera.property.PropertyAccessorHelper.getObject(PropertyAccessorHelper.java:140)
    at com.impetus.client.hbase.admin.HBaseDataHandler.preparePersistentData(HBaseDataHandler.java:1300)
    at com.impetus.client.hbase.admin.HBaseDataHandler.writeData(HBaseDataHandler.java:371)
    at com.impetus.client.hbase.HBaseClient.onPersist(HBaseClient.java:535)
    at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:114)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:197)
    at com.impetus.kundera.graph.Node.flush(Node.java:531)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:403)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:145)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)
```

**Comment by devender-yadav** [comment]
@saarelabronto 

We are looking into the issue. Please share your sample project or valid  Entity classes if possible at kundera@impetus.co.in

-Devender

**Comment by karthikprasad13** [comment]
@saarelabronto 

Any Updates?

-Karthik
