### ISSUE TITLE
Error while finding relations for column family 

### ISSUE THREAD

**Issue by AdityaSureka** [Impetus/kundera#809]
Trying to use MySQL + Cassandra Polyglot Persistence 
The issue is when I use a ElementCollection such as List or ArrayList in FileModel class else its fine
Error as follows :-

```
org.apache.cassandra.thrift.InvalidRequestException: null
    at org.apache.cassandra.thrift.Cassandra$get_indexed_slices_result$get_indexed_slices_resultStandardScheme.read(Cassandra.java:20455) ~[cassandra-thrift-2.2.2.jar:2.2.2]
    at org.apache.cassandra.thrift.Cassandra$get_indexed_slices_result$get_indexed_slices_resultStandardScheme.read(Cassandra.java:20422) ~[cassandra-thrift-2.2.2.jar:2.2.2]
    at org.apache.cassandra.thrift.Cassandra$get_indexed_slices_result.read(Cassandra.java:20348) ~[cassandra-thrift-2.2.2.jar:2.2.2]
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78) ~[libthrift-0.9.2.jar:0.9.2]
    at org.apache.cassandra.thrift.Cassandra$Client.recv_get_indexed_slices(Cassandra.java:881) ~[cassandra-thrift-2.2.2.jar:2.2.2]
    at org.apache.cassandra.thrift.Cassandra$Client.get_indexed_slices(Cassandra.java:865) ~[cassandra-thrift-2.2.2.jar:2.2.2]
    at com.impetus.client.cassandra.thrift.ThriftClient.findByRelation(ThriftClient.java:739) ~[kundera-cassandra-3.2.jar:na]
    at com.impetus.kundera.persistence.AbstractEntityReader.fetchRelations(AbstractEntityReader.java:501) [kundera-core-3.2.jar:na]
    at com.impetus.kundera.persistence.AbstractEntityReader.onRelation(AbstractEntityReader.java:220) [kundera-core-3.2.jar:na]
    at com.impetus.kundera.persistence.AbstractEntityReader.onRelation(AbstractEntityReader.java:186) [kundera-core-3.2.jar:na]
    at com.impetus.kundera.persistence.AbstractEntityReader.handleAssociation(AbstractEntityReader.java:126) [kundera-core-3.2.jar:na]
    at com.impetus.kundera.persistence.AbstractEntityReader.recursivelyFindEntities(AbstractEntityReader.java:521) [kundera-core-3.2.jar:na]
    at com.impetus.kundera.proxy.collection.AbstractProxyBase.eagerlyLoadDataCollection(AbstractProxyBase.java:117) [kundera-core-3.2.jar:na]
    at com.impetus.kundera.proxy.collection.AbstractProxyCollection.isEmpty(AbstractProxyCollection.java:108) [kundera-core-3.2.jar:na]
    at com.impetus.kundera.proxy.collection.ProxySet.isEmpty(ProxySet.java:76) [kundera-core-3.2.jar:na]
    at com.FileDao.save(FileDao.java:42) [classes/:na]
com.impetus.kundera.KunderaException: InvalidRequestException(why:[757365725f6964]=[32] failed name validation (Not enough bytes to read value of component 0))
    at com.impetus.client.cassandra.thrift.ThriftClient.findByRelation(ThriftClient.java:752)
    at com.impetus.kundera.persistence.AbstractEntityReader.fetchRelations(AbstractEntityReader.java:501)
    at com.impetus.kundera.persistence.AbstractEntityReader.onRelation(AbstractEntityReader.java:220)
    at com.impetus.kundera.persistence.AbstractEntityReader.onRelation(AbstractEntityReader.java:186)
    at com.impetus.kundera.persistence.AbstractEntityReader.handleAssociation(AbstractEntityReader.java:126)
    at com.impetus.kundera.persistence.AbstractEntityReader.recursivelyFindEntities(AbstractEntityReader.java:521)
    at com.impetus.kundera.proxy.collection.AbstractProxyBase.eagerlyLoadDataCollection(AbstractProxyBase.java:117)
    at com.impetus.kundera.proxy.collection.AbstractProxyCollection.isEmpty(AbstractProxyCollection.java:108)
    at com.impetus.kundera.proxy.collection.ProxySet.isEmpty(ProxySet.java:76)
    at com.FileDao.save(FileDao.java:42) [classes/:na]

```

Code as follow :- 
DAO Function :- 

```
    public void save(String username,FileModel uploadFile) {
        User user=new User();
        propertyMap.put(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_3_0);
        entityManagerFactory = Persistence.createEntityManagerFactory("mysql,cassandra",propertyMap);
        entityManager = entityManagerFactory.createEntityManager();
        Query q = entityManager.createQuery("select u from User u where u.username =:username",User.class);//where u.username = admin");
        q.setParameter("username", username);
        List<User> users = q.getResultList();
        user= users.get(0);
        Set<FileModel> fm=user.getFiles();
        if(fm==null||fm.isEmpty())
        {
            fm= new HashSet<FileModel>();
        }
        fm.add(uploadFile);
        user.setFiles(fm);
        entityManager.persist(user);
        entityManager.close();
    }
```

FileModel Class :- 

```
@Entity
@Table(name="files", schema="test@cassandra")
public class FileModel {

    @Id
    @Column(name = "file_id")
    private String file_id=UUID.randomUUID().toString();;

    @Column(name = "image_location")
    private String image_location;

    @ElementCollection
    @Column(name = "permission_list")
    private List<String> permission_list;  

    }
//Getter setter and constructor 
}
```

**Comment by karthikprasad13** [comment]
@AdityaSureka 

How did you create the tables? Did you use `create` property of Kundera to automatically create them or manually?

-Karthik

**Comment by AdityaSureka** [comment]
I used the "create" property

**Comment by devender-yadav** [comment]
@AdityaSureka 

Can you please share both `persistence.xml` files & `User` entity so that we can reproduce the issue at our end.

-Dev

**Comment by AdityaSureka** [comment]
You can close this one .

**Comment by devender-yadav** [comment]
@AdityaSureka 

Are you able to resolve the issue?

-Dev

**Comment by AdityaSureka** [comment]
Yes . Re installed cassandra 3.0.1 and it was fine
