### ISSUE TITLE
com.impetus.kundera.KunderaException: All hosts are down. please check servers manully.

### ISSUE THREAD

**Issue by vinitsharma87** [Impetus/kundera#817]
I am having a web application built with Play!  framework 2.4 and I am using Kundera as an ORM tool for connecting to Cassandra database. Cassandra is installed on my local system. I have downloaded this application from Git itself for an example of CRUD operations with Cassandra and Kundera. I have not been able to connect to the Cassandra database from my application. After making several changes in the persistence.xml file, lastly I am getting  the below error in my application:

com.impetus.kundera.KunderaException: All hosts are down. please check servers manully.
    at com.impetus.client.cassandra.thrift.ThriftClientFactory.getPoolUsingPolicy(ThriftClientFactory.java:215) ~[kundera-cassandra-3.2.jar:na]
    at com.impetus.client.cassandra.thrift.ThriftClientFactory.instantiateClient(ThriftClientFactory.java:200) ~[kundera-cassandra-3.2.jar:na]
    at com.impetus.kundera.loader.GenericClientFactory.getClientInstance(GenericClientFactory.java:259) ~[kundera-core-3.2.jar:na]
    at com.impetus.kundera.persistence.EntityManagerImpl.discoverClient(EntityManagerImpl.java:990) ~[kundera-core-3.2.jar:na]
    at com.impetus.kundera.persistence.EntityManagerImpl.<init>(EntityManagerImpl.java:142) ~[kundera-core-3.2.jar:na]
[error] m.p.EmployeeProcessImpl$ - All hosts are down. please check servers manully.

What could be the wrong thing in my application ? Please help me in connecting Cassandra db from my application. I am using Cassandra 2.2 version.

**Comment by devender-yadav** [comment]
@vinitsharma87 

You raised a related issue with a different exception. Are you able to solve this "All hosts are down" issue? 

-Dev

**Comment by vinitsharma87** [comment]
I face a strange problem, wheneve I write EmployeeExample in persistence.xml, I get All hosts are down error, while when I change it to employeeexample, I get some other error stating that Kundera cannot find the entity Employee. What could be the problem ?

**Comment by vinitsharma87** [comment]
@devender-yadav  as of now its showing a different error now. I guess my database may have got connected. It shows the below error when I try to open the listing page of Employees. The error is as under:

com.impetus.kundera.query.QueryHandlerException: No entity found by the name: Employee
    at com.impetus.kundera.query.KunderaQuery.initEntityClass(KunderaQuery.java:608) ~[kundera-core-3.2.jar:na]
    at com.impetus.kundera.query.KunderaQuery.postParsingInit(KunderaQuery.java:540) ~[kundera-core-3.2.jar:na]
    at com.impetus.kundera.query.QueryResolver.getQueryImplementation(QueryResolver.java:86) ~[kundera-core-3.2.jar:na]
    at com.impetus.kundera.persistence.PersistenceDelegator.getQueryInstance(PersistenceDelegator.java:560) ~[kundera-core-3.2.jar:na]
    at com.impetus.kundera.persistence.PersistenceDelegator.createQuery(PersistenceDelegator.java:521) ~[kundera-core-3.2.jar:na]
[error] m.p.EmployeeProcessImpl$ - No entity found by the name: Employee

Any reason you know for this error generation ? What things I need to check VERSION SPECIFIC so as to avoid any conflicts getting generated because of the version related errors ?

**Comment by karthikprasad13** [comment]
As discussed, problem was with the configuration. Closing as not an issue.
