### ISSUE TITLE
Getting Started Kundera  HBase ORM - Exception org.apache.hadoop.hbase.TableNotFoundException 

### ISSUE THREAD

**Issue by jainman** [Impetus/kundera#82]
I am facing  following issues-

Issue 1. Exception throwen

org.apache.hadoop.hbase.TableNotFoundException: Cannot find row in .META. for table: husers, row=husers,,99999999999999
    at org.apache.hadoop.hbase.client.MetaScanner.metaScan(MetaScanner.java:136)

Issue 2.  Following property is not accepted in my persistence unit

```
        <property name="kundera_ddl_auto_prepare" value="create-drop"/>
```

----- Full details about the problem ---

I am trying to use Kundra HBase ORM and followed the steps mentioned in Getting Started in 5 minutes

I have  hbase / hadoop  standalone cluster running remotely. It is working fine.  

hbase-site.xml

<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<configuration>
  <property>
    <name>hbase.rootdir</name>
    <value>hdfs://myhadoop.demo.edu:54310/hbase</value>
  </property>
  <property>
    <name>hbase.master</name>
    <value>myhadoop.demo.edu:52545</value>
  </property>
  <property>
    <name>dfs.replication</name>
    <value>1</value>
  </property>
  <property>
    <name>hbase.cluster.distributed</name>
    <value>true</value>
  </property>
  <property>
    <name>hbase.zookeeper.quorum</name>
    <value>myhadoop.demo.edu</value>
  </property>
  <property>
    <name>hbase.zookeeper.property.clientPort</name>
    <value>2181</value>
  </property>  
</configuration>

I am able to  connect to hbase remotely and create / add/ delete tables.

Now I am building an ORM layer  over hbase using kundera

I am using the test code in  

https://github.com/impetus-opensource/Kundera/wiki/Getting-Started-in-5-minutes

My persistance.xml  is

```
<persistence-unit name="testhbase">
    <provider>com.impetus.kundera.KunderaPersistence</provider>     
    <properties>            
        <property name="kundera.nodes" value="192.168.72.129"/>
        <property name="kundera.port" value="2181"/>
        <property name="kundera.keyspace" value="KunderaExamples" />
        <property name="kundera.dialect" value="hbase" />

        <property name="kundera.client.lookup.class" value="com.impetus.client.hbase.HBaseClientFactory" />
        <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider" />
        <property name="kundera.cache.config.resource" value="/ehcache-test.xml" />
        <property name="index_home_dir" value="/home/impadmin/lucene"/>                 
    </properties>       
</persistence-unit>
```

I am getting following exception.

org.apache.hadoop.hbase.TableNotFoundException: Cannot find row in .META. for table: husers, row=husers,,99999999999999
    at org.apache.hadoop.hbase.client.MetaScanner.metaScan(MetaScanner.java:136)
    at org.apache.hadoop.hbase.client.MetaScanner.metaScan(MetaScanner.java:95)
    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.prefetchRegionCache(HConnectionManager.java:649)
    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:703)
    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:594)
    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:559)
    at org.apache.hadoop.hbase.client.HTable.<init>(HTable.java:173)
    at org.apache.hadoop.hbase.client.HTableFactory.createHTableInterface(HTableFactory.java:36)
    at org.apache.hadoop.hbase.client.HTablePool.createHTable(HTablePool.java:133)
    at org.apache.hadoop.hbase.client.HTablePool.getTable(HTablePool.java:89)
    at com.impetus.client.hbase.admin.HBaseDataHandler.gethTable(HBaseDataHandler.java:443)
    at com.impetus.client.hbase.admin.HBaseDataHandler.writeData(HBaseDataHandler.java:247)
    at com.impetus.client.hbase.HBaseClient.onPersist(HBaseClient.java:301)
    at com.impetus.client.hbase.HBaseClient.persist(HBaseClient.java:250)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:153)
    at com.impetus.kundera.graph.Node.flush(Node.java:478)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:290)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:148)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:191)
    at com.emc.bda.hbase.jpa.KunderaExample.main(KunderaExample.java:20)
Exception in thread "main" java.lang.RuntimeException: org.apache.hadoop.hbase.TableNotFoundException: husers
    at org.apache.hadoop.hbase.client.HTableFactory.createHTableInterface(HTableFactory.java:38)
    at org.apache.hadoop.hbase.client.HTablePool.createHTable(HTablePool.java:133)
    at org.apache.hadoop.hbase.client.HTablePool.getTable(HTablePool.java:89)
    at com.impetus.client.hbase.admin.HBaseDataHandler.gethTable(HBaseDataHandler.java:443)
    at com.impetus.client.hbase.admin.HBaseDataHandler.writeData(HBaseDataHandler.java:247)
    at com.impetus.client.hbase.HBaseClient.onPersist(HBaseClient.java:301)
    at com.impetus.client.hbase.HBaseClient.persist(HBaseClient.java:250)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:153)
    at com.impetus.kundera.graph.Node.flush(Node.java:478)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:290)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:148)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:191)
    at com.emc.bda.hbase.jpa.KunderaExample.main(KunderaExample.java:20)
Caused by: org.apache.hadoop.hbase.TableNotFoundException: husers
    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:725)
    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:594)
    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:559)
    at org.apache.hadoop.hbase.client.HTable.<init>(HTable.java:173)
    at org.apache.hadoop.hbase.client.HTableFactory.createHTableInterface(HTableFactory.java:36)
    ... 12 more

**Comment by mevivs** [comment]
As per
" Exception in thread "main" java.lang.RuntimeException: org.apache.hadoop.hbase.TableNotFoundException: husers
at org.apache.hadoop.hbase.client.HTableFactory.createHTableInterface(HTableFactory.java:38) "

You need to create table & column family "husers". Or Alternatively you can specify,

<property name="kundera_ddl_auto_prepare" value="create" />

in your persistence.xml to auto create the schema. Make sure to remove for after first run to avoid removal of data.

-Vivek

**Comment by jainman** [comment]
I tried adding property in persistence.xml

Issue 2.  Following property is not accepted in my persistence unit

```
        <property name="kundera_ddl_auto_prepare" value="create-drop"/>
```

In this case it is not connecting to remote hbase server rather it is failing as it is trying to connect to localhost not remote server 192.168.72.129

**Comment by mevivs** [comment]
Please share your persistence.xml

**Comment by mevivs** [comment]
version of kundera, you are working with?

**Comment by mevivs** [comment]
Okay. i think i understand the issue now.

Please download:
https://github.com/downloads/impetus-opensource/Kundera-Examples/kundera-hbase-2.0.6.jar
and replace it with the one you contain. It was a post release fix. Or you can also download and build 2.0.6 manually, if wants.

-Vivek

**Comment by jainman** [comment]
I want to verify if kundera_ddl_auto_prepare is supported for HBase.
When I am setting this property - I am not able to connect to my remote hbase server and get following exception --
The Client is trying to connect to localhost while my  server is running at  192.168.72.129

```
        <property name="kundera.nodes" value="192.168.72.129"/>
        <property name="kundera.port" value="2181"/>
```

SLF4J: The requested version 1.5.8 by your slf4j binding is not compatible with [1.6]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
2012-07-03 18:50:42,890 [WARN ] [main] org.apache.hadoop.hbase.HBaseConfiguration  - instantiating HBaseConfiguration() is deprecated. Please use HBaseConfiguration#create() to construct a plain Configuration
2012-07-03 18:50:42,921 [WARN ] [main] org.apache.hadoop.hbase.HBaseConfiguration  - instantiating HBaseConfiguration() is deprecated. Please use HBaseConfiguration#create() to construct a plain Configuration
2012-07-03 18:50:44,062 [WARN ] [main-SendThread(localhost:2181)] org.apache.zookeeper.ClientCnxn  - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused: no further information
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1119)

**Comment by jainman** [comment]
I am using kundera-hbase-2.0.6.jar
    <dependencies>
        <dependency>
            <groupId>com.impetus.client</groupId>
            <artifactId>kundera-hbase</artifactId>
            <version>2.0.6</version>
        </dependency>
    </dependencies>

**Comment by mevivs** [comment]
Please download:
https://github.com/downloads/impetus-opensource/Kundera-Examples/kundera-hbase-2.0.6.jar

and replace it in your local maven repo and then try.

-Vivek

**Comment by jainman** [comment]
One more data point - when I don't use this property My application is able to connect remote server and I get following NoSuchColumnFamilyException:

This is fine as there is no table husers. The question is how following entity will map to hbase table

@Entity
@Table(name = "husers", schema = "KunderaExamples@testhbase")
public class HUser 
{
    @Id
    private String userId;

```
@Column(name="first_name")
private String firstName;

@Column(name="last_name")
private String lastName;

@Column(name="city")
private String city;    

public HUser()
{
}
```

....
}

SLF4J: The requested version 1.5.8 by your slf4j binding is not compatible with [1.6]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
2012-07-03 19:16:08,062 [WARN ] [main] org.apache.hadoop.hbase.HBaseConfiguration  - instantiating HBaseConfiguration() is deprecated. Please use HBaseConfiguration#create() to construct a plain Configuration
Exception in thread "main" javax.persistence.PersistenceException: Failed 1 action: NoSuchColumnFamilyException: 1 time, servers with issues: myhadoop.demo.edu:60020, 
    at com.impetus.client.hbase.HBaseClient.onPersist(HBaseClient.java:305)
    at com.impetus.client.hbase.HBaseClient.persist(HBaseClient.java:250)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:153)
    at com.impetus.kundera.graph.Node.flush(Node.java:478)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:290)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:148)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:191)
    at com.emc.bda.hbase.jpa.HbaseJpaPoc.main(HbaseJpaPoc.java:20)

**Comment by mevivs** [comment]
IF you do not wish to use "ddl_auto_create", it's fine. Then you need to manually crate "husers" table.

now coming to mapping,
it will create corresponding column families like "first_name" etc for "husers".

**Comment by jainman** [comment]
Well, I want to use ddl_auto_create but having problems. I described it above

**Comment by mevivs** [comment]
You can use it ofcourse!

Please download:
https://github.com/downloads/impetus-opensource/Kundera-Examples/kundera-hbase-2.0.6.jar

and replace it in your local maven repo and then try.

**Comment by jainman** [comment]
Great it is working. I am able to persist and retrieve entities from HBASE. Thank you for your help 

Somehow, I didn't change anything in my application. It just worked.

I am suspecting if some caching was done  due to which application was trying to connect to wrong server (localhost).

What I did, was run standalone application (without kundera ORM) to connect to remote server:port - which runs successfully

After that, I run ORM application, It also works successfully.

So, I am suspecting HBaseConfiguration is cached somewhere and it is reusing that - need to investigate further.

My Setup is --
Standalone HBase cluster in pseudo distributed mode (Ubuntu Linux 192.168.72.129:2181)
Remote application client on windows (Kundra ORM client / Hbase java client)

**Comment by mevivs** [comment]
Good. shall i close this now?

-Vivek

**Comment by jainman** [comment]
Yes, please

**Comment by mevivs** [comment]
closing, as discussed.
