### ISSUE TITLE
Unexpected extraneous bytes after list value

### ISSUE THREAD

**Issue by AdityaSureka** [Impetus/kundera#821]
```
INFO : com.impetus.client.cassandra.CassandraClientBase - Executing query SELECT * FROM "analysis" WHERE "user_id" = 'aditya' LIMIT 100  ALLOW FILTERING.
ERROR: com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase - Error while setting fieldcpu_usage value via CQL, Caused by: .
org.apache.cassandra.serializers.MarshalException: Unexpected extraneous bytes after list value
    at org.apache.cassandra.serializers.ListSerializer.deserializeForNativeProtocol(ListSerializer.java:104)
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator$ListTypeBuilder.decompose(CassandraDataTranslator.java:1267)
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator$ListTypeBuilder.access$4900(CassandraDataTranslator.java:1198)
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator.decompose(CassandraDataTranslator.java:534)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.setCollectionValue(CassandraDataHandlerBase.java:2508)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.setFieldValueViaCQL(CassandraDataHandlerBase.java:1504)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateViaThrift(CassandraDataHandlerBase.java:1163)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.onColumn(CassandraDataHandlerBase.java:1054)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateEntity(CassandraDataHandlerBase.java:653)
    at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2272)
    at com.impetus.client.cassandra.CassandraClientBase.executeSelectQuery(CassandraClientBase.java:926)
    at com.impetus.client.cassandra.thrift.ThriftClient.executeQuery(ThriftClient.java:1062)
    at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:146)
    at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:1377)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:200)
    at com.impetus.kundera.query.KunderaTypedQuery.getResultList(KunderaTypedQuery.java:250)
    at com.easytest.easytst.analysis.dao.AnalysisDao.analysis_user_list(AnalysisDao.java:117)
    at com.easytest.easytst.AnalysisController.add(AnalysisController.java:71)

ERROR: com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase - Eror while retrieving data, Caused by: .
javax.persistence.PersistenceException: org.apache.cassandra.serializers.MarshalException: Unexpected extraneous bytes after list value
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.setCollectionValue(CassandraDataHandlerBase.java:2526)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.setFieldValueViaCQL(CassandraDataHandlerBase.java:1504)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateViaThrift(CassandraDataHandlerBase.java:1163)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.onColumn(CassandraDataHandlerBase.java:1054)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateEntity(CassandraDataHandlerBase.java:653)
    at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2272)
    at com.impetus.client.cassandra.CassandraClientBase.executeSelectQuery(CassandraClientBase.java:926)
    at com.impetus.client.cassandra.thrift.ThriftClient.executeQuery(ThriftClient.java:1062)
    at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:146)
    at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:1377)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:200)
    at com.impetus.kundera.query.KunderaTypedQuery.getResultList(KunderaTypedQuery.java:250)
    at com.easytest.easytst.analysis.dao.AnalysisDao.analysis_user_list(AnalysisDao.java:117)
    at com.easytest.easytst.AnalysisController.add(AnalysisController.java:71)
    at ............
Caused by: org.apache.cassandra.serializers.MarshalException: Unexpected extraneous bytes after list value
    at org.apache.cassandra.serializers.ListSerializer.deserializeForNativeProtocol(ListSerializer.java:104)
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator$ListTypeBuilder.decompose(CassandraDataTranslator.java:1267)
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator$ListTypeBuilder.access$4900(CassandraDataTranslator.java:1198)
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator.decompose(CassandraDataTranslator.java:534)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.setCollectionValue(CassandraDataHandlerBase.java:2508)
    ... 84 more
ERROR: com.impetus.client.cassandra.CassandraClientBase - Error while executing native CQL query Caused by {}.
javax.persistence.PersistenceException: javax.persistence.PersistenceException: org.apache.cassandra.serializers.MarshalException: Unexpected extraneous bytes after list value
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateEntity(CassandraDataHandlerBase.java:833)
    at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2272)
    at com.impetus.client.cassandra.CassandraClientBase.executeSelectQuery(CassandraClientBase.java:926)
    at com.impetus.client.cassandra.thrift.ThriftClient.executeQuery(ThriftClient.java:1062)
    at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:146)
    at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:1377)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:200)
    at com.impetus.kundera.query.KunderaTypedQuery.getResultList(KunderaTypedQuery.java:250)
    at com.easytest.easytst.analysis.dao.AnalysisDao.analysis_user_list(AnalysisDao.java:117)
Caused by: org.apache.cassandra.serializers.MarshalException: Unexpected extraneous bytes after list value
    at org.apache.cassandra.serializers.ListSerializer.deserializeForNativeProtocol(ListSerializer.java:104)
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator$ListTypeBuilder.decompose(CassandraDataTranslator.java:1267)
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator$ListTypeBuilder.access$4900(CassandraDataTranslator.java:1198)
    at com.impetus.client.cassandra.schemamanager.CassandraDataTranslator.decompose(CassandraDataTranslator.java:534)
    at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.setCollectionValue(CassandraDataHandlerBase.java:2508)
    ... 84 more
```

Persistence

```

<persistence-unit name="cassandra">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <properties>
            <property name="kundera.annotations.scan.package" value="com.easytest.easytst.file.model,com.easytest.easytst.device.model,com.easytest.easytst.analysis.model"/>
            <property name="kundera.nodes" value="127.0.0.1" />
            <property name="kundera.port" value="9160" />
            <property name="kundera.keyspace" value="test" />
            <property name="kundera.dialect" value="cassandra" />
            <property name="kundera.client.lookup.class" value = "com.impetus.client.cassandra.thrift.ThriftClientFactory" />
        </properties>
    </persistence-unit>
```

**Comment by devender-yadav** [comment]
@AdityaSureka 

Please share kundera-version, cassandra-version and test code.

-Dev

**Comment by AdityaSureka** [comment]
kundera-version=3.2 
tried with cassandra version=3.0.0 and 3.0.1
Test Code 

```
@Entity
@Table(name = "analysis", schema = "test@cassandra")
public class AnalysisModel{

    @Id
    @Column(name = "analysis_id")
    private String analysis_id=UUID.randomUUID().toString();

    @Column(name = "user_id")
    private String user_id;

    @ElementCollection
    @Column(name = "cpu_usage")
    private List<String> cpu_usage;  
```

DAO 

```
    @Override
    public List<AnalysisModel> analysis_user_list(String username) {
        propertyMap.put(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_3_0);
        entityManagerFactory = Persistence.createEntityManagerFactory("cassandra", propertyMap);
        entityManager = entityManagerFactory.createEntityManager();
        List<AnalysisModel> analysis ;
        Query q = entityManager.createQuery("select a from AnalysisModel a where a.user_id =:user_id ",AnalysisModel.class);
        q.setParameter("user_id", username);
        analysis = q.getResultList();
        entityManager.close();
        return analysis;
    }

```

**Comment by AdityaSureka** [comment]
by the way native queries work fine but as it does not support setParameter ,I have to use JPA Query

**Comment by devender-yadav** [comment]
@AdityaSureka 

We will look into your issue and get back to you ASAP.

-Dev

**Comment by AdityaSureka** [comment]
Problem does not appear on apache cassandra 2.2.4.

**Comment by karthikprasad13** [comment]
@AdityaSureka 

Kundera is not completely compatible with Cassandra 3.0+ (latest compatibility is with 2.2+). There are some changes in serialization api and we will address it as a part of Kundera-Cassandra upgrade.

-Karthik

**Comment by AdityaSureka** [comment]
Okay .You can close it for now then.I reverted back older version

**Comment by AdityaSureka** [comment]
any updates on this issue ?

**Comment by devender-yadav** [comment]
Hi Aditya,

We are working on cassandra upgrade (_3.x_) [issue](https://github.com/impetus-opensource/Kundera/issues/846).

We are planning to release this feature in Kundera **3.5** (_which is expected to be released in mid June_).

-Dev
