### ISSUE TITLE
Composite keys in MongoDB

### ISSUE THREAD

**Issue by ansarrafique** [Impetus/kundera#859]
Does composite key concept using Kundera is also supported in MongoDB ? I have designed an entity for Cassandra taking composite key concept in mind, means using @Embedded annotation. It work fines for Cassandra. However, if I run the same code for MongoDB, I get an exception (can't serialize class)

com.impetus.kundera.KunderaException: java.lang.IllegalArgumentException: can't serialize class com.PartitionKey
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)
    at com.leuven.distrinet.encryption.crypto.AbstractCryptoEntityManager.persist(AbstractCryptoEntityManager.java:57)
    at com.leuven.distrinet.encryption.service.DataStorageService.persit(DataStorageService.java:14)
    at com.leuven.distrinet.encryption.driver.EncryptionDriver.main(EncryptionDriver.java:16)
Caused by: java.lang.IllegalArgumentException: can't serialize class com.leuven.distrinet.encryption.crypto.PartitionKey
    at org.bson.BasicBSONEncoder._putObjectField(BasicBSONEncoder.java:299)
    at org.bson.BasicBSONEncoder.putObject(BasicBSONEncoder.java:194)
    at org.bson.BasicBSONEncoder._putObjectField(BasicBSONEncoder.java:255)
    at org.bson.BasicBSONEncoder.putObject(BasicBSONEncoder.java:175)
    at org.bson.BasicBSONEncoder.putObject(BasicBSONEncoder.java:136)
    at com.mongodb.DefaultDBEncoder.writeObject(DefaultDBEncoder.java:36)
    at com.mongodb.OutMessage.putObject(OutMessage.java:289)
    at com.mongodb.DBCollectionImpl.insertWithWriteProtocol(DBCollectionImpl.java:556)
    at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:195)
    at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:167)
    at com.mongodb.DBCollection.insert(DBCollection.java:93)
    at com.impetus.client.mongodb.MongoDBClient.onFlushCollection(MongoDBClient.java:1091)
    at com.impetus.client.mongodb.MongoDBClient.onPersist(MongoDBClient.java:834)
    at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:114)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:197)
    at com.impetus.kundera.graph.Node.flush(Node.java:531)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:403)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:145)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)
    ... 3 more

**Comment by devender-yadav** [comment]
@ansarrafique 

Composite key is supported in MongoDB. Please share your entities and test case so that I can replicate this at my end. 

Check [this](https://github.com/impetus-opensource/Kundera/blob/6ee77aa5ee891be90d181ec41c52c1af8cacdb5f/src/kundera-mongo/src/test/java/com/impetus/client/crud/compositeType/MongoCompositeTypeTest.java) test case for details.

-Dev

**Comment by ansarrafique** [comment]
@devender-yadav 

The data model is bit different in my case. I have a partition key too. Please see below:

Entity
public class EncryptedData{
    @EmbeddedId
    private Key key;
    @Column
    private String name;
    @Column
    private int score;
}

@Embeddable
public class Key{
    @Embedded
    private PartitionKey partitionKey;
    @Column
    private String columname;
}

@Embeddable
public class PartitionKey{
    @Column
    private String classname;
    @Column
    private String id;
}

It works fine for Cassandra, but get an exception for MongoDB. Anything wrong here?

**Comment by ansarrafique** [comment]
Do I need to change the entity model for the MongoDB to make it work? The above entity model doesn't seems to work with the  MongoDB. 

I dig into the issue and I think the partition key is not supported in MongoDB using Kundera. Is @Embedded annotation is supported in MongoDB using Kundera?

**Comment by devender-yadav** [comment]
@ansarrafique 

`@Embedded` annotation is supported in Kundera-MongoDB (_test case shared in previous comment_). Also, **Composite key** is supported in Kundera-MongoDB using `@EmbeddedId`. 

 In your case, you are using nested composite key (_embeddable within embeddable_), we are looking into this and will get back to you.

-Dev

**Comment by ansarrafique** [comment]
Indeed, I have designed the entities taking Cassandra data model into account (e.g., partition key, cluster key). This makes sure that the same partition key are stored on a single node, which are sorted by clustering key. 

I am not entirely sure if such a concept exists in the MongoDB. I was reading the documentation and I didn't find such a thing except that MongoDB supports a compound key. This might not be supported by Kundera because internally MongoDB doesn't support this. 

I was rather wondering do I have to change the data model in order to make it work  with the MongoDB?

**Comment by devender-yadav** [comment]
hi @ansarrafique 

In MongoDB, there is nothing like partition key & cluster key as in Cassandra. So, the composite key in Kundera-MongoDB is not supported in the same way as in Kundera-Cassandra. You can't have Embedded fields in your EmbeddedId entity in case of  Kundera-MongoDB.

So, you need to change your data model in the case of MongoDB.

-Dev

**Comment by ansarrafique** [comment]
Yup, that's what I was wondering. I was actually looking at if we can used @Embedded  annotation inside the @EmbeddedId entity. Is this not internally supported by the MongoDB? How does MongoDB stores data based on the compound/composite keys? For example, in Cassandra, the data for the same partition key will always be stored on ONE node in a cluster. How the compound key would work in  the MongoDB for the data distribution?

**Comment by devender-yadav** [comment]
Hi Ansar,

**composite key** in MongoDB is not used for data distribution and all. It's just to make primary key more complex and unique. There are other options also like creating **unique index** or **unique compound index** to achieve unique primary keys. 

Users generally  don't design primary key in such a way that included nested embedded objects in MongoDB. That's why it's not supported by Kundera. 

-Dev
