### ISSUE TITLE
Primary Key Auto generate with Annotation does not work

### ISSUE THREAD

**Issue by ghost** [Impetus/kundera#864]
Spring 3.2.17
Cassandra 3.4
kundera-cassandra 3.4

Hi,
I'm new to kundera, We rencently uprgrade from Cassandra 1.2 to Cassandra 3 + JPA.
We are facing several issues, one of them is regarding the auto-generation of primary key.

Using: 

```
@Id
@GeneratedValue(strategy = GenerationType.AUTO)
private String id;

```

=> Exception in thread "main" com.impetus.kundera.KunderaException: 
`[ERROR] 27 mai 2016 17:46:43,212 [main] - Error while executing query SELECT NOW() FROM system.schema_columns LIMIT 1
Exception in thread "main" com.impetus.kundera.KunderaException: com.impetus.kundera.KunderaException: InvalidRequestException(why:unconfigured table schema_columns)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)`

Using: 

```
@Id @GeneratedValue(strategy = GenerationType.TABLE)
    @Column(name="ID")
    private String id;

```

First element is created then, second creation returns 

```
[ERROR] 27 mai 2016 17:49:45,515 [main] - Error while reading counter value from tablekundera_sequences, Caused by: .
TimedOutException(acknowledged_by:0)
    at org.apache.cassandra.thrift.Cassandra$add_result$add_resultStandardScheme.read(Cassandra.java:23059)
    at org.apache.cassandra.thrift.Cassandra$add_result$add_resultStandardScheme.read(Cassandra.java:23027)
    at org.apache.cassandra.thrift.Cassandra$add_result.read(Cassandra.java:22961)
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
    at org.apache.cassandra.thrift.Cassandra$Client.recv_add(Cassandra.java:948)
    at org.apache.cassandra.thrift.Cassandra$Client.add(Cassandra.java:932)
    at com.impetus.client.cassandra.CassandraIdGenerator.generate(CassandraIdGenerator.java:139)
    at com.impetus.kundera.persistence.IdGenerator.onTableGenerator(IdGenerator.java:208)
    at com.impetus.kundera.persistence.IdGenerator.generateId(IdGenerator.java:77)
    at com.impetus.kundera.persistence.IdGenerator.generateAndSetId(IdGenerator.java:58)
```

finally
  GenerationType.SEQUENCE and IDENTITY are not supported.

Help will be appreciated.

Thanks,

**Comment by karthikprasad13** [comment]
@hToulan 

Kundera 3.4 is not yet compatible with Cassandra 3+. We are working on the upgrade and will be available in the next release (planned mid of June).

-Karthik

**Comment by devender-yadav** [comment]
@hToulan 

Upgrade for Cassandra 3.5 has been added to the trunk and it will be available from next release i.e. **3.5** (_expected to be released in this month_)

-Dev

**Comment by ghost** [comment]
Thank you for this update.

**Comment by mmajcenic** [comment]
Hello,
I am having this same issue, but while using Cassandra 3.7 and Kundera 3.5.
Does Kundera 3.5 support Cassandra 3.7?

**Comment by karthikprasad13** [comment]
@Sarpedion 

Kundera 3.5 is tested with Cassandra 3.5. It should support 3.7 too as there are no core changes.

-Karthik

**Comment by Kinle** [comment]
Does it work with Cassandra 3.11.0? I am having issue with auto-generation
