### ISSUE TITLE
Issue with one to Many Relationship

### ISSUE THREAD

**Issue by pmanicka** [Impetus/kundera#868]
Hi Team,

I'm trying to persist an Object through One to Many Relationship. I'm getting the below exception when trying to persist the same. It seems its trying to persist the whole object in the second table. 

com.impetus.kundera.KunderaException: com.impetus.kundera.KunderaException: InvalidRequestException(why:line 1:271 no viable alternative at input ']' (...,"audTrailRecId") VALUES('EAQ151203PVQHFNBIDZRSMRJEKP',[EAQ151203PVQHFNBIDZRSMRJEKPRAW[]]...))
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at 

Sample Entity Classes Below:

---

@Entity
@Table(name = "AUD_TRAIL")
public class AudTrail implements /\* DomainObject, */Serializable {
    private static final long serialVersionUID = -6898685332089128609L;

```
@Id
private String audTrailRecId;
private String corrlId;
private Timestamp javaMessagingSrvcTs;
private Timestamp msgPollingTs;
private String rcvCommunId;
private String rcvFeederSysId;
private String rcvTmpltId;
private String recStaTypeCd;
private Timestamp thunderheadCallTs;

@ElementCollection
@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
@JoinColumn(name="AUD_TRAIL_REC_ID")
private List<AudTrailDetail> details;

public AudTrail() {
}
```

---

@Entity
@Table(name = "AUD_TRAIL_DTL")
public class AudTrailDetail extends AbstractAudTrailDetail implements Serializable {

```
private static final long serialVersionUID = 7819910291306346201L;
private byte[] audTrailMsgTx;

public AudTrailDetail() {
    super();
}

public AudTrailDetail(AudTrail audTrail, AuditTrailStageCodeEnum stage) {
    super(audTrail, stage);
}

public AudTrailDetail(AudTrail audTrail) {
    super(audTrail, AuditTrailStageCodeEnum.RAW_DATA);
}

@Lob
@Column(name = "AUD_TRAIL_MSG_TX", nullable = false)
public byte[] getAudTrailMsgTx() {
    return this.audTrailMsgTx;
}

public void setAudTrailMsgTx(byte[] audTrailMsgTx) {
    this.audTrailMsgTx = audTrailMsgTx;
}

@Transient
public String getAudTrailText() {
    return new String(getAudTrailMsgTx());
}


@Override
public String toString() {
    return (getId() == null ? super.toString() : getId().toString());
}
```

}

---

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

@Embeddable
public class CompositeId implements Serializable {
    private static final long serialVersionUID = 4916657868633152852L;
    private AudTrail audTrail;
    private String audPrcsStageCd;

```
public CompositeId() {
}

public CompositeId(AudTrail audTrail, String statusCode) {
    this.audTrail = audTrail;
    audPrcsStageCd = statusCode;
}

@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
@JoinColumn(name = "AUD_TRAIL_REC_ID", insertable = false, updatable = false)
public AudTrail getAudTrail() {
    return audTrail;
}

public void setAudTrail(AudTrail audTrail) {
    this.audTrail = audTrail;
}

@Column(name = "AUD_PRCS_STAGE_CD", nullable = false, length = 4)
public String getAudPrcsStageCd() {
    return audPrcsStageCd;
}

public void setAudPrcsStageCd(String audPrcsStageCd) {
    this.audPrcsStageCd = audPrcsStageCd;
}

@Override
public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
}

@Override
public int hashCode() {
    return new HashCodeBuilder(17, 37).append(audPrcsStageCd)
            .append(audTrail == null ? null : audTrail.getAudTrailRecId()).toHashCode();
}

@Override
public String toString() {
    return (audTrail == null ? "null" : audTrail.getRcvCommunId()) + audPrcsStageCd;
}
```

}

---

import java.sql.Timestamp;
import java.util.ArrayList;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.MappedSuperclass;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.pmanicka.schema.audit;

@MappedSuperclass
/**
- Abstract class to be used by AudTrailDetail and AudTrailDetailExtension
- Common things are kept here
  _/
  public abstract class AbstractAudTrailDetail /_ implements DomainObject */{
  
  @EmbeddedId
  private CompositeId id;
  private Timestamp lstUpdtTs;
  
  public AbstractAudTrailDetail(AudTrail audTrail, AuditTrailStageCodeEnum stage) {
      if (AuditTrailStageCodeEnum.RAW_DATA.equals(stage)) {
  
  ```
      if (audTrail.getDetails() == null) {
          audTrail.setDetails(new ArrayList<AudTrailDetail>());
      }
      audTrail.getDetails().add((AudTrailDetail) this);
  }
  id = new CompositeId(audTrail, stage.getStatusCode());
  setLstUpdtTs(new Timestamp(System.currentTimeMillis()));
  ```
  
  }
  
  public AbstractAudTrailDetail() {
  }
  
  @Cascade(value = { CascadeType.SAVE_UPDATE })
  public CompositeId getId() {
      return id;
  }
  
  public void setId(CompositeId id) {
      this.id = id;
  }
  
  @Column(name = "LST_UPDT_TS", nullable = false)
  public Timestamp getLstUpdtTs() {
      return lstUpdtTs;
  }
  
  public/\* final */void setLstUpdtTs(Timestamp lstUpdtTs) {
      this.lstUpdtTs = lstUpdtTs;
  }
  
  }
  ---

package com.pmanicka.schema.audit;

public enum AuditTrailStageCodeEnum {

```
MESSAGE_HEADERS("HEAD"), RAW_DATA("RAW"), PRE_PROCESSING_ENVELOPE("PREP"), POST_PROCESSING_ENVELOPE(
        "POST"), THUNDERHEAD_DATA("CUST"), SOR_REQUEST("SREQ"), SOR_BB_REQUEST("SRBB"), SOR_RESPONSE(
        "SREP"), THUNDERHEAD_CONTENT_RESPONSE("CONT"), THUNDERHEAD_ALT_RESPONSE("ALT"), FEEDER_RESPONSE(
        "RESP"), ADE_REQUEST("ADE"), ADE_RESPONSE("ADER"), SMC_REQUEST("SMC"), SMC_RESPONSE("SMCR"), CI_REQUEST(
        "CI"), FAX_REQUEST("FAX"), BHR_REQUEST("BHR"), HKM_REQUEST("HKM"), EMAIL_SERVICE_REQUEST("EMS"), SMS_REQUEST(
        "SMS"), LETTER_REQUEST("LETR"), IMD_REQUEST("IMD"), SOR_AUGMENTATION("SAUG"), MAINFRAME_CONFIRMATION(
        "MFCM"), MTA_SUCCESS_CONFIRMATION("MTAS"), MTA_FAILED_CONFIRMATION("MTAF"), BPS_CONFIRMATION(
        "BPS"), BPS_ACKNOWLEDGMENT("BPSA"), DISPATCH_SUPPRESSION("SPRS"), SLA_STATUS("SLA");
private String statusCode;


private AuditTrailStageCodeEnum(String s) {
    statusCode = s;
}

public String getStatusCode() {
    return statusCode;
}
```

}

**Comment by pmanicka** [comment]
Correcting the Class for AudTrail 

@Entity
@Table(name = "AUD_TRAIL")
public class AudTrail implements /\* DomainObject, */Serializable {
    private static final long serialVersionUID = -6898685332089128609L;

```
@Id
private String audTrailRecId;
private String corrlId;
private Timestamp javaMessagingSrvcTs;
private Timestamp msgPollingTs;
private String rcvCommunId;
private String rcvFeederSysId;
private String rcvTmpltId;
private String recStaTypeCd;
private Timestamp thunderheadCallTs;

private List<String> rejectReasons;

@OneToMany(mappedBy = "audTrailRecId", cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
private List<AudTrailDetail> details;

public AudTrail() {
}
```

**Comment by devender-yadav** [comment]
Hi @pmanicka 

Please share persistence unit, test case (_used for insertion_) and  Kundera version.

-Dev

**Comment by pmanicka** [comment]
Hi Dev,

Please find below PU & Junit.

  @Test
    public void validateAudTrailDetail() throws Exception {
        System.out.println("Inside Test");

```
    AudTrail objaudtrail = new AudTrail();
    objaudtrail.setAudTrailRecId("7000000000000000000");
    Calendar calendar = Calendar.getInstance();
    java.sql.Timestamp ourJavaTimestampObject = new java.sql.Timestamp(calendar.getTime().getTime());
    objaudtrail.setJavaMessagingSrvcTs(ourJavaTimestampObject);
    objaudtrail.setMsgPollingTs(ourJavaTimestampObject);
    objaudtrail.setRcvCommunId("EAQ151203PVQHFNBIDZRSMRJEKP");
    objaudtrail.setRcvTmpltId("IMSENEAQCMA0003");       


    AudTrailDetail objAudtraildetail = new AudTrailDetail();
    CompositeId objcompid = new CompositeId();
    objcompid.setAudPrcsStageCd("RAW");
    objcompid.setAudTrail(objaudtrail);
    objAudtraildetail.setId(objcompid);
    String strInputxml = "ABC";
    objAudtraildetail.setAudTrailMsgTx(strInputxml.getBytes());
    List<AudTrailDetail> objaudtraillist = new ArrayList<AudTrailDetail>();
    objaudtraillist.add(objAudtraildetail);
    objaudtrail.setDetails(objaudtraillist);        
    objaudtrailutil.persist(objaudtrail);

    AudTrail at = objaudtrailutil.find("7000000000000000000");
    assertEquals("7000000000000000000",""+at.getAudTrailRecId());


}
```

Persistance Unit

```
<bean id="cassandrajpaProperties"
    class="org.springframework.beans.factory.config.PropertiesFactoryBean">
    <property name="ignoreResourceNotFound" value="true" />
    <property name="properties">
        <props>
            <prop key="kundera.nodes">localhost</prop>
            <prop key="kundera.port">9160</prop>
            <prop key="kundera.keyspace">IT</prop>
            <prop key="kundera.client.lookup.class">com.impetus.client.cassandra.thrift.ThriftClientFactory
            </prop>
            <prop key="kundera.ddl.auto.prepare">update</prop>
            <prop key="cql.version">3.0.0</prop>
        </props>
    </property>
</bean>
```
