### ISSUE TITLE
Class not found, it won't be loaded as entity

### ISSUE THREAD

**Issue by ZakariaHili** [Impetus/kundera#871]
Hi,

I want to use play framework with Cassandra, so I followed this tutorial :https://github.com/impetus-opensource/Kundera/wiki/Using-Kundera-with-Play!-Framework
but kundera can't generate schema or even connect to my database.
the error:

```
--- (RELOAD) ---                                                                                             

[info] application - ApplicationTimer demo: Stopping application at 2016-06-17T22:10:53.535Z after 3194s.    
[info] application - ApplicationTimer demo: Starting application at 2016-06-17T22:10:53.648Z                 
[info] play.api.Play - Application started (Dev)                                                             
**[error] c.i.k.c.MetamodelConfiguration - Class entities.user not found, it won't be loaded as ent
y**                                                                                                                                                                                   
[error] application -                                                                                        

! @70e78k734 - Internal server error, for (GET) [/] ->                                                       

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: com.impetus.kunde
.KunderaException: java.lang.IllegalArgumentException: Entity object is invalid, operation failed. Please che
 previous log message for details]]                                                                          
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)  
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)                   
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)                                   
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)                                         
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)             
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandl
.scala:100)                                                                                                  
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandl
.scala:99)                                                                                                   
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)                            
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)                            
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)                                      
Caused by: java.util.concurrent.CompletionException: com.impetus.kundera.KunderaException: java.lang.IllegalA
umentException: Entity object is invalid, operation failed. Please check previous log message for details    
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)                
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)              
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)                       
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)               
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)                   
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)         
        at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:21)              
        at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:18)              
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)                                      
        at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)  
Caused by: com.impetus.kundera.KunderaException: java.lang.IllegalArgumentException: Entity object is invalid
operation failed. Please check previous log message for details                                              
        at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)             
        at dao.testDAOImpl.insert(testDAOImpl.java:61)                                           
        at controllers.HomeController.index(HomeController.java:34)                                          
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(Routes.scala:139)   
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(Routes.scala:139)   
        at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)              
        at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:156)              
        at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocati
(HandlerInvoker.scala:136)                                                                                   
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:73)                                          
        at play.http.HttpRequestHandler$1.call(HttpRequestHandler.java:54)                                   
Caused by: java.lang.IllegalArgumentException: Entity object is invalid, operation failed. Please check previ
s log message for details                                                                                    
        at com.impetus.kundera.validation.rules.NullOrInvalidEntityRule.validate(NullOrInvalidEntityRule.java
2)                                                                                                           
        at com.impetus.kundera.graph.GraphGenerator.generate(GraphGenerator.java:125)                        
        at com.impetus.kundera.graph.GraphGenerator.generateGraph(GraphGenerator.java:78)                    
        at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:130)       
        at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)             
        at dao.testDAOImpl.insert(testDAOImpl.java:61)                                           
        at controllers.HomeController.index(HomeController.java:34)                                          
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(Routes.scala:139)   
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(Routes.scala:139)   
        at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)              



```

 my persistence.xml file:                  

```

<persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
    <persistence-unit name="cassandra_pu">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>entities.user</class>
        <exclude-unlisted-classes>true</exclude-unlisted-classes>
        <properties>
            <property name="kundera.nodes" value="192.168.0.2"/>
            <property name="kundera.port" value="9160"/>
            <property name="kundera.keyspace" value="test"/>
            <property name="kundera.dialect" value="cassandra" />
            <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />


        </properties>
    </persistence-unit>
</persistence>                                                                                                            

```

my entity class

```
@Entity
@Table(name = "User", schema = "test@cassadra_pu")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="user_Id" ,unique = true)
    private String Id;
    @Column
    private String firstName;
    @Column 
    private String lastName;
    @Column 

    public User() {
        }
 ....

```

**Comment by devender-yadav** [comment]
Hi  @ZakariaHili 

Please share your sample project at kundera@impetus.co.in so that we can reproduce same issue at our end.

-Dev

**Comment by devender-yadav** [comment]
Hi @ZakariaHili,

Any update on this?  Are you able to resolve the issue?

-Dev

**Comment by raphaelauv** [comment]
Hi , i'm having kind of the same problem 
i'm using scala  and folllowing this tutorial : https://dzone.com/articles/play-nosql-building-nosql


and i'm getting this error , could you please give me some help

[error] c.i.k.c.MetamodelConfiguration - Class model.MyUser not found, it won't be loaded as entity

my class is -> 

```scala
package model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "users", schema = "KunderaExamples@cassandra_pu")
class MyUser() {

  @Id
  var userId:String=""

  @Column(name = "first_name")
  var firstName:String=""

  @Column(name = "last_name")
  var lastName:String=""

  @Column(name = "city")
  var city:String=""

}
```

my controller 


```scala
package controllers;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.inject._
import play.api.mvc._
import model.MyUser

  object MyUserController {

    var emf: EntityManagerFactory = null
    val userTmp = new MyUser()
    var classUser =  userTmp.getClass

  }


class MyUserController @Inject() (cc: ControllerComponents) extends AbstractController(cc) {

  def index = Action {
    Ok(views.html.index("Your new application is ready."))
  }

  def getEmf: EntityManagerFactory = {
      if (MyUserController.emf == null) {
        MyUserController.emf = Persistence.createEntityManagerFactory("cassandra_pu");
       System.out.println("WE CREATED : "+MyUserController.emf);
      }
      MyUserController.emf

  }

 	def persist = Action {
      var em: EntityManager = getEmf.createEntityManager();

      var user: MyUser = new MyUser();
      user.setUserId("0001");
      user.setFirstName("John");
      user.setLastName("Smith");
      user.setCity("London");

      em.persist(user);
      em.close();
      Ok(views.html.index("User 0001 record persisted for persistence unit cassandra_pu"));
    }


```

and my persistancefile 
```XML
<persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
 <persistence-unit name="cassandra_pu">
 <provider>com.impetus.kundera.KunderaPersistence</provider>
 <class>model.MyUser</class>
<exclude-unlisted-classes>true</exclude-unlisted-classes>
 <properties>
 <property name="kundera.nodes" value="localhost"/>
 <property name="kundera.port" value="9160"/>
 <property name="kundera.keyspace" value="KunderaExamples"/>
 <property name="kundera.dialect" value="cassandra"/>
 <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
 </properties>
 </persistence-unit>
</persistence>
```
thank you
