### ISSUE TITLE
Problems with persisting entities with auto generated ID

### ISSUE THREAD

**Issue by mmajcenic** [Impetus/kundera#872]
Greetings,

I am using Cassandra 3.7 and Kundera 3.5. Issue can be replicated from [Getting Started in 5 minutes](https://github.com/impetus-opensource/Kundera/wiki/Getting-Started-in-5-minutes), only difference being that ID field of User entity is annotated:

```
@Id
@GeneratedValue(strategy = GenerationType.TABLE)
private Long userId;
```

and dependencies are:

```
<dependencies>
    <dependency>
        <groupId>com.impetus.kundera.core</groupId>
        <artifactId>kundera-core</artifactId>
        <version>3.5</version>
    </dependency>
    <dependency>
        <groupId>com.impetus.kundera.client</groupId>
        <artifactId>kundera-cassandra</artifactId>
        <version>3.5</version>
    </dependency>
</dependencies>
```

and, of course, in main method I create more than one entity.

Everything works fine when I persist first entity, or when I manually set id, but on second entity it fails with following stacktrace:

<pre><code>Exception in thread "main" 17:27:46.511 [main] ERROR c.i.c.cassandra.CassandraIdGenerator - Error while reading counter value from tablekundera_sequences, Caused by: .
org.apache.cassandra.thrift.TimedOutException: null
    at org.apache.cassandra.thrift.Cassandra$add_result$add_resultStandardScheme.read(Cassandra.java:23059) ~[cassandra-thrift-3.5.jar:3.5]
    at org.apache.cassandra.thrift.Cassandra$add_result$add_resultStandardScheme.read(Cassandra.java:23027) ~[cassandra-thrift-3.5.jar:3.5]
    at org.apache.cassandra.thrift.Cassandra$add_result.read(Cassandra.java:22961) ~[cassandra-thrift-3.5.jar:3.5]
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78) ~[libthrift-0.9.2.jar:0.9.2]
    at org.apache.cassandra.thrift.Cassandra$Client.recv_add(Cassandra.java:948) ~[cassandra-thrift-3.5.jar:3.5]
    at org.apache.cassandra.thrift.Cassandra$Client.add(Cassandra.java:932) ~[cassandra-thrift-3.5.jar:3.5]
    at com.impetus.client.cassandra.CassandraIdGenerator.generate(CassandraIdGenerator.java:139) ~[kundera-cassandra-3.5.jar:na]
    at com.impetus.kundera.persistence.IdGenerator.onTableGenerator(IdGenerator.java:208) [kundera-core-3.5.jar:na]
    at com.impetus.kundera.persistence.IdGenerator.generateId(IdGenerator.java:77) [kundera-core-3.5.jar:na]
    at com.impetus.kundera.persistence.IdGenerator.generateAndSetId(IdGenerator.java:58) [kundera-core-3.5.jar:na]
    at com.impetus.kundera.graph.GraphGenerator.onPreChecks(GraphGenerator.java:229) [kundera-core-3.5.jar:na]
    at com.impetus.kundera.graph.GraphGenerator.generate(GraphGenerator.java:127) [kundera-core-3.5.jar:na]
    at com.impetus.kundera.graph.GraphGenerator.generateGraph(GraphGenerator.java:78) [kundera-core-3.5.jar:na]
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:130) [kundera-core-3.5.jar:na]
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174) [kundera-core-3.5.jar:na]
    at main.Main.main(Main.java:25) [classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:na]
com.impetus.kundera.KunderaException: com.impetus.kundera.KunderaException: TimedOutException(acknowledged_by:0)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)
    at main.Main.main(Main.java:25)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: com.impetus.kundera.KunderaException: TimedOutException(acknowledged_by:0)
    at com.impetus.client.cassandra.CassandraIdGenerator.generate(CassandraIdGenerator.java:159)
    at com.impetus.kundera.persistence.IdGenerator.onTableGenerator(IdGenerator.java:208)
    at com.impetus.kundera.persistence.IdGenerator.generateId(IdGenerator.java:77)
    at com.impetus.kundera.persistence.IdGenerator.generateAndSetId(IdGenerator.java:58)
    at com.impetus.kundera.graph.GraphGenerator.onPreChecks(GraphGenerator.java:229)
    at com.impetus.kundera.graph.GraphGenerator.generate(GraphGenerator.java:127)
    at com.impetus.kundera.graph.GraphGenerator.generateGraph(GraphGenerator.java:78)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:130)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)
    ... 6 more
Caused by: TimedOutException(acknowledged_by:0)
    at org.apache.cassandra.thrift.Cassandra$add_result$add_resultStandardScheme.read(Cassandra.java:23059)
    at org.apache.cassandra.thrift.Cassandra$add_result$add_resultStandardScheme.read(Cassandra.java:23027)
    at org.apache.cassandra.thrift.Cassandra$add_result.read(Cassandra.java:22961)
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
    at org.apache.cassandra.thrift.Cassandra$Client.recv_add(Cassandra.java:948)
    at org.apache.cassandra.thrift.Cassandra$Client.add(Cassandra.java:932)
    at com.impetus.client.cassandra.CassandraIdGenerator.generate(CassandraIdGenerator.java:139)
    ... 14 more</code></pre>

**Comment by karthikprasad13** [comment]
@Sarpedion 

We are looking into this issue. Will update soon.

-Karthik
