### ISSUE TITLE
Using CriteriaBuilder with Kundera

### ISSUE THREAD

**Issue by mmajcenic** [Impetus/kundera#874]
Greetings,

Here I am with new issue.

I am still using Cassandra 3.7 and Kundera 3.5. Issue can be replicated from [Getting Started in 5 minutes](https://github.com/impetus-opensource/Kundera/wiki/Getting-Started-in-5-minutes), with main difference being that in main method I try to fetch data using CriteriaBuilder:

```
    CriteriaBuilder cb = em.getCriteriaBuilder();
    CriteriaQuery<User> cq = cb.createQuery(User.class);
    Root<User> from = cq.from(User.class);
    cq.select(from);
    TypedQuery<User> query = em.createQuery(cq);
    query.getResultList();
```

And on row `query.getResultList();` exception is thrown:

<pre><code>Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1967)
    at com.impetus.kundera.query.KunderaQueryParser.buildResultColumns(KunderaQueryParser.java:488)
    at com.impetus.kundera.query.KunderaQueryParser.access$300(KunderaQueryParser.java:54)
    at com.impetus.kundera.query.KunderaQueryParser$Compiler.compileResult(KunderaQueryParser.java:263)
    at com.impetus.kundera.query.KunderaQueryParser$Compiler.compileSelectOrDelete(KunderaQueryParser.java:180)
    at com.impetus.kundera.query.KunderaQueryParser$Compiler.compile(KunderaQueryParser.java:132)
    at com.impetus.kundera.query.KunderaQueryParser$Compiler.access$100(KunderaQueryParser.java:116)
    at com.impetus.kundera.query.KunderaQueryParser.parse(KunderaQueryParser.java:85)
    at com.impetus.kundera.query.QueryResolver.getQueryImplementation(QueryResolver.java:84)
    at com.impetus.kundera.persistence.PersistenceDelegator.getQueryInstance(PersistenceDelegator.java:561)
    at com.impetus.kundera.persistence.PersistenceDelegator.createQuery(PersistenceDelegator.java:521)
    at com.impetus.kundera.persistence.EntityManagerImpl.createQuery(EntityManagerImpl.java:384)
    at com.impetus.kundera.persistence.EntityManagerImpl.createQuery(EntityManagerImpl.java:722)
    at com.impetus.kundera.persistence.EntityManagerImpl.createQuery(EntityManagerImpl.java:709)</code></pre>

Does Kundera even support using CriteriaBuilder?

**Comment by devender-yadav** [comment]
Hi @Sarpedion,

Try with assigning an alias to the selection item. It should work. 

```
CriteriaBuilder cb = em.getCriteriaBuilder();
CriteriaQuery<User> cq = cb.createQuery(User.class);
Root<User> from = cq.from(User.class);
cq.select(from.alias("p"));
TypedQuery<User> query = em.createQuery(cq);
query.getResultList();
```

Check [testcase](https://github.com/impetus-opensource/Kundera/blob/6ee77aa5ee891be90d181ec41c52c1af8cacdb5f/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/crud/BaseTest.java#L94) for more details.

-Dev

**Comment by mmajcenic** [comment]
It works, thank you very much.
Closing issue.

Sarpedion
