### ISSUE TITLE
error in automatically created schema  in cassandra

### ISSUE THREAD

**Issue by iiyam** [Impetus/kundera#88]
I created simple class User:

@Entity(name="User")
@Table(name="users")//, schema="ReeRoo@reeroo_pu")
public class User {

```
@Id
@Column(name="user_id")
private String userID;


@Column(name="first_name")
private String firstName;

public User() {}

public String getUserID() {
    return userID;
}

public void setUserID(String userID) {
    this.userID = userID;
}

public String getFirstName() {
    return firstName;
}

public void setFirstName(String firstName) {
    this.firstName = firstName;
}
```

}

in persistence.xml I added new option <property name="kundera_ddl_auto_prepare" value="create-drop" />

SImple main method to run program ...

User user = new User();
        user.setUserID("0001");
        user.setFirstName("John");

```
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("whatever");
    EntityManager em = emf.createEntityManager();


    em.persist(user);
    em.close();    
    emf.close();  
```

and the result  is :

Exception in thread "main" com.impetus.kundera.configure.schema.SchemaGenerationException: InvalidRequestException(why:SimpleStrategy requires a replication_factor strategy option.)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.createKeyspaceAndTables(CassandraSchemaManager.java:464)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.create(CassandraSchemaManager.java:117)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.create_drop(CassandraSchemaManager.java:98)
    at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.handleOperations(AbstractSchemaManager.java:205)
    at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.exportSchema(AbstractSchemaManager.java:107)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.exportSchema(CassandraSchemaManager.java:87)
    at com.impetus.client.cassandra.pelops.PelopsClientFactory.initialize(PelopsClientFactory.java:79)
    at com.impetus.kundera.loader.GenericClientFactory.load(GenericClientFactory.java:67)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:127)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:74)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)
    MainMethod.main(MainMethod.java:19)
Caused by: InvalidRequestException(why:SimpleStrategy requires a replication_factor strategy option.)
    at org.apache.cassandra.thrift.Cassandra$system_add_keyspace_result.read(Cassandra.java:28494)
    at org.apache.cassandra.thrift.Cassandra$Client.recv_system_add_keyspace(Cassandra.java:1539)
    at org.apache.cassandra.thrift.Cassandra$Client.system_add_keyspace(Cassandra.java:1514)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.createKeyspace(CassandraSchemaManager.java:486)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.createKeyspaceAndTables(CassandraSchemaManager.java:459)
    ... 12 more

**Comment by kkmishra** [comment]
Hi iiyam,
can you please provide the property file information.

Thanks
kuldeep

**Comment by iiyam** [comment]
Hi kkmishra,

```
        <property name="kundera.nodes" value="localhost"/>
        <property name="kundera.port" value="9160"/>
        <property name="kundera.keyspace" value="newKeyspace"/>
        <property name="kundera.dialect" value="cassandra"/>
        <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.pelops.PelopsClientFactory" />
        <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
        <property name="kundera.cache.config.resource" value="/ehcache-test.xml"/>
        <property name="kundera_ddl_auto_prepare" value="create-drop" />
```

Thanks
iiyam

**Comment by mevivs** [comment]
Working with kundera 2.0.6 or 2.0.7-SNAPSHOT?

**Comment by iiyam** [comment]
kundera-cassandra-2.0.6-jar-with-dependencies.jar

**Comment by kkmishra** [comment]
Hi iiyam,
Which version of apache-cassadnra you are using .

**Comment by xamry** [comment]
Kundera 2.0.6 works with Cassandra 1.0.x...
A migration to Cassandra 1.1.x is slated for release 2.0.7. You can use trunk branch and it should work for you.

**Comment by iiyam** [comment]
I have cassandra 1.1.X so probably this is reason of my problems. 
Thanks guys for help

**Comment by mevivs** [comment]
Okay great. Shall i mark it close now?
