### ISSUE TITLE
NullPointerException for fields that contain Null

### ISSUE THREAD

**Issue by dstrawson** [Impetus/kundera#92]
I have an object with a property of type Long, which is set to null.

When persist is called I get the following exception:

com.impetus.kundera.KunderaException: com.impetus.kundera.KunderaException: java.lang.NullPointerException
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:285)
    at example.Test1.testNewItem(Test1.java:24)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
    at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: com.impetus.kundera.KunderaException: java.lang.NullPointerException
    at com.impetus.client.cassandra.pelops.PelopsClient.onPersist(PelopsClient.java:876)
    at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:84)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:180)
    at com.impetus.kundera.graph.Node.flush(Node.java:522)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:367)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:154)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:279)
    ... 25 more
Caused by: java.lang.NullPointerException
    at com.impetus.kundera.property.accessor.LongAccessor.toBytes(LongAccessor.java:62)
    at com.impetus.kundera.property.PropertyAccessorHelper.get(PropertyAccessorHelper.java:188)
    at com.impetus.client.cassandra.pelops.PelopsDataHandler.addColumnsToThriftRow(PelopsDataHandler.java:1467)
    at com.impetus.client.cassandra.pelops.PelopsDataHandler.toThriftRow(PelopsDataHandler.java:956)
    at com.impetus.client.cassandra.pelops.PelopsClient.populateTfRow(PelopsClient.java:986)
    at com.impetus.client.cassandra.pelops.PelopsClient.onPersist(PelopsClient.java:871)
    ... 31 more

**Comment by mevivs** [comment]
Fixed. Added null check on LongAccessor. Please take update and build kundera-core to verify this

Thanks,
Vivek

**Comment by dstrawson** [comment]
Thanks, that's fixed it, I have nulls with fields for several other data types, so I'll let you know which other ones break if any :)

Daniel

**Comment by mevivs** [comment]
I am already null checks to all accesssor :) Wait for 5 minute, let me commit for others as well

**Comment by mevivs** [comment]
Done for all . You can now take update and test for others as well .

Thanks,
Vivek

**Comment by dstrawson** [comment]
marvellous :)

**Comment by jeremyhahn** [comment]
The latest version solves this issue for top level entities, but it appears it may still be effecting @Embedded entities? Are you able to confirm?

**Comment by mevivs** [comment]
Verifying it.

-Vivek

**Comment by kkmishra** [comment]
Hi,
  I have verified and it ok for me,
  If you have any such scenario which is not working for you, then please
share.

Thanks
KK

On Thu, Mar 21, 2013 at 3:44 PM, Vivek Mishra notifications@github.comwrote:

> Verifying.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/impetus-opensource/Kundera/issues/92#issuecomment-15228530
> .

## 

Thanks and Regards
Kuldeep Kumar Mishra
+919540965199

**Comment by jeremyhahn** [comment]
package my.package.project.workflow;

import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import my.package.project.data.entity.Document;
import my.package.project.data.entity.UniqueId;

@Entity
@Table(name = "activity", schema = "project@default")
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonTypeInfo(use=JsonTypeInfo.Id.CLASS, include=JsonTypeInfo.As.PROPERTY, property="_class")
public class Activity implements Document {

```
@Id
@Column(name = "_id")
private String id;

@Column
private String hostname;

@Column
private String username;

@Column
private String password;

@Embedded
private Collection<Task> tasks;

@Column
private Collection<ParameterMapping> mappings;

public Activity() {
}

public Activity(String id, String hostname, String username, String password,
        Collection<Task> tasks, Collection<ParameterMapping> mappings) {
    this.id = id;
    this.hostname = hostname;
    this.username = username;
    this.password = password;
    this.tasks = tasks;
    this.mappings = mappings;
}

public String getId() {
    return id;
}

public void setId(final String id) {
    this.id = id;
}

@Override
@JsonIgnore
public void setId(UniqueId id) {
    this.id = id.toString();
}

public String getHostname() {
    return hostname;
}

public void setHostname(final String hostname) {
    this.hostname = hostname;
}

public String getUsername() {
    return username;
}

public void setUsername(final String username) {
    this.username = username;
}

public String getPassword() {
    return password;
}

public void setPassword(final String password) {
    this.password = password;
}

public Collection<Task> getTasks() {
    return tasks;
}

public void setTasks(final Collection<Task> tasks) {
    this.tasks = tasks;
}

@Override
public String toString() {
    return "Workflow [id=" + id + ", hostname=" + hostname + ", username=" + username
            + ", password=" + password + ", tasks=" + tasks + ", mappings=" + mappings + "]";
}
```

}

package my.package.project.workflow;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.mediasilo.flight.Properties;
import com.mediasilo.flight.workflow.task.ApiTask;

@Embeddable
@JsonTypeInfo(use=JsonTypeInfo.Id.CLASS, include=JsonTypeInfo.As.PROPERTY, property="_class")
public class Task {

```
private static final Log log = LogFactory.getLog(Task.class);

@Column
private String task;

@Column
private String[] properties;

@Column
private String converter;

@Column
private Collection<ParameterMapping> mappings;

private TaskResponse response;
private boolean executed;
private int taskTimeout;

public Task() {
    mappings = new ArrayList<ParameterMapping>();
    taskTimeout = new Integer(Properties.getFlightProperties()
            .getProperty("com.mediasilo.flight.workflow.task.timeout"));
}

public void setTask(String task) {
    this.task = task;
}

public String getTask() {
    return task;
}

public void setProperties(String[] properties) {
    this.properties = properties;
}

public String[] getProperties() {
    return properties;
}

public String getConverter() {
    return converter;
}

public void setConverter(String converter) {
    this.converter = converter;
}

public Collection<ParameterMapping> getMappings() {
    return mappings;
}

public void setMappings(Collection<ParameterMapping> mappings) {
    this.mappings = mappings;
}

public void addMapping(ParameterMapping mapping) {
    mappings.add(mapping);
}

public boolean hasMappings() {
    return mappings.size() > 0;
}

public void setResponse(TaskResponse response) {
    this.response = response;
}

public boolean hasResponse() {
    return response != null;
}

public TaskResponse getResponse() {
    return response;
}

public boolean hasExecuted() {
    return executed;
}

@Override
public String toString() {
    return "Task [task=" + task + ", properties="
            + Arrays.toString(properties) + ", converter=" + converter
            + ", mappings=" + mappings + ", response=" + response
            + ", executed=" + executed + ", taskTimeout=" + taskTimeout + "]";
}
```

}

[INFO] The entity: Activity [id=9807cb76-2f3c-4d42-9011-493de1f0d2ed, hostname=test, username=tester, password=secret, tasks=[Task [task=my.package.project.workflow.task.CreateProjectTask, properties=[Workflow Project, This is a workflow generated project, 32221], converter=my.package.project.workflow.task.converter.ProjectCreateConverter, mappings=[], response=null, executed=false, taskTimeout=10], Task [task=my.package.project.workflow.task.CreateFolderTask, properties=[null, 0, Workflow Folder 1], converter=my.package.project.workflow.task.converter.FolderCreateConverter, mappings=[ParameterMapping [key=projectId, references=1, value=id]], response=null, executed=false, taskTimeout=10], Task [task=my.package.project.workflow.task.DuplicateFileTask, properties=[44E17F6D-0221-DAD1-069577934661511B, tag1,tag2,tag3, This is a comment, Some metadata, 0, null], converter=my.package.project.workflow.task.converter.AssetCopyConverter, mappings=[ParameterMapping [key=folderId, references=2, value=id]], response=null, executed=false, taskTimeout=10], Task [task=my.package.project.workflow.task.ApplyMetadataTask, properties=[null, null, testKey, testValue, null], converter=null, mappings=[ParameterMapping [key=uuid, references=3, value=uuid]], response=null, executed=false, taskTimeout=10], Task [task=my.package.project.workflow.task.ApplyTagsTask, properties=[null, testTagName1, testTagName2], converter=null, mappings=[ParameterMapping [key=uuid, references=3, value=uuid]], response=null, executed=false, taskTimeout=10], Task [task=my.package.project.workflow.task.QuickLinkCreateTask, properties=[0, null, null, null, null, null, null, false, null], converter=my.package.project.workflow.task.converter.QuickLinkCreateConverter, mappings=[ParameterMapping [key=uuid, references=3, value=uuid]], response=null, executed=false, taskTimeout=10], Task [task=my.package.project.workflow.task.QuickLinkSendTask, properties=[32221, null, null, null, null], converter=null, mappings=[ParameterMapping [key=uuid, references=6, value=uuid]], response=null, executed=false, taskTimeout=10]], mappings=null]
09:20:33,792 ERROR my.package.commons.net.service.restlet.AbstractCrudRestletResource Activity:56 - com.impetus.kundera.KunderaException: java.lang.NullPointerException
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:208)
    at my.package.commons.data.dao.AbstractDAO.persist(AbstractDAO.java:58)
    at my.package.commons.net.service.restlet.AbstractCrudRestletResource.create(AbstractCrudRestletResource.java:52)
    at my.package.project.restlet.resource.WorkflowResource.create(WorkflowResource.java:22)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)
    at org.restlet.resource.ServerResource.post(ServerResource.java:1328)
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:621)
    at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:679)
    at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357)
    at org.restlet.resource.ServerResource.handle(ServerResource.java:1014)
    at org.restlet.resource.Finder.handle(Finder.java:246)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:431)
    at org.restlet.routing.Router.handle(Router.java:648)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
    at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:84)
    at org.restlet.Application.handle(Application.java:384)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:431)
    at org.restlet.routing.Router.handle(Router.java:648)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:431)
    at org.restlet.routing.Router.handle(Router.java:648)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
    at org.restlet.Component.handle(Component.java:406)
    at org.restlet.Server.handle(Server.java:516)
    at org.restlet.engine.connector.ServerConnectionHelper.handle(ServerConnectionHelper.java:257)
    at org.restlet.engine.connector.ServerConnectionHelper.doHandleInbound(ServerConnectionHelper.java:186)
    at org.restlet.engine.connector.BaseHelper$2.run(BaseHelper.java:593)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
    at com.impetus.kundera.graph.Node.initializeNode(Node.java:139)
    at com.impetus.kundera.graph.Node.<init>(Node.java:101)
    at com.impetus.kundera.graph.ObjectGraphBuilder.getNode(ObjectGraphBuilder.java:134)
    at com.impetus.kundera.graph.ObjectGraphBuilder.getObjectGraph(ObjectGraphBuilder.java:57)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:152)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:202)
    ... 52 more

**Comment by jeremyhahn** [comment]
I've also trimmed the object down to just the top level 'Activity' and am still getting the NPE, I assume because the 'tasks' field is null.

Is there a config somewhere that needs to be set to enable persisting null fields? I am using kundera-mongo-2.2.1-jar-with-dependencies.jar 

[INFO] The entity: Activity [id=33f4b77f-d7d6-4317-a9db-8dc068669e46, hostname=test, username=tester, password=secret, tasks=null]
09:41:01,501 ERROR my.package.commons.net.service.restlet.AbstractCrudRestletResource Activity:56 - com.impetus.kundera.KunderaException: java.lang.NullPointerException
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:208)
    at my.package.commons.data.dao.AbstractDAO.persist(AbstractDAO.java:58)
    at my.package.commons.net.service.restlet.AbstractCrudRestletResource.create(AbstractCrudRestletResource.java:52)
    at my.package.flight.restlet.resource.WorkflowResource.create(WorkflowResource.java:22)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)
    at org.restlet.resource.ServerResource.post(ServerResource.java:1328)
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:621)
    at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:679)
    at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357)
    at org.restlet.resource.ServerResource.handle(ServerResource.java:1014)
    at org.restlet.resource.Finder.handle(Finder.java:246)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:431)
    at org.restlet.routing.Router.handle(Router.java:648)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
    at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:84)
    at org.restlet.Application.handle(Application.java:384)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:431)
    at org.restlet.routing.Router.handle(Router.java:648)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:431)
    at org.restlet.routing.Router.handle(Router.java:648)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
    at org.restlet.Component.handle(Component.java:406)
    at org.restlet.Server.handle(Server.java:516)
    at org.restlet.engine.connector.ServerConnectionHelper.handle(ServerConnectionHelper.java:257)
    at org.restlet.engine.connector.ServerConnectionHelper.doHandleInbound(ServerConnectionHelper.java:186)
    at org.restlet.engine.connector.BaseHelper$2.run(BaseHelper.java:593)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
    at com.impetus.client.mongodb.DocumentObjectMapper.getDocumentListFromCollection(DocumentObjectMapper.java:113)
    at com.impetus.client.mongodb.MongoDBDataHandler.onEmbeddable(MongoDBDataHandler.java:586)
    at com.impetus.client.mongodb.MongoDBDataHandler.getDocumentFromEntity(MongoDBDataHandler.java:336)
    at com.impetus.client.mongodb.MongoDBClient.onPersist(MongoDBClient.java:631)
    at com.impetus.client.mongodb.MongoDBClient.onPersist(MongoDBClient.java:522)
    at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:83)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:193)
    at com.impetus.kundera.graph.Node.flush(Node.java:525)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:411)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:169)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:202)
    ... 52 more

**Comment by xamry** [comment]
This indeed is an issue,

Would it be possible for you to build Kundera for source. I have fixed this
and checked in latest code in trunk.

Sincerely,
Amresh

**Comment by jeremyhahn** [comment]
Thanks Amresh.

I've got the 2.5 snapshot built, but without deps. How do I get a build 
that includes all dependencies?

Thanks

**Comment by xamry** [comment]
mvn assembly:assembly -DskipTests

**Comment by jeremyhahn** [comment]
After compiling all profiles and then installing them to my local repo, I am getting this error.

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error reading assemblies: No assembly descriptors found.

How do I get the descriptors and where do they go?

**Comment by mevivs** [comment]
Please follow given below steps:

1) cd kundera-mongo
2) execute mvn assembly:assembly -DskipTests

It will generate kundera-mongo-VERSION-jar-with-dependencies.jar

hope it helps.

-Vivek

**Comment by jeremyhahn** [comment]
Thanks, Vivek. That worked.

Still getting the NPE with kundera-mongo-2.5-SNAPSHOT-jar-with-dependencies.jar

[INFO] The entity: Activity [id=2dad94d2-4184-4001-803c-dee4ae67e80d, hostname=test, username=tester, password=secret, tasks=[Task [task=my.package.project.workflow.task.CreateProjectTask, properties=[Workflow Project, This is a workflow generated project, 32221], converter=my.package.project.workflow.task.converter.ProjectCreateConverter, mappings=[], response=null, executed=false, taskTimeout=10]]]
12:13:33,488 ERROR my.package.commons.net.service.restlet.AbstractCrudRestletResource Activity:56 - com.impetus.kundera.KunderaException: java.lang.NullPointerException
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)
    at my.package.commons.data.dao.AbstractDAO.persist(AbstractDAO.java:58)
    at my.package.commons.net.service.restlet.AbstractCrudRestletResource.create(AbstractCrudRestletResource.java:52)
    at my.package.project.restlet.resource.WorkflowResource.create(WorkflowResource.java:22)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)
    at org.restlet.resource.ServerResource.post(ServerResource.java:1328)
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:621)
    at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:679)
    at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357)
    at org.restlet.resource.ServerResource.handle(ServerResource.java:1014)
    at org.restlet.resource.Finder.handle(Finder.java:246)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:431)
    at org.restlet.routing.Router.handle(Router.java:648)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
    at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:84)
    at org.restlet.Application.handle(Application.java:384)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:431)
    at org.restlet.routing.Router.handle(Router.java:648)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:431)
    at org.restlet.routing.Router.handle(Router.java:648)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
    at org.restlet.Component.handle(Component.java:406)
    at org.restlet.Server.handle(Server.java:516)
    at org.restlet.engine.connector.ServerConnectionHelper.handle(ServerConnectionHelper.java:257)
    at org.restlet.engine.connector.ServerConnectionHelper.doHandleInbound(ServerConnectionHelper.java:186)
    at org.restlet.engine.connector.BaseHelper$2.run(BaseHelper.java:593)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
    at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:54)
    at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
    at java.lang.reflect.Field.get(Field.java:372)
    at com.impetus.kundera.property.PropertyAccessorHelper.getObject(PropertyAccessorHelper.java:137)
    at com.impetus.kundera.property.PropertyAccessorHelper.getId(PropertyAccessorHelper.java:265)
    at com.impetus.client.mongodb.MongoDBDataHandler.getDocumentFromEntity(MongoDBDataHandler.java:308)
    at com.impetus.client.mongodb.MongoDBClient.onPersist(MongoDBClient.java:645)
    at com.impetus.client.mongodb.MongoDBClient.onPersist(MongoDBClient.java:520)
    at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:86)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:183)
    at com.impetus.kundera.graph.Node.flush(Node.java:525)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:456)
    at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:184)
    at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:168)
    ... 52 more

**Comment by mevivs** [comment]
Hi,
Let me try this and get back to you. Initially i guess it was raised for Cassandra and now somehow failing in one of the scenario in MongoDB.

**Comment by mevivs** [comment]
1) Can you please share your CRUD code snippet?
2) TaskResponse is an entity or an enum? 

-Vivek

**Comment by jeremyhahn** [comment]
1) 

AbstractCrudResetletResource:

protected String create(Representation entity) {
        String response = null;
        try {
            String body = entity.getText();
            T t = mapper.readValue(body, clazz);
            if(t.getId() == null || t.getId().equals("")) {
               t.setId(new UniqueId(UUID.randomUUID()));
            }
            UniqueId id = new DynamicDAO<T>(clazz).persist(t);
            response = mapper.writeValueAsString(id);
        }
        catch(Exception e) {
            log.error(ExceptionUtils.getStackTrace(e));
        }
        return response;
    }

DynamicDAO.persist:

public UniqueId persist(T entity) {
        if(entity.getId() == null || entity.getId().isEmpty()) {
           entity.setId(new UniqueId(UUID.randomUUID()));
        }
        em.persist(entity);
        return new UniqueId(entity.getId());
    }

2) TaskResponse is an entity.

**Comment by mevivs** [comment]
IF TaskResponse is an entity then it should have some association within Task entity, isn't it?

-Vivek

**Comment by mevivs** [comment]
So basically, as per given definitions:

Activity entity is holding up an Embedded Task and where as for each task there has to be a TaskResponse.  I think it looks to me bit incorrect the way it is defined as mentioned above.

-Vivek

**Comment by jeremyhahn** [comment]
Yes, in the final object model TaskResponse will be present, but right now I've removed it from the request and am passing a null to try and simplify things. Since Kundera doesnt mention what object/field is null, I am stripping the object model as much as possible to get it working and then add complexity object by object until I get it working.

The latest commit on trunk did fix the NPE on the top level object (Activity) but I am still getting NPE when I send a request that has the Activity with a single Task. Task.response is null and there is no Embedded annotation on the field, so Kundera should just try and persist that as a null field value, no? Or is it seeing its a TaskResponse type and assuming its an entity and follow the relationship?

Here is the entity.toString() just before the call to em.persist

Activity [id=a4064ae0-11d3-43f7-80ac-52d2688dcf11, hostname=test, username=tester, password=secret, tasks=[Task [task=my.package.project.workflow.task.CreateProjectTask, properties=[Workflow Project, This is a workflow generated project, 32221], converter=my.package.project.workflow.task.converter.ProjectCreateConverter, mappings=[], response=null, executed=false, taskTimeout=10]]]

I also just tried adding Embedded to the Task.response field and persist the entire object model but it's still causing a NPE.

It would be really helpful if Kundera told me what object/field was causing the problem.

**Comment by mevivs** [comment]
If TaskResponse is an entity then there has to be some sort of association defined like @OneToOne, @OneToMany etc. However that should work if you define:

```
@OneToOne
private TaskResponse response;
```

Within Activity entity. I doubt it may break if you define it within @Embeddable entity(e.g. Task). As far as latest NPE is concerned, it can only happen if id is not set for any associated entity. I would suggest you to try by moving TaskResponse mapping out of Task embeddable entity to Activity entity. Still if it does not work, i will give it a try at my end and will share working piece of code. 

Hope it is fine.

-Vivek

**Comment by jeremyhahn** [comment]
All of these objects need to be embedded into a single collection in Mongo. Is there a restriction on how many levels deep I can embed?

I will play with the TaskResponse structure and see what I can do. I have a lot of code written around handling the response so getting rid of the field is going to take some time.

**Comment by jeremyhahn** [comment]
And my original question still stands as well: Can I persist a document that contains an Embedded field that is null?

**Comment by xamry** [comment]
setting null values to any field should be allowed and should be ignored by
JPA provider while persisting entity, any violation is a bug and is a
candidate for fixing.

Nesting of embedded fields is not allowed as per JPA soecification, AFAIK.

Sincerely,
Amresh

**Comment by jeremyhahn** [comment]
OK, I've changed the Task.response field to a string and have a hard coded value so there aren't ANY null values and I'm still getting the NPE. I also gave the Task entity an ID in case that was causing an issue.

Attempting to persist entity: Activity [id=f781f473-e3b5-42b0-941b-548ac222e158, hostname=test, username=tester, password=secret, tasks=[Task [id=b5c7625f-4e7b-453b-b2d2-e8e3bad04078, task=my.package.project.workflow.task.CreateProjectTask, properties=[Workflow Project, This is a workflow generated project, 32221], converter=my.package.project.workflow.task.converter.ProjectCreateConverter, mappings=[], response=Test, executed=false, taskTimeout=10]]]

ERROR my.package.commons.net.service.restlet.AbstractCrudRestletResource Activity:56 - com.impetus.kundera.KunderaException: java.lang.NullPointerException
at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)
