### ISSUE TITLE
Cannot load persistence.xml from arbitrary location

### ISSUE THREAD

**Issue by romikk** [Impetus/kundera#927]
I'm trying to provide my own path to persistence.xml file in this way:
```
        String persistenceConfig = "C:\dev\myapp\target\classes\persistence.xml";
        Map<String, String> properties = Collections.singletonMap(Constants.PERSISTENCE_UNIT_LOCATIION, persistenceConfig);
        EntityManagerFactory emf = Persistence.createEntityManagerFactory(persistenceUnit, properties);
```
but I get this exception:

```
Caused by: java.io.FileNotFoundException: C:\dev\myapp\targe (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1038)
	at com.impetus.kundera.classreading.Reader.getResourceIterator(Reader.java:154)
	... 30 more
```
This boils down to this method in `com.impetus.kundera.loader.PersistenceXMLLoader`:
```
    private static String parseFilePath(String file)
    {
        final String excludePattern = "/META-INF/persistence.xml";
        file = file.substring(0, file.length() - excludePattern.length());

        // in case protocol is "file".
        file = file.endsWith("!") ? file.substring(0, file.length() - 1) : file;

        return file;
    }
```

This will never work with any path outside of META-INF.

Guys, this is low quality coding!

**Comment by devender-yadav** [comment]
Hi @romikk,

First of all, Kundera is JPA 2.1 compliant.  I am not sure you read JPA specifications. 

As per JPA,

>A persistence.xml file defines a persistence unit. The persistence.xml file is located in the
META-INF directory of the root of the persistence unit.

There is a thing about open-source projects - _people with collaborative efforts make it beautiful, improve it's quality_.  So, you are most welcome.


-Dev

**Comment by romikk** [comment]
I'm glad Kundera is JPA 2.1 compliant, can you tell me the point of exposing `Constants.PERSISTENCE_UNIT_LOCATIION` then?
Unfortunately life is too short to fix all the bugs on all open-source projects, especially with low quality code. I'd just move on.
