### ISSUE TITLE
Redis select query results in IllegalArgumentException

### ISSUE THREAD

**Issue by jpadhye** [Impetus/kundera#933]
Same use case as #930. I was able to progress a step further but hitting this issue now.

`broker.dao.DerivedPolicyDaoImpl - Deleting derived policy: df271ff3416c4753adc231d16655b017
11:01:43.117 [main] INFO com.impetus.kundera.query.QueryImpl - On getResultList() executing query: select p from DerivedPolicy p where p.derivedPolicyId = :policy
11:01:43.118 [main] INFO com.impetus.client.redis.RedisClientFactory - borrowing connection from pool
11:01:43.122 [main] ERROR com.impetus.client.redis.RedisClient - Error during persist, Caused by:
java.lang.IllegalArgumentException: attribute of the given name and type is not present in the managed type, for name:PRIMARY-PATH
	at com.impetus.kundera.metadata.model.type.AbstractManagedType.checkForValid(AbstractManagedType.java:1096)
	at com.impetus.kundera.metadata.model.type.AbstractManagedType.getAttribute(AbstractManagedType.java:537)
	at com.impetus.client.redis.RedisClient.unwrap(RedisClient.java:1546)
	at com.impetus.client.redis.RedisClient.fetch(RedisClient.java:312)
	at com.impetus.client.redis.RedisClient.onExecuteQuery(RedisClient.java:1779)
	at com.impetus.client.redis.RedisQuery.populateEntities(RedisQuery.java:95)
	at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:1377)
	at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:200)`

**Comment by devender-yadav** [comment]
Hi @jpadhye,

This issue is due to `@Column(name = "any-name")`  on embedded **enum** type columns for redis. We will fix it soon. 

-Dev
