### ISSUE TITLE
issue with @onetomany:llegalArgumentException: No columns to insert

### ISSUE THREAD

**Issue by mferlay** [Impetus/kundera#937]
Hi everybody, 
we currently meet an issue during executing the code in the attached link.  We try simply to insert data by using `@oneToMany` annotation in HBase. We managed to do it with mySql database but failed each time we tried it in HBase. Could you help us?
Best regards, Mathieu

```
com.impetus.kundera.KunderaException: java.lang.IllegalArgumentException: No columns to insert
	at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)
	at poc2.TestCrit.persist(TestCrit.java:56)
	at poc2.Main.main(Main.java:22)
Caused by: java.lang.IllegalArgumentException: No columns to insert
	at org.apache.hadoop.hbase.client.HTable.validatePut(HTable.java:1500)
	at org.apache.hadoop.hbase.client.BufferedMutatorImpl.validatePut(BufferedMutatorImpl.java:152)
	at org.apache.hadoop.hbase.client.BufferedMutatorImpl.mutate(BufferedMutatorImpl.java:127)
	at org.apache.hadoop.hbase.client.BufferedMutatorImpl.mutate(BufferedMutatorImpl.java:113)
	at org.apache.hadoop.hbase.client.HTable.put(HTable.java:1016)
	at com.impetus.client.hbase.service.HBaseWriter.writeRow(HBaseWriter.java:56)
	at com.impetus.client.hbase.admin.HBaseDataHandler.writeHbaseRowInATable(HBaseDataHandler.java:319)
	at com.impetus.client.hbase.admin.HBaseDataHandler.writeData(HBaseDataHandler.java:233)
	at com.impetus.client.hbase.HBaseClient.onPersist(HBaseClient.java:357)
	at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:114)
	at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:197)
	at com.impetus.kundera.graph.Node.flush(Node.java:531)
	at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:403)
	at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:145)
	at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)
	... 2 more
```

[source](https://gist.github.com/mferlay/6bb60b5834a1edc1b169720b398f2465)

**Comment by mferlay** [comment]
It's work if this field is added to the PersonCrit class :  
```java
  @Column(name = "PERSONCRIT_NAME")
  private String personCritName;
```

So PersonCrit can't be used with only one ```@Id``` and one ```@OneToMany``` relation.

Is it intended ?

**Comment by devender-yadav** [comment]
@mferlay,

This is an old thread. Still adding my comments for future reference.

>PersonCrit can't be used with only one @Id and one @OneToMany relation.

The id field is *Row Key* in HBase. `@OneToMany` will create join column in child entity. 

So, `PersonCrit` table only left with 1 column i.e. rowkey. In HBase, you cant insert only rowkey. You need to add some data to a particular row key.


Behaviour is different for Mysql (and many other RDBMS). A primary key is a column of the table and you can create a table with only primary key and insert data successfully.
