### ISSUE TITLE
Cannot persiest inherited Entity

### ISSUE THREAD

**Issue by giribikki** [Impetus/kundera#939]
Hi,
I have two entities,
@Entity
@Table(name = "common", schema = "url_results@hbase_pu")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "launcher")
public class Person implements Serializable{
    @Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    private String id;
    @Column(name = "name")
    private String name;
    @Column(name = "path")
    private String url;
---
}

another child class,
@Entity
@DiscriminatorValue(value = "owner")
public class Owner extends Person implements Serializable {
    @Column(name = "workload_id")
    protected long workloadId;
----
}

my persiestance.xml is

<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0">
    <persistence-unit name="hbase_pu">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>com.abc.Person</class>  

        <exclude-unlisted-classes>true</exclude-unlisted-classes>     
        <properties>            
            <property name="kundera.nodes" value="quickstart.cloudera"/>
            <property name="kundera.port" value="2181"/>
            <property name="kundera.keyspace" value="url_results"/>
            <property name="kundera.dialect" value="hbase"/>
            <property name="kundera.ddl.auto.prepare" value="create" />
            <property name="kundera.client.lookup.class" value="com.impetus.client.hbase.HBaseClientFactory" />         
        </properties>       
    </persistence-unit>
</persistence>

When I use persist call, it fails with 

com.impetus.kundera.KunderaException: java.lang.IllegalArgumentException: Entity object is invalid, operation failed. Please check previous log message for details
	at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)
	at xx..xx.xx.xx.(DatabaseConnector.java:46)
	at xx.xx.xx.testDatabaseConnector(DatabaseConnectorTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalArgumentException: Entity object is invalid, operation failed. Please check previous log message for details
	at com.impetus.kundera.validation.rules.NullOrInvalidEntityRule.validate(NullOrInvalidEntityRule.java:52)
	at com.impetus.kundera.graph.GraphGenerator.generate(GraphGenerator.java:125)
	at com.impetus.kundera.graph.GraphGenerator.generateGraph(GraphGenerator.java:78)
	at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:130)
	at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)
	... 25 more

here is my pom entry:

<dependency>
            <groupId>com.impetus.kundera.client</groupId>
            <artifactId>kundera-hbase</artifactId>
            <version>3.8</version>

If I use base class directly instead of child, I was able to persist.

Any idea what I am doing wrong?

**Comment by devender-yadav** [comment]
Hi @giribikki,

`kundera-hbase` module is no longer active. Please use [`kundera-hbase-v2`](https://github.com/impetus-opensource/Kundera/wiki/Kundera-with-HBase#kundera-hbase-v2)

Add `Owner` class in `persistence.xml` too.

-Dev

**Comment by giribikki** [comment]
My bad, I actually added Owner class to persistence.xml but, some how copied here, will try v2 and let you know.

Thanks,

**Comment by giribikki** [comment]
Looks like there is an issue with configuration,
with base class, I had to set 
```
<property name="kundera.keyspace" value="url_results"/>
```
while with derived class, I had to set
```
<property name="kundera.keyspace" value="url_results@hbase_pu"/> 
```
here is the issue in `MetadataBuilder`

```
 if (metadata.getPersistenceUnit() != null && !metadata.getPersistenceUnit().equals(persistenceUnit)
                || (keyspace != null && metadata.getSchema() != null && !metadata.getSchema().equals(keyspace)))
        {
            metadata = null;
        }
        else
        {
            applyMetadataChanges(metadata);
        }
```

if loop is true if I set the keyspace with @hase_bu, may be a bug.

**Comment by giribikki** [comment]
my bad, auto format removed some of the text from my comment, 
with base class, I had to set
property name="kundera.keyspace" value="url" 

with derived class, I had to set
property name="kundera.keyspace" value="url@hbase_pu"

**Comment by giribikki** [comment]
But, later it fails with 
Caused by: java.lang.IllegalArgumentException: Illegal character <64> at 3. Namespaces can only contain 'alphanumeric characters': i.e. [a-zA-Z_0-9]: url@hbase_pu during connection to hbase so, I think, it is bug.

**Comment by giribikki** [comment]
I was able to persist finally by just making annotated schema as just 'url' instead of url@hbase_pu, however this is not jpa standard, can you take  a look please?

**Comment by devender-yadav** [comment]
Hi @giribikki,

While setting `kundera.keyspace`in persistence.xml, only specify **keyspace** name.

For example,

    <property name="kundera.keyspace" value="testdb"/>

`keyspace@pu` is specified on entity in `Table` annotation. 

For example,

    @Table(name = "TBL_NAME", schema = "url_results@hbase_pu")

Do it for both the classes.

-Dev

**Comment by giribikki** [comment]
Dev, 
The way you mentioned is working for base class however, failed for derived class.
When I set,

property name="kundera.keyspace" value="url_results"
and 
@Table(name = "TBL_NAME", schema = "url_results")        -- observe no @hbase_pu

it works for both base and derived classes.

however mentioning schema with out @hbase_pu is not JPA compatible isn't it?

**Comment by devender-yadav** [comment]
Have you added 

  ```<property name="kundera.keyspace" value="testdb"/>```

in the persistence unit and

```@Table(name = "TBL_NAME", schema = "testdb@hbase_pu")```

on the both entities?


If you are adding persistence unit name in `schema` (testdb@hbase_pu) then you must specify that entity in persistence.xml. 

eg  ```<class>com.abc.Person</class>```


-Dev

**Comment by giribikki** [comment]
Yes, I did that.
As I said, this issue is only with derived classes, base class works with the way you mentioned.

Thanks,
