### ISSUE TITLE
Syntax error while quering entity with embedded user type

### ISSUE THREAD

**Issue by erweider** [Impetus/kundera#944]
Hi,
I have problem with querying already stored entities with some field which is type of user type.

```
@Entity
@Table(name = "encja", schema = "KunderaExamples5@cassandra_pu")
public class Encja 
{
    @Id
    @Column(name = "userId")
    private String userId;
    
    @Column(name="first_name")
    private String firstName;
    
    @Column(name="last_name")
    private String lastName;
    
    @Column(name="city")
    private String city;
    @Embedded    
    private Adres adres;

GETTERS/SETTERS...
```

```
@Embeddable
public class Adres implements Serializable {
	@Column(name="miasto")
	private String miasto;
	@Column(name="kot")
	private String kot;

	public String getKot() {
		return kot;
	}
	public void setKot(String kot) {
		this.kot = kot;
	}
	public String getMiasto() {
		return miasto;
	}
	public void setMiasto(String miasto) {
		this.miasto = miasto;
	}
}
```

**Main class:**
```
  Encja user = new Encja();
	        user.setUserId("fdfc5c74-256f-4a9b-8a97-d3bf46c54efd");
	        user.setFirstName("John2");
	        user.setLastName("Smith");
	        user.setCity("London");
	        Adres adres = new Adres();
	        adres.setKot("2");
	        adres.setMiasto("Swiny");
	        user.setAdres(adres);
	        
	        Map<String, String> props = new HashMap<>();
	        props.put(CassandraConstants.CQL_VERSION, CassandraConstants.CQL_VERSION_3_0);
	        EntityManagerFactory emf = Persistence.createEntityManagerFactory("cassandra_pu", props);
	        EntityManager em = emf.createEntityManager();
	        
	        em.persist(user);
	        em.flush();
	       
	       Query c = em.createQuery("Select a from Encja a", Encja.class);
               c.getResultList();
```

**And persistence.xml:**
```
<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
	http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
	version="2.0">
	<persistence-unit name="cassandra_pu">
		<provider>com.impetus.kundera.KunderaPersistence</provider>		
		
     <!-- Include all entity classes here... -->
    <class>com.prejch.Encja</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>		 

		<properties>			
			<property name="kundera.nodes" value="localhost"/>
			<property name="kundera.port" value="9160"/>
			<property name="kundera.keyspace" value="KunderaExamples5"/>
			<property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.ddl.auto.prepare" value="update" />
			<property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
		</properties>
			
	</persistence-unit>
</persistence>
```

I got error while querying:

```
18:59:42.953 [main] INFO  com.impetus.kundera.query.QueryImpl - On getResultList() executing query: Select * from encja
18:59:42.953 [main] DEBUG c.i.client.cassandra.query.CassQuery - Populating entities for Cassandra query Select * from encja.
18:59:42.953 [main] DEBUG c.i.c.cassandra.CassandraClientBase - Executing cql query Select * from encja.
18:59:42.953 [main] DEBUG c.i.c.cassandra.CassandraClientBase - Executing query Select * from encja.
18:59:42.953 [main] DEBUG c.i.c.c.thrift.ThriftClientFactory - Returning connection of localhost :9160 .
18:59:42.970 [main] ERROR c.i.c.c.d.CassandraDataHandlerBase - Syntax error parsing '(org.apache.cassandra.db.marshal.UserType(KunderaExamples5,4164726573,6d696173746f:org.apache.cassandra.db.marshal.UTF8Type,6b6f74:org.apache.cassandra.db.marshal.UTF8Type))' at char 41: expecting ':' token
18:59:42.972 [main] ERROR c.i.c.c.d.CassandraDataHandlerBase - Eror while retrieving data, Caused by: .
com.impetus.kundera.KunderaException: Error while getting instance of UserType org.apache.cassandra.exceptions.SyntaxException: Syntax error parsing '(org.apache.cassandra.db.marshal.UserType(KunderaExamples5,4164726573,6d696173746f:org.apache.cassandra.db.marshal.UTF8Type,6b6f74:org.apache.cassandra.db.marshal.UTF8Type))' at char 41: expecting ':' token
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.setUdtValue(CassandraDataHandlerBase.java:1300) ~[kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateViaThrift(CassandraDataHandlerBase.java:1158) ~[kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.onColumn(CassandraDataHandlerBase.java:1054) ~[kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateEntity(CassandraDataHandlerBase.java:653) ~[kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2301) [kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.CassandraClientBase.executeSelectQuery(CassandraClientBase.java:926) [kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.thrift.ThriftClient.executeQuery(ThriftClient.java:1062) [kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:153) [kundera-cassandra-3.8.jar:na]
	at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:1377) [kundera-core-3.8.jar:na]
	at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:200) [kundera-core-3.8.jar:na]
	at com.prejch.MAin.main(MAin.java:37) [classes/:na]
Exception in thread "main" 18:59:42.972 [main] ERROR c.i.c.cassandra.CassandraClientBase - Error while executing native CQL query Caused by {}.
javax.persistence.PersistenceException: com.impetus.kundera.KunderaException: Error while getting instance of UserType org.apache.cassandra.exceptions.SyntaxException: Syntax error parsing '(org.apache.cassandra.db.marshal.UserType(KunderaExamples5,4164726573,6d696173746f:org.apache.cassandra.db.marshal.UTF8Type,6b6f74:org.apache.cassandra.db.marshal.UTF8Type))' at char 41: expecting ':' token
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateEntity(CassandraDataHandlerBase.java:833) ~[kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2301) ~[kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.CassandraClientBase.executeSelectQuery(CassandraClientBase.java:926) [kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.thrift.ThriftClient.executeQuery(ThriftClient.java:1062) [kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:153) [kundera-cassandra-3.8.jar:na]
	at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:1377) [kundera-core-3.8.jar:na]
	at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:200) [kundera-core-3.8.jar:na]
	at com.prejch.MAin.main(MAin.java:37) [classes/:na]
Caused by: com.impetus.kundera.KunderaException: Error while getting instance of UserType org.apache.cassandra.exceptions.SyntaxException: Syntax error parsing '(org.apache.cassandra.db.marshal.UserType(KunderaExamples5,4164726573,6d696173746f:org.apache.cassandra.db.marshal.UTF8Type,6b6f74:org.apache.cassandra.db.marshal.UTF8Type))' at char 41: expecting ':' token
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.setUdtValue(CassandraDataHandlerBase.java:1300) ~[kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateViaThrift(CassandraDataHandlerBase.java:1158) ~[kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.onColumn(CassandraDataHandlerBase.java:1054) ~[kundera-cassandra-3.8.jar:na]
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateEntity(CassandraDataHandlerBase.java:653) ~[kundera-cassandra-3.8.jar:na]
	... 7 common frames omitted
javax.persistence.PersistenceException: javax.persistence.PersistenceException: com.impetus.kundera.KunderaException: Error while getting instance of UserType org.apache.cassandra.exceptions.SyntaxException: Syntax error parsing '(org.apache.cassandra.db.marshal.UserType(KunderaExamples5,4164726573,6d696173746f:org.apache.cassandra.db.marshal.UTF8Type,6b6f74:org.apache.cassandra.db.marshal.UTF8Type))' at char 41: expecting ':' token
	at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2320)
	at com.impetus.client.cassandra.CassandraClientBase.executeSelectQuery(CassandraClientBase.java:926)
	at com.impetus.client.cassandra.thrift.ThriftClient.executeQuery(ThriftClient.java:1062)
	at com.impetus.client.cassandra.query.CassQuery.populateEntities(CassQuery.java:153)
	at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:1377)
	at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:200)
	at com.prejch.MAin.main(MAin.java:37)
Caused by: javax.persistence.PersistenceException: com.impetus.kundera.KunderaException: Error while getting instance of UserType org.apache.cassandra.exceptions.SyntaxException: Syntax error parsing '(org.apache.cassandra.db.marshal.UserType(KunderaExamples5,4164726573,6d696173746f:org.apache.cassandra.db.marshal.UTF8Type,6b6f74:org.apache.cassandra.db.marshal.UTF8Type))' at char 41: expecting ':' token
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateEntity(CassandraDataHandlerBase.java:833)
	at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2301)
	... 6 more
Caused by: com.impetus.kundera.KunderaException: Error while getting instance of UserType org.apache.cassandra.exceptions.SyntaxException: Syntax error parsing '(org.apache.cassandra.db.marshal.UserType(KunderaExamples5,4164726573,6d696173746f:org.apache.cassandra.db.marshal.UTF8Type,6b6f74:org.apache.cassandra.db.marshal.UTF8Type))' at char 41: expecting ':' token
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.setUdtValue(CassandraDataHandlerBase.java:1300)
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateViaThrift(CassandraDataHandlerBase.java:1158)
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.onColumn(CassandraDataHandlerBase.java:1054)
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateEntity(CassandraDataHandlerBase.java:653)
	... 7 more

```

**Comment by karthikprasad13** [comment]
Hi @erweider 

This should work. Can you show `table` and `type` description of what is being created by Kundera on Cassandra database?

-Karthik
