### ISSUE TITLE
Not able to insert data in cassandra

### ISSUE THREAD

**Issue by satyabsarker** [Impetus/kundera#950]
Not able to insert data in cassandra. Getting below Exception -

19:07:10.954 [main] DEBUG c.i.k.persistence.context.CacheBase - Node: com.infy.cass.dto.EmployeeDTO$0001:: ADDED TO  Persistence Context
19:07:10.958 [main] DEBUG c.i.k.p.PersistenceDelegator - Flushing following flush stack to database(s) (showing stack objects from top to bottom):
[[com.infy.cass.dto.EmployeeDTO$0001]com.infy.cass.dto.EmployeeDTO$0001]
19:07:10.960 [main] DEBUG c.i.c.c.thrift.ThriftClientFactory - Returning connection of localhost :9160 .
Exception in thread "main" java.lang.NoSuchMethodError: com.impetus.kundera.metadata.model.attributes.AbstractAttribute.getTableName()Ljava/lang/String;
	at com.impetus.client.cassandra.thrift.CQLTranslator.onTranslation(CQLTranslator.java:232)
	at com.impetus.client.cassandra.thrift.CQLTranslator.prepareColumnOrColumnValues(CQLTranslator.java:186)
	at com.impetus.client.cassandra.CassandraClientBase.createInsertQuery(CassandraClientBase.java:1033)
	at com.impetus.client.cassandra.CassandraClientBase$CQLClient.persist(CassandraClientBase.java:2066)
	at com.impetus.client.cassandra.thrift.ThriftClient.onPersist(ThriftClient.java:154)
	at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:88)
	at com.impetus.client.cassandra.thrift.ThriftClient.persist(ThriftClient.java:136)
	at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:183)
	at com.impetus.kundera.graph.Node.flush(Node.java:533)
	at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:413)
	at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:151)
	at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:168)
	at com.infy.cass.main.CassMain.main(CassMain.java:41)

**Comment by devender-yadav** [comment]
@satyabsarker,

Please share your sample POJO class and `persistence.xml` along with Kundera and Cassandra version. 


-Dev

**Comment by satyabsarker** [comment]
Hi Dev,

Thanks for your response.

It is working now . There was a version mismatch.

Thanks & Regards,
Satya
