### ISSUE TITLE
MongoDB aggregation pipeline issue

### ISSUE THREAD

**Issue by michael-rhoese** [Impetus/kundera#952]
Hi Dev Team,
I use the latest kundera version with mongodb. I want to execute a native query:
`db.test_model_a.aggregate( [ { $match: { $and: [ { "intValue": 1 }, { "embedded.intValue": 1 } ] } }, { $count: "passing_scores" } ] )`
The query works if I run them in consol. Kundera throws a NullPointerException. The stacktrace is:
```
com.impetus.kundera.query.QueryHandlerException: java.lang.NullPointerException

	at com.impetus.client.mongodb.query.MongoDBQuery.populateEntities(MongoDBQuery.java:193)
	at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:1377)
	at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:200)
	at de.fhe.ai.campusapp.core.persistence.repository.impl.AbstractCriteriaRepository.count(AbstractCriteriaRepository.java:145)
	at de.fhe.ai.campusapp.core.persistence.repository.CriteriaRepositoryTests.count(CriteriaRepositoryTests.java:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at de.fhe.ai.campusapp.environment.persistence.PersistenceTestRunner.run(PersistenceTestRunner.java:107)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at de.fhe.ai.campusapp.environment.persistence.CampusBEPersistenceSuite.runChild(CampusBEPersistenceSuite.java:115)
	at de.fhe.ai.campusapp.environment.persistence.CampusBEPersistenceSuite.runChild(CampusBEPersistenceSuite.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at com.impetus.client.mongodb.DefaultMongoDBDataHandler.getEntityFromDocument(DefaultMongoDBDataHandler.java:95)
	at com.impetus.client.mongodb.MongoDBClient.populateEntity(MongoDBClient.java:1903)
	at com.impetus.client.mongodb.MongoDBClient.executeNativeQuery(MongoDBClient.java:1688)
	at com.impetus.client.mongodb.MongoDBClient.executeQuery(MongoDBClient.java:1646)
	at com.impetus.client.mongodb.query.MongoDBQuery.populateEntities(MongoDBQuery.java:163)
	... 37 more
```
The result in console is `{ "passing_scores" : 4 }`. Supports Kundera this kind of queries for Mongo?

I have an other question by side. Is it possible to execute a script with Kundera in Mongo? The aggregation allows me to aggregate a list of entities. These entities I want to delete on Mongo side. The query looks like `db.test_model_a.aggregate( { $match: { $and: [ { "intValue": 2 }, { "stringValue": /test/ } ] } } ).forEach( function( doc ) { db.test_model_a.remove( { "_id": doc._id } ) } )`. The function (script) removes all aggregated entities. It works in console but Kundera does nothing.

Thx for your time.

**Comment by devender-yadav** [comment]
Hi @michael-rhoese,

You can use `executeScript()` method available in `Client`.

 > Object result = (client).executeScript(script);

Check [test case](https://github.com/impetus-opensource/Kundera/blob/49eb8973c44c3dbd825dd9bd13037c0457d5d71c/src/kundera-mongo/src/test/java/com/impetus/client/crud/PersonMongoTest.java#L337) for details. 

-Dev
