### ISSUE TITLE
Kundera - Cassandra : Issue with Embedded UDT Entities

### ISSUE THREAD

**Issue by crashedserver** [Impetus/kundera#953]
The issue is described below.

https://stackoverflow.com/questions/45467495/kundera-cassandra-jpql-with-compound-key

If I remove the ElementCollection attribute "Comments" (which is equivalent to Comments UDT in Cassandra) things work fine.

Any known issues around it?

The issue is observed with 3.8 release as well.

**Comment by karthikprasad13** [comment]
@crashedserver 

Yes this is a bug. We will fix it and it will be available in next release.

-Karthik

**Comment by crashedserver** [comment]
Thanks Karthik for the confirmation. Any tentative schedule for the next
release?

On Aug 3, 2017 2:04 PM, "karthikprasad13" <notifications@github.com> wrote:

@crashedserver <https://github.com/crashedserver>

Yes this is a bug. We will fix it and it will be available in next release.

-Karthik

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/impetus-opensource/Kundera/issues/953#issuecomment-319904965>,
or mute the thread

**Comment by karthikprasad13** [comment]
@crashedserver 

We planned our next release within 2 weeks.

-Karthik

**Comment by devender-yadav** [comment]
Hi @crashedserver,

This has been fixed and will be available in Kundera 3.10

-Dev

**Comment by crashedserver** [comment]
Getting the following exception with 3.10.  Looks like dependency issue.  Using the following Cassandra dependency.

    <dependency>
            <groupId>org.apache.cassandra</groupId>
            <artifactId>cassandra-all</artifactId>
            <version>3.11.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>


java.lang.NoSuchMethodError: org.apache.cassandra.serializers.ListSerializer.deserializeForNativeProtocol(Ljava/nio/ByteBuffer;I)Ljava/util/List;
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.setElementCollectionList(CassandraDataHandlerBase.java:1735)
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.setElementCollection(CassandraDataHandlerBase.java:1576)
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateViaThrift(CassandraDataHandlerBase.java:1154)
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.onColumn(CassandraDataHandlerBase.java:1054)
	at com.impetus.client.cassandra.datahandler.CassandraDataHandlerBase.populateEntity(CassandraDataHandlerBase.java:653)
	at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:2301)
	at com.impetus.client.cassandra.CassandraClientBase.executeSelectQuery(CassandraClientBase.java:926)
	at com.impetus.client.cassandra.thrift.ThriftClient.executeQuery(ThriftClient.java:1062)
	at com.impetus.client.cassandra.CassandraClientBase$CQLClient.find(CassandraClientBase.java:2421)
	at com.impetus.client.cassandra.CassandraClientBase.populate(CassandraClientBase.java:787)
	at com.impetus.client.cassandra.CassandraClientBase.find(CassandraClientBase.java:752)
	at com.impetus.client.cassandra.CassandraClientBase.find(CassandraClientBase.java:686)
	at com.impetus.client.cassandra.thrift.ThriftClient.find(ThriftClient.java:350)
	at com.impetus.kundera.persistence.AbstractEntityReader.findById(AbstractEntityReader.java:81)
	at com.impetus.client.cassandra.query.CassandraEntityReader.findById(CassandraEntityReader.java:93)
	at com.impetus.kundera.lifecycle.states.ManagedState.handleFind(ManagedState.java:137)
	at com.impetus.kundera.graph.Node.find(Node.java:500)
	at com.impetus.kundera.persistence.PersistenceDelegator.find(PersistenceDelegator.java:225)
	at com.impetus.kundera.persistence.PersistenceDelegator.findById(PersistenceDelegator.java:174)
	at com.impetus.kundera.persistence.EntityManagerImpl.find(EntityManagerImpl.java:263)

**Comment by devender-yadav** [comment]
Hi @crashedserver 

Why are you adding `cassandra-all` dependency?
It's already added in `Kundera-cassandra`.

-Dev

**Comment by crashedserver** [comment]
@devender-yadav  Many Thanks. It works now. Will do some more testing around it and update in case of issues. Thanks for fixing it.

**Comment by devender-yadav** [comment]
You're welcome @crashedserver!
