### ISSUE TITLE
Cassandra: Named Parameter Not supported for token function

### ISSUE THREAD

**Issue by crashedserver** [Impetus/kundera#959]
String FIND_SIMPLE_ENTITY = "Select s from SimpleEntity s where token(\"PKEY\") > token(:pkey)";
        Query query = entityManager.createNamedQuery(FIND_SIMPLE_ENTITY, SimpleEntity.class);
        query.setParameter("pkey",1);

In the above code am not able to set the partition key parameter value. Throws the following exception.

    Caused by: com.impetus.kundera.query.QueryHandlerException: No named parameter present for query
	at com.impetus.kundera.query.KunderaQuery.setParameterValue(KunderaQuery.java:971) ~[kundera-core-3.10.1.jar:na]
	at com.impetus.kundera.query.KunderaQuery.setParameter(KunderaQuery.java:916) ~[kundera-core-3.10.1.jar:na]
	at com.impetus.kundera.query.QueryImpl.setParameter(QueryImpl.java:838) ~[kundera-core-3.10.1.jar:na]
	at com.impetus.kundera.query.KunderaTypedQuery.setParameter(KunderaTypedQuery.java:352) ~[kundera-core-3.10.1.jar:na]
	at com.impetus.kundera.query.KunderaTypedQuery.setParameter(KunderaTypedQuery.java:40) ~[kundera-core-3.10.1.jar:na]

Looks like it is not supported. Please see if it can be supported.

**Comment by karthikprasad13** [comment]
@crashedserver 

Lets discuss this on [gitter](https://gitter.im/karthikprasad13/issue959)

-Karthik
