### ISSUE TITLE
IS NULL and IS NOT NULL

### ISSUE THREAD

**Issue by dstrawson** [Impetus/kundera#96]
My query is:

SELECT w FROM Task w WHERE w.lockTimeout IS NOT NULL

lockTimeout is a java.util.Date field

This gives the following error

Caused by: javax.persistence.PersistenceException: bad jpa query: w.lockTimeout IS NOT NULL
    at com.impetus.kundera.query.KunderaQuery.initFilter(KunderaQuery.java:423)
    at com.impetus.kundera.query.KunderaQuery.postParsingInit(KunderaQuery.java:331)
    at com.impetus.kundera.query.QueryResolver.getQueryImplementation(QueryResolver.java:75)
    at com.impetus.kundera.persistence.PersistenceDelegator.createQuery(PersistenceDelegator.java:550)
    at com.impetus.kundera.persistence.EntityManagerImpl.createQuery(EntityManagerImpl.java:337)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:365)
    at $Proxy30.createQuery(Unknown Source)

**Comment by mevivs** [comment]
"NULL" "NOT NULL" not yet supported in kundera.

**Comment by dstrawson** [comment]
OK thanks
