### ISSUE TITLE
Cannot create secondary index on partition key column

### ISSUE THREAD

**Issue by RobertMlo** [Impetus/kundera#970]
I've created two one-to-one relationships (unidirectional) in an `Application` entity:

```java
@Entity
@Table
@IndexCollection(columns = {@Index(name = "appConfigFile"), @Index(name = "appFiles")})
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
@EqualsAndHashCode
public class Application {
    @Id
    @Column(name = "application_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String id;
    @Column
    private String name;
    @Column
    private String displayName;
    @Column
    private String description;
    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "application_id")
    private AppConfigFile appConfigFile;
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "application_id")
    private Set<AppFile> appFiles;
}
```

`AppFile` and `AppFileConfig` classes look like the same, so I'll put only one of them:

```java
@Entity
@Table
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
@EqualsAndHashCode
public class AppFile {
    @Id
    @Column(name = "appFile_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String id;
    @Column
    private String name;
    @Column
    private String content;
}
```

I wrote that based on your [ARTICLE](https://github.com/impetus-opensource/Kundera/wiki/Polyglot-Persistence#unidirectional-association). Unfortunately, when I start my app, I receive the following error. I also noticed that I receive this error when I use an `update` value for `kundera.ddl.auto.prepare` option in `persistance.xml`. Do you have any idea how can I fix this issue?

> Caused by: com.impetus.kundera.configure.schema.SchemaGenerationException: Error occurred while creating indexes on column application_id of table Application
        at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.createIndexUsingCql(CassandraSchemaManager.java:1435)
        at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.updateExistingColumnFamily(CassandraSchemaManager.java:570)
        at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.createOrUpdateUsingCQL3(CassandraSchemaManager.java:855)
        at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.createColumnFamilies(CassandraSchemaManager.java:430)
        at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.createOrUpdateKeyspace(CassandraSchemaManager.java:279)
        at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.update(CassandraSchemaManager.java:639)
        ... 313 more
Caused by: InvalidRequestException(why:Cannot create secondary index on partition key column application_id)
        at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result$execute_cql3_query_resultStandardScheme.read(Cassandra.java:50297)
        at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result$execute_cql3_query_resultStandardScheme.read(Cassandra.java:50274)
        at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result.read(Cassandra.java:50189)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
        at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql3_query(Cassandra.java:1734)
        at org.apache.cassandra.thrift.Cassandra$Client.execute_cql3_query(Cassandra.java:1719)
        at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.createIndexUsingCql(CassandraSchemaManager.java:1424)
        ... 318 more

I use a Cassandra 3.10. My `build.gradle` included the following dependencies:

    compile group: 'com.impetus.kundera.client', name: 'kundera-cassandra-ds-driver', version: '3.10.1'
    compile group: 'com.impetus.kundera.client', name: 'kundera-cassandra', version: '3.10.1'
    compile group: 'com.datastax.cassandra', name: 'cassandra-driver-core', version: '3.3.0'

Here is my `persistance.xml`:

```xml
<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
	http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
	version="2.0">
    <persistence-unit name="cassandra_pu">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <class>...</class>
        <exclude-unlisted-classes>true</exclude-unlisted-classes>
        <properties>
            <property name="kundera.nodes" value="<IP>"/>
            <property name="kundera.port" value="<PORT>" />
            <property name="kundera.keyspace" value="test"/>
            <property name="kundera.dialect" value="cassandra" />
            <property name="kundera.ddl.auto.prepare" value="update" />
            <property name="kundera.client.lookup.class"
                      value="com.impetus.kundera.client.cassandra.dsdriver.DSClientFactory" />
            <property name="kundera.show.query" value="false" />
            <property name="jboss.as.jpa.managed" value="false" />
        </properties>
    </persistence-unit>
</persistence>
```

**Comment by karthikprasad13** [comment]
@RobertMlo 

I don't see any partition keys in your entities. I tried with your entities and it is working fine. Please confirm if you shared correct entities.

-Karthik
