### ISSUE TITLE
Configuration Cassandra

### ISSUE THREAD

**Issue by gsndr** [Impetus/kundera#975]
Hi,
I need to know correct configuration for Cassandra Kundera.
I'm using this configuration in my pom.xml
```
<!-- https://mvnrepository.com/artifact/com.impetus.kundera.client/kundera-cassandra-ds-driver -->
<dependency>
    <groupId>com.impetus.kundera.client</groupId>
    <artifactId>kundera-cassandra-ds-driver</artifactId>
    <version>3.11</version>
</dependency>
```

And this persistence configuration:
```
<persistence-unit name="cassandra">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>org.netminer.database.nosql.model.Edge</class>
    <properties>
      <property name="kundera.dialect" value="cassandra"/>
      <property name="kundera.nodes" value="localhost"/>
      <property name="kundera.port" value="9042"/>
      <property name="kundera.ddl.auto.prepare" value="validate"/>
         <property name="kundera.client.lookup.class"
				value="com.impetus.kundera.client.cassandra.dsdriver.DSClientFactory" />
    </properties>
  </persistence-unit>
```

But problem is this:
`16:41:16.670 [main] WARN  c.i.c.c.s.CassandraSchemaManager - Error while opening socket for host localhost, skipping for next available node 
com.impetus.kundera.configure.schema.SchemaGenerationException: Error while opening socket, Caused by: .
	at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.initiateClient(CassandraSchemaManager.java:718)
	at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.exportSchema(AbstractSchemaManager.java:112)
	at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.exportSchema(CassandraSchemaManager.java:166)
	at com.impetus.kundera.configure.SchemaConfiguration.configure(SchemaConfiguration.java:191)
	at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:48)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:408)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configure(EntityManagerFactoryImpl.java:161)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:135)
	at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:85)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
	at org.netminer.database.access.DataPlatformCassandra$DataAccessPlatform.SetUpBeforeClass(DataPlatformCassandra.java:129)
	at org.netminer.database.access.DataPlatformCassandra$DataAccessPlatform.<init>(DataPlatformCassandra.java:114)
	at org.netminer.database.access.DataPlatformCassandra.<init>(DataPlatformCassandra.java:41)
	at org.netminer.database.access.DataPlatformCassandra.getDynamicIstance(DataPlatformCassandra.java:70)
	at org.netminer.streamchangemining.test.AnalyzerThree.main(AnalyzerThree.java:574)
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connessione rifiutata (Connection refused)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
	at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.initiateClient(CassandraSchemaManager.java:695)
	... 14 more
Caused by: java.net.ConnectException: Connessione rifiutata (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
	... 15 more`

**Comment by gsndr** [comment]
If I use this configuration:
```
<dependency>
    <groupId>com.impetus.kundera.client</groupId>
    <artifactId>kundera-cassandra</artifactId>
    <version>3.11</version>
</dependency>
```
And this persistence:
```
<persistence-unit name="cassandra">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>org.netminer.database.nosql.model.Edge</class>
    <properties>
      <property name="kundera.dialect" value="cassandra"/>
      <property name="kundera.nodes" value="localhost"/>
      <property name="kundera.port" value="9160"/>
      <property name="kundera.ddl.auto.prepare" value="validate"/>
     <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.pelops.PelopsClientFactory" />
			<property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
    </properties>
  </persistence-unit>
```
I've got this error message:
`6:48:40.746 [main] ERROR c.i.kundera.client.ClientResolver - Error while initializing client factory, Caused by: .
com.impetus.kundera.client.ClientResolverException: java.lang.ClassNotFoundException: com.impetus.client.cassandra.pelops.PelopsClientFactory
	at com.impetus.kundera.client.ClientResolver.onError(ClientResolver.java:173)
	at com.impetus.kundera.client.ClientResolver.instantiateClientFactory(ClientResolver.java:128)
	at com.impetus.kundera.client.ClientResolver.getClientFactory(ClientResolver.java:56)
	at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:42)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:408)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configure(EntityManagerFactoryImpl.java:161)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:135)
	at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:85)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
	at org.netminer.database.access.DataPlatformCassandra$DataAccessPlatform.SetUpBeforeClass(DataPlatformCassandra.java:129)
	at org.netminer.database.access.DataPlatformCassandra$DataAccessPlatform.<init>(DataPlatformCassandra.java:114)
	at org.netminer.database.access.DataPlatformCassandra.<init>(DataPlatformCassandra.java:41)
	at org.netminer.database.access.DataPlatformCassandra.getDynamicIstance(DataPlatformCassandra.java:70)
	at org.netminer.streamchangemining.test.AnalyzerThree.main(AnalyzerThree.java:574)
Caused by: java.lang.ClassNotFoundException: com.impetus.client.cassandra.pelops.PelopsClientFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.impetus.kundera.client.ClientResolver.instantiateClientFactory(ClientResolver.java:91)
	... 12 more`

**Comment by gsndr** [comment]
And finally, if i use this persistence configuration:
```
`<persistence-unit name="cassandra">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>org.netminer.database.nosql.model.Edge</class>
    <properties>
      <property name="kundera.dialect" value="cassandra"/>
      <property name="kundera.nodes" value="localhost"/>
      <property name="kundera.port" value="9160"/>
      <property name="kundera.ddl.auto.prepare" value="validate"/>
     <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
  </properties>
  </persistence-unit>`
```
			
  
Error is:
`16:52:42.411 [main] WARN  c.i.c.c.s.CassandraSchemaManager - Error while opening socket for host localhost, skipping for next available node 
com.impetus.kundera.configure.schema.SchemaGenerationException: Error while opening socket, Caused by: .
	at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.initiateClient(CassandraSchemaManager.java:718)
	at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.exportSchema(AbstractSchemaManager.java:112)
	at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.exportSchema(CassandraSchemaManager.java:166)
	at com.impetus.kundera.configure.SchemaConfiguration.configure(SchemaConfiguration.java:191)
	at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:48)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:408)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configure(EntityManagerFactoryImpl.java:161)
	at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:135)
	at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:85)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
	at org.netminer.database.access.DataPlatformCassandra$DataAccessPlatform.SetUpBeforeClass(DataPlatformCassandra.java:129)
	at org.netminer.database.access.DataPlatformCassandra$DataAccessPlatform.<init>(DataPlatformCassandra.java:114)
	at org.netminer.database.access.DataPlatformCassandra.<init>(DataPlatformCassandra.java:41)
	at org.netminer.database.access.DataPlatformCassandra.getDynamicIstance(DataPlatformCassandra.java:70)
	at org.netminer.streamchangemining.test.AnalyzerThree.main(AnalyzerThree.java:574)
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connessione rifiutata (Connection refused)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
	at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.initiateClient(CassandraSchemaManager.java:695)
	... 14 more
Caused by: java.net.ConnectException: Connessione rifiutata (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
	... 15 more`

**Comment by gsndr** [comment]
I solved changing /etc/cassandra.yaml:
```
start_rpc: false
to
start_rpc: true
```
And opened terminal  terminal and
`$ nodetool enablethrift`

Now third configuration works
