### ISSUE TITLE
Class not found, it won't be loaded as entity 

### ISSUE THREAD

**Issue by raphaelauv** [Impetus/kundera#976]
Hi , i'm having this error 
```
[info] play.api.Play - Application started (Dev)
[error] c.i.k.c.MetamodelConfiguration - Class model.MyUser not found, it won't be loaded as entity
WE CREATED : com.impetus.kundera.persistence.EntityManagerFactoryImpl@29e42f19
[error] c.i.k.p.PersistenceDelegator - Entity metadata not found for {}, possible reasons may be: 1) not annotated with @Entity. 2) is annotated with @MappedSuperclass.3) does not properly with mapped persistence unit for persistence unit and keyspace. Please verify with @Table annotation or persistence.xml class model.MyUser
[error] application - 

! @762c06p2m - Internal server error, for (GET) [/find] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[KunderaException: Entity metadata not found for model.MyUser]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:251)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:250)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
Caused by: com.impetus.kundera.KunderaException: Entity metadata not found for model.MyUser
	at com.impetus.kundera.persistence.PersistenceDelegator.getMetadata(PersistenceDelegator.java:691)
	at com.impetus.kundera.persistence.PersistenceDelegator.find(PersistenceDelegator.java:206)
	at com.impetus.kundera.persistence.PersistenceDelegator.findById(PersistenceDelegator.java:174)
	at com.impetus.kundera.persistence.EntityManagerImpl.find(EntityManagerImpl.java:263)
	at controllers.MyUserController.$anonfun$find$1(UserController.scala:51)
	at play.api.mvc.ActionBuilder.$anonfun$apply$11(Action.scala:363)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:482)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:480)
	at play.api.mvc.ActionBuilder$$anon$9.invokeBlock(Action.scala:331)
[error] c.i.k.p.PersistenceDelegator - Entity metadata not found for {}, possible reasons may be: 1) not annotated with @Entity. 2) is annotated with @MappedSuperclass.3) does not properly with mapped persistence unit for persistence unit and keyspace. Please verify with @Table annotation or persistence.xml class model.MyUser
[error] application - 

```

i'm using scala  and folllowing this tutorial : https://dzone.com/articles/play-nosql-building-nosql

and i'm getting this error , could you please give me some help

[error] c.i.k.c.MetamodelConfiguration - Class model.MyUser not found, it won't be loaded as entity

my class is -> 

```scala
package model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "users", schema = "KunderaExamples@cassandra_pu")
class MyUser() {

  @Id
  var userId:String=""

  @Column(name = "first_name")
  var firstName:String=""

  @Column(name = "last_name")
  var lastName:String=""

  @Column(name = "city")
  var city:String=""

}
```

my controller 

```scala
package controllers;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.inject._
import play.api.mvc._
import model.MyUser

  object MyUserController {

    var emf: EntityManagerFactory = null
    val userTmp = new MyUser()
    var classUser =  userTmp.getClass

  }


class MyUserController @Inject() (cc: ControllerComponents) extends AbstractController(cc) {

  def index = Action {
    Ok(views.html.index("Your new application is ready."))
  }

  def getEmf: EntityManagerFactory = {
      if (MyUserController.emf == null) {
        MyUserController.emf = Persistence.createEntityManagerFactory("cassandra_pu");
       System.out.println("WE CREATED : "+MyUserController.emf);
      }
      MyUserController.emf

  }

 	def persist = Action {
      var em: EntityManager = getEmf.createEntityManager();

      var user: MyUser = new MyUser();
      user.setUserId("0001");
      user.setFirstName("John");
      user.setLastName("Smith");
      user.setCity("London");

      em.persist(user);
      em.close();
      Ok(views.html.index("User 0001 record persisted for persistence unit cassandra_pu"));
    }


```

and my persistancefile 
```XML
<persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
 <persistence-unit name="cassandra_pu">
 <provider>com.impetus.kundera.KunderaPersistence</provider>
 <class>model.MyUser</class>
<exclude-unlisted-classes>true</exclude-unlisted-classes>
 <properties>
 <property name="kundera.nodes" value="localhost"/>
 <property name="kundera.port" value="9160"/>
 <property name="kundera.keyspace" value="KunderaExamples"/>
 <property name="kundera.dialect" value="cassandra"/>
 <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
 </properties>
 </persistence-unit>
</persistence>
```
thank you

**Comment by raphaelauv** [comment]
i forgot to follow this instruction ->

Make entity classes available at runtime !
