### ISSUE TITLE
running the kvapps from your github account but i am getting this exception

### ISSUE THREAD

**Issue by mayankqait** [Impetus/kundera#991]
Exception in thread "main" com.impetus.kundera.KunderaException: com.impetus.kundera.KunderaException: InvalidRequestException(why:Unknown identifier personalDetail)
	at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:180)
	at com.impetus.kvapps.runner.ExecutorService.persist(ExecutorService.java:254)
	at com.impetus.kvapps.runner.ExecutorService.onPersist(ExecutorService.java:82)
	at com.impetus.kvapps.runner.AppRunner.main(AppRunner.java:88)
Caused by: com.impetus.kundera.KunderaException: InvalidRequestException(why:Unknown identifier personalDetail)
	at com.impetus.client.cassandra.CassandraClientBase.execute(CassandraClientBase.java:2607)
	at com.impetus.client.cassandra.CassandraClientBase$CQLClient.persist(CassandraClientBase.java:2246)
	at com.impetus.client.cassandra.thrift.ThriftClient.onPersist(ThriftClient.java:193)
	at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:114)
	at com.impetus.client.cassandra.thrift.ThriftClient.persist(ThriftClient.java:167)
	at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:197)
	at com.impetus.kundera.graph.Node.flush(Node.java:531)
	at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:403)
	at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:145)
	at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:174)
	... 3 more
Caused by: InvalidRequestException(why:Unknown identifier personalDetail)
	at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result$execute_cql3_query_resultStandardScheme.read(Cassandra.java:50297)
	at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result$execute_cql3_query_resultStandardScheme.read(Cassandra.java:50274)
	at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result.read(Cassandra.java:50189)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql3_query(Cassandra.java:1734)
	at org.apache.cassandra.thrift.Cassandra$Client.execute_cql3_query(Cassandra.java:1719)
	at com.impetus.client.cassandra.CassandraClientBase.execute(CassandraClientBase.java:2601)
	... 12 more

**Comment by devender-yadav** [comment]
Hi @mayankqait,

Above details are not sufficient. Mention database with version and Kundera version. 

Do reply on your last issues. Close if those are resolved.

**Comment by mayankqait** [comment]
I am providing the zip of project.
And Thank you very much for the quick response I got for my queries.

[kvapps.zip](https://github.com/Impetus/Kundera/files/1719428/kvapps.zip)

**Comment by devender-yadav** [comment]
Hi @mayankqait,

If you are storing in Cassandra, simply enable **CQL3** using below mentioned code:

    Map<String, String> props = new java.util.HashMap<>();
    props.put("cql.version", "3.0.0");
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("twissandra", props);

Are you trying [polyglot persistence](https://github.com/Impetus/Kundera/wiki/Polyglot-Persistence)?

**Comment by mayankqait** [comment]
yes i am using polyglot persistence. mysql and cassandra

**Comment by devender-yadav** [comment]
@mayankqait are we good to close this issue?

**Comment by mayankqait** [comment]
> One last question

 how to overcome double quotes problem in querry.This is auto generated query by kundera
INSERT INTO "User"("first_name","last_name","emailId","user_id") VALUES('RDBMSUser','RDBMSUser','RDBMSUser@RDBMSUser.com','RDBMSUser')

It is adding double quotes around table name and column name.

**Comment by karthikprasad13** [comment]
@mayankqait 

I don't see this as a problem. Double quotes are required to maintain the table and column names case sensitive. 
Can you explain your problem in brief?

-Karthik

**Comment by mayankqait** [comment]
Yes we can close this issue #991 also.
There was a dependency conflict.
Thank u
